/* This file is part of the Spring engine (GPL v2 or later), see LICENSE.html */

#include "ModelConfigLoader.h"

#include "Lua/LuaConfigLoader.h"
#include "Lua/LuaParser.h"
#include "Sim/Units/Scripts/LocalModelPieceStub.h"
#include "System/SpringLog/SpringLog.h"

#define LOG_SECTION "model-config"

#include <cstdio>
#include <filesystem>
#include <memory>

namespace {

/// Pull a float3 field from a sub-table. Both the Lua and JSON
/// forms of the config expose a `{x, y, z}` triple as a nested
/// sub-table indexed by 1/2/3 — Friedl's JSON decoder maps JSON
/// arrays to 1-indexed Lua tables, which is exactly what
/// `LuaTable` expects.
float3 ReadFloat3Field(const LuaTable& parent, const char* key, const float3& fallback) {
    const LuaTable t = parent.SubTable(key);
    if (!t.IsValid())
        return fallback;
    return float3(
        t.Get(1, fallback.x),
        t.Get(2, fallback.y),
        t.Get(3, fallback.z));
}

} // namespace

S3DModel* ModelConfigLoader::Load(const std::string& basePath) {
    auto* model = new S3DModel();
    if (!LoadInto(*model, basePath)) {
        delete model;
        return nullptr;
    }
    return model;
}

bool ModelConfigLoader::LoadInto(S3DModel& out, const std::string& basePath) {
    if (basePath.empty())
        return false;

    // LuaConfig::Load tries <basePath>.config.lua first, then
    // <basePath>.config.json. Both end up in the same LuaParser-backed
    // representation so the rest of this function is format-agnostic.
    std::unique_ptr<LuaParser> parser = LuaConfig::Load(basePath);
    if (!parser) {
        // Caller is expected to have probed for the file already; a
        // silent miss here just means "no config, keep defaults".
        return false;
    }

    // If the .config.lua was loaded but produces no piece array (legacy
    // sidecar that only has overrides like textures/midpos), also load
    // the .config.json for the full piece tree generated by modelimporter.
    // We'll use jsonParser for pieces if the primary parser has none.
    std::unique_ptr<LuaParser> jsonParser;
    {
        namespace fs = std::filesystem;
        const std::string luaPath  = basePath + LuaConfig::kLuaSuffix;
        const std::string jsonPath = basePath + LuaConfig::kJsonSuffix;
        if (fs::exists(luaPath) && fs::exists(jsonPath)) {
            jsonParser = LuaConfig::LoadJson(basePath);
        }
    }

    const LuaTable root = parser->GetRoot();
    if (!root.IsValid()) {
        SLOG(SPRING_LOG_ERROR,
            "%s: root is not a table (did the file forget "
            "`return <table>`?)",
            basePath.c_str());
        return false;
    }

    // ---- Schema version check ----
    // `configVersion` is mandatory on files produced by the current
    // modelimporter. A missing key means the file was produced by a
    // pre-versioning build and should be regenerated. Older versions
    // are accepted as best-effort. The newest accepted version is
    // tracked here so future bumps that aren't yet wired don't
    // silently produce wrong data.
    //
    // v5 (2026-05-16) flipped the on-disk coordinate convention from
    // Spring-native LH to glTF-native RH. Engine internals are still
    // LH through Phase 1, so this loader applies a one-shot Z-flip
    // bridge below for v5+ sidecars. Phase 2 deletes the bridge when
    // the sim and client flip to RH natively. See
    // PLAN-coordinate-system.md.
    constexpr int kSupportedConfigVersion = 5;
    int configVersion = root.GetInt("configVersion", 0);
    if (configVersion == 0)
        configVersion = root.GetInt("metaVersion", 0);

    if (configVersion == 0) {
        SLOG(SPRING_LOG_WARNING,
            "%s: no `configVersion` field — file predates the "
            "versioned schema. Run `modelimporter --update-meta` to "
            "regenerate.",
            basePath.c_str());
    } else if (configVersion > kSupportedConfigVersion) {
        SLOG(SPRING_LOG_NOTICE,
            "%s: configVersion=%d is newer than this engine "
            "understands (%d). Some fields may be ignored.",
            basePath.c_str(), configVersion, kSupportedConfigVersion);
    }

    // Phase 1d coordinate-system bridge: sidecars at v5+ carry
    // RH-canonical values (-Z forward). The engine sim and the wire
    // format still speak LH through Phase 1, so flip Z back here so
    // internal state is unchanged. For min/max bounds this is a
    // negate-AND-swap (the original LH min.z, the most-negative LH
    // Z, became the new max.z under the writer's flip; the same
    // operation is its own inverse).
    const bool flipFromRh = (configVersion >= 5);
    auto adaptOffsetOrMid = [flipFromRh](float3 v) {
        if (flipFromRh) v.z = -v.z;
        return v;
    };
    auto adaptMin = [flipFromRh](float3 mins, float3 maxs) {
        if (flipFromRh) mins.z = -maxs.z;
        return mins;
    };
    auto adaptMax = [flipFromRh](float3 mins, float3 maxs) {
        if (flipFromRh) maxs.z = -mins.z;
        return maxs;
    };

    // ---- Top-level bounds ----
    const float3 rawMid  = ReadFloat3Field(root, "midpos", float3(0, 0, 0));
    const float3 rawMins = ReadFloat3Field(root, "mins",   float3(-1, -1, -1));
    const float3 rawMaxs = ReadFloat3Field(root, "maxs",   float3( 1,  1,  1));
    out.radius    = root.GetFloat("radius", 1.0f);
    out.height    = root.GetFloat("height", 1.0f);
    out.relMidPos = adaptOffsetOrMid(rawMid);
    out.mins      = adaptMin(rawMins, rawMaxs);
    out.maxs      = adaptMax(rawMins, rawMaxs);

    // ---- Piece tree ----
    // Try pieces from the primary config first. If the primary config
    // (often a legacy .config.lua sidecar) has a pieces table that's
    // keyed by name (not an array), GetLength() returns 0 and we get
    // no pieces. In that case, fall back to the JSON config which has
    // the full piece array generated by modelimporter.
    LuaTable pieces = root.SubTable("pieces");
    int numPieces = pieces.IsValid() ? pieces.GetLength() : 0;
    if (numPieces == 0 && jsonParser) {
        const LuaTable jsonRoot = jsonParser->GetRoot();
        if (jsonRoot.IsValid()) {
            pieces = jsonRoot.SubTable("pieces");
            numPieces = pieces.IsValid() ? pieces.GetLength() : 0;
        }
    }
    if (pieces.IsValid() && numPieces > 0) {
        out.pieces.clear();
        out.pieces.reserve(numPieces);

        // First pass: copy fields. We can't set up parent/children
        // pointers yet because pushing into the vector may reallocate
        // and invalidate earlier addresses.
        std::vector<int> parentIndices;
        parentIndices.reserve(numPieces);

        for (int i = 1; i <= numPieces; ++i) {
            const LuaTable p = pieces.SubTable(i);
            if (!p.IsValid()) continue;

            S3DModelPiece piece;
            piece.name = p.GetString("name", "");

            const float3 pOff  = ReadFloat3Field(p, "offset", float3(0, 0, 0));
            const float3 pMins = ReadFloat3Field(p, "mins",   float3(0, 0, 0));
            const float3 pMaxs = ReadFloat3Field(p, "maxs",   float3(0, 0, 0));
            // Same Phase 1d RH→LH bridge as the top-level bounds.
            piece.offset = adaptOffsetOrMid(pOff);
            piece.mins   = adaptMin(pMins, pMaxs);
            piece.maxs   = adaptMax(pMins, pMaxs);

            parentIndices.push_back(p.GetInt("parent", -1));
            out.pieces.push_back(std::move(piece));
        }

        // Second pass: link parent/children. `parent` index is
        // 0-based into the flat list; -1 marks the root.
        for (size_t i = 0; i < out.pieces.size(); ++i) {
            const int parentIdx = parentIndices[i];
            if (parentIdx >= 0 && static_cast<size_t>(parentIdx) < out.pieces.size()) {
                out.pieces[i].parent = &out.pieces[parentIdx];
                out.pieces[parentIdx].children.push_back(&out.pieces[i]);
            }
        }

        out.numPieces = static_cast<int>(out.pieces.size());
    }

    out.metaPath = basePath;

    SLOG(SPRING_LOG_INFO,
        "loaded %s: radius=%.2f height=%.2f pieces=%d",
        basePath.c_str(), out.radius, out.height, out.numPieces);
    return true;
}
