/* This file is part of the Spring engine (GPL v2 or later), see LICENSE.html */

#include "SolidObjectDef.h"
#include "Lua/LuaParser.h"
#include "Lua/LuaConfigLoader.h"
#include "Sim/Misc/CollisionVolume.h"
#include "Sim/Objects/ModelConfigLoader.h"
#include "Sim/Units/Scripts/LocalModelPieceStub.h"
#include "System/EventHandler.h"
#include "System/FileSystem/FileHandler.h"
#include "System/Log/ILog.h"
#include "System/SpringLog/SpringLog.h"

#define LOG_SECTION "model"

#include <filesystem>

#include "System/Misc/TracyDefs.h"

SolidObjectDecalDef::SolidObjectDecalDef()
	: useGroundDecal(false)
	, groundDecalType(-1)
	, groundDecalSizeX(-1)
	, groundDecalSizeY(-1)
	, groundDecalDecaySpeed(0.0f)

	, leaveTrackDecals(false)
	//, trackDecalType(-1)
	, trackDecalWidth(0.0f)
	, trackDecalOffset(0.0f)
	, trackDecalStrength(0.0f)
	, trackDecalStretch(0.0f)
{}

void SolidObjectDecalDef::Parse(const LuaTable& table) {
	groundDecalTypeName = table.GetString("groundDecalType", table.GetString("buildingGroundDecalType", ""));
	trackDecalTypeName = table.GetString("trackType", "StdTank");

	useGroundDecal        = table.GetBool("useGroundDecal", table.GetBool("useBuildingGroundDecal", false));
	groundDecalType       = -1;
	groundDecalSizeX      = table.GetInt("groundDecalSizeX", table.GetInt("buildingGroundDecalSizeX", 4));
	groundDecalSizeY      = table.GetInt("groundDecalSizeY", table.GetInt("buildingGroundDecalSizeY", 4));
	groundDecalDecaySpeed = table.GetFloat("groundDecalDecaySpeed", table.GetFloat("buildingGroundDecalDecaySpeed", 0.1f));

	leaveTrackDecals   = table.GetBool("leaveTracks", false);
	//trackDecalType     = -1;
	trackDecalWidth    = table.GetFloat("trackWidth",   32.0f);
	trackDecalOffset   = table.GetFloat("trackOffset",   0.0f);
	trackDecalStrength = table.GetFloat("trackStrength", 0.0f);
	trackDecalStretch  = table.GetFloat("trackStretch",  1.0f);
}

SolidObjectDef::SolidObjectDef()
	: id(-1)

	, xsize(0)
	, zsize(0)

	, cost(0.0f)
	, health(0.0f)
	, mass(0.0f)
	, crushResistance(0.0f)

	, collidable(false)
	, selectable(true)
	, upright(false)
	, reclaimable(true)

	, model(nullptr)
{
}


void SolidObjectDef::PreloadModel() const
{
	(void)LoadModel();
}

S3DModel* SolidObjectDef::LoadModel() const
{
	// The server doesn't render, but it does need each unit's piece
	// tree (offsets, names, hierarchy) so unit scripts can call Move /
	// Turn against named pieces and the sim can compute weapon-fire
	// origins. The geometry data comes from a sidecar `.config.lua`
	// (hand-authored) or `.config.json` (machine-generated by
	// modelimporter) that ships next to each `.glb` in the processed
	// game's models dir. We skip the actual mesh data — only the piece
	// metadata is meaningful for sim-side animation.
	if (model != nullptr)
		return model;
	if (modelName.empty())
		return nullptr;

	// Strip any extension on modelName ("strikecom.s3o" → "strikecom")
	// and probe for the sidecar file via CFileHandler. A direct
	// fs::exists test off the bare name handles the common case where
	// the processed-models dir was added as a content root in
	// server_main.cpp; ResolvePath also lets the lookup be
	// case-insensitive (Spring def files reference models with mixed
	// case while the on-disk path is lowercase).
	namespace fs = std::filesystem;
	const std::string stem = fs::path(modelName).stem().string();

	// Probe order matches ModelConfigLoader's precedence: Lua wins.
	std::string basePath;
	const std::string luaName  = stem + LuaConfig::kLuaSuffix;
	const std::string jsonName = stem + LuaConfig::kJsonSuffix;
	std::string resolved;
	if (CFileHandler::FileExists(luaName, SPRING_VFS_MOD))
		resolved = CFileHandler::GetFileAbsolutePath(luaName, SPRING_VFS_MOD);
	else if (CFileHandler::FileExists(jsonName, SPRING_VFS_MOD))
		resolved = CFileHandler::GetFileAbsolutePath(jsonName, SPRING_VFS_MOD);
	if (!resolved.empty()) {
		// Strip the suffix to get the base path the loader expects.
		const fs::path p(resolved);
		basePath = (p.parent_path() / stem).string();
	}

	if (basePath.empty()) {
		SLOG(SPRING_LOG_NOTICE,
			"[SolidObjectDef::LoadModel] no sidecar for '%s' (stem='%s')",
			modelName.c_str(), stem.c_str());
		return nullptr;
	}

	model = ModelConfigLoader::Load(basePath);
	if (model != nullptr) {
		model->name = stem;
	}
	return model;
}

float SolidObjectDef::GetModelRadius() const
{
	// Model loading removed: server-side headless build does not load render models.
	return 0.0f;
}


void SolidObjectDef::ParseCollisionVolume(const LuaTable& odTable)
{
	RECOIL_DETAILED_TRACY_ZONE;
	const LuaTable& cvTable = odTable.SubTable("collisionVolume");
	const std::string& cvType = odTable.GetString("collisionVolumeType", "");

	if (cvTable.IsValid()) {
		collisionVolume = CollisionVolume(
			cvTable.GetInt("type", 's'),
			cvTable.GetInt("axis", 'z'),
			cvTable.GetFloat3("scales" , ZeroVector),
			cvTable.GetFloat3("offsets", ZeroVector)
		);
	} else {
		collisionVolume = CollisionVolume(
			((cvType.empty())? 's': cvType.front()),
			((cvType.empty())? 'z': cvType.back ()),
			odTable.GetFloat3("collisionVolumeScales" , ZeroVector),
			odTable.GetFloat3("collisionVolumeOffsets", ZeroVector)
		);
	}

	// if this unit wants per-piece volumes, make
	// its main collision volume deferent and let
	// it ignore hits
	collisionVolume.SetDefaultToPieceTree(odTable.GetBool("usePieceCollisionVolumes", false));
	collisionVolume.SetDefaultToFootPrint(odTable.GetBool("useFootPrintCollisionVolume", false));
	collisionVolume.SetIgnoreHits(collisionVolume.DefaultToPieceTree());
}

void SolidObjectDef::ParseSelectionVolume(const LuaTable& odTable)
{
	RECOIL_DETAILED_TRACY_ZONE;
	const LuaTable& svTable = odTable.SubTable("selectionVolume");
	const std::string& svType = odTable.GetString("selectionVolumeType", odTable.GetString("collisionVolumeType", ""));

	if (svTable.IsValid()) {
		selectionVolume = CollisionVolume(
			svTable.GetInt("type", 's'),
			svTable.GetInt("axis", 'z'),
			svTable.GetFloat3("scales" , ZeroVector),
			svTable.GetFloat3("offsets", ZeroVector)
		);
	} else {
		selectionVolume = CollisionVolume(
			((svType.empty())? 's': svType.front()),
			((svType.empty())? 'z': svType.back ()),
			odTable.GetFloat3("selectionVolumeScales" , odTable.GetFloat3("collisionVolumeScales" , ZeroVector)),
			odTable.GetFloat3("selectionVolumeOffsets", odTable.GetFloat3("collisionVolumeOffsets", ZeroVector))
		);
	}

	selectionVolume.SetDefaultToPieceTree(odTable.GetBool("usePieceSelectionVolumes", false));
	selectionVolume.SetDefaultToFootPrint(odTable.GetBool("useFootPrintSelectionVolume", false));
	selectionVolume.SetIgnoreHits(selectionVolume.DefaultToPieceTree());
}

