// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class Ack implements flatbuffers.IUnpackableObject<AckT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Ack {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAck(bb:flatbuffers.ByteBuffer, obj?:Ack):Ack {
  return (obj || new Ack()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAck(bb:flatbuffers.ByteBuffer, obj?:Ack):Ack {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Ack()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

lastReceivedSeq():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startAck(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addLastReceivedSeq(builder:flatbuffers.Builder, lastReceivedSeq:number) {
  builder.addFieldInt32(0, lastReceivedSeq, 0);
}

static endAck(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAck(builder:flatbuffers.Builder, lastReceivedSeq:number):flatbuffers.Offset {
  Ack.startAck(builder);
  Ack.addLastReceivedSeq(builder, lastReceivedSeq);
  return Ack.endAck(builder);
}

unpack(): AckT {
  return new AckT(
    this.lastReceivedSeq()
  );
}


unpackTo(_o: AckT): void {
  _o.lastReceivedSeq = this.lastReceivedSeq();
}
}

export class AckT implements flatbuffers.IGeneratedObject {
constructor(
  public lastReceivedSeq: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return Ack.createAck(builder,
    this.lastReceivedSeq
  );
}
}
