// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class AuthRequest implements flatbuffers.IUnpackableObject<AuthRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):AuthRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAuthRequest(bb:flatbuffers.ByteBuffer, obj?:AuthRequest):AuthRequest {
  return (obj || new AuthRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAuthRequest(bb:flatbuffers.ByteBuffer, obj?:AuthRequest):AuthRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new AuthRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

username():string|null
username(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
username(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

passwordHash():string|null
passwordHash(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
passwordHash(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

token():string|null
token(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
token(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startAuthRequest(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addUsername(builder:flatbuffers.Builder, usernameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, usernameOffset, 0);
}

static addPasswordHash(builder:flatbuffers.Builder, passwordHashOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, passwordHashOffset, 0);
}

static addToken(builder:flatbuffers.Builder, tokenOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, tokenOffset, 0);
}

static endAuthRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAuthRequest(builder:flatbuffers.Builder, usernameOffset:flatbuffers.Offset, passwordHashOffset:flatbuffers.Offset, tokenOffset:flatbuffers.Offset):flatbuffers.Offset {
  AuthRequest.startAuthRequest(builder);
  AuthRequest.addUsername(builder, usernameOffset);
  AuthRequest.addPasswordHash(builder, passwordHashOffset);
  AuthRequest.addToken(builder, tokenOffset);
  return AuthRequest.endAuthRequest(builder);
}

unpack(): AuthRequestT {
  return new AuthRequestT(
    this.username(),
    this.passwordHash(),
    this.token()
  );
}


unpackTo(_o: AuthRequestT): void {
  _o.username = this.username();
  _o.passwordHash = this.passwordHash();
  _o.token = this.token();
}
}

export class AuthRequestT implements flatbuffers.IGeneratedObject {
constructor(
  public username: string|Uint8Array|null = null,
  public passwordHash: string|Uint8Array|null = null,
  public token: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const username = (this.username !== null ? builder.createString(this.username!) : 0);
  const passwordHash = (this.passwordHash !== null ? builder.createString(this.passwordHash!) : 0);
  const token = (this.token !== null ? builder.createString(this.token!) : 0);

  return AuthRequest.createAuthRequest(builder,
    username,
    passwordHash,
    token
  );
}
}
