// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ChatSend {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ChatSend {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsChatSend(bb:flatbuffers.ByteBuffer, obj?:ChatSend):ChatSend {
  return (obj || new ChatSend()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsChatSend(bb:flatbuffers.ByteBuffer, obj?:ChatSend):ChatSend {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ChatSend()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

text():string|null
text(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
text(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

destination():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

static startChatSend(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addText(builder:flatbuffers.Builder, textOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, textOffset, 0);
}

static addDestination(builder:flatbuffers.Builder, destination:number) {
  builder.addFieldInt8(1, destination, 0);
}

static endChatSend(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createChatSend(builder:flatbuffers.Builder, textOffset:flatbuffers.Offset, destination:number):flatbuffers.Offset {
  ChatSend.startChatSend(builder);
  ChatSend.addText(builder, textOffset);
  ChatSend.addDestination(builder, destination);
  return ChatSend.endChatSend(builder);
}
}
