// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Ack, AckT } from '../spring-web/ack.js';
import { AuthRequest, AuthRequestT } from '../spring-web/auth-request.js';
import { ChatSend, ChatSendT } from '../spring-web/chat-send.js';
import { ClientPayload, unionToClientPayload, unionListToClientPayload } from '../spring-web/client-payload.js';
import { Handshake, HandshakeT } from '../spring-web/handshake.js';
import { Ping, PingT } from '../spring-web/ping.js';
import { PlayerCommand, PlayerCommandT } from '../spring-web/player-command.js';
import { ReconnectRequest, ReconnectRequestT } from '../spring-web/reconnect-request.js';
import { RoomCreate, RoomCreateT } from '../spring-web/room-create.js';
import { RoomJoin, RoomJoinT } from '../spring-web/room-join.js';
import { RoomKick, RoomKickT } from '../spring-web/room-kick.js';
import { RoomLeave, RoomLeaveT } from '../spring-web/room-leave.js';
import { RoomReady, RoomReadyT } from '../spring-web/room-ready.js';
import { RoomStartGame, RoomStartGameT } from '../spring-web/room-start-game.js';
import { RoomTeamSelect, RoomTeamSelectT } from '../spring-web/room-team-select.js';
import { ViewportUpdate, ViewportUpdateT } from '../spring-web/viewport-update.js';


export class ClientMessage implements flatbuffers.IUnpackableObject<ClientMessageT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ClientMessage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsClientMessage(bb:flatbuffers.ByteBuffer, obj?:ClientMessage):ClientMessage {
  return (obj || new ClientMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsClientMessage(bb:flatbuffers.ByteBuffer, obj?:ClientMessage):ClientMessage {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ClientMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

payloadType():ClientPayload {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ClientPayload.NONE;
}

payload<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startClientMessage(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addPayloadType(builder:flatbuffers.Builder, payloadType:ClientPayload) {
  builder.addFieldInt8(0, payloadType, ClientPayload.NONE);
}

static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, payloadOffset, 0);
}

static endClientMessage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishClientMessageBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedClientMessageBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createClientMessage(builder:flatbuffers.Builder, payloadType:ClientPayload, payloadOffset:flatbuffers.Offset):flatbuffers.Offset {
  ClientMessage.startClientMessage(builder);
  ClientMessage.addPayloadType(builder, payloadType);
  ClientMessage.addPayload(builder, payloadOffset);
  return ClientMessage.endClientMessage(builder);
}

unpack(): ClientMessageT {
  return new ClientMessageT(
    this.payloadType(),
    (() => {
      const temp = unionToClientPayload(this.payloadType(), this.payload.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })()
  );
}


unpackTo(_o: ClientMessageT): void {
  _o.payloadType = this.payloadType();
  _o.payload = (() => {
      const temp = unionToClientPayload(this.payloadType(), this.payload.bind(this));
      if(temp === null) { return null; }
      return temp.unpack()
  })();
}
}

export class ClientMessageT implements flatbuffers.IGeneratedObject {
constructor(
  public payloadType: ClientPayload = ClientPayload.NONE,
  public payload: AckT|AuthRequestT|ChatSendT|HandshakeT|PingT|PlayerCommandT|ReconnectRequestT|RoomCreateT|RoomJoinT|RoomKickT|RoomLeaveT|RoomReadyT|RoomStartGameT|RoomTeamSelectT|ViewportUpdateT|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const payload = builder.createObjectOffset(this.payload);

  return ClientMessage.createClientMessage(builder,
    this.payloadType,
    payload
  );
}
}
