// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Metalstorm damage-field lifecycle (Model 3 — area bombardment, C6,
 * PLAN-metalstorm-combat-resolution.md §4). A field is an area that applies
 * `intensity` damage/sec on a fixed cadence for `duration` frames. The SIM
 * owns all damage (units inside take it via DoDamage). The client receives
 * only these Created/Removed lifecycle events and INVENTS the barrage FX
 * (procedural shell arcs + impacts scattered in the area at the given
 * cadence) — no per-shell wire traffic. Visibility-filtered per session in
 * StateStreamer::BroadcastCombatEvents by area overlap with the viewer's
 * known space (own-team fields always shown).
 */
export enum DamageFieldEventKind {
  Created = 0,
  Removed = 1
}
