// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Macro-directive type — a superset of StandingOrderType. Values 0..7
 * alias StandingOrderType 1:1 so a group-scoped classic order maps with
 * no translation; 8+ are the new platoon-level macro directives
 * (PLAN-macro-orders §2). DefendFront carries the polyline "front line"
 * shape — the first genuinely new order shape.
 */
export enum DirectiveType {
  DefendArea = 0,
  PatrolRoute = 1,
  RallyPoint = 2,
  Fallback = 3,
  Reinforce = 4,
  Screen = 5,
  SupplyRoute = 6,
  BuildBase = 7,
  MoveFormation = 8,
  Assault = 9,
  Defend = 10,
  Overwatch = 11,
  Withdraw = 12,
  Escort = 13,
  DefendFront = 14
}
