// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Vec3, Vec3T } from '../spring-web/vec3.js';


export class EntityDestroy implements flatbuffers.IUnpackableObject<EntityDestroyT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EntityDestroy {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEntityDestroy(bb:flatbuffers.ByteBuffer, obj?:EntityDestroy):EntityDestroy {
  return (obj || new EntityDestroy()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEntityDestroy(bb:flatbuffers.ByteBuffer, obj?:EntityDestroy):EntityDestroy {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EntityDestroy()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

entityId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

destructionType():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

position(obj?:Vec3):Vec3|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Vec3()).__init(this.bb_pos + offset, this.bb!) : null;
}

/**
 * Sim frame the unit actually died on, stamped at CUnit::KillUnit time
 * (not at broadcast time). L1 schedules the death on the presentation
 * timeline at this frame so it lands together with its explosion.
 * Before this field existed the client had to guess with
 * `max(last GameEventBatch frame, newest entity-state base_frame)`,
 * which is only a lower bound: the server sends no combat batch on
 * event-less ticks, and it LOS-filters those batches per viewer while
 * destroys use a different losMask. 0 = unstamped (pre-L2 server).
 */
frame():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startEntityDestroy(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addEntityId(builder:flatbuffers.Builder, entityId:number) {
  builder.addFieldInt32(0, entityId, 0);
}

static addDestructionType(builder:flatbuffers.Builder, destructionType:number) {
  builder.addFieldInt8(1, destructionType, 0);
}

static addPosition(builder:flatbuffers.Builder, positionOffset:flatbuffers.Offset) {
  builder.addFieldStruct(2, positionOffset, 0);
}

static addFrame(builder:flatbuffers.Builder, frame:number) {
  builder.addFieldInt32(3, frame, 0);
}

static endEntityDestroy(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


unpack(): EntityDestroyT {
  return new EntityDestroyT(
    this.entityId(),
    this.destructionType(),
    (this.position() !== null ? this.position()!.unpack() : null),
    this.frame()
  );
}


unpackTo(_o: EntityDestroyT): void {
  _o.entityId = this.entityId();
  _o.destructionType = this.destructionType();
  _o.position = (this.position() !== null ? this.position()!.unpack() : null);
  _o.frame = this.frame();
}
}

export class EntityDestroyT implements flatbuffers.IGeneratedObject {
constructor(
  public entityId: number = 0,
  public destructionType: number = 0,
  public position: Vec3T|null = null,
  public frame: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  EntityDestroy.startEntityDestroy(builder);
  EntityDestroy.addEntityId(builder, this.entityId);
  EntityDestroy.addDestructionType(builder, this.destructionType);
  EntityDestroy.addPosition(builder, (this.position !== null ? this.position!.pack(builder) : 0));
  EntityDestroy.addFrame(builder, this.frame);

  return EntityDestroy.endEntityDestroy(builder);
}
}
