// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Vec3 } from '../spring-web/vec3.js';


export class EntityDestroy {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EntityDestroy {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEntityDestroy(bb:flatbuffers.ByteBuffer, obj?:EntityDestroy):EntityDestroy {
  return (obj || new EntityDestroy()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEntityDestroy(bb:flatbuffers.ByteBuffer, obj?:EntityDestroy):EntityDestroy {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EntityDestroy()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

entityId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

destructionType():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

position(obj?:Vec3):Vec3|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Vec3()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startEntityDestroy(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addEntityId(builder:flatbuffers.Builder, entityId:number) {
  builder.addFieldInt32(0, entityId, 0);
}

static addDestructionType(builder:flatbuffers.Builder, destructionType:number) {
  builder.addFieldInt8(1, destructionType, 0);
}

static addPosition(builder:flatbuffers.Builder, positionOffset:flatbuffers.Offset) {
  builder.addFieldStruct(2, positionOffset, 0);
}

static endEntityDestroy(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
