// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { SensorType } from '../spring-web/sensor-type.js';


/**
 * Per-unit sensor radius override. Emitted whenever
 * `Spring.SetUnitSensorRadius` mutates a sensor on the server so the
 * client widget worker can refresh range-circle widgets immediately
 * instead of waiting for an entity-state snapshot (snapshots don't
 * re-stream the unit def — they have no field for the override).
 * `radius` is in elmos, matching `Spring.GetUnitSensorRadius`'s
 * return value. A radius of 0 means the sensor was disabled.
 */
export class EntitySensorUpdate implements flatbuffers.IUnpackableObject<EntitySensorUpdateT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EntitySensorUpdate {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEntitySensorUpdate(bb:flatbuffers.ByteBuffer, obj?:EntitySensorUpdate):EntitySensorUpdate {
  return (obj || new EntitySensorUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEntitySensorUpdate(bb:flatbuffers.ByteBuffer, obj?:EntitySensorUpdate):EntitySensorUpdate {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EntitySensorUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

entityId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

sensorType():SensorType {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : SensorType.Los;
}

radius():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startEntitySensorUpdate(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addEntityId(builder:flatbuffers.Builder, entityId:number) {
  builder.addFieldInt32(0, entityId, 0);
}

static addSensorType(builder:flatbuffers.Builder, sensorType:SensorType) {
  builder.addFieldInt8(1, sensorType, SensorType.Los);
}

static addRadius(builder:flatbuffers.Builder, radius:number) {
  builder.addFieldFloat32(2, radius, 0.0);
}

static endEntitySensorUpdate(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createEntitySensorUpdate(builder:flatbuffers.Builder, entityId:number, sensorType:SensorType, radius:number):flatbuffers.Offset {
  EntitySensorUpdate.startEntitySensorUpdate(builder);
  EntitySensorUpdate.addEntityId(builder, entityId);
  EntitySensorUpdate.addSensorType(builder, sensorType);
  EntitySensorUpdate.addRadius(builder, radius);
  return EntitySensorUpdate.endEntitySensorUpdate(builder);
}

unpack(): EntitySensorUpdateT {
  return new EntitySensorUpdateT(
    this.entityId(),
    this.sensorType(),
    this.radius()
  );
}


unpackTo(_o: EntitySensorUpdateT): void {
  _o.entityId = this.entityId();
  _o.sensorType = this.sensorType();
  _o.radius = this.radius();
}
}

export class EntitySensorUpdateT implements flatbuffers.IGeneratedObject {
constructor(
  public entityId: number = 0,
  public sensorType: SensorType = SensorType.Los,
  public radius: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return EntitySensorUpdate.createEntitySensorUpdate(builder,
    this.entityId,
    this.sensorType,
    this.radius
  );
}
}
