// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { FireOutcome } from '../spring-web/fire-outcome.js';
import { Vec3, Vec3T } from '../spring-web/vec3.js';


/**
 * PLAN-latency L2.1 — Tier-C ("cosmetic") fire outcome.
 *
 * For a weaponDef classified FX_TIER_COSMETIC the server does NOT spawn a
 * CWeaponProjectile at all. It resolves the whole shot at fire time and
 * sends this ONE event in place of the Fired / Trajectory / Impact triple.
 * Damage is still applied authoritatively on the server, scheduled on the
 * sim timeline at `impact_frame`.
 *
 * The client invents the entire visual: it schedules a spawn at
 * `fire_frame` and a detonation at `impact_frame` on the L1 presentation
 * timeline, and solves a trajectory that provably satisfies
 * `pos(fire_frame) == origin` and `pos(impact_frame) == impact_pos`. There
 * is no mid-flight correction and therefore no snap.
 */
export class FireOutcomeEvent implements flatbuffers.IUnpackableObject<FireOutcomeEventT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FireOutcomeEvent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFireOutcomeEvent(bb:flatbuffers.ByteBuffer, obj?:FireOutcomeEvent):FireOutcomeEvent {
  return (obj || new FireOutcomeEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFireOutcomeEvent(bb:flatbuffers.ByteBuffer, obj?:FireOutcomeEvent):FireOutcomeEvent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FireOutcomeEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

fireFrame():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

weaponDefId():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

ownerId():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

team():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

origin(obj?:Vec3):Vec3|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new Vec3()).__init(this.bb_pos + offset, this.bb!) : null;
}

targetId():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

targetPos(obj?:Vec3):Vec3|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new Vec3()).__init(this.bb_pos + offset, this.bb!) : null;
}

outcome():FireOutcome {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : FireOutcome.Hit;
}

impactFrame():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

impactPos(obj?:Vec3):Vec3|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? (obj || new Vec3()).__init(this.bb_pos + offset, this.bb!) : null;
}

/**
 * Per-frame gravity the server used to resolve the arc (0 for a
 * straight shot). Not in PLAN-latency-projectiles §3.1's field list,
 * but the client's closed-form solver needs it: the ballistic solution
 * through (origin, impact_pos, Δt) is only unique once g is fixed, and
 * `mygravity` is a per-projectile resolution of the def default against
 * the map gravity that the client cannot reconstruct from weaponDefs
 * alone. ProjectileFiredEvent carries it for the same reason.
 */
gravity():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startFireOutcomeEvent(builder:flatbuffers.Builder) {
  builder.startObject(11);
}

static addFireFrame(builder:flatbuffers.Builder, fireFrame:number) {
  builder.addFieldInt32(0, fireFrame, 0);
}

static addWeaponDefId(builder:flatbuffers.Builder, weaponDefId:number) {
  builder.addFieldInt16(1, weaponDefId, 0);
}

static addOwnerId(builder:flatbuffers.Builder, ownerId:number) {
  builder.addFieldInt32(2, ownerId, 0);
}

static addTeam(builder:flatbuffers.Builder, team:number) {
  builder.addFieldInt8(3, team, 0);
}

static addOrigin(builder:flatbuffers.Builder, originOffset:flatbuffers.Offset) {
  builder.addFieldStruct(4, originOffset, 0);
}

static addTargetId(builder:flatbuffers.Builder, targetId:number) {
  builder.addFieldInt32(5, targetId, 0);
}

static addTargetPos(builder:flatbuffers.Builder, targetPosOffset:flatbuffers.Offset) {
  builder.addFieldStruct(6, targetPosOffset, 0);
}

static addOutcome(builder:flatbuffers.Builder, outcome:FireOutcome) {
  builder.addFieldInt8(7, outcome, FireOutcome.Hit);
}

static addImpactFrame(builder:flatbuffers.Builder, impactFrame:number) {
  builder.addFieldInt32(8, impactFrame, 0);
}

static addImpactPos(builder:flatbuffers.Builder, impactPosOffset:flatbuffers.Offset) {
  builder.addFieldStruct(9, impactPosOffset, 0);
}

static addGravity(builder:flatbuffers.Builder, gravity:number) {
  builder.addFieldFloat32(10, gravity, 0.0);
}

static endFireOutcomeEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


unpack(): FireOutcomeEventT {
  return new FireOutcomeEventT(
    this.fireFrame(),
    this.weaponDefId(),
    this.ownerId(),
    this.team(),
    (this.origin() !== null ? this.origin()!.unpack() : null),
    this.targetId(),
    (this.targetPos() !== null ? this.targetPos()!.unpack() : null),
    this.outcome(),
    this.impactFrame(),
    (this.impactPos() !== null ? this.impactPos()!.unpack() : null),
    this.gravity()
  );
}


unpackTo(_o: FireOutcomeEventT): void {
  _o.fireFrame = this.fireFrame();
  _o.weaponDefId = this.weaponDefId();
  _o.ownerId = this.ownerId();
  _o.team = this.team();
  _o.origin = (this.origin() !== null ? this.origin()!.unpack() : null);
  _o.targetId = this.targetId();
  _o.targetPos = (this.targetPos() !== null ? this.targetPos()!.unpack() : null);
  _o.outcome = this.outcome();
  _o.impactFrame = this.impactFrame();
  _o.impactPos = (this.impactPos() !== null ? this.impactPos()!.unpack() : null);
  _o.gravity = this.gravity();
}
}

export class FireOutcomeEventT implements flatbuffers.IGeneratedObject {
constructor(
  public fireFrame: number = 0,
  public weaponDefId: number = 0,
  public ownerId: number = 0,
  public team: number = 0,
  public origin: Vec3T|null = null,
  public targetId: number = 0,
  public targetPos: Vec3T|null = null,
  public outcome: FireOutcome = FireOutcome.Hit,
  public impactFrame: number = 0,
  public impactPos: Vec3T|null = null,
  public gravity: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  FireOutcomeEvent.startFireOutcomeEvent(builder);
  FireOutcomeEvent.addFireFrame(builder, this.fireFrame);
  FireOutcomeEvent.addWeaponDefId(builder, this.weaponDefId);
  FireOutcomeEvent.addOwnerId(builder, this.ownerId);
  FireOutcomeEvent.addTeam(builder, this.team);
  FireOutcomeEvent.addOrigin(builder, (this.origin !== null ? this.origin!.pack(builder) : 0));
  FireOutcomeEvent.addTargetId(builder, this.targetId);
  FireOutcomeEvent.addTargetPos(builder, (this.targetPos !== null ? this.targetPos!.pack(builder) : 0));
  FireOutcomeEvent.addOutcome(builder, this.outcome);
  FireOutcomeEvent.addImpactFrame(builder, this.impactFrame);
  FireOutcomeEvent.addImpactPos(builder, (this.impactPos !== null ? this.impactPos!.pack(builder) : 0));
  FireOutcomeEvent.addGravity(builder, this.gravity);

  return FireOutcomeEvent.endFireOutcomeEvent(builder);
}
}
