// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CustomParam, CustomParamT } from '../spring-web/custom-param.js';


/**
 * Definition of one unit type. Sent once at game start so the client
 * knows what model/texture to load for each def_id it sees in entity
 * state snapshots. Parallel to MapFeatureDef but for dynamic entities.
 *
 * `model_url` and `texture_url` are HTTP paths relative to the game
 * server root, pointing at preprocessed `.glb` and `.png` files under
 * `data/games/<gameId>/models/`. Either may be empty if the unit type
 * has no model or preprocessing failed — the client falls back to a
 * coloured procedural shape.
 */
export class GameUnitDef implements flatbuffers.IUnpackableObject<GameUnitDefT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GameUnitDef {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGameUnitDef(bb:flatbuffers.ByteBuffer, obj?:GameUnitDef):GameUnitDef {
  return (obj || new GameUnitDef()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGameUnitDef(bb:flatbuffers.ByteBuffer, obj?:GameUnitDef):GameUnitDef {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GameUnitDef()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

defId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

modelUrl():string|null
modelUrl(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
modelUrl(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

textureUrl():string|null
textureUrl(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
textureUrl(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

humanName():string|null
humanName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
humanName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

tooltip():string|null
tooltip(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
tooltip(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

wreckName():string|null
wreckName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
wreckName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

metalCost():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

energyCost():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

buildTime():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

metalMake():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

energyMake():number {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

metalUpkeep():number {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

energyUpkeep():number {
  const offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

metalStorage():number {
  const offset = this.bb!.__offset(this.bb_pos, 32);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

energyStorage():number {
  const offset = this.bb!.__offset(this.bb_pos, 34);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

extractsMetal():number {
  const offset = this.bb!.__offset(this.bb_pos, 36);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

health():number {
  const offset = this.bb!.__offset(this.bb_pos, 38);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

mass():number {
  const offset = this.bb!.__offset(this.bb_pos, 40);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

radius():number {
  const offset = this.bb!.__offset(this.bb_pos, 42);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

xsize():number {
  const offset = this.bb!.__offset(this.bb_pos, 44);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

zsize():number {
  const offset = this.bb!.__offset(this.bb_pos, 46);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

speed():number {
  const offset = this.bb!.__offset(this.bb_pos, 48);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

turnRate():number {
  const offset = this.bb!.__offset(this.bb_pos, 50);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

maxAcc():number {
  const offset = this.bb!.__offset(this.bb_pos, 52);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

maxDec():number {
  const offset = this.bb!.__offset(this.bb_pos, 54);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

losRadius():number {
  const offset = this.bb!.__offset(this.bb_pos, 56);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

airLosRadius():number {
  const offset = this.bb!.__offset(this.bb_pos, 58);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

radarRadius():number {
  const offset = this.bb!.__offset(this.bb_pos, 60);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

sonarRadius():number {
  const offset = this.bb!.__offset(this.bb_pos, 62);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

jammerRadius():number {
  const offset = this.bb!.__offset(this.bb_pos, 64);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

seismicRadius():number {
  const offset = this.bb!.__offset(this.bb_pos, 66);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

flags():number {
  const offset = this.bb!.__offset(this.bb_pos, 68);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

buildDistance():number {
  const offset = this.bb!.__offset(this.bb_pos, 70);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

buildSpeed():number {
  const offset = this.bb!.__offset(this.bb_pos, 72);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * def_ids of every unit this builder can construct.
 */
buildOptions(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 74);
  return offset ? this.bb!.readUint16(this.bb!.__vector(this.bb_pos + offset) + index * 2) : 0;
}

buildOptionsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 74);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

buildOptionsArray():Uint16Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 74);
  return offset ? new Uint16Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

/**
 * def_ids of weapons this unit carries (in MAX_WEAPONS slots,
 * 0 for unused). Indexes into the weapondef table the client
 * already has via GameWeaponDef streaming.
 */
weaponDefIds(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 76);
  return offset ? this.bb!.readUint16(this.bb!.__vector(this.bb_pos + offset) + index * 2) : 0;
}

weaponDefIdsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 76);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

weaponDefIdsArray():Uint16Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 76);
  return offset ? new Uint16Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

/**
 * Game-specific key/value extensions. ZK widgets read commtype,
 * level, dynamic_comm, planetwars_structure, child_of_factory,
 * thrower_gather, nuke_coverage, hide, helptext, and many more.
 * Empty unless the unitdef has any customParams entries.
 */
customParams(index: number, obj?:CustomParam):CustomParam|null {
  const offset = this.bb!.__offset(this.bb_pos, 78);
  return offset ? (obj || new CustomParam()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

customParamsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 78);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

/**
 * Rare fields ZK widgets occasionally read. Default 0 / empty.
 */
repairSpeed():number {
  const offset = this.bb!.__offset(this.bb_pos, 80);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

transportSize():number {
  const offset = this.bb!.__offset(this.bb_pos, 82);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

transportMass():number {
  const offset = this.bb!.__offset(this.bb_pos, 84);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

transportCapacity():number {
  const offset = this.bb!.__offset(this.bb_pos, 86);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

/**
 * Yardmap string (factory placement footprint), e.g. "yyy yyy yyy".
 */
yardmap():string|null
yardmap(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
yardmap(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 88);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * SolidObjectDef.script — animation script filename (e.g.
 * "scripts/armcom1.cob" or "scripts/armcom1.lua").
 */
script():string|null
script(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
script(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 90);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * Pre-rendered icon path for build menu (relative to game base).
 */
buildPic():string|null
buildPic(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
buildPic(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 92);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

/**
 * Maximum velocity (different from speed for some unit types).
 */
maxVelocity():number {
  const offset = this.bb!.__offset(this.bb_pos, 94);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * Build cost float (combined). Some widgets read this directly.
 */
cost():number {
  const offset = this.bb!.__offset(this.bb_pos, 96);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * Maximum range (max of all weapon ranges, derived).
 */
maxWeaponRange():number {
  const offset = this.bb!.__offset(this.bb_pos, 98);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * Maximum copies of this unit allowed per team. 0 = unlimited.
 */
maxThisUnit():number {
  const offset = this.bb!.__offset(this.bb_pos, 100);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

/**
 * Number of build power required to construct this unit.
 */
canBeAssisted():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 102);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

/**
 * Whether this unit can self-destruct (separate from canKamikaze).
 */
canSelfDestruct():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 104);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

/**
 * Self-destruct countdown in seconds.
 */
selfDCountdown():number {
  const offset = this.bb!.__offset(this.bb_pos, 106);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

/**
 * Build pic / unit category for build menus.
 * Spring's category bitfield (terrain/movement/factory).
 */
categoryBits():number {
  const offset = this.bb!.__offset(this.bb_pos, 108);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startGameUnitDef(builder:flatbuffers.Builder) {
  builder.startObject(53);
}

static addDefId(builder:flatbuffers.Builder, defId:number) {
  builder.addFieldInt16(0, defId, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static addModelUrl(builder:flatbuffers.Builder, modelUrlOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, modelUrlOffset, 0);
}

static addTextureUrl(builder:flatbuffers.Builder, textureUrlOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, textureUrlOffset, 0);
}

static addHumanName(builder:flatbuffers.Builder, humanNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, humanNameOffset, 0);
}

static addTooltip(builder:flatbuffers.Builder, tooltipOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, tooltipOffset, 0);
}

static addWreckName(builder:flatbuffers.Builder, wreckNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, wreckNameOffset, 0);
}

static addMetalCost(builder:flatbuffers.Builder, metalCost:number) {
  builder.addFieldFloat32(7, metalCost, 0.0);
}

static addEnergyCost(builder:flatbuffers.Builder, energyCost:number) {
  builder.addFieldFloat32(8, energyCost, 0.0);
}

static addBuildTime(builder:flatbuffers.Builder, buildTime:number) {
  builder.addFieldFloat32(9, buildTime, 0.0);
}

static addMetalMake(builder:flatbuffers.Builder, metalMake:number) {
  builder.addFieldFloat32(10, metalMake, 0.0);
}

static addEnergyMake(builder:flatbuffers.Builder, energyMake:number) {
  builder.addFieldFloat32(11, energyMake, 0.0);
}

static addMetalUpkeep(builder:flatbuffers.Builder, metalUpkeep:number) {
  builder.addFieldFloat32(12, metalUpkeep, 0.0);
}

static addEnergyUpkeep(builder:flatbuffers.Builder, energyUpkeep:number) {
  builder.addFieldFloat32(13, energyUpkeep, 0.0);
}

static addMetalStorage(builder:flatbuffers.Builder, metalStorage:number) {
  builder.addFieldFloat32(14, metalStorage, 0.0);
}

static addEnergyStorage(builder:flatbuffers.Builder, energyStorage:number) {
  builder.addFieldFloat32(15, energyStorage, 0.0);
}

static addExtractsMetal(builder:flatbuffers.Builder, extractsMetal:number) {
  builder.addFieldFloat32(16, extractsMetal, 0.0);
}

static addHealth(builder:flatbuffers.Builder, health:number) {
  builder.addFieldFloat32(17, health, 0.0);
}

static addMass(builder:flatbuffers.Builder, mass:number) {
  builder.addFieldFloat32(18, mass, 0.0);
}

static addRadius(builder:flatbuffers.Builder, radius:number) {
  builder.addFieldFloat32(19, radius, 0.0);
}

static addXsize(builder:flatbuffers.Builder, xsize:number) {
  builder.addFieldInt32(20, xsize, 0);
}

static addZsize(builder:flatbuffers.Builder, zsize:number) {
  builder.addFieldInt32(21, zsize, 0);
}

static addSpeed(builder:flatbuffers.Builder, speed:number) {
  builder.addFieldFloat32(22, speed, 0.0);
}

static addTurnRate(builder:flatbuffers.Builder, turnRate:number) {
  builder.addFieldFloat32(23, turnRate, 0.0);
}

static addMaxAcc(builder:flatbuffers.Builder, maxAcc:number) {
  builder.addFieldFloat32(24, maxAcc, 0.0);
}

static addMaxDec(builder:flatbuffers.Builder, maxDec:number) {
  builder.addFieldFloat32(25, maxDec, 0.0);
}

static addLosRadius(builder:flatbuffers.Builder, losRadius:number) {
  builder.addFieldFloat32(26, losRadius, 0.0);
}

static addAirLosRadius(builder:flatbuffers.Builder, airLosRadius:number) {
  builder.addFieldFloat32(27, airLosRadius, 0.0);
}

static addRadarRadius(builder:flatbuffers.Builder, radarRadius:number) {
  builder.addFieldInt32(28, radarRadius, 0);
}

static addSonarRadius(builder:flatbuffers.Builder, sonarRadius:number) {
  builder.addFieldInt32(29, sonarRadius, 0);
}

static addJammerRadius(builder:flatbuffers.Builder, jammerRadius:number) {
  builder.addFieldInt32(30, jammerRadius, 0);
}

static addSeismicRadius(builder:flatbuffers.Builder, seismicRadius:number) {
  builder.addFieldInt32(31, seismicRadius, 0);
}

static addFlags(builder:flatbuffers.Builder, flags:number) {
  builder.addFieldInt32(32, flags, 0);
}

static addBuildDistance(builder:flatbuffers.Builder, buildDistance:number) {
  builder.addFieldFloat32(33, buildDistance, 0.0);
}

static addBuildSpeed(builder:flatbuffers.Builder, buildSpeed:number) {
  builder.addFieldFloat32(34, buildSpeed, 0.0);
}

static addBuildOptions(builder:flatbuffers.Builder, buildOptionsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(35, buildOptionsOffset, 0);
}

static createBuildOptionsVector(builder:flatbuffers.Builder, data:number[]|Uint16Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createBuildOptionsVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createBuildOptionsVector(builder:flatbuffers.Builder, data:number[]|Uint16Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(2, data.length, 2);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt16(data[i]!);
  }
  return builder.endVector();
}

static startBuildOptionsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(2, numElems, 2);
}

static addWeaponDefIds(builder:flatbuffers.Builder, weaponDefIdsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(36, weaponDefIdsOffset, 0);
}

static createWeaponDefIdsVector(builder:flatbuffers.Builder, data:number[]|Uint16Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createWeaponDefIdsVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createWeaponDefIdsVector(builder:flatbuffers.Builder, data:number[]|Uint16Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(2, data.length, 2);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt16(data[i]!);
  }
  return builder.endVector();
}

static startWeaponDefIdsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(2, numElems, 2);
}

static addCustomParams(builder:flatbuffers.Builder, customParamsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(37, customParamsOffset, 0);
}

static createCustomParamsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startCustomParamsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addRepairSpeed(builder:flatbuffers.Builder, repairSpeed:number) {
  builder.addFieldFloat32(38, repairSpeed, 0.0);
}

static addTransportSize(builder:flatbuffers.Builder, transportSize:number) {
  builder.addFieldInt32(39, transportSize, 0);
}

static addTransportMass(builder:flatbuffers.Builder, transportMass:number) {
  builder.addFieldFloat32(40, transportMass, 0.0);
}

static addTransportCapacity(builder:flatbuffers.Builder, transportCapacity:number) {
  builder.addFieldInt32(41, transportCapacity, 0);
}

static addYardmap(builder:flatbuffers.Builder, yardmapOffset:flatbuffers.Offset) {
  builder.addFieldOffset(42, yardmapOffset, 0);
}

static addScript(builder:flatbuffers.Builder, scriptOffset:flatbuffers.Offset) {
  builder.addFieldOffset(43, scriptOffset, 0);
}

static addBuildPic(builder:flatbuffers.Builder, buildPicOffset:flatbuffers.Offset) {
  builder.addFieldOffset(44, buildPicOffset, 0);
}

static addMaxVelocity(builder:flatbuffers.Builder, maxVelocity:number) {
  builder.addFieldFloat32(45, maxVelocity, 0.0);
}

static addCost(builder:flatbuffers.Builder, cost:number) {
  builder.addFieldFloat32(46, cost, 0.0);
}

static addMaxWeaponRange(builder:flatbuffers.Builder, maxWeaponRange:number) {
  builder.addFieldFloat32(47, maxWeaponRange, 0.0);
}

static addMaxThisUnit(builder:flatbuffers.Builder, maxThisUnit:number) {
  builder.addFieldInt32(48, maxThisUnit, 0);
}

static addCanBeAssisted(builder:flatbuffers.Builder, canBeAssisted:boolean) {
  builder.addFieldInt8(49, +canBeAssisted, +true);
}

static addCanSelfDestruct(builder:flatbuffers.Builder, canSelfDestruct:boolean) {
  builder.addFieldInt8(50, +canSelfDestruct, +true);
}

static addSelfDCountdown(builder:flatbuffers.Builder, selfDCountdown:number) {
  builder.addFieldInt32(51, selfDCountdown, 0);
}

static addCategoryBits(builder:flatbuffers.Builder, categoryBits:number) {
  builder.addFieldInt32(52, categoryBits, 0);
}

static endGameUnitDef(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGameUnitDef(builder:flatbuffers.Builder, defId:number, nameOffset:flatbuffers.Offset, modelUrlOffset:flatbuffers.Offset, textureUrlOffset:flatbuffers.Offset, humanNameOffset:flatbuffers.Offset, tooltipOffset:flatbuffers.Offset, wreckNameOffset:flatbuffers.Offset, metalCost:number, energyCost:number, buildTime:number, metalMake:number, energyMake:number, metalUpkeep:number, energyUpkeep:number, metalStorage:number, energyStorage:number, extractsMetal:number, health:number, mass:number, radius:number, xsize:number, zsize:number, speed:number, turnRate:number, maxAcc:number, maxDec:number, losRadius:number, airLosRadius:number, radarRadius:number, sonarRadius:number, jammerRadius:number, seismicRadius:number, flags:number, buildDistance:number, buildSpeed:number, buildOptionsOffset:flatbuffers.Offset, weaponDefIdsOffset:flatbuffers.Offset, customParamsOffset:flatbuffers.Offset, repairSpeed:number, transportSize:number, transportMass:number, transportCapacity:number, yardmapOffset:flatbuffers.Offset, scriptOffset:flatbuffers.Offset, buildPicOffset:flatbuffers.Offset, maxVelocity:number, cost:number, maxWeaponRange:number, maxThisUnit:number, canBeAssisted:boolean, canSelfDestruct:boolean, selfDCountdown:number, categoryBits:number):flatbuffers.Offset {
  GameUnitDef.startGameUnitDef(builder);
  GameUnitDef.addDefId(builder, defId);
  GameUnitDef.addName(builder, nameOffset);
  GameUnitDef.addModelUrl(builder, modelUrlOffset);
  GameUnitDef.addTextureUrl(builder, textureUrlOffset);
  GameUnitDef.addHumanName(builder, humanNameOffset);
  GameUnitDef.addTooltip(builder, tooltipOffset);
  GameUnitDef.addWreckName(builder, wreckNameOffset);
  GameUnitDef.addMetalCost(builder, metalCost);
  GameUnitDef.addEnergyCost(builder, energyCost);
  GameUnitDef.addBuildTime(builder, buildTime);
  GameUnitDef.addMetalMake(builder, metalMake);
  GameUnitDef.addEnergyMake(builder, energyMake);
  GameUnitDef.addMetalUpkeep(builder, metalUpkeep);
  GameUnitDef.addEnergyUpkeep(builder, energyUpkeep);
  GameUnitDef.addMetalStorage(builder, metalStorage);
  GameUnitDef.addEnergyStorage(builder, energyStorage);
  GameUnitDef.addExtractsMetal(builder, extractsMetal);
  GameUnitDef.addHealth(builder, health);
  GameUnitDef.addMass(builder, mass);
  GameUnitDef.addRadius(builder, radius);
  GameUnitDef.addXsize(builder, xsize);
  GameUnitDef.addZsize(builder, zsize);
  GameUnitDef.addSpeed(builder, speed);
  GameUnitDef.addTurnRate(builder, turnRate);
  GameUnitDef.addMaxAcc(builder, maxAcc);
  GameUnitDef.addMaxDec(builder, maxDec);
  GameUnitDef.addLosRadius(builder, losRadius);
  GameUnitDef.addAirLosRadius(builder, airLosRadius);
  GameUnitDef.addRadarRadius(builder, radarRadius);
  GameUnitDef.addSonarRadius(builder, sonarRadius);
  GameUnitDef.addJammerRadius(builder, jammerRadius);
  GameUnitDef.addSeismicRadius(builder, seismicRadius);
  GameUnitDef.addFlags(builder, flags);
  GameUnitDef.addBuildDistance(builder, buildDistance);
  GameUnitDef.addBuildSpeed(builder, buildSpeed);
  GameUnitDef.addBuildOptions(builder, buildOptionsOffset);
  GameUnitDef.addWeaponDefIds(builder, weaponDefIdsOffset);
  GameUnitDef.addCustomParams(builder, customParamsOffset);
  GameUnitDef.addRepairSpeed(builder, repairSpeed);
  GameUnitDef.addTransportSize(builder, transportSize);
  GameUnitDef.addTransportMass(builder, transportMass);
  GameUnitDef.addTransportCapacity(builder, transportCapacity);
  GameUnitDef.addYardmap(builder, yardmapOffset);
  GameUnitDef.addScript(builder, scriptOffset);
  GameUnitDef.addBuildPic(builder, buildPicOffset);
  GameUnitDef.addMaxVelocity(builder, maxVelocity);
  GameUnitDef.addCost(builder, cost);
  GameUnitDef.addMaxWeaponRange(builder, maxWeaponRange);
  GameUnitDef.addMaxThisUnit(builder, maxThisUnit);
  GameUnitDef.addCanBeAssisted(builder, canBeAssisted);
  GameUnitDef.addCanSelfDestruct(builder, canSelfDestruct);
  GameUnitDef.addSelfDCountdown(builder, selfDCountdown);
  GameUnitDef.addCategoryBits(builder, categoryBits);
  return GameUnitDef.endGameUnitDef(builder);
}

unpack(): GameUnitDefT {
  return new GameUnitDefT(
    this.defId(),
    this.name(),
    this.modelUrl(),
    this.textureUrl(),
    this.humanName(),
    this.tooltip(),
    this.wreckName(),
    this.metalCost(),
    this.energyCost(),
    this.buildTime(),
    this.metalMake(),
    this.energyMake(),
    this.metalUpkeep(),
    this.energyUpkeep(),
    this.metalStorage(),
    this.energyStorage(),
    this.extractsMetal(),
    this.health(),
    this.mass(),
    this.radius(),
    this.xsize(),
    this.zsize(),
    this.speed(),
    this.turnRate(),
    this.maxAcc(),
    this.maxDec(),
    this.losRadius(),
    this.airLosRadius(),
    this.radarRadius(),
    this.sonarRadius(),
    this.jammerRadius(),
    this.seismicRadius(),
    this.flags(),
    this.buildDistance(),
    this.buildSpeed(),
    this.bb!.createScalarList<number>(this.buildOptions.bind(this), this.buildOptionsLength()),
    this.bb!.createScalarList<number>(this.weaponDefIds.bind(this), this.weaponDefIdsLength()),
    this.bb!.createObjList<CustomParam, CustomParamT>(this.customParams.bind(this), this.customParamsLength()),
    this.repairSpeed(),
    this.transportSize(),
    this.transportMass(),
    this.transportCapacity(),
    this.yardmap(),
    this.script(),
    this.buildPic(),
    this.maxVelocity(),
    this.cost(),
    this.maxWeaponRange(),
    this.maxThisUnit(),
    this.canBeAssisted(),
    this.canSelfDestruct(),
    this.selfDCountdown(),
    this.categoryBits()
  );
}


unpackTo(_o: GameUnitDefT): void {
  _o.defId = this.defId();
  _o.name = this.name();
  _o.modelUrl = this.modelUrl();
  _o.textureUrl = this.textureUrl();
  _o.humanName = this.humanName();
  _o.tooltip = this.tooltip();
  _o.wreckName = this.wreckName();
  _o.metalCost = this.metalCost();
  _o.energyCost = this.energyCost();
  _o.buildTime = this.buildTime();
  _o.metalMake = this.metalMake();
  _o.energyMake = this.energyMake();
  _o.metalUpkeep = this.metalUpkeep();
  _o.energyUpkeep = this.energyUpkeep();
  _o.metalStorage = this.metalStorage();
  _o.energyStorage = this.energyStorage();
  _o.extractsMetal = this.extractsMetal();
  _o.health = this.health();
  _o.mass = this.mass();
  _o.radius = this.radius();
  _o.xsize = this.xsize();
  _o.zsize = this.zsize();
  _o.speed = this.speed();
  _o.turnRate = this.turnRate();
  _o.maxAcc = this.maxAcc();
  _o.maxDec = this.maxDec();
  _o.losRadius = this.losRadius();
  _o.airLosRadius = this.airLosRadius();
  _o.radarRadius = this.radarRadius();
  _o.sonarRadius = this.sonarRadius();
  _o.jammerRadius = this.jammerRadius();
  _o.seismicRadius = this.seismicRadius();
  _o.flags = this.flags();
  _o.buildDistance = this.buildDistance();
  _o.buildSpeed = this.buildSpeed();
  _o.buildOptions = this.bb!.createScalarList<number>(this.buildOptions.bind(this), this.buildOptionsLength());
  _o.weaponDefIds = this.bb!.createScalarList<number>(this.weaponDefIds.bind(this), this.weaponDefIdsLength());
  _o.customParams = this.bb!.createObjList<CustomParam, CustomParamT>(this.customParams.bind(this), this.customParamsLength());
  _o.repairSpeed = this.repairSpeed();
  _o.transportSize = this.transportSize();
  _o.transportMass = this.transportMass();
  _o.transportCapacity = this.transportCapacity();
  _o.yardmap = this.yardmap();
  _o.script = this.script();
  _o.buildPic = this.buildPic();
  _o.maxVelocity = this.maxVelocity();
  _o.cost = this.cost();
  _o.maxWeaponRange = this.maxWeaponRange();
  _o.maxThisUnit = this.maxThisUnit();
  _o.canBeAssisted = this.canBeAssisted();
  _o.canSelfDestruct = this.canSelfDestruct();
  _o.selfDCountdown = this.selfDCountdown();
  _o.categoryBits = this.categoryBits();
}
}

export class GameUnitDefT implements flatbuffers.IGeneratedObject {
constructor(
  public defId: number = 0,
  public name: string|Uint8Array|null = null,
  public modelUrl: string|Uint8Array|null = null,
  public textureUrl: string|Uint8Array|null = null,
  public humanName: string|Uint8Array|null = null,
  public tooltip: string|Uint8Array|null = null,
  public wreckName: string|Uint8Array|null = null,
  public metalCost: number = 0.0,
  public energyCost: number = 0.0,
  public buildTime: number = 0.0,
  public metalMake: number = 0.0,
  public energyMake: number = 0.0,
  public metalUpkeep: number = 0.0,
  public energyUpkeep: number = 0.0,
  public metalStorage: number = 0.0,
  public energyStorage: number = 0.0,
  public extractsMetal: number = 0.0,
  public health: number = 0.0,
  public mass: number = 0.0,
  public radius: number = 0.0,
  public xsize: number = 0,
  public zsize: number = 0,
  public speed: number = 0.0,
  public turnRate: number = 0.0,
  public maxAcc: number = 0.0,
  public maxDec: number = 0.0,
  public losRadius: number = 0.0,
  public airLosRadius: number = 0.0,
  public radarRadius: number = 0,
  public sonarRadius: number = 0,
  public jammerRadius: number = 0,
  public seismicRadius: number = 0,
  public flags: number = 0,
  public buildDistance: number = 0.0,
  public buildSpeed: number = 0.0,
  public buildOptions: (number)[] = [],
  public weaponDefIds: (number)[] = [],
  public customParams: (CustomParamT)[] = [],
  public repairSpeed: number = 0.0,
  public transportSize: number = 0,
  public transportMass: number = 0.0,
  public transportCapacity: number = 0,
  public yardmap: string|Uint8Array|null = null,
  public script: string|Uint8Array|null = null,
  public buildPic: string|Uint8Array|null = null,
  public maxVelocity: number = 0.0,
  public cost: number = 0.0,
  public maxWeaponRange: number = 0.0,
  public maxThisUnit: number = 0,
  public canBeAssisted: boolean = true,
  public canSelfDestruct: boolean = true,
  public selfDCountdown: number = 0,
  public categoryBits: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const name = (this.name !== null ? builder.createString(this.name!) : 0);
  const modelUrl = (this.modelUrl !== null ? builder.createString(this.modelUrl!) : 0);
  const textureUrl = (this.textureUrl !== null ? builder.createString(this.textureUrl!) : 0);
  const humanName = (this.humanName !== null ? builder.createString(this.humanName!) : 0);
  const tooltip = (this.tooltip !== null ? builder.createString(this.tooltip!) : 0);
  const wreckName = (this.wreckName !== null ? builder.createString(this.wreckName!) : 0);
  const buildOptions = GameUnitDef.createBuildOptionsVector(builder, this.buildOptions);
  const weaponDefIds = GameUnitDef.createWeaponDefIdsVector(builder, this.weaponDefIds);
  const customParams = GameUnitDef.createCustomParamsVector(builder, builder.createObjectOffsetList(this.customParams));
  const yardmap = (this.yardmap !== null ? builder.createString(this.yardmap!) : 0);
  const script = (this.script !== null ? builder.createString(this.script!) : 0);
  const buildPic = (this.buildPic !== null ? builder.createString(this.buildPic!) : 0);

  return GameUnitDef.createGameUnitDef(builder,
    this.defId,
    name,
    modelUrl,
    textureUrl,
    humanName,
    tooltip,
    wreckName,
    this.metalCost,
    this.energyCost,
    this.buildTime,
    this.metalMake,
    this.energyMake,
    this.metalUpkeep,
    this.energyUpkeep,
    this.metalStorage,
    this.energyStorage,
    this.extractsMetal,
    this.health,
    this.mass,
    this.radius,
    this.xsize,
    this.zsize,
    this.speed,
    this.turnRate,
    this.maxAcc,
    this.maxDec,
    this.losRadius,
    this.airLosRadius,
    this.radarRadius,
    this.sonarRadius,
    this.jammerRadius,
    this.seismicRadius,
    this.flags,
    this.buildDistance,
    this.buildSpeed,
    buildOptions,
    weaponDefIds,
    customParams,
    this.repairSpeed,
    this.transportSize,
    this.transportMass,
    this.transportCapacity,
    yardmap,
    script,
    buildPic,
    this.maxVelocity,
    this.cost,
    this.maxWeaponRange,
    this.maxThisUnit,
    this.canBeAssisted,
    this.canSelfDestruct,
    this.selfDCountdown,
    this.categoryBits
  );
}
}
