// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { CegProperty, CegPropertyT } from '../spring-web/ceg-property.js';


/**
 * One entry in a CEG def — Spring's CEGs are tables mapping a
 * sub-emitter name to a class + count + flags + properties block.
 * `class_name` is the Spring runtime class (`CSimpleParticleSystem`,
 * `CSimpleGroundFlash`, `CHeatCloudProjectile`, `CSmokeTrailProjectile`,
 * `CExpGenSpawner`, `explspike`, etc.). The client maps known classes
 * to its particle pools and skips unknown ones.
 *
 * `flags` packs the Lua "ground/air/water/unit/underwater" booleans
 * that gate when this spawn fires:
 *   bit 0: ground   bit 1: air     bit 2: water
 *   bit 3: unit     bit 4: underwater
 * All zeros means "always emit" (legacy CEGs that omit the flags).
 */
export class GameCegSpawn implements flatbuffers.IUnpackableObject<GameCegSpawnT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GameCegSpawn {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGameCegSpawn(bb:flatbuffers.ByteBuffer, obj?:GameCegSpawn):GameCegSpawn {
  return (obj || new GameCegSpawn()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGameCegSpawn(bb:flatbuffers.ByteBuffer, obj?:GameCegSpawn):GameCegSpawn {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GameCegSpawn()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

spawnName():string|null
spawnName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
spawnName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

className():string|null
className(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
className(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

count():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

flags():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

properties(index: number, obj?:CegProperty):CegProperty|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new CegProperty()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

propertiesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startGameCegSpawn(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addSpawnName(builder:flatbuffers.Builder, spawnNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, spawnNameOffset, 0);
}

static addClassName(builder:flatbuffers.Builder, classNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, classNameOffset, 0);
}

static addCount(builder:flatbuffers.Builder, count:number) {
  builder.addFieldInt32(2, count, 0);
}

static addFlags(builder:flatbuffers.Builder, flags:number) {
  builder.addFieldInt8(3, flags, 0);
}

static addProperties(builder:flatbuffers.Builder, propertiesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, propertiesOffset, 0);
}

static createPropertiesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startPropertiesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endGameCegSpawn(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGameCegSpawn(builder:flatbuffers.Builder, spawnNameOffset:flatbuffers.Offset, classNameOffset:flatbuffers.Offset, count:number, flags:number, propertiesOffset:flatbuffers.Offset):flatbuffers.Offset {
  GameCegSpawn.startGameCegSpawn(builder);
  GameCegSpawn.addSpawnName(builder, spawnNameOffset);
  GameCegSpawn.addClassName(builder, classNameOffset);
  GameCegSpawn.addCount(builder, count);
  GameCegSpawn.addFlags(builder, flags);
  GameCegSpawn.addProperties(builder, propertiesOffset);
  return GameCegSpawn.endGameCegSpawn(builder);
}

unpack(): GameCegSpawnT {
  return new GameCegSpawnT(
    this.spawnName(),
    this.className(),
    this.count(),
    this.flags(),
    this.bb!.createObjList<CegProperty, CegPropertyT>(this.properties.bind(this), this.propertiesLength())
  );
}


unpackTo(_o: GameCegSpawnT): void {
  _o.spawnName = this.spawnName();
  _o.className = this.className();
  _o.count = this.count();
  _o.flags = this.flags();
  _o.properties = this.bb!.createObjList<CegProperty, CegPropertyT>(this.properties.bind(this), this.propertiesLength());
}
}

export class GameCegSpawnT implements flatbuffers.IGeneratedObject {
constructor(
  public spawnName: string|Uint8Array|null = null,
  public className: string|Uint8Array|null = null,
  public count: number = 0,
  public flags: number = 0,
  public properties: (CegPropertyT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const spawnName = (this.spawnName !== null ? builder.createString(this.spawnName!) : 0);
  const className = (this.className !== null ? builder.createString(this.className!) : 0);
  const properties = GameCegSpawn.createPropertiesVector(builder, builder.createObjectOffsetList(this.properties));

  return GameCegSpawn.createGameCegSpawn(builder,
    spawnName,
    className,
    this.count,
    this.flags,
    properties
  );
}
}
