// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ModOption, ModOptionT } from '../spring-web/mod-option.js';


/**
 * The active game's modoptions. Sent reliably, once, per-client on auth
 * (modoptions are immutable for the life of a game server, so there is no
 * re-broadcast — a late joiner gets them on its own auth). Feeds the worker
 * `liveState.modOptions` so the unsynced LuaUI `Spring.GetModOptions()`
 * returns the same set the synced gadgets and the defs-cache key already see.
 */
export class GameModOptions implements flatbuffers.IUnpackableObject<GameModOptionsT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GameModOptions {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGameModOptions(bb:flatbuffers.ByteBuffer, obj?:GameModOptions):GameModOptions {
  return (obj || new GameModOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGameModOptions(bb:flatbuffers.ByteBuffer, obj?:GameModOptions):GameModOptions {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GameModOptions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

options(index: number, obj?:ModOption):ModOption|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ModOption()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

optionsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startGameModOptions(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addOptions(builder:flatbuffers.Builder, optionsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, optionsOffset, 0);
}

static createOptionsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startOptionsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endGameModOptions(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGameModOptions(builder:flatbuffers.Builder, optionsOffset:flatbuffers.Offset):flatbuffers.Offset {
  GameModOptions.startGameModOptions(builder);
  GameModOptions.addOptions(builder, optionsOffset);
  return GameModOptions.endGameModOptions(builder);
}

unpack(): GameModOptionsT {
  return new GameModOptionsT(
    this.bb!.createObjList<ModOption, ModOptionT>(this.options.bind(this), this.optionsLength())
  );
}


unpackTo(_o: GameModOptionsT): void {
  _o.options = this.bb!.createObjList<ModOption, ModOptionT>(this.options.bind(this), this.optionsLength());
}
}

export class GameModOptionsT implements flatbuffers.IGeneratedObject {
constructor(
  public options: (ModOptionT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const options = GameModOptions.createOptionsVector(builder, builder.createObjectOffsetList(this.options));

  return GameModOptions.createGameModOptions(builder,
    options
  );
}
}
