// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ProjectileVisualType } from '../spring-web/projectile-visual-type.js';


/**
 * Definition of one weapon type. Sent once at game start so the
 * client can render projectiles with appropriate visuals.
 */
export class GameWeaponDef implements flatbuffers.IUnpackableObject<GameWeaponDefT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GameWeaponDef {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGameWeaponDef(bb:flatbuffers.ByteBuffer, obj?:GameWeaponDef):GameWeaponDef {
  return (obj || new GameWeaponDef()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGameWeaponDef(bb:flatbuffers.ByteBuffer, obj?:GameWeaponDef):GameWeaponDef {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GameWeaponDef()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

defId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

visualType():ProjectileVisualType {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ProjectileVisualType.Cannon;
}

projectileSpeed():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

range():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

aoe():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

size():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

intensity():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * RGB color hint (3 floats, 0-1). Client uses this to tint
 * the projectile mesh/trail. Defaults to weapon-type defaults
 * if all zeros.
 */
colorR():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

colorG():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

colorB():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

duration():number {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

highTrajectory():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startGameWeaponDef(builder:flatbuffers.Builder) {
  builder.startObject(13);
}

static addDefId(builder:flatbuffers.Builder, defId:number) {
  builder.addFieldInt16(0, defId, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
}

static addVisualType(builder:flatbuffers.Builder, visualType:ProjectileVisualType) {
  builder.addFieldInt8(2, visualType, ProjectileVisualType.Cannon);
}

static addProjectileSpeed(builder:flatbuffers.Builder, projectileSpeed:number) {
  builder.addFieldFloat32(3, projectileSpeed, 0.0);
}

static addRange(builder:flatbuffers.Builder, range:number) {
  builder.addFieldFloat32(4, range, 0.0);
}

static addAoe(builder:flatbuffers.Builder, aoe:number) {
  builder.addFieldFloat32(5, aoe, 0.0);
}

static addSize(builder:flatbuffers.Builder, size:number) {
  builder.addFieldFloat32(6, size, 0.0);
}

static addIntensity(builder:flatbuffers.Builder, intensity:number) {
  builder.addFieldFloat32(7, intensity, 0.0);
}

static addColorR(builder:flatbuffers.Builder, colorR:number) {
  builder.addFieldFloat32(8, colorR, 0.0);
}

static addColorG(builder:flatbuffers.Builder, colorG:number) {
  builder.addFieldFloat32(9, colorG, 0.0);
}

static addColorB(builder:flatbuffers.Builder, colorB:number) {
  builder.addFieldFloat32(10, colorB, 0.0);
}

static addDuration(builder:flatbuffers.Builder, duration:number) {
  builder.addFieldFloat32(11, duration, 0.0);
}

static addHighTrajectory(builder:flatbuffers.Builder, highTrajectory:boolean) {
  builder.addFieldInt8(12, +highTrajectory, +false);
}

static endGameWeaponDef(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGameWeaponDef(builder:flatbuffers.Builder, defId:number, nameOffset:flatbuffers.Offset, visualType:ProjectileVisualType, projectileSpeed:number, range:number, aoe:number, size:number, intensity:number, colorR:number, colorG:number, colorB:number, duration:number, highTrajectory:boolean):flatbuffers.Offset {
  GameWeaponDef.startGameWeaponDef(builder);
  GameWeaponDef.addDefId(builder, defId);
  GameWeaponDef.addName(builder, nameOffset);
  GameWeaponDef.addVisualType(builder, visualType);
  GameWeaponDef.addProjectileSpeed(builder, projectileSpeed);
  GameWeaponDef.addRange(builder, range);
  GameWeaponDef.addAoe(builder, aoe);
  GameWeaponDef.addSize(builder, size);
  GameWeaponDef.addIntensity(builder, intensity);
  GameWeaponDef.addColorR(builder, colorR);
  GameWeaponDef.addColorG(builder, colorG);
  GameWeaponDef.addColorB(builder, colorB);
  GameWeaponDef.addDuration(builder, duration);
  GameWeaponDef.addHighTrajectory(builder, highTrajectory);
  return GameWeaponDef.endGameWeaponDef(builder);
}

unpack(): GameWeaponDefT {
  return new GameWeaponDefT(
    this.defId(),
    this.name(),
    this.visualType(),
    this.projectileSpeed(),
    this.range(),
    this.aoe(),
    this.size(),
    this.intensity(),
    this.colorR(),
    this.colorG(),
    this.colorB(),
    this.duration(),
    this.highTrajectory()
  );
}


unpackTo(_o: GameWeaponDefT): void {
  _o.defId = this.defId();
  _o.name = this.name();
  _o.visualType = this.visualType();
  _o.projectileSpeed = this.projectileSpeed();
  _o.range = this.range();
  _o.aoe = this.aoe();
  _o.size = this.size();
  _o.intensity = this.intensity();
  _o.colorR = this.colorR();
  _o.colorG = this.colorG();
  _o.colorB = this.colorB();
  _o.duration = this.duration();
  _o.highTrajectory = this.highTrajectory();
}
}

export class GameWeaponDefT implements flatbuffers.IGeneratedObject {
constructor(
  public defId: number = 0,
  public name: string|Uint8Array|null = null,
  public visualType: ProjectileVisualType = ProjectileVisualType.Cannon,
  public projectileSpeed: number = 0.0,
  public range: number = 0.0,
  public aoe: number = 0.0,
  public size: number = 0.0,
  public intensity: number = 0.0,
  public colorR: number = 0.0,
  public colorG: number = 0.0,
  public colorB: number = 0.0,
  public duration: number = 0.0,
  public highTrajectory: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const name = (this.name !== null ? builder.createString(this.name!) : 0);

  return GameWeaponDef.createGameWeaponDef(builder,
    this.defId,
    name,
    this.visualType,
    this.projectileSpeed,
    this.range,
    this.aoe,
    this.size,
    this.intensity,
    this.colorR,
    this.colorG,
    this.colorB,
    this.duration,
    this.highTrajectory
  );
}
}
