// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class GameInfo implements flatbuffers.IUnpackableObject<GameInfoT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GameInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGameInfo(bb:flatbuffers.ByteBuffer, obj?:GameInfo):GameInfo {
  return (obj || new GameInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGameInfo(bb:flatbuffers.ByteBuffer, obj?:GameInfo):GameInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GameInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

mapId():string|null
mapId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
mapId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

gameId():string|null
gameId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
gameId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

gameSpeed():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

frame():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

paused():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

/**
 * Current wind vector (elmos/sec). y is always near 0 in practice.
 * Updated server-side every 15 game-seconds; client is free to
 * interpolate between snapshots if visual smoothness matters.
 */
windX():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

windY():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

windZ():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * |wind_vec| — what Spring.GetWind / wind generators read.
 */
windStrength():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * Map's tidal energy multiplier; constant per map but cheaper to
 * piggyback here than to add a one-shot message.
 */
tidalStrength():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * True when the active game ships with Lua content authored
 * against Spring's legacy left-handed coord system. Clients pipe
 * this flag into `lua-spring-api.ts` / `lua-gl-bridge.ts` so the
 * LH-style values legacy widgets/gadgets expect bridge back to
 * the RH internal state. Defaults to false for RH-native games.
 * See PLAN-coordinate-system.md and docs/coordinate-system.md.
 */
legacyCoordSystem():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

/**
 * The engine's global unit-ID ceiling — `unitHandler.MaxUnits()` =
 * Σ active teams of their per-team cap (the `maxunits` modoption clamped
 * to MAX_UNITS / numTeams). Immutable for the game-server's lifetime.
 * The client's `Game.maxUnits` MUST equal this exactly: it's the
 * unit/feature ID-space boundary order params pack against
 * (`featureID + maxUnits`), so a mismatch silently misdecodes every
 * feature-targeted reclaim/repair/resurrect order. 0 = not yet known.
 * See PLAN-bar.md (Game-table maxUnits thread).
 */
maxUnits():number {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startGameInfo(builder:flatbuffers.Builder) {
  builder.startObject(12);
}

static addMapId(builder:flatbuffers.Builder, mapIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, mapIdOffset, 0);
}

static addGameId(builder:flatbuffers.Builder, gameIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, gameIdOffset, 0);
}

static addGameSpeed(builder:flatbuffers.Builder, gameSpeed:number) {
  builder.addFieldFloat32(2, gameSpeed, 0.0);
}

static addFrame(builder:flatbuffers.Builder, frame:number) {
  builder.addFieldInt32(3, frame, 0);
}

static addPaused(builder:flatbuffers.Builder, paused:boolean) {
  builder.addFieldInt8(4, +paused, +false);
}

static addWindX(builder:flatbuffers.Builder, windX:number) {
  builder.addFieldFloat32(5, windX, 0.0);
}

static addWindY(builder:flatbuffers.Builder, windY:number) {
  builder.addFieldFloat32(6, windY, 0.0);
}

static addWindZ(builder:flatbuffers.Builder, windZ:number) {
  builder.addFieldFloat32(7, windZ, 0.0);
}

static addWindStrength(builder:flatbuffers.Builder, windStrength:number) {
  builder.addFieldFloat32(8, windStrength, 0.0);
}

static addTidalStrength(builder:flatbuffers.Builder, tidalStrength:number) {
  builder.addFieldFloat32(9, tidalStrength, 0.0);
}

static addLegacyCoordSystem(builder:flatbuffers.Builder, legacyCoordSystem:boolean) {
  builder.addFieldInt8(10, +legacyCoordSystem, +false);
}

static addMaxUnits(builder:flatbuffers.Builder, maxUnits:number) {
  builder.addFieldInt32(11, maxUnits, 0);
}

static endGameInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGameInfo(builder:flatbuffers.Builder, mapIdOffset:flatbuffers.Offset, gameIdOffset:flatbuffers.Offset, gameSpeed:number, frame:number, paused:boolean, windX:number, windY:number, windZ:number, windStrength:number, tidalStrength:number, legacyCoordSystem:boolean, maxUnits:number):flatbuffers.Offset {
  GameInfo.startGameInfo(builder);
  GameInfo.addMapId(builder, mapIdOffset);
  GameInfo.addGameId(builder, gameIdOffset);
  GameInfo.addGameSpeed(builder, gameSpeed);
  GameInfo.addFrame(builder, frame);
  GameInfo.addPaused(builder, paused);
  GameInfo.addWindX(builder, windX);
  GameInfo.addWindY(builder, windY);
  GameInfo.addWindZ(builder, windZ);
  GameInfo.addWindStrength(builder, windStrength);
  GameInfo.addTidalStrength(builder, tidalStrength);
  GameInfo.addLegacyCoordSystem(builder, legacyCoordSystem);
  GameInfo.addMaxUnits(builder, maxUnits);
  return GameInfo.endGameInfo(builder);
}

unpack(): GameInfoT {
  return new GameInfoT(
    this.mapId(),
    this.gameId(),
    this.gameSpeed(),
    this.frame(),
    this.paused(),
    this.windX(),
    this.windY(),
    this.windZ(),
    this.windStrength(),
    this.tidalStrength(),
    this.legacyCoordSystem(),
    this.maxUnits()
  );
}


unpackTo(_o: GameInfoT): void {
  _o.mapId = this.mapId();
  _o.gameId = this.gameId();
  _o.gameSpeed = this.gameSpeed();
  _o.frame = this.frame();
  _o.paused = this.paused();
  _o.windX = this.windX();
  _o.windY = this.windY();
  _o.windZ = this.windZ();
  _o.windStrength = this.windStrength();
  _o.tidalStrength = this.tidalStrength();
  _o.legacyCoordSystem = this.legacyCoordSystem();
  _o.maxUnits = this.maxUnits();
}
}

export class GameInfoT implements flatbuffers.IGeneratedObject {
constructor(
  public mapId: string|Uint8Array|null = null,
  public gameId: string|Uint8Array|null = null,
  public gameSpeed: number = 0.0,
  public frame: number = 0,
  public paused: boolean = false,
  public windX: number = 0.0,
  public windY: number = 0.0,
  public windZ: number = 0.0,
  public windStrength: number = 0.0,
  public tidalStrength: number = 0.0,
  public legacyCoordSystem: boolean = false,
  public maxUnits: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const mapId = (this.mapId !== null ? builder.createString(this.mapId!) : 0);
  const gameId = (this.gameId !== null ? builder.createString(this.gameId!) : 0);

  return GameInfo.createGameInfo(builder,
    mapId,
    gameId,
    this.gameSpeed,
    this.frame,
    this.paused,
    this.windX,
    this.windY,
    this.windZ,
    this.windStrength,
    this.tidalStrength,
    this.legacyCoordSystem,
    this.maxUnits
  );
}
}
