// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { GameEvent, GameEventT } from '../spring-web/game-event.js';


export class GameEventBatch implements flatbuffers.IUnpackableObject<GameEventBatchT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GameEventBatch {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGameEventBatch(bb:flatbuffers.ByteBuffer, obj?:GameEventBatch):GameEventBatch {
  return (obj || new GameEventBatch()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGameEventBatch(bb:flatbuffers.ByteBuffer, obj?:GameEventBatch):GameEventBatch {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GameEventBatch()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

frame():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

events(index: number, obj?:GameEvent):GameEvent|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new GameEvent()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

eventsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startGameEventBatch(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addFrame(builder:flatbuffers.Builder, frame:number) {
  builder.addFieldInt32(0, frame, 0);
}

static addEvents(builder:flatbuffers.Builder, eventsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, eventsOffset, 0);
}

static createEventsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startEventsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endGameEventBatch(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGameEventBatch(builder:flatbuffers.Builder, frame:number, eventsOffset:flatbuffers.Offset):flatbuffers.Offset {
  GameEventBatch.startGameEventBatch(builder);
  GameEventBatch.addFrame(builder, frame);
  GameEventBatch.addEvents(builder, eventsOffset);
  return GameEventBatch.endGameEventBatch(builder);
}

unpack(): GameEventBatchT {
  return new GameEventBatchT(
    this.frame(),
    this.bb!.createObjList<GameEvent, GameEventT>(this.events.bind(this), this.eventsLength())
  );
}


unpackTo(_o: GameEventBatchT): void {
  _o.frame = this.frame();
  _o.events = this.bb!.createObjList<GameEvent, GameEventT>(this.events.bind(this), this.eventsLength());
}
}

export class GameEventBatchT implements flatbuffers.IGeneratedObject {
constructor(
  public frame: number = 0,
  public events: (GameEventT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const events = GameEventBatch.createEventsVector(builder, builder.createObjectOffsetList(this.events));

  return GameEventBatch.createGameEventBatch(builder,
    this.frame,
    events
  );
}
}
