// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Vec3, Vec3T } from '../spring-web/vec3.js';


export class GameEvent implements flatbuffers.IUnpackableObject<GameEventT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GameEvent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGameEvent(bb:flatbuffers.ByteBuffer, obj?:GameEvent):GameEvent {
  return (obj || new GameEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGameEvent(bb:flatbuffers.ByteBuffer, obj?:GameEvent):GameEvent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GameEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

topic():string|null
topic(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
topic(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

frame():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

entityId():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

position(obj?:Vec3):Vec3|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Vec3()).__init(this.bb_pos + offset, this.bb!) : null;
}

payload(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

payloadLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

payloadArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startGameEvent(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addTopic(builder:flatbuffers.Builder, topicOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, topicOffset, 0);
}

static addFrame(builder:flatbuffers.Builder, frame:number) {
  builder.addFieldInt32(1, frame, 0);
}

static addEntityId(builder:flatbuffers.Builder, entityId:number) {
  builder.addFieldInt32(2, entityId, 0);
}

static addPosition(builder:flatbuffers.Builder, positionOffset:flatbuffers.Offset) {
  builder.addFieldStruct(3, positionOffset, 0);
}

static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, payloadOffset, 0);
}

static createPayloadVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startPayloadVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endGameEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


unpack(): GameEventT {
  return new GameEventT(
    this.topic(),
    this.frame(),
    this.entityId(),
    (this.position() !== null ? this.position()!.unpack() : null),
    this.bb!.createScalarList<number>(this.payload.bind(this), this.payloadLength())
  );
}


unpackTo(_o: GameEventT): void {
  _o.topic = this.topic();
  _o.frame = this.frame();
  _o.entityId = this.entityId();
  _o.position = (this.position() !== null ? this.position()!.unpack() : null);
  _o.payload = this.bb!.createScalarList<number>(this.payload.bind(this), this.payloadLength());
}
}

export class GameEventT implements flatbuffers.IGeneratedObject {
constructor(
  public topic: string|Uint8Array|null = null,
  public frame: number = 0,
  public entityId: number = 0,
  public position: Vec3T|null = null,
  public payload: (number)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const topic = (this.topic !== null ? builder.createString(this.topic!) : 0);
  const payload = GameEvent.createPayloadVector(builder, this.payload);

  GameEvent.startGameEvent(builder);
  GameEvent.addTopic(builder, topic);
  GameEvent.addFrame(builder, this.frame);
  GameEvent.addEntityId(builder, this.entityId);
  GameEvent.addPosition(builder, (this.position !== null ? this.position!.pack(builder) : 0));
  GameEvent.addPayload(builder, payload);

  return GameEvent.endGameEvent(builder);
}
}
