// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * Client → Server: set a group's posture bundle (engagement / casualty
 * tolerance / reinforcement policy / area-weapon ROE — macro-orders §3).
 * Stored per group and streamed back in OrgGroupInfo. Posture *inheritance*
 * down the tree is post-v0; v0 stores + echoes the per-group setting.
 */
export class GroupPosture implements flatbuffers.IUnpackableObject<GroupPostureT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GroupPosture {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGroupPosture(bb:flatbuffers.ByteBuffer, obj?:GroupPosture):GroupPosture {
  return (obj || new GroupPosture()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGroupPosture(bb:flatbuffers.ByteBuffer, obj?:GroupPosture):GroupPosture {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GroupPosture()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sequence():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

groupId():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

postureJson():string|null
postureJson(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
postureJson(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startGroupPosture(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addSequence(builder:flatbuffers.Builder, sequence:number) {
  builder.addFieldInt32(0, sequence, 0);
}

static addGroupId(builder:flatbuffers.Builder, groupId:number) {
  builder.addFieldInt32(1, groupId, 0);
}

static addPostureJson(builder:flatbuffers.Builder, postureJsonOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, postureJsonOffset, 0);
}

static endGroupPosture(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGroupPosture(builder:flatbuffers.Builder, sequence:number, groupId:number, postureJsonOffset:flatbuffers.Offset):flatbuffers.Offset {
  GroupPosture.startGroupPosture(builder);
  GroupPosture.addSequence(builder, sequence);
  GroupPosture.addGroupId(builder, groupId);
  GroupPosture.addPostureJson(builder, postureJsonOffset);
  return GroupPosture.endGroupPosture(builder);
}

unpack(): GroupPostureT {
  return new GroupPostureT(
    this.sequence(),
    this.groupId(),
    this.postureJson()
  );
}


unpackTo(_o: GroupPostureT): void {
  _o.sequence = this.sequence();
  _o.groupId = this.groupId();
  _o.postureJson = this.postureJson();
}
}

export class GroupPostureT implements flatbuffers.IGeneratedObject {
constructor(
  public sequence: number = 0,
  public groupId: number = 0,
  public postureJson: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const postureJson = (this.postureJson !== null ? builder.createString(this.postureJson!) : 0);

  return GroupPosture.createGroupPosture(builder,
    this.sequence,
    this.groupId,
    postureJson
  );
}
}
