// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * Spring's `CStandardGroundFlash` parameters. Authored as a
 * top-level `groundflash = { … }` subtable on a CEG def — *not*
 * a spawn entry, despite the name. Mirrors Recoil's
 * `ExpGenParams.groundFlash` from `ExplosionGenerator.cpp`.
 *
 * `ttl` of 0 / unset means "no ground flash"; the client checks
 * this to decide whether to emit anything at all. Fields default
 * to the same zero values Recoil uses for missing keys.
 */
export class GroundFlashInfo implements flatbuffers.IUnpackableObject<GroundFlashInfoT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GroundFlashInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGroundFlashInfo(bb:flatbuffers.ByteBuffer, obj?:GroundFlashInfo):GroundFlashInfo {
  return (obj || new GroundFlashInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGroundFlashInfo(bb:flatbuffers.ByteBuffer, obj?:GroundFlashInfo):GroundFlashInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GroundFlashInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * Lifetime in sim frames. Required (`ttl > 0`).
 */
ttl():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

/**
 * Centre disc alpha at peak.
 */
circleAlpha():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * Outer flash quad world-space half-size.
 */
flashSize():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * Outer flash quad alpha at peak.
 */
flashAlpha():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * Per-frame radial growth of the centre disc, in world units.
 */
circleGrowth():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * RGB tint (alpha is the per-element flashAlpha / circleAlpha).
 */
colorR():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 1.0;
}

colorG():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 1.0;
}

colorB():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.8;
}

/**
 * Visibility flags — same bit layout as `GameCegSpawn.flags`
 * but with `CEG_FLAG_GROUND` always implicitly set.
 */
flags():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

static startGroundFlashInfo(builder:flatbuffers.Builder) {
  builder.startObject(9);
}

static addTtl(builder:flatbuffers.Builder, ttl:number) {
  builder.addFieldInt32(0, ttl, 0);
}

static addCircleAlpha(builder:flatbuffers.Builder, circleAlpha:number) {
  builder.addFieldFloat32(1, circleAlpha, 0.0);
}

static addFlashSize(builder:flatbuffers.Builder, flashSize:number) {
  builder.addFieldFloat32(2, flashSize, 0.0);
}

static addFlashAlpha(builder:flatbuffers.Builder, flashAlpha:number) {
  builder.addFieldFloat32(3, flashAlpha, 0.0);
}

static addCircleGrowth(builder:flatbuffers.Builder, circleGrowth:number) {
  builder.addFieldFloat32(4, circleGrowth, 0.0);
}

static addColorR(builder:flatbuffers.Builder, colorR:number) {
  builder.addFieldFloat32(5, colorR, 1.0);
}

static addColorG(builder:flatbuffers.Builder, colorG:number) {
  builder.addFieldFloat32(6, colorG, 1.0);
}

static addColorB(builder:flatbuffers.Builder, colorB:number) {
  builder.addFieldFloat32(7, colorB, 0.8);
}

static addFlags(builder:flatbuffers.Builder, flags:number) {
  builder.addFieldInt8(8, flags, 0);
}

static endGroundFlashInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGroundFlashInfo(builder:flatbuffers.Builder, ttl:number, circleAlpha:number, flashSize:number, flashAlpha:number, circleGrowth:number, colorR:number, colorG:number, colorB:number, flags:number):flatbuffers.Offset {
  GroundFlashInfo.startGroundFlashInfo(builder);
  GroundFlashInfo.addTtl(builder, ttl);
  GroundFlashInfo.addCircleAlpha(builder, circleAlpha);
  GroundFlashInfo.addFlashSize(builder, flashSize);
  GroundFlashInfo.addFlashAlpha(builder, flashAlpha);
  GroundFlashInfo.addCircleGrowth(builder, circleGrowth);
  GroundFlashInfo.addColorR(builder, colorR);
  GroundFlashInfo.addColorG(builder, colorG);
  GroundFlashInfo.addColorB(builder, colorB);
  GroundFlashInfo.addFlags(builder, flags);
  return GroundFlashInfo.endGroundFlashInfo(builder);
}

unpack(): GroundFlashInfoT {
  return new GroundFlashInfoT(
    this.ttl(),
    this.circleAlpha(),
    this.flashSize(),
    this.flashAlpha(),
    this.circleGrowth(),
    this.colorR(),
    this.colorG(),
    this.colorB(),
    this.flags()
  );
}


unpackTo(_o: GroundFlashInfoT): void {
  _o.ttl = this.ttl();
  _o.circleAlpha = this.circleAlpha();
  _o.flashSize = this.flashSize();
  _o.flashAlpha = this.flashAlpha();
  _o.circleGrowth = this.circleGrowth();
  _o.colorR = this.colorR();
  _o.colorG = this.colorG();
  _o.colorB = this.colorB();
  _o.flags = this.flags();
}
}

export class GroundFlashInfoT implements flatbuffers.IGeneratedObject {
constructor(
  public ttl: number = 0,
  public circleAlpha: number = 0.0,
  public flashSize: number = 0.0,
  public flashAlpha: number = 0.0,
  public circleGrowth: number = 0.0,
  public colorR: number = 1.0,
  public colorG: number = 1.0,
  public colorB: number = 0.8,
  public flags: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return GroundFlashInfo.createGroundFlashInfo(builder,
    this.ttl,
    this.circleAlpha,
    this.flashSize,
    this.flashAlpha,
    this.circleGrowth,
    this.colorR,
    this.colorG,
    this.colorB,
    this.flags
  );
}
}
