// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class Handshake implements flatbuffers.IUnpackableObject<HandshakeT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Handshake {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsHandshake(bb:flatbuffers.ByteBuffer, obj?:Handshake):Handshake {
  return (obj || new Handshake()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsHandshake(bb:flatbuffers.ByteBuffer, obj?:Handshake):Handshake {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Handshake()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

protocolVersion():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

clientVersion():string|null
clientVersion(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
clientVersion(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

schemaHash():string|null
schemaHash(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
schemaHash(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startHandshake(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addProtocolVersion(builder:flatbuffers.Builder, protocolVersion:number) {
  builder.addFieldInt16(0, protocolVersion, 0);
}

static addClientVersion(builder:flatbuffers.Builder, clientVersionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, clientVersionOffset, 0);
}

static addSchemaHash(builder:flatbuffers.Builder, schemaHashOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, schemaHashOffset, 0);
}

static endHandshake(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createHandshake(builder:flatbuffers.Builder, protocolVersion:number, clientVersionOffset:flatbuffers.Offset, schemaHashOffset:flatbuffers.Offset):flatbuffers.Offset {
  Handshake.startHandshake(builder);
  Handshake.addProtocolVersion(builder, protocolVersion);
  Handshake.addClientVersion(builder, clientVersionOffset);
  Handshake.addSchemaHash(builder, schemaHashOffset);
  return Handshake.endHandshake(builder);
}

unpack(): HandshakeT {
  return new HandshakeT(
    this.protocolVersion(),
    this.clientVersion(),
    this.schemaHash()
  );
}


unpackTo(_o: HandshakeT): void {
  _o.protocolVersion = this.protocolVersion();
  _o.clientVersion = this.clientVersion();
  _o.schemaHash = this.schemaHash();
}
}

export class HandshakeT implements flatbuffers.IGeneratedObject {
constructor(
  public protocolVersion: number = 0,
  public clientVersion: string|Uint8Array|null = null,
  public schemaHash: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const clientVersion = (this.clientVersion !== null ? builder.createString(this.clientVersion!) : 0);
  const schemaHash = (this.schemaHash !== null ? builder.createString(this.schemaHash!) : 0);

  return Handshake.createHandshake(builder,
    this.protocolVersion,
    clientVersion,
    schemaHash
  );
}
}
