// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * Subscribe to log streaming from the log server.
 */
export class LogSubscribe implements flatbuffers.IUnpackableObject<LogSubscribeT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LogSubscribe {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLogSubscribe(bb:flatbuffers.ByteBuffer, obj?:LogSubscribe):LogSubscribe {
  return (obj || new LogSubscribe()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLogSubscribe(bb:flatbuffers.ByteBuffer, obj?:LogSubscribe):LogSubscribe {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LogSubscribe()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

roomId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

minLevel():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

sectionFilter():string|null
sectionFilter(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
sectionFilter(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

scopeFilter():string|null
scopeFilter(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
scopeFilter(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startLogSubscribe(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addRoomId(builder:flatbuffers.Builder, roomId:number) {
  builder.addFieldInt32(0, roomId, 0);
}

static addMinLevel(builder:flatbuffers.Builder, minLevel:number) {
  builder.addFieldInt8(1, minLevel, 0);
}

static addSectionFilter(builder:flatbuffers.Builder, sectionFilterOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, sectionFilterOffset, 0);
}

static addScopeFilter(builder:flatbuffers.Builder, scopeFilterOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, scopeFilterOffset, 0);
}

static endLogSubscribe(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createLogSubscribe(builder:flatbuffers.Builder, roomId:number, minLevel:number, sectionFilterOffset:flatbuffers.Offset, scopeFilterOffset:flatbuffers.Offset):flatbuffers.Offset {
  LogSubscribe.startLogSubscribe(builder);
  LogSubscribe.addRoomId(builder, roomId);
  LogSubscribe.addMinLevel(builder, minLevel);
  LogSubscribe.addSectionFilter(builder, sectionFilterOffset);
  LogSubscribe.addScopeFilter(builder, scopeFilterOffset);
  return LogSubscribe.endLogSubscribe(builder);
}

unpack(): LogSubscribeT {
  return new LogSubscribeT(
    this.roomId(),
    this.minLevel(),
    this.sectionFilter(),
    this.scopeFilter()
  );
}


unpackTo(_o: LogSubscribeT): void {
  _o.roomId = this.roomId();
  _o.minLevel = this.minLevel();
  _o.sectionFilter = this.sectionFilter();
  _o.scopeFilter = this.scopeFilter();
}
}

export class LogSubscribeT implements flatbuffers.IGeneratedObject {
constructor(
  public roomId: number = 0,
  public minLevel: number = 0,
  public sectionFilter: string|Uint8Array|null = null,
  public scopeFilter: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const sectionFilter = (this.sectionFilter !== null ? builder.createString(this.sectionFilter!) : 0);
  const scopeFilter = (this.scopeFilter !== null ? builder.createString(this.scopeFilter!) : 0);

  return LogSubscribe.createLogSubscribe(builder,
    this.roomId,
    this.minLevel,
    sectionFilter,
    scopeFilter
  );
}
}
