// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * Forwarded `Spring.SendLuaUIMsg(msg, mode)` call from a client widget.
 * Unlike LuaRulesMsg (which feeds the server's synced LuaRules state), this
 * is a player→player LuaUI broadcast: the server relays it to every eligible
 * client as a `LuaUIMsgRelay` where it surfaces as
 * `widget:RecvLuaMsg(msg, playerID)`. `mode` selects the audience and is
 * resolved on the receiving end (Recoil `CLuaHandle::HandleLuaMsg`):
 * 0 = everyone, 'a' (97) = allies only, 's' (115) = spectators only. The
 * sending player also receives its own message back (faithful loopback).
 * Bytes (not string) so embedded nulls survive. PlayerID is resolved
 * server-side from the authenticated session, not trusted from the client.
 */
export class LuaUIMsg implements flatbuffers.IUnpackableObject<LuaUIMsgT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):LuaUIMsg {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsLuaUIMsg(bb:flatbuffers.ByteBuffer, obj?:LuaUIMsg):LuaUIMsg {
  return (obj || new LuaUIMsg()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsLuaUIMsg(bb:flatbuffers.ByteBuffer, obj?:LuaUIMsg):LuaUIMsg {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new LuaUIMsg()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

data(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

dataLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

dataArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

mode():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

static startLuaUIMsg(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addData(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, dataOffset, 0);
}

static createDataVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startDataVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addMode(builder:flatbuffers.Builder, mode:number) {
  builder.addFieldInt8(1, mode, 0);
}

static endLuaUIMsg(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createLuaUIMsg(builder:flatbuffers.Builder, dataOffset:flatbuffers.Offset, mode:number):flatbuffers.Offset {
  LuaUIMsg.startLuaUIMsg(builder);
  LuaUIMsg.addData(builder, dataOffset);
  LuaUIMsg.addMode(builder, mode);
  return LuaUIMsg.endLuaUIMsg(builder);
}

unpack(): LuaUIMsgT {
  return new LuaUIMsgT(
    this.bb!.createScalarList<number>(this.data.bind(this), this.dataLength()),
    this.mode()
  );
}


unpackTo(_o: LuaUIMsgT): void {
  _o.data = this.bb!.createScalarList<number>(this.data.bind(this), this.dataLength());
  _o.mode = this.mode();
}
}

export class LuaUIMsgT implements flatbuffers.IGeneratedObject {
constructor(
  public data: (number)[] = [],
  public mode: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const data = LuaUIMsg.createDataVector(builder, this.data);

  return LuaUIMsg.createLuaUIMsg(builder,
    data,
    this.mode
  );
}
}
