// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * Map feature placed on the terrain.
 */
export class MapFeature implements flatbuffers.IUnpackableObject<MapFeatureT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MapFeature {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMapFeature(bb:flatbuffers.ByteBuffer, obj?:MapFeature):MapFeature {
  return (obj || new MapFeature()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMapFeature(bb:flatbuffers.ByteBuffer, obj?:MapFeature):MapFeature {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MapFeature()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

typeIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

x():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

y():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

z():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

rotation():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

relativeSize():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startMapFeature(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addTypeIndex(builder:flatbuffers.Builder, typeIndex:number) {
  builder.addFieldInt16(0, typeIndex, 0);
}

static addX(builder:flatbuffers.Builder, x:number) {
  builder.addFieldFloat32(1, x, 0.0);
}

static addY(builder:flatbuffers.Builder, y:number) {
  builder.addFieldFloat32(2, y, 0.0);
}

static addZ(builder:flatbuffers.Builder, z:number) {
  builder.addFieldFloat32(3, z, 0.0);
}

static addRotation(builder:flatbuffers.Builder, rotation:number) {
  builder.addFieldFloat32(4, rotation, 0.0);
}

static addRelativeSize(builder:flatbuffers.Builder, relativeSize:number) {
  builder.addFieldFloat32(5, relativeSize, 0.0);
}

static endMapFeature(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMapFeature(builder:flatbuffers.Builder, typeIndex:number, x:number, y:number, z:number, rotation:number, relativeSize:number):flatbuffers.Offset {
  MapFeature.startMapFeature(builder);
  MapFeature.addTypeIndex(builder, typeIndex);
  MapFeature.addX(builder, x);
  MapFeature.addY(builder, y);
  MapFeature.addZ(builder, z);
  MapFeature.addRotation(builder, rotation);
  MapFeature.addRelativeSize(builder, relativeSize);
  return MapFeature.endMapFeature(builder);
}

unpack(): MapFeatureT {
  return new MapFeatureT(
    this.typeIndex(),
    this.x(),
    this.y(),
    this.z(),
    this.rotation(),
    this.relativeSize()
  );
}


unpackTo(_o: MapFeatureT): void {
  _o.typeIndex = this.typeIndex();
  _o.x = this.x();
  _o.y = this.y();
  _o.z = this.z();
  _o.rotation = this.rotation();
  _o.relativeSize = this.relativeSize();
}
}

export class MapFeatureT implements flatbuffers.IGeneratedObject {
constructor(
  public typeIndex: number = 0,
  public x: number = 0.0,
  public y: number = 0.0,
  public z: number = 0.0,
  public rotation: number = 0.0,
  public relativeSize: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return MapFeature.createMapFeature(builder,
    this.typeIndex,
    this.x,
    this.y,
    this.z,
    this.rotation,
    this.relativeSize
  );
}
}
