// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * Splat/decal texture set — Spring's terrain detail texturing system.
 * All URLs are HTTP paths to PNG files (relative to the lobby HTTP root).
 * Empty string means the texture is not defined by the map.
 */
export class MapDecals implements flatbuffers.IUnpackableObject<MapDecalsT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MapDecals {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMapDecals(bb:flatbuffers.ByteBuffer, obj?:MapDecals):MapDecals {
  return (obj || new MapDecals()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMapDecals(bb:flatbuffers.ByteBuffer, obj?:MapDecals):MapDecals {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MapDecals()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

detailTex():string|null
detailTex(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
detailTex(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

specularTex():string|null
specularTex(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
specularTex(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

splatDetailTex():string|null
splatDetailTex(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
splatDetailTex(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

splatDistrTex():string|null
splatDistrTex(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
splatDistrTex(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

splatNormal0():string|null
splatNormal0(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
splatNormal0(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

splatNormal1():string|null
splatNormal1(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
splatNormal1(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

splatNormal2():string|null
splatNormal2(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
splatNormal2(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

splatNormal3():string|null
splatNormal3(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
splatNormal3(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

detailNormalTex():string|null
detailNormalTex(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
detailNormalTex(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

splatScales(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.readFloat32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

splatScalesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

splatScalesArray():Float32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? new Float32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

splatMults(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.readFloat32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

splatMultsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

splatMultsArray():Float32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? new Float32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

splatDetailNormalDiffuseAlpha():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startMapDecals(builder:flatbuffers.Builder) {
  builder.startObject(12);
}

static addDetailTex(builder:flatbuffers.Builder, detailTexOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, detailTexOffset, 0);
}

static addSpecularTex(builder:flatbuffers.Builder, specularTexOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, specularTexOffset, 0);
}

static addSplatDetailTex(builder:flatbuffers.Builder, splatDetailTexOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, splatDetailTexOffset, 0);
}

static addSplatDistrTex(builder:flatbuffers.Builder, splatDistrTexOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, splatDistrTexOffset, 0);
}

static addSplatNormal0(builder:flatbuffers.Builder, splatNormal0Offset:flatbuffers.Offset) {
  builder.addFieldOffset(4, splatNormal0Offset, 0);
}

static addSplatNormal1(builder:flatbuffers.Builder, splatNormal1Offset:flatbuffers.Offset) {
  builder.addFieldOffset(5, splatNormal1Offset, 0);
}

static addSplatNormal2(builder:flatbuffers.Builder, splatNormal2Offset:flatbuffers.Offset) {
  builder.addFieldOffset(6, splatNormal2Offset, 0);
}

static addSplatNormal3(builder:flatbuffers.Builder, splatNormal3Offset:flatbuffers.Offset) {
  builder.addFieldOffset(7, splatNormal3Offset, 0);
}

static addDetailNormalTex(builder:flatbuffers.Builder, detailNormalTexOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, detailNormalTexOffset, 0);
}

static addSplatScales(builder:flatbuffers.Builder, splatScalesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, splatScalesOffset, 0);
}

static createSplatScalesVector(builder:flatbuffers.Builder, data:number[]|Float32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createSplatScalesVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createSplatScalesVector(builder:flatbuffers.Builder, data:number[]|Float32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addFloat32(data[i]!);
  }
  return builder.endVector();
}

static startSplatScalesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addSplatMults(builder:flatbuffers.Builder, splatMultsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, splatMultsOffset, 0);
}

static createSplatMultsVector(builder:flatbuffers.Builder, data:number[]|Float32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createSplatMultsVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createSplatMultsVector(builder:flatbuffers.Builder, data:number[]|Float32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addFloat32(data[i]!);
  }
  return builder.endVector();
}

static startSplatMultsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addSplatDetailNormalDiffuseAlpha(builder:flatbuffers.Builder, splatDetailNormalDiffuseAlpha:boolean) {
  builder.addFieldInt8(11, +splatDetailNormalDiffuseAlpha, +false);
}

static endMapDecals(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createMapDecals(builder:flatbuffers.Builder, detailTexOffset:flatbuffers.Offset, specularTexOffset:flatbuffers.Offset, splatDetailTexOffset:flatbuffers.Offset, splatDistrTexOffset:flatbuffers.Offset, splatNormal0Offset:flatbuffers.Offset, splatNormal1Offset:flatbuffers.Offset, splatNormal2Offset:flatbuffers.Offset, splatNormal3Offset:flatbuffers.Offset, detailNormalTexOffset:flatbuffers.Offset, splatScalesOffset:flatbuffers.Offset, splatMultsOffset:flatbuffers.Offset, splatDetailNormalDiffuseAlpha:boolean):flatbuffers.Offset {
  MapDecals.startMapDecals(builder);
  MapDecals.addDetailTex(builder, detailTexOffset);
  MapDecals.addSpecularTex(builder, specularTexOffset);
  MapDecals.addSplatDetailTex(builder, splatDetailTexOffset);
  MapDecals.addSplatDistrTex(builder, splatDistrTexOffset);
  MapDecals.addSplatNormal0(builder, splatNormal0Offset);
  MapDecals.addSplatNormal1(builder, splatNormal1Offset);
  MapDecals.addSplatNormal2(builder, splatNormal2Offset);
  MapDecals.addSplatNormal3(builder, splatNormal3Offset);
  MapDecals.addDetailNormalTex(builder, detailNormalTexOffset);
  MapDecals.addSplatScales(builder, splatScalesOffset);
  MapDecals.addSplatMults(builder, splatMultsOffset);
  MapDecals.addSplatDetailNormalDiffuseAlpha(builder, splatDetailNormalDiffuseAlpha);
  return MapDecals.endMapDecals(builder);
}

unpack(): MapDecalsT {
  return new MapDecalsT(
    this.detailTex(),
    this.specularTex(),
    this.splatDetailTex(),
    this.splatDistrTex(),
    this.splatNormal0(),
    this.splatNormal1(),
    this.splatNormal2(),
    this.splatNormal3(),
    this.detailNormalTex(),
    this.bb!.createScalarList<number>(this.splatScales.bind(this), this.splatScalesLength()),
    this.bb!.createScalarList<number>(this.splatMults.bind(this), this.splatMultsLength()),
    this.splatDetailNormalDiffuseAlpha()
  );
}


unpackTo(_o: MapDecalsT): void {
  _o.detailTex = this.detailTex();
  _o.specularTex = this.specularTex();
  _o.splatDetailTex = this.splatDetailTex();
  _o.splatDistrTex = this.splatDistrTex();
  _o.splatNormal0 = this.splatNormal0();
  _o.splatNormal1 = this.splatNormal1();
  _o.splatNormal2 = this.splatNormal2();
  _o.splatNormal3 = this.splatNormal3();
  _o.detailNormalTex = this.detailNormalTex();
  _o.splatScales = this.bb!.createScalarList<number>(this.splatScales.bind(this), this.splatScalesLength());
  _o.splatMults = this.bb!.createScalarList<number>(this.splatMults.bind(this), this.splatMultsLength());
  _o.splatDetailNormalDiffuseAlpha = this.splatDetailNormalDiffuseAlpha();
}
}

export class MapDecalsT implements flatbuffers.IGeneratedObject {
constructor(
  public detailTex: string|Uint8Array|null = null,
  public specularTex: string|Uint8Array|null = null,
  public splatDetailTex: string|Uint8Array|null = null,
  public splatDistrTex: string|Uint8Array|null = null,
  public splatNormal0: string|Uint8Array|null = null,
  public splatNormal1: string|Uint8Array|null = null,
  public splatNormal2: string|Uint8Array|null = null,
  public splatNormal3: string|Uint8Array|null = null,
  public detailNormalTex: string|Uint8Array|null = null,
  public splatScales: (number)[] = [],
  public splatMults: (number)[] = [],
  public splatDetailNormalDiffuseAlpha: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const detailTex = (this.detailTex !== null ? builder.createString(this.detailTex!) : 0);
  const specularTex = (this.specularTex !== null ? builder.createString(this.specularTex!) : 0);
  const splatDetailTex = (this.splatDetailTex !== null ? builder.createString(this.splatDetailTex!) : 0);
  const splatDistrTex = (this.splatDistrTex !== null ? builder.createString(this.splatDistrTex!) : 0);
  const splatNormal0 = (this.splatNormal0 !== null ? builder.createString(this.splatNormal0!) : 0);
  const splatNormal1 = (this.splatNormal1 !== null ? builder.createString(this.splatNormal1!) : 0);
  const splatNormal2 = (this.splatNormal2 !== null ? builder.createString(this.splatNormal2!) : 0);
  const splatNormal3 = (this.splatNormal3 !== null ? builder.createString(this.splatNormal3!) : 0);
  const detailNormalTex = (this.detailNormalTex !== null ? builder.createString(this.detailNormalTex!) : 0);
  const splatScales = MapDecals.createSplatScalesVector(builder, this.splatScales);
  const splatMults = MapDecals.createSplatMultsVector(builder, this.splatMults);

  return MapDecals.createMapDecals(builder,
    detailTex,
    specularTex,
    splatDetailTex,
    splatDistrTex,
    splatNormal0,
    splatNormal1,
    splatNormal2,
    splatNormal3,
    detailNormalTex,
    splatScales,
    splatMults,
    this.splatDetailNormalDiffuseAlpha
  );
}
}
