// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class MapStartPos implements flatbuffers.IUnpackableObject<MapStartPosT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MapStartPos {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

x():number {
  return this.bb!.readFloat32(this.bb_pos);
}

z():number {
  return this.bb!.readFloat32(this.bb_pos + 4);
}

static sizeOf():number {
  return 8;
}

static createMapStartPos(builder:flatbuffers.Builder, x: number, z: number):flatbuffers.Offset {
  builder.prep(4, 8);
  builder.writeFloat32(z);
  builder.writeFloat32(x);
  return builder.offset();
}


unpack(): MapStartPosT {
  return new MapStartPosT(
    this.x(),
    this.z()
  );
}


unpackTo(_o: MapStartPosT): void {
  _o.x = this.x();
  _o.z = this.z();
}
}

export class MapStartPosT implements flatbuffers.IGeneratedObject {
constructor(
  public x: number = 0.0,
  public z: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return MapStartPos.createMapStartPos(builder,
    this.x,
    this.z
  );
}
}
