// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { OrgGroupInfo, OrgGroupInfoT } from '../spring-web/org-group-info.js';


export class OrgGroupState implements flatbuffers.IUnpackableObject<OrgGroupStateT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):OrgGroupState {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsOrgGroupState(bb:flatbuffers.ByteBuffer, obj?:OrgGroupState):OrgGroupState {
  return (obj || new OrgGroupState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsOrgGroupState(bb:flatbuffers.ByteBuffer, obj?:OrgGroupState):OrgGroupState {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new OrgGroupState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

groups(index: number, obj?:OrgGroupInfo):OrgGroupInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new OrgGroupInfo()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

groupsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startOrgGroupState(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addGroups(builder:flatbuffers.Builder, groupsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, groupsOffset, 0);
}

static createGroupsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startGroupsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endOrgGroupState(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createOrgGroupState(builder:flatbuffers.Builder, groupsOffset:flatbuffers.Offset):flatbuffers.Offset {
  OrgGroupState.startOrgGroupState(builder);
  OrgGroupState.addGroups(builder, groupsOffset);
  return OrgGroupState.endOrgGroupState(builder);
}

unpack(): OrgGroupStateT {
  return new OrgGroupStateT(
    this.bb!.createObjList<OrgGroupInfo, OrgGroupInfoT>(this.groups.bind(this), this.groupsLength())
  );
}


unpackTo(_o: OrgGroupStateT): void {
  _o.groups = this.bb!.createObjList<OrgGroupInfo, OrgGroupInfoT>(this.groups.bind(this), this.groupsLength());
}
}

export class OrgGroupStateT implements flatbuffers.IGeneratedObject {
constructor(
  public groups: (OrgGroupInfoT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const groups = OrgGroupState.createGroupsVector(builder, builder.createObjectOffsetList(this.groups));

  return OrgGroupState.createOrgGroupState(builder,
    groups
  );
}
}
