// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Echelon } from '../spring-web/echelon.js';


/**
 * One org group in the team's org tree. `echelon`/`parent_id` are streamed
 * regardless of the v0 platoon-only surface so the client OOB tree is
 * already tier-shaped (PLAN-macro-directives §1 field discipline).
 */
export class OrgGroupInfo implements flatbuffers.IUnpackableObject<OrgGroupInfoT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):OrgGroupInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsOrgGroupInfo(bb:flatbuffers.ByteBuffer, obj?:OrgGroupInfo):OrgGroupInfo {
  return (obj || new OrgGroupInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsOrgGroupInfo(bb:flatbuffers.ByteBuffer, obj?:OrgGroupInfo):OrgGroupInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new OrgGroupInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

groupId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

echelon():Echelon {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : Echelon.Squad;
}

ownerTeam():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

parentId():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

memberIds(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

memberIdsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

memberIdsArray():Uint32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? new Uint32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

currentDirectiveId():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

postureJson():string|null
postureJson(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
postureJson(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

createdAtFrame():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startOrgGroupInfo(builder:flatbuffers.Builder) {
  builder.startObject(9);
}

static addGroupId(builder:flatbuffers.Builder, groupId:number) {
  builder.addFieldInt32(0, groupId, 0);
}

static addEchelon(builder:flatbuffers.Builder, echelon:Echelon) {
  builder.addFieldInt8(1, echelon, Echelon.Squad);
}

static addOwnerTeam(builder:flatbuffers.Builder, ownerTeam:number) {
  builder.addFieldInt8(2, ownerTeam, 0);
}

static addParentId(builder:flatbuffers.Builder, parentId:number) {
  builder.addFieldInt32(3, parentId, 0);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, nameOffset, 0);
}

static addMemberIds(builder:flatbuffers.Builder, memberIdsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, memberIdsOffset, 0);
}

static createMemberIdsVector(builder:flatbuffers.Builder, data:number[]|Uint32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createMemberIdsVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createMemberIdsVector(builder:flatbuffers.Builder, data:number[]|Uint32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]!);
  }
  return builder.endVector();
}

static startMemberIdsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addCurrentDirectiveId(builder:flatbuffers.Builder, currentDirectiveId:number) {
  builder.addFieldInt32(6, currentDirectiveId, 0);
}

static addPostureJson(builder:flatbuffers.Builder, postureJsonOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, postureJsonOffset, 0);
}

static addCreatedAtFrame(builder:flatbuffers.Builder, createdAtFrame:number) {
  builder.addFieldInt32(8, createdAtFrame, 0);
}

static endOrgGroupInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createOrgGroupInfo(builder:flatbuffers.Builder, groupId:number, echelon:Echelon, ownerTeam:number, parentId:number, nameOffset:flatbuffers.Offset, memberIdsOffset:flatbuffers.Offset, currentDirectiveId:number, postureJsonOffset:flatbuffers.Offset, createdAtFrame:number):flatbuffers.Offset {
  OrgGroupInfo.startOrgGroupInfo(builder);
  OrgGroupInfo.addGroupId(builder, groupId);
  OrgGroupInfo.addEchelon(builder, echelon);
  OrgGroupInfo.addOwnerTeam(builder, ownerTeam);
  OrgGroupInfo.addParentId(builder, parentId);
  OrgGroupInfo.addName(builder, nameOffset);
  OrgGroupInfo.addMemberIds(builder, memberIdsOffset);
  OrgGroupInfo.addCurrentDirectiveId(builder, currentDirectiveId);
  OrgGroupInfo.addPostureJson(builder, postureJsonOffset);
  OrgGroupInfo.addCreatedAtFrame(builder, createdAtFrame);
  return OrgGroupInfo.endOrgGroupInfo(builder);
}

unpack(): OrgGroupInfoT {
  return new OrgGroupInfoT(
    this.groupId(),
    this.echelon(),
    this.ownerTeam(),
    this.parentId(),
    this.name(),
    this.bb!.createScalarList<number>(this.memberIds.bind(this), this.memberIdsLength()),
    this.currentDirectiveId(),
    this.postureJson(),
    this.createdAtFrame()
  );
}


unpackTo(_o: OrgGroupInfoT): void {
  _o.groupId = this.groupId();
  _o.echelon = this.echelon();
  _o.ownerTeam = this.ownerTeam();
  _o.parentId = this.parentId();
  _o.name = this.name();
  _o.memberIds = this.bb!.createScalarList<number>(this.memberIds.bind(this), this.memberIdsLength());
  _o.currentDirectiveId = this.currentDirectiveId();
  _o.postureJson = this.postureJson();
  _o.createdAtFrame = this.createdAtFrame();
}
}

export class OrgGroupInfoT implements flatbuffers.IGeneratedObject {
constructor(
  public groupId: number = 0,
  public echelon: Echelon = Echelon.Squad,
  public ownerTeam: number = 0,
  public parentId: number = 0,
  public name: string|Uint8Array|null = null,
  public memberIds: (number)[] = [],
  public currentDirectiveId: number = 0,
  public postureJson: string|Uint8Array|null = null,
  public createdAtFrame: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const name = (this.name !== null ? builder.createString(this.name!) : 0);
  const memberIds = OrgGroupInfo.createMemberIdsVector(builder, this.memberIds);
  const postureJson = (this.postureJson !== null ? builder.createString(this.postureJson!) : 0);

  return OrgGroupInfo.createOrgGroupInfo(builder,
    this.groupId,
    this.echelon,
    this.ownerTeam,
    this.parentId,
    name,
    memberIds,
    this.currentDirectiveId,
    postureJson,
    this.createdAtFrame
  );
}
}
