// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Vec3, Vec3T } from '../spring-web/vec3.js';


/**
 * Client → Server: ask the server's IPathManager to compute a path.
 * Mirrors Spring's native `Spring.PathRequest(moveType, sx, sy, sz, ex, ey,
 * ez, radius)` Lua API but routed through the network. The server replies
 * with a `PathResponse` carrying the full waypoint list — typically on
 * the same sim tick, since `IPathManager::RequestPath` returns
 * synchronously for HAPFS and within ~1 tick for QTPFS. `request_id` is
 * client-assigned and must be unique per session; client-side widget
 * code keys path results by this id so concurrent requests don't
 * collide.
 *
 * `move_type` matches `MoveDef::pathType` (resolved via
 * `UnitDefs[unitDefID].moveDef.id` on the client). Air units have no
 * move def — widgets must skip the request entirely rather than send a
 * 0 move type.
 */
export class PathRequest implements flatbuffers.IUnpackableObject<PathRequestT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PathRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPathRequest(bb:flatbuffers.ByteBuffer, obj?:PathRequest):PathRequest {
  return (obj || new PathRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPathRequest(bb:flatbuffers.ByteBuffer, obj?:PathRequest):PathRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PathRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

requestId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

start(obj?:Vec3):Vec3|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Vec3()).__init(this.bb_pos + offset, this.bb!) : null;
}

end(obj?:Vec3):Vec3|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Vec3()).__init(this.bb_pos + offset, this.bb!) : null;
}

/**
 * Index into the server's MoveDefHandler (`MoveDef::pathType`).
 * Different unit types take different routes — a kbot can climb
 * hills a tank can't.
 */
moveType():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

/**
 * Search radius around `end` — if the exact end is unreachable,
 * accept any reachable point within this distance. Spring's
 * default is 8.0 elmos.
 */
goalRadius():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startPathRequest(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addRequestId(builder:flatbuffers.Builder, requestId:number) {
  builder.addFieldInt32(0, requestId, 0);
}

static addStart(builder:flatbuffers.Builder, startOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, startOffset, 0);
}

static addEnd(builder:flatbuffers.Builder, endOffset:flatbuffers.Offset) {
  builder.addFieldStruct(2, endOffset, 0);
}

static addMoveType(builder:flatbuffers.Builder, moveType:number) {
  builder.addFieldInt32(3, moveType, 0);
}

static addGoalRadius(builder:flatbuffers.Builder, goalRadius:number) {
  builder.addFieldFloat32(4, goalRadius, 0.0);
}

static endPathRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


unpack(): PathRequestT {
  return new PathRequestT(
    this.requestId(),
    (this.start() !== null ? this.start()!.unpack() : null),
    (this.end() !== null ? this.end()!.unpack() : null),
    this.moveType(),
    this.goalRadius()
  );
}


unpackTo(_o: PathRequestT): void {
  _o.requestId = this.requestId();
  _o.start = (this.start() !== null ? this.start()!.unpack() : null);
  _o.end = (this.end() !== null ? this.end()!.unpack() : null);
  _o.moveType = this.moveType();
  _o.goalRadius = this.goalRadius();
}
}

export class PathRequestT implements flatbuffers.IGeneratedObject {
constructor(
  public requestId: number = 0,
  public start: Vec3T|null = null,
  public end: Vec3T|null = null,
  public moveType: number = 0,
  public goalRadius: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  PathRequest.startPathRequest(builder);
  PathRequest.addRequestId(builder, this.requestId);
  PathRequest.addStart(builder, (this.start !== null ? this.start!.pack(builder) : 0));
  PathRequest.addEnd(builder, (this.end !== null ? this.end!.pack(builder) : 0));
  PathRequest.addMoveType(builder, this.moveType);
  PathRequest.addGoalRadius(builder, this.goalRadius);

  return PathRequest.endPathRequest(builder);
}
}
