// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * Broadcast to remaining clients when a player disconnects from
 * the game server. The game's Lua scripts decide what happens next
 * (kill units, pause, hand to AI, etc.) — this message is purely
 * informational so clients can update their UI.
 */
export class PlayerLeft implements flatbuffers.IUnpackableObject<PlayerLeftT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PlayerLeft {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPlayerLeft(bb:flatbuffers.ByteBuffer, obj?:PlayerLeft):PlayerLeft {
  return (obj || new PlayerLeft()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPlayerLeft(bb:flatbuffers.ByteBuffer, obj?:PlayerLeft):PlayerLeft {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PlayerLeft()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * DB **account** id, like `AuthResponse.player_id` — not the sim
 * playerNum. Anything that needs to key a departure against synced state
 * should read the `PlayerRoster` broadcast that accompanies this message
 * (the leaver's entry flips to `active = false`).
 */
playerId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

username():string|null
username(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
username(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

team():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : 0;
}

/**
 * 0 = voluntary quit, 1 = kicked, 2 = connection timeout, 3 = detach
 * (worker parked client-side; may reconnect — PLAN-quickstart.md §3.3)
 */
reason():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

static startPlayerLeft(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addPlayerId(builder:flatbuffers.Builder, playerId:number) {
  builder.addFieldInt32(0, playerId, 0);
}

static addUsername(builder:flatbuffers.Builder, usernameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, usernameOffset, 0);
}

static addTeam(builder:flatbuffers.Builder, team:number) {
  builder.addFieldInt8(2, team, 0);
}

static addReason(builder:flatbuffers.Builder, reason:number) {
  builder.addFieldInt8(3, reason, 0);
}

static endPlayerLeft(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPlayerLeft(builder:flatbuffers.Builder, playerId:number, usernameOffset:flatbuffers.Offset, team:number, reason:number):flatbuffers.Offset {
  PlayerLeft.startPlayerLeft(builder);
  PlayerLeft.addPlayerId(builder, playerId);
  PlayerLeft.addUsername(builder, usernameOffset);
  PlayerLeft.addTeam(builder, team);
  PlayerLeft.addReason(builder, reason);
  return PlayerLeft.endPlayerLeft(builder);
}

unpack(): PlayerLeftT {
  return new PlayerLeftT(
    this.playerId(),
    this.username(),
    this.team(),
    this.reason()
  );
}


unpackTo(_o: PlayerLeftT): void {
  _o.playerId = this.playerId();
  _o.username = this.username();
  _o.team = this.team();
  _o.reason = this.reason();
}
}

export class PlayerLeftT implements flatbuffers.IGeneratedObject {
constructor(
  public playerId: number = 0,
  public username: string|Uint8Array|null = null,
  public team: number = 0,
  public reason: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const username = (this.username !== null ? builder.createString(this.username!) : 0);

  return PlayerLeft.createPlayerLeft(builder,
    this.playerId,
    username,
    this.team,
    this.reason
  );
}
}
