// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { PlayerEntry, PlayerEntryT } from '../spring-web/player-entry.js';


/**
 * The full player roster, sent reliably to each client on auth and
 * re-broadcast to everyone whenever it changes (join, reconnect, leave).
 * Always complete, never a delta — it is a handful of rows and a client that
 * missed one broadcast would otherwise be permanently wrong.
 *
 * This is the only place the client learns player *names* and which
 * playerNums exist; the lobby room roster is not a substitute (it has no AI
 * entries, no sim playerNums, and is frozen at game start).
 */
export class PlayerRoster implements flatbuffers.IUnpackableObject<PlayerRosterT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PlayerRoster {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPlayerRoster(bb:flatbuffers.ByteBuffer, obj?:PlayerRoster):PlayerRoster {
  return (obj || new PlayerRoster()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPlayerRoster(bb:flatbuffers.ByteBuffer, obj?:PlayerRoster):PlayerRoster {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PlayerRoster()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

players(index: number, obj?:PlayerEntry):PlayerEntry|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new PlayerEntry()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

playersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startPlayerRoster(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addPlayers(builder:flatbuffers.Builder, playersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, playersOffset, 0);
}

static createPlayersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startPlayersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endPlayerRoster(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPlayerRoster(builder:flatbuffers.Builder, playersOffset:flatbuffers.Offset):flatbuffers.Offset {
  PlayerRoster.startPlayerRoster(builder);
  PlayerRoster.addPlayers(builder, playersOffset);
  return PlayerRoster.endPlayerRoster(builder);
}

unpack(): PlayerRosterT {
  return new PlayerRosterT(
    this.bb!.createObjList<PlayerEntry, PlayerEntryT>(this.players.bind(this), this.playersLength())
  );
}


unpackTo(_o: PlayerRosterT): void {
  _o.players = this.bb!.createObjList<PlayerEntry, PlayerEntryT>(this.players.bind(this), this.playersLength());
}
}

export class PlayerRosterT implements flatbuffers.IGeneratedObject {
constructor(
  public players: (PlayerEntryT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const players = PlayerRoster.createPlayersVector(builder, builder.createObjectOffsetList(this.players));

  return PlayerRoster.createPlayerRoster(builder,
    players
  );
}
}
