// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { PlayerCommand, PlayerCommandT } from '../spring-web/player-command.js';


/**
 * Multi-command batch sent atomically. Used for building drag-row /
 * drag-rectangle placement (N PlayerCommand entries, same builder
 * list, different positions), waypoint drag (CMD.INSERT + CMD.REMOVE
 * pair against the same unit), and any sequence where dropping or
 * reordering between entries would break intent. The server executes
 * the contained commands in order on the same sim tick — no
 * in-between state visible to other clients.
 */
export class PlayerCommandBatch implements flatbuffers.IUnpackableObject<PlayerCommandBatchT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PlayerCommandBatch {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPlayerCommandBatch(bb:flatbuffers.ByteBuffer, obj?:PlayerCommandBatch):PlayerCommandBatch {
  return (obj || new PlayerCommandBatch()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPlayerCommandBatch(bb:flatbuffers.ByteBuffer, obj?:PlayerCommandBatch):PlayerCommandBatch {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PlayerCommandBatch()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sequence():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

commands(index: number, obj?:PlayerCommand):PlayerCommand|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new PlayerCommand()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

commandsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startPlayerCommandBatch(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addSequence(builder:flatbuffers.Builder, sequence:number) {
  builder.addFieldInt32(0, sequence, 0);
}

static addCommands(builder:flatbuffers.Builder, commandsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, commandsOffset, 0);
}

static createCommandsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startCommandsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endPlayerCommandBatch(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPlayerCommandBatch(builder:flatbuffers.Builder, sequence:number, commandsOffset:flatbuffers.Offset):flatbuffers.Offset {
  PlayerCommandBatch.startPlayerCommandBatch(builder);
  PlayerCommandBatch.addSequence(builder, sequence);
  PlayerCommandBatch.addCommands(builder, commandsOffset);
  return PlayerCommandBatch.endPlayerCommandBatch(builder);
}

unpack(): PlayerCommandBatchT {
  return new PlayerCommandBatchT(
    this.sequence(),
    this.bb!.createObjList<PlayerCommand, PlayerCommandT>(this.commands.bind(this), this.commandsLength())
  );
}


unpackTo(_o: PlayerCommandBatchT): void {
  _o.sequence = this.sequence();
  _o.commands = this.bb!.createObjList<PlayerCommand, PlayerCommandT>(this.commands.bind(this), this.commandsLength());
}
}

export class PlayerCommandBatchT implements flatbuffers.IGeneratedObject {
constructor(
  public sequence: number = 0,
  public commands: (PlayerCommandT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const commands = PlayerCommandBatch.createCommandsVector(builder, builder.createObjectOffsetList(this.commands));

  return PlayerCommandBatch.createPlayerCommandBatch(builder,
    this.sequence,
    commands
  );
}
}
