// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ReplayControlAction } from '../spring-web/replay-control-action.js';


/**
 * Spectator → replay server. Ignored (and logged) anywhere else.
 */
export class ReplayControl implements flatbuffers.IUnpackableObject<ReplayControlT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ReplayControl {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsReplayControl(bb:flatbuffers.ByteBuffer, obj?:ReplayControl):ReplayControl {
  return (obj || new ReplayControl()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsReplayControl(bb:flatbuffers.ByteBuffer, obj?:ReplayControl):ReplayControl {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ReplayControl()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

action():ReplayControlAction {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : ReplayControlAction.Pause;
}

speed():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 1.0;
}

frame():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

povTeam():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : -1;
}

static startReplayControl(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addAction(builder:flatbuffers.Builder, action:ReplayControlAction) {
  builder.addFieldInt8(0, action, ReplayControlAction.Pause);
}

static addSpeed(builder:flatbuffers.Builder, speed:number) {
  builder.addFieldFloat32(1, speed, 1.0);
}

static addFrame(builder:flatbuffers.Builder, frame:number) {
  builder.addFieldInt32(2, frame, 0);
}

static addPovTeam(builder:flatbuffers.Builder, povTeam:number) {
  builder.addFieldInt32(3, povTeam, -1);
}

static endReplayControl(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createReplayControl(builder:flatbuffers.Builder, action:ReplayControlAction, speed:number, frame:number, povTeam:number):flatbuffers.Offset {
  ReplayControl.startReplayControl(builder);
  ReplayControl.addAction(builder, action);
  ReplayControl.addSpeed(builder, speed);
  ReplayControl.addFrame(builder, frame);
  ReplayControl.addPovTeam(builder, povTeam);
  return ReplayControl.endReplayControl(builder);
}

unpack(): ReplayControlT {
  return new ReplayControlT(
    this.action(),
    this.speed(),
    this.frame(),
    this.povTeam()
  );
}


unpackTo(_o: ReplayControlT): void {
  _o.action = this.action();
  _o.speed = this.speed();
  _o.frame = this.frame();
  _o.povTeam = this.povTeam();
}
}

export class ReplayControlT implements flatbuffers.IGeneratedObject {
constructor(
  public action: ReplayControlAction = ReplayControlAction.Pause,
  public speed: number = 1.0,
  public frame: number = 0,
  public povTeam: number = -1
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return ReplayControl.createReplayControl(builder,
    this.action,
    this.speed,
    this.frame,
    this.povTeam
  );
}
}
