// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class ResourceUpdate {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ResourceUpdate {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsResourceUpdate(bb:flatbuffers.ByteBuffer, obj?:ResourceUpdate):ResourceUpdate {
  return (obj || new ResourceUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsResourceUpdate(bb:flatbuffers.ByteBuffer, obj?:ResourceUpdate):ResourceUpdate {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ResourceUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

team():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

metal():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

maxMetal():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

energy():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

maxEnergy():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

metalIncome():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

energyIncome():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startResourceUpdate(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addTeam(builder:flatbuffers.Builder, team:number) {
  builder.addFieldInt8(0, team, 0);
}

static addMetal(builder:flatbuffers.Builder, metal:number) {
  builder.addFieldFloat32(1, metal, 0.0);
}

static addMaxMetal(builder:flatbuffers.Builder, maxMetal:number) {
  builder.addFieldFloat32(2, maxMetal, 0.0);
}

static addEnergy(builder:flatbuffers.Builder, energy:number) {
  builder.addFieldFloat32(3, energy, 0.0);
}

static addMaxEnergy(builder:flatbuffers.Builder, maxEnergy:number) {
  builder.addFieldFloat32(4, maxEnergy, 0.0);
}

static addMetalIncome(builder:flatbuffers.Builder, metalIncome:number) {
  builder.addFieldFloat32(5, metalIncome, 0.0);
}

static addEnergyIncome(builder:flatbuffers.Builder, energyIncome:number) {
  builder.addFieldFloat32(6, energyIncome, 0.0);
}

static endResourceUpdate(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createResourceUpdate(builder:flatbuffers.Builder, team:number, metal:number, maxMetal:number, energy:number, maxEnergy:number, metalIncome:number, energyIncome:number):flatbuffers.Offset {
  ResourceUpdate.startResourceUpdate(builder);
  ResourceUpdate.addTeam(builder, team);
  ResourceUpdate.addMetal(builder, metal);
  ResourceUpdate.addMaxMetal(builder, maxMetal);
  ResourceUpdate.addEnergy(builder, energy);
  ResourceUpdate.addMaxEnergy(builder, maxEnergy);
  ResourceUpdate.addMetalIncome(builder, metalIncome);
  ResourceUpdate.addEnergyIncome(builder, energyIncome);
  return ResourceUpdate.endResourceUpdate(builder);
}
}
