// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * Assign a map start position to a player or AI slot in the current
 * room. Start positions are indices into the map's start_positions
 * array (see MapInfo) — the game server uses them to decide where
 * each team spawns at game start.
 *
 * Addressing rules:
 *   - target_player_id = 0 and target_ai_slot = -1: "my own slot"
 *     (any player can do this; assigns to the sender).
 *   - target_player_id > 0: target that player's slot. Host only.
 *   - target_ai_slot >= 0: target that AI slot. Host only.
 *   - pos_index = -1 clears the assignment (will be auto-filled
 *     at game start).
 *
 * The server rejects the request if `pos_index` is already held by
 * another slot in the same room, or is out of range for the map.
 */
export class RoomSetStartPos implements flatbuffers.IUnpackableObject<RoomSetStartPosT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RoomSetStartPos {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRoomSetStartPos(bb:flatbuffers.ByteBuffer, obj?:RoomSetStartPos):RoomSetStartPos {
  return (obj || new RoomSetStartPos()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRoomSetStartPos(bb:flatbuffers.ByteBuffer, obj?:RoomSetStartPos):RoomSetStartPos {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RoomSetStartPos()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

targetPlayerId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

targetAiSlot():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : -1;
}

posIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : 0;
}

static startRoomSetStartPos(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addTargetPlayerId(builder:flatbuffers.Builder, targetPlayerId:number) {
  builder.addFieldInt32(0, targetPlayerId, 0);
}

static addTargetAiSlot(builder:flatbuffers.Builder, targetAiSlot:number) {
  builder.addFieldInt8(1, targetAiSlot, -1);
}

static addPosIndex(builder:flatbuffers.Builder, posIndex:number) {
  builder.addFieldInt8(2, posIndex, 0);
}

static endRoomSetStartPos(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRoomSetStartPos(builder:flatbuffers.Builder, targetPlayerId:number, targetAiSlot:number, posIndex:number):flatbuffers.Offset {
  RoomSetStartPos.startRoomSetStartPos(builder);
  RoomSetStartPos.addTargetPlayerId(builder, targetPlayerId);
  RoomSetStartPos.addTargetAiSlot(builder, targetAiSlot);
  RoomSetStartPos.addPosIndex(builder, posIndex);
  return RoomSetStartPos.endRoomSetStartPos(builder);
}

unpack(): RoomSetStartPosT {
  return new RoomSetStartPosT(
    this.targetPlayerId(),
    this.targetAiSlot(),
    this.posIndex()
  );
}


unpackTo(_o: RoomSetStartPosT): void {
  _o.targetPlayerId = this.targetPlayerId();
  _o.targetAiSlot = this.targetAiSlot();
  _o.posIndex = this.posIndex();
}
}

export class RoomSetStartPosT implements flatbuffers.IGeneratedObject {
constructor(
  public targetPlayerId: number = 0,
  public targetAiSlot: number = -1,
  public posIndex: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return RoomSetStartPos.createRoomSetStartPos(builder,
    this.targetPlayerId,
    this.targetAiSlot,
    this.posIndex
  );
}
}
