// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class RoomTeamSelect implements flatbuffers.IUnpackableObject<RoomTeamSelectT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RoomTeamSelect {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRoomTeamSelect(bb:flatbuffers.ByteBuffer, obj?:RoomTeamSelect):RoomTeamSelect {
  return (obj || new RoomTeamSelect()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRoomTeamSelect(bb:flatbuffers.ByteBuffer, obj?:RoomTeamSelect):RoomTeamSelect {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RoomTeamSelect()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

team():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

static startRoomTeamSelect(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addTeam(builder:flatbuffers.Builder, team:number) {
  builder.addFieldInt8(0, team, 0);
}

static endRoomTeamSelect(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRoomTeamSelect(builder:flatbuffers.Builder, team:number):flatbuffers.Offset {
  RoomTeamSelect.startRoomTeamSelect(builder);
  RoomTeamSelect.addTeam(builder, team);
  return RoomTeamSelect.endRoomTeamSelect(builder);
}

unpack(): RoomTeamSelectT {
  return new RoomTeamSelectT(
    this.team()
  );
}


unpackTo(_o: RoomTeamSelectT): void {
  _o.team = this.team();
}
}

export class RoomTeamSelectT implements flatbuffers.IGeneratedObject {
constructor(
  public team: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return RoomTeamSelect.createRoomTeamSelect(builder,
    this.team
  );
}
}
