// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class RoomCreate implements flatbuffers.IUnpackableObject<RoomCreateT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RoomCreate {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRoomCreate(bb:flatbuffers.ByteBuffer, obj?:RoomCreate):RoomCreate {
  return (obj || new RoomCreate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRoomCreate(bb:flatbuffers.ByteBuffer, obj?:RoomCreate):RoomCreate {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RoomCreate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

mapName():string|null
mapName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
mapName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

gameId():string|null
gameId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
gameId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

maxPlayers():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 8;
}

password():string|null
password(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
password(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startRoomCreate(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static addMapName(builder:flatbuffers.Builder, mapNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, mapNameOffset, 0);
}

static addGameId(builder:flatbuffers.Builder, gameIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, gameIdOffset, 0);
}

static addMaxPlayers(builder:flatbuffers.Builder, maxPlayers:number) {
  builder.addFieldInt8(3, maxPlayers, 8);
}

static addPassword(builder:flatbuffers.Builder, passwordOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, passwordOffset, 0);
}

static endRoomCreate(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRoomCreate(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, mapNameOffset:flatbuffers.Offset, gameIdOffset:flatbuffers.Offset, maxPlayers:number, passwordOffset:flatbuffers.Offset):flatbuffers.Offset {
  RoomCreate.startRoomCreate(builder);
  RoomCreate.addName(builder, nameOffset);
  RoomCreate.addMapName(builder, mapNameOffset);
  RoomCreate.addGameId(builder, gameIdOffset);
  RoomCreate.addMaxPlayers(builder, maxPlayers);
  RoomCreate.addPassword(builder, passwordOffset);
  return RoomCreate.endRoomCreate(builder);
}

unpack(): RoomCreateT {
  return new RoomCreateT(
    this.name(),
    this.mapName(),
    this.gameId(),
    this.maxPlayers(),
    this.password()
  );
}


unpackTo(_o: RoomCreateT): void {
  _o.name = this.name();
  _o.mapName = this.mapName();
  _o.gameId = this.gameId();
  _o.maxPlayers = this.maxPlayers();
  _o.password = this.password();
}
}

export class RoomCreateT implements flatbuffers.IGeneratedObject {
constructor(
  public name: string|Uint8Array|null = null,
  public mapName: string|Uint8Array|null = null,
  public gameId: string|Uint8Array|null = null,
  public maxPlayers: number = 8,
  public password: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const name = (this.name !== null ? builder.createString(this.name!) : 0);
  const mapName = (this.mapName !== null ? builder.createString(this.mapName!) : 0);
  const gameId = (this.gameId !== null ? builder.createString(this.gameId!) : 0);
  const password = (this.password !== null ? builder.createString(this.password!) : 0);

  return RoomCreate.createRoomCreate(builder,
    name,
    mapName,
    gameId,
    this.maxPlayers,
    password
  );
}
}
