// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class RoomJoin implements flatbuffers.IUnpackableObject<RoomJoinT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RoomJoin {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRoomJoin(bb:flatbuffers.ByteBuffer, obj?:RoomJoin):RoomJoin {
  return (obj || new RoomJoin()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRoomJoin(bb:flatbuffers.ByteBuffer, obj?:RoomJoin):RoomJoin {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RoomJoin()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

roomId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

password():string|null
password(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
password(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startRoomJoin(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addRoomId(builder:flatbuffers.Builder, roomId:number) {
  builder.addFieldInt32(0, roomId, 0);
}

static addPassword(builder:flatbuffers.Builder, passwordOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, passwordOffset, 0);
}

static endRoomJoin(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRoomJoin(builder:flatbuffers.Builder, roomId:number, passwordOffset:flatbuffers.Offset):flatbuffers.Offset {
  RoomJoin.startRoomJoin(builder);
  RoomJoin.addRoomId(builder, roomId);
  RoomJoin.addPassword(builder, passwordOffset);
  return RoomJoin.endRoomJoin(builder);
}

unpack(): RoomJoinT {
  return new RoomJoinT(
    this.roomId(),
    this.password()
  );
}


unpackTo(_o: RoomJoinT): void {
  _o.roomId = this.roomId();
  _o.password = this.password();
}
}

export class RoomJoinT implements flatbuffers.IGeneratedObject {
constructor(
  public roomId: number = 0,
  public password: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const password = (this.password !== null ? builder.createString(this.password!) : 0);

  return RoomJoin.createRoomJoin(builder,
    this.roomId,
    password
  );
}
}
