// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * Host-only request to close (delete) the entire room. Kills the
 * game subprocess if one is still running, removes the room from
 * the lobby's room list, and leaves every member in the browser
 * view. Symmetric with RoomCreate — once the close broadcast goes
 * out, the room id no longer resolves. Rejected if the sender is
 * not the current room host.
 */
export class RoomCloseRoom implements flatbuffers.IUnpackableObject<RoomCloseRoomT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RoomCloseRoom {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRoomCloseRoom(bb:flatbuffers.ByteBuffer, obj?:RoomCloseRoom):RoomCloseRoom {
  return (obj || new RoomCloseRoom()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRoomCloseRoom(bb:flatbuffers.ByteBuffer, obj?:RoomCloseRoom):RoomCloseRoom {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RoomCloseRoom()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startRoomCloseRoom(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endRoomCloseRoom(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRoomCloseRoom(builder:flatbuffers.Builder):flatbuffers.Offset {
  RoomCloseRoom.startRoomCloseRoom(builder);
  return RoomCloseRoom.endRoomCloseRoom(builder);
}

unpack(): RoomCloseRoomT {
  return new RoomCloseRoomT();
}


unpackTo(_o: RoomCloseRoomT): void {}
}

export class RoomCloseRoomT implements flatbuffers.IGeneratedObject {
constructor(){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return RoomCloseRoom.createRoomCloseRoom(builder);
}
}
