// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { RoomPlayerInfo } from '../spring-web/room-player-info.js';


export class RoomPlayerJoined {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RoomPlayerJoined {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRoomPlayerJoined(bb:flatbuffers.ByteBuffer, obj?:RoomPlayerJoined):RoomPlayerJoined {
  return (obj || new RoomPlayerJoined()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRoomPlayerJoined(bb:flatbuffers.ByteBuffer, obj?:RoomPlayerJoined):RoomPlayerJoined {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RoomPlayerJoined()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

roomId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

player(obj?:RoomPlayerInfo):RoomPlayerInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new RoomPlayerInfo()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startRoomPlayerJoined(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addRoomId(builder:flatbuffers.Builder, roomId:number) {
  builder.addFieldInt32(0, roomId, 0);
}

static addPlayer(builder:flatbuffers.Builder, playerOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, playerOffset, 0);
}

static endRoomPlayerJoined(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
