// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { RoomAISlot, RoomAISlotT } from '../spring-web/room-aislot.js';
import { RoomPlayerInfo, RoomPlayerInfoT } from '../spring-web/room-player-info.js';
import { RoomState } from '../spring-web/room-state.js';


export class RoomStateUpdate implements flatbuffers.IUnpackableObject<RoomStateUpdateT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RoomStateUpdate {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRoomStateUpdate(bb:flatbuffers.ByteBuffer, obj?:RoomStateUpdate):RoomStateUpdate {
  return (obj || new RoomStateUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRoomStateUpdate(bb:flatbuffers.ByteBuffer, obj?:RoomStateUpdate):RoomStateUpdate {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RoomStateUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

roomId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

state():RoomState {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : RoomState.Configuring;
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

mapName():string|null
mapName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
mapName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

gameName():string|null
gameName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
gameName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

players(index: number, obj?:RoomPlayerInfo):RoomPlayerInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new RoomPlayerInfo()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

playersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

countdownSeconds():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

gameServerPort():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

aiSlots(index: number, obj?:RoomAISlot):RoomAISlot|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? (obj || new RoomAISlot()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

aiSlotsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startRoomStateUpdate(builder:flatbuffers.Builder) {
  builder.startObject(9);
}

static addRoomId(builder:flatbuffers.Builder, roomId:number) {
  builder.addFieldInt32(0, roomId, 0);
}

static addState(builder:flatbuffers.Builder, state:RoomState) {
  builder.addFieldInt8(1, state, RoomState.Configuring);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, nameOffset, 0);
}

static addMapName(builder:flatbuffers.Builder, mapNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, mapNameOffset, 0);
}

static addGameName(builder:flatbuffers.Builder, gameNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, gameNameOffset, 0);
}

static addPlayers(builder:flatbuffers.Builder, playersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, playersOffset, 0);
}

static createPlayersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startPlayersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addCountdownSeconds(builder:flatbuffers.Builder, countdownSeconds:number) {
  builder.addFieldInt8(6, countdownSeconds, 0);
}

static addGameServerPort(builder:flatbuffers.Builder, gameServerPort:number) {
  builder.addFieldInt16(7, gameServerPort, 0);
}

static addAiSlots(builder:flatbuffers.Builder, aiSlotsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, aiSlotsOffset, 0);
}

static createAiSlotsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startAiSlotsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endRoomStateUpdate(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRoomStateUpdate(builder:flatbuffers.Builder, roomId:number, state:RoomState, nameOffset:flatbuffers.Offset, mapNameOffset:flatbuffers.Offset, gameNameOffset:flatbuffers.Offset, playersOffset:flatbuffers.Offset, countdownSeconds:number, gameServerPort:number, aiSlotsOffset:flatbuffers.Offset):flatbuffers.Offset {
  RoomStateUpdate.startRoomStateUpdate(builder);
  RoomStateUpdate.addRoomId(builder, roomId);
  RoomStateUpdate.addState(builder, state);
  RoomStateUpdate.addName(builder, nameOffset);
  RoomStateUpdate.addMapName(builder, mapNameOffset);
  RoomStateUpdate.addGameName(builder, gameNameOffset);
  RoomStateUpdate.addPlayers(builder, playersOffset);
  RoomStateUpdate.addCountdownSeconds(builder, countdownSeconds);
  RoomStateUpdate.addGameServerPort(builder, gameServerPort);
  RoomStateUpdate.addAiSlots(builder, aiSlotsOffset);
  return RoomStateUpdate.endRoomStateUpdate(builder);
}

unpack(): RoomStateUpdateT {
  return new RoomStateUpdateT(
    this.roomId(),
    this.state(),
    this.name(),
    this.mapName(),
    this.gameName(),
    this.bb!.createObjList<RoomPlayerInfo, RoomPlayerInfoT>(this.players.bind(this), this.playersLength()),
    this.countdownSeconds(),
    this.gameServerPort(),
    this.bb!.createObjList<RoomAISlot, RoomAISlotT>(this.aiSlots.bind(this), this.aiSlotsLength())
  );
}


unpackTo(_o: RoomStateUpdateT): void {
  _o.roomId = this.roomId();
  _o.state = this.state();
  _o.name = this.name();
  _o.mapName = this.mapName();
  _o.gameName = this.gameName();
  _o.players = this.bb!.createObjList<RoomPlayerInfo, RoomPlayerInfoT>(this.players.bind(this), this.playersLength());
  _o.countdownSeconds = this.countdownSeconds();
  _o.gameServerPort = this.gameServerPort();
  _o.aiSlots = this.bb!.createObjList<RoomAISlot, RoomAISlotT>(this.aiSlots.bind(this), this.aiSlotsLength());
}
}

export class RoomStateUpdateT implements flatbuffers.IGeneratedObject {
constructor(
  public roomId: number = 0,
  public state: RoomState = RoomState.Configuring,
  public name: string|Uint8Array|null = null,
  public mapName: string|Uint8Array|null = null,
  public gameName: string|Uint8Array|null = null,
  public players: (RoomPlayerInfoT)[] = [],
  public countdownSeconds: number = 0,
  public gameServerPort: number = 0,
  public aiSlots: (RoomAISlotT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const name = (this.name !== null ? builder.createString(this.name!) : 0);
  const mapName = (this.mapName !== null ? builder.createString(this.mapName!) : 0);
  const gameName = (this.gameName !== null ? builder.createString(this.gameName!) : 0);
  const players = RoomStateUpdate.createPlayersVector(builder, builder.createObjectOffsetList(this.players));
  const aiSlots = RoomStateUpdate.createAiSlotsVector(builder, builder.createObjectOffsetList(this.aiSlots));

  return RoomStateUpdate.createRoomStateUpdate(builder,
    this.roomId,
    this.state,
    name,
    mapName,
    gameName,
    players,
    this.countdownSeconds,
    this.gameServerPort,
    aiSlots
  );
}
}
