// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * An AI player occupying a slot in a room's roster. Unlike human
 * players, AI slots have no playerId / clientId — they only exist
 * on the lobby server until the game starts, at which point the
 * game server spawns an AIRuntimePool entry for each slot.
 */
export class RoomAISlot implements flatbuffers.IUnpackableObject<RoomAISlotT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RoomAISlot {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRoomAISlot(bb:flatbuffers.ByteBuffer, obj?:RoomAISlot):RoomAISlot {
  return (obj || new RoomAISlot()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRoomAISlot(bb:flatbuffers.ByteBuffer, obj?:RoomAISlot):RoomAISlot {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RoomAISlot()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

aiId():string|null
aiId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
aiId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

displayName():string|null
displayName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
displayName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

team():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

/**
 * Same semantics as RoomPlayerInfo.start_pos — -1 means the
 * lobby will auto-assign at game start.
 */
startPos():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : -1;
}

/**
 * Optional personality/difficulty profile name for AI plugins that
 * support one (e.g. Metalstorm's strategos: "aggressive", "caretaker")
 * — PLAN-metalstorm-ai.md §10 task 6. Empty = no override. Opaque to
 * the engine; set via POST /api/rooms/ai/profile.
 */
profile():string|null
profile(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
profile(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startRoomAISlot(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addAiId(builder:flatbuffers.Builder, aiIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, aiIdOffset, 0);
}

static addDisplayName(builder:flatbuffers.Builder, displayNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, displayNameOffset, 0);
}

static addTeam(builder:flatbuffers.Builder, team:number) {
  builder.addFieldInt8(2, team, 0);
}

static addStartPos(builder:flatbuffers.Builder, startPos:number) {
  builder.addFieldInt8(3, startPos, -1);
}

static addProfile(builder:flatbuffers.Builder, profileOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, profileOffset, 0);
}

static endRoomAISlot(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRoomAISlot(builder:flatbuffers.Builder, aiIdOffset:flatbuffers.Offset, displayNameOffset:flatbuffers.Offset, team:number, startPos:number, profileOffset:flatbuffers.Offset):flatbuffers.Offset {
  RoomAISlot.startRoomAISlot(builder);
  RoomAISlot.addAiId(builder, aiIdOffset);
  RoomAISlot.addDisplayName(builder, displayNameOffset);
  RoomAISlot.addTeam(builder, team);
  RoomAISlot.addStartPos(builder, startPos);
  RoomAISlot.addProfile(builder, profileOffset);
  return RoomAISlot.endRoomAISlot(builder);
}

unpack(): RoomAISlotT {
  return new RoomAISlotT(
    this.aiId(),
    this.displayName(),
    this.team(),
    this.startPos(),
    this.profile()
  );
}


unpackTo(_o: RoomAISlotT): void {
  _o.aiId = this.aiId();
  _o.displayName = this.displayName();
  _o.team = this.team();
  _o.startPos = this.startPos();
  _o.profile = this.profile();
}
}

export class RoomAISlotT implements flatbuffers.IGeneratedObject {
constructor(
  public aiId: string|Uint8Array|null = null,
  public displayName: string|Uint8Array|null = null,
  public team: number = 0,
  public startPos: number = -1,
  public profile: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const aiId = (this.aiId !== null ? builder.createString(this.aiId!) : 0);
  const displayName = (this.displayName !== null ? builder.createString(this.displayName!) : 0);
  const profile = (this.profile !== null ? builder.createString(this.profile!) : 0);

  return RoomAISlot.createRoomAISlot(builder,
    aiId,
    displayName,
    this.team,
    this.startPos,
    profile
  );
}
}
