// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Vec3, Vec3T } from '../spring-web/vec3.js';


/**
 * Seismic ping — emitted server-side when a moving unit's seismic
 * signature exceeds the local seismic-listener radius for an ally
 * team. Carries the (already deceived) world position the listener
 * "hears", not the unit's true position. The unit id and unit-team
 * are NOT included on the wire: seismic pings are intentionally
 * anonymous (the whole point is "something is moving over there").
 * `ally_team` is the listener team — server filters per-session so a
 * client only ever receives pings for its own ally team.
 */
export class SeismicPing implements flatbuffers.IUnpackableObject<SeismicPingT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SeismicPing {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSeismicPing(bb:flatbuffers.ByteBuffer, obj?:SeismicPing):SeismicPing {
  return (obj || new SeismicPing()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSeismicPing(bb:flatbuffers.ByteBuffer, obj?:SeismicPing):SeismicPing {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SeismicPing()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

pos(obj?:Vec3):Vec3|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Vec3()).__init(this.bb_pos + offset, this.bb!) : null;
}

strength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

allyTeam():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

static startSeismicPing(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addPos(builder:flatbuffers.Builder, posOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, posOffset, 0);
}

static addStrength(builder:flatbuffers.Builder, strength:number) {
  builder.addFieldFloat32(1, strength, 0.0);
}

static addAllyTeam(builder:flatbuffers.Builder, allyTeam:number) {
  builder.addFieldInt16(2, allyTeam, 0);
}

static endSeismicPing(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSeismicPing(builder:flatbuffers.Builder, posOffset:flatbuffers.Offset, strength:number, allyTeam:number):flatbuffers.Offset {
  SeismicPing.startSeismicPing(builder);
  SeismicPing.addPos(builder, posOffset);
  SeismicPing.addStrength(builder, strength);
  SeismicPing.addAllyTeam(builder, allyTeam);
  return SeismicPing.endSeismicPing(builder);
}

unpack(): SeismicPingT {
  return new SeismicPingT(
    (this.pos() !== null ? this.pos()!.unpack() : null),
    this.strength(),
    this.allyTeam()
  );
}


unpackTo(_o: SeismicPingT): void {
  _o.pos = (this.pos() !== null ? this.pos()!.unpack() : null);
  _o.strength = this.strength();
  _o.allyTeam = this.allyTeam();
}
}

export class SeismicPingT implements flatbuffers.IGeneratedObject {
constructor(
  public pos: Vec3T|null = null,
  public strength: number = 0.0,
  public allyTeam: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return SeismicPing.createSeismicPing(builder,
    (this.pos !== null ? this.pos!.pack(builder) : 0),
    this.strength,
    this.allyTeam
  );
}
}
