// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { StandingOrderConditions, StandingOrderConditionsT } from '../spring-web/standing-order-conditions.js';
import { StandingOrderType } from '../spring-web/standing-order-type.js';


/**
 * Client → Server: create a new standing order owned by the
 * authenticated session's team. Server assigns an `order_id`,
 * broadcasts the resulting StandingOrderState to all sessions whose
 * allied-team view includes the owner team, and begins evaluation on
 * the next standing-order tick.
 */
export class StandingOrderCreate implements flatbuffers.IUnpackableObject<StandingOrderCreateT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StandingOrderCreate {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStandingOrderCreate(bb:flatbuffers.ByteBuffer, obj?:StandingOrderCreate):StandingOrderCreate {
  return (obj || new StandingOrderCreate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStandingOrderCreate(bb:flatbuffers.ByteBuffer, obj?:StandingOrderCreate):StandingOrderCreate {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StandingOrderCreate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

sequence():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

type():StandingOrderType {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : StandingOrderType.DefendArea;
}

/**
 * 0..100. Higher = wins ties when multiple orders compete for the
 * same idle squad. See PLAN-orders.md "Standing Order Assignment
 * Priority" for the full tie-break ladder.
 */
priority():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

params(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

paramsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

paramsArray():Float32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? new Float32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

conditions(obj?:StandingOrderConditions):StandingOrderConditions|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new StandingOrderConditions()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

/**
 * 0 = no expiry. Otherwise the order auto-removes itself this
 * many sim frames after creation.
 */
expiresInFrames():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startStandingOrderCreate(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addSequence(builder:flatbuffers.Builder, sequence:number) {
  builder.addFieldInt32(0, sequence, 0);
}

static addType(builder:flatbuffers.Builder, type:StandingOrderType) {
  builder.addFieldInt8(1, type, StandingOrderType.DefendArea);
}

static addPriority(builder:flatbuffers.Builder, priority:number) {
  builder.addFieldInt8(2, priority, 0);
}

static addParams(builder:flatbuffers.Builder, paramsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, paramsOffset, 0);
}

static createParamsVector(builder:flatbuffers.Builder, data:number[]|Float32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createParamsVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createParamsVector(builder:flatbuffers.Builder, data:number[]|Float32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addFloat32(data[i]!);
  }
  return builder.endVector();
}

static startParamsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addConditions(builder:flatbuffers.Builder, conditionsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, conditionsOffset, 0);
}

static addExpiresInFrames(builder:flatbuffers.Builder, expiresInFrames:number) {
  builder.addFieldInt32(5, expiresInFrames, 0);
}

static endStandingOrderCreate(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


unpack(): StandingOrderCreateT {
  return new StandingOrderCreateT(
    this.sequence(),
    this.type(),
    this.priority(),
    this.bb!.createScalarList<number>(this.params.bind(this), this.paramsLength()),
    (this.conditions() !== null ? this.conditions()!.unpack() : null),
    this.expiresInFrames()
  );
}


unpackTo(_o: StandingOrderCreateT): void {
  _o.sequence = this.sequence();
  _o.type = this.type();
  _o.priority = this.priority();
  _o.params = this.bb!.createScalarList<number>(this.params.bind(this), this.paramsLength());
  _o.conditions = (this.conditions() !== null ? this.conditions()!.unpack() : null);
  _o.expiresInFrames = this.expiresInFrames();
}
}

export class StandingOrderCreateT implements flatbuffers.IGeneratedObject {
constructor(
  public sequence: number = 0,
  public type: StandingOrderType = StandingOrderType.DefendArea,
  public priority: number = 0,
  public params: (number)[] = [],
  public conditions: StandingOrderConditionsT|null = null,
  public expiresInFrames: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const params = StandingOrderCreate.createParamsVector(builder, this.params);
  const conditions = (this.conditions !== null ? this.conditions!.pack(builder) : 0);

  StandingOrderCreate.startStandingOrderCreate(builder);
  StandingOrderCreate.addSequence(builder, this.sequence);
  StandingOrderCreate.addType(builder, this.type);
  StandingOrderCreate.addPriority(builder, this.priority);
  StandingOrderCreate.addParams(builder, params);
  StandingOrderCreate.addConditions(builder, conditions);
  StandingOrderCreate.addExpiresInFrames(builder, this.expiresInFrames);

  return StandingOrderCreate.endStandingOrderCreate(builder);
}
}
