// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Vec3, Vec3T } from '../spring-web/vec3.js';


/**
 * Squad-match conditions. A squad qualifies if it matches every
 * populated field. Zero-radius spatial filters are wildcards (the
 * `*_center` field is then ignored).
 */
export class StandingOrderConditions implements flatbuffers.IUnpackableObject<StandingOrderConditionsT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StandingOrderConditions {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStandingOrderConditions(bb:flatbuffers.ByteBuffer, obj?:StandingOrderConditions):StandingOrderConditions {
  return (obj || new StandingOrderConditions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStandingOrderConditions(bb:flatbuffers.ByteBuffer, obj?:StandingOrderConditions):StandingOrderConditions {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StandingOrderConditions()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

/**
 * Only consider squads with an empty command queue. Default true —
 * directly commanded squads are off-limits for standing orders
 * until they finish their queue.
 */
idleOnly():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : true;
}

/**
 * Allowed unit def IDs. Empty = any.
 */
squadTypes(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint16(this.bb!.__vector(this.bb_pos + offset) + index * 2) : 0;
}

squadTypesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

squadTypesArray():Uint16Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint16Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

/**
 * "Must be inside this circle" filter on the squad's mid-position.
 */
withinRadiusCenter(obj?:Vec3):Vec3|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Vec3()).__init(this.bb_pos + offset, this.bb!) : null;
}

withinRadiusRadius():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * "Must be outside this circle" filter on the squad's mid-position.
 */
outsideRadiusCenter(obj?:Vec3):Vec3|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new Vec3()).__init(this.bb_pos + offset, this.bb!) : null;
}

outsideRadiusRadius():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * Minimum aggregate squad strength (HP × count). 0 = no minimum.
 */
minStrength():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

/**
 * Capability tags the squad must have, e.g. "build", "repair",
 * "scout". Resolution against unit defs is server-side and may be
 * game-specific (Lua callback or unit-def category lookup).
 */
hasCapabilities(index: number):string
hasCapabilities(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
hasCapabilities(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

hasCapabilitiesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

/**
 * Org-group scope (macro-orders §4.2 — the A+C fusion). When non-zero,
 * only squads that are members of this org group qualify; this is the
 * field that draws a group-scoped directive from its own roster rather
 * than the whole idle pool. 0 = any squad (classic condition/area
 * scope). For a GroupDirective the server sets this from `group_id`.
 */
orgGroup():number {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startStandingOrderConditions(builder:flatbuffers.Builder) {
  builder.startObject(9);
}

static addIdleOnly(builder:flatbuffers.Builder, idleOnly:boolean) {
  builder.addFieldInt8(0, +idleOnly, +true);
}

static addSquadTypes(builder:flatbuffers.Builder, squadTypesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, squadTypesOffset, 0);
}

static createSquadTypesVector(builder:flatbuffers.Builder, data:number[]|Uint16Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createSquadTypesVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createSquadTypesVector(builder:flatbuffers.Builder, data:number[]|Uint16Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(2, data.length, 2);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt16(data[i]!);
  }
  return builder.endVector();
}

static startSquadTypesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(2, numElems, 2);
}

static addWithinRadiusCenter(builder:flatbuffers.Builder, withinRadiusCenterOffset:flatbuffers.Offset) {
  builder.addFieldStruct(2, withinRadiusCenterOffset, 0);
}

static addWithinRadiusRadius(builder:flatbuffers.Builder, withinRadiusRadius:number) {
  builder.addFieldFloat32(3, withinRadiusRadius, 0.0);
}

static addOutsideRadiusCenter(builder:flatbuffers.Builder, outsideRadiusCenterOffset:flatbuffers.Offset) {
  builder.addFieldStruct(4, outsideRadiusCenterOffset, 0);
}

static addOutsideRadiusRadius(builder:flatbuffers.Builder, outsideRadiusRadius:number) {
  builder.addFieldFloat32(5, outsideRadiusRadius, 0.0);
}

static addMinStrength(builder:flatbuffers.Builder, minStrength:number) {
  builder.addFieldFloat32(6, minStrength, 0.0);
}

static addHasCapabilities(builder:flatbuffers.Builder, hasCapabilitiesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, hasCapabilitiesOffset, 0);
}

static createHasCapabilitiesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startHasCapabilitiesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addOrgGroup(builder:flatbuffers.Builder, orgGroup:number) {
  builder.addFieldInt32(8, orgGroup, 0);
}

static endStandingOrderConditions(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


unpack(): StandingOrderConditionsT {
  return new StandingOrderConditionsT(
    this.idleOnly(),
    this.bb!.createScalarList<number>(this.squadTypes.bind(this), this.squadTypesLength()),
    (this.withinRadiusCenter() !== null ? this.withinRadiusCenter()!.unpack() : null),
    this.withinRadiusRadius(),
    (this.outsideRadiusCenter() !== null ? this.outsideRadiusCenter()!.unpack() : null),
    this.outsideRadiusRadius(),
    this.minStrength(),
    this.bb!.createScalarList<string>(this.hasCapabilities.bind(this), this.hasCapabilitiesLength()),
    this.orgGroup()
  );
}


unpackTo(_o: StandingOrderConditionsT): void {
  _o.idleOnly = this.idleOnly();
  _o.squadTypes = this.bb!.createScalarList<number>(this.squadTypes.bind(this), this.squadTypesLength());
  _o.withinRadiusCenter = (this.withinRadiusCenter() !== null ? this.withinRadiusCenter()!.unpack() : null);
  _o.withinRadiusRadius = this.withinRadiusRadius();
  _o.outsideRadiusCenter = (this.outsideRadiusCenter() !== null ? this.outsideRadiusCenter()!.unpack() : null);
  _o.outsideRadiusRadius = this.outsideRadiusRadius();
  _o.minStrength = this.minStrength();
  _o.hasCapabilities = this.bb!.createScalarList<string>(this.hasCapabilities.bind(this), this.hasCapabilitiesLength());
  _o.orgGroup = this.orgGroup();
}
}

export class StandingOrderConditionsT implements flatbuffers.IGeneratedObject {
constructor(
  public idleOnly: boolean = true,
  public squadTypes: (number)[] = [],
  public withinRadiusCenter: Vec3T|null = null,
  public withinRadiusRadius: number = 0.0,
  public outsideRadiusCenter: Vec3T|null = null,
  public outsideRadiusRadius: number = 0.0,
  public minStrength: number = 0.0,
  public hasCapabilities: (string)[] = [],
  public orgGroup: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const squadTypes = StandingOrderConditions.createSquadTypesVector(builder, this.squadTypes);
  const hasCapabilities = StandingOrderConditions.createHasCapabilitiesVector(builder, builder.createObjectOffsetList(this.hasCapabilities));

  StandingOrderConditions.startStandingOrderConditions(builder);
  StandingOrderConditions.addIdleOnly(builder, this.idleOnly);
  StandingOrderConditions.addSquadTypes(builder, squadTypes);
  StandingOrderConditions.addWithinRadiusCenter(builder, (this.withinRadiusCenter !== null ? this.withinRadiusCenter!.pack(builder) : 0));
  StandingOrderConditions.addWithinRadiusRadius(builder, this.withinRadiusRadius);
  StandingOrderConditions.addOutsideRadiusCenter(builder, (this.outsideRadiusCenter !== null ? this.outsideRadiusCenter!.pack(builder) : 0));
  StandingOrderConditions.addOutsideRadiusRadius(builder, this.outsideRadiusRadius);
  StandingOrderConditions.addMinStrength(builder, this.minStrength);
  StandingOrderConditions.addHasCapabilities(builder, hasCapabilities);
  StandingOrderConditions.addOrgGroup(builder, this.orgGroup);

  return StandingOrderConditions.endStandingOrderConditions(builder);
}
}
