// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { AllyStartBox, AllyStartBoxT } from '../spring-web/ally-start-box.js';
import { TeamStartPos, TeamStartPosT } from '../spring-web/team-start-pos.js';


/**
 * Team start positions + ally start boxes. Sent reliably to each client
 * on auth (initial values) and re-broadcast once after GameStart (final
 * values, since gadgets like BAR's game_initial_spawn.lua relocate teams
 * via Spring.SetTeamStartPosition during the start sequence). Tiny and
 * infrequent, so it is its own message rather than bloating per-second
 * GameInfo.
 */
export class TeamStartInfo implements flatbuffers.IUnpackableObject<TeamStartInfoT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TeamStartInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTeamStartInfo(bb:flatbuffers.ByteBuffer, obj?:TeamStartInfo):TeamStartInfo {
  return (obj || new TeamStartInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTeamStartInfo(bb:flatbuffers.ByteBuffer, obj?:TeamStartInfo):TeamStartInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TeamStartInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

teams(index: number, obj?:TeamStartPos):TeamStartPos|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new TeamStartPos()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 20, this.bb!) : null;
}

teamsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

boxes(index: number, obj?:AllyStartBox):AllyStartBox|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new AllyStartBox()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 20, this.bb!) : null;
}

boxesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startTeamStartInfo(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addTeams(builder:flatbuffers.Builder, teamsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, teamsOffset, 0);
}

static startTeamsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(20, numElems, 4);
}

static addBoxes(builder:flatbuffers.Builder, boxesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, boxesOffset, 0);
}

static startBoxesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(20, numElems, 4);
}

static endTeamStartInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTeamStartInfo(builder:flatbuffers.Builder, teamsOffset:flatbuffers.Offset, boxesOffset:flatbuffers.Offset):flatbuffers.Offset {
  TeamStartInfo.startTeamStartInfo(builder);
  TeamStartInfo.addTeams(builder, teamsOffset);
  TeamStartInfo.addBoxes(builder, boxesOffset);
  return TeamStartInfo.endTeamStartInfo(builder);
}

unpack(): TeamStartInfoT {
  return new TeamStartInfoT(
    this.bb!.createObjList<TeamStartPos, TeamStartPosT>(this.teams.bind(this), this.teamsLength()),
    this.bb!.createObjList<AllyStartBox, AllyStartBoxT>(this.boxes.bind(this), this.boxesLength())
  );
}


unpackTo(_o: TeamStartInfoT): void {
  _o.teams = this.bb!.createObjList<TeamStartPos, TeamStartPosT>(this.teams.bind(this), this.teamsLength());
  _o.boxes = this.bb!.createObjList<AllyStartBox, AllyStartBoxT>(this.boxes.bind(this), this.boxesLength());
}
}

export class TeamStartInfoT implements flatbuffers.IGeneratedObject {
constructor(
  public teams: (TeamStartPosT)[] = [],
  public boxes: (AllyStartBoxT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const teams = builder.createStructOffsetList(this.teams, TeamStartInfo.startTeamsVector);
  const boxes = builder.createStructOffsetList(this.boxes, TeamStartInfo.startBoxesVector);

  return TeamStartInfo.createTeamStartInfo(builder,
    teams,
    boxes
  );
}
}
