// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { TeamStatsEntry, TeamStatsEntryT } from '../spring-web/team-stats-entry.js';


/**
 * Incremental stats-history update for one team. `base_index` is the 0-based
 * position of `entries[0]` within the team's full `statHistory`; the client
 * overwrites slots `[base_index ..]` so the previously-live tail (re-sent once
 * it finalises) is replaced and the new live tail appended. In the steady
 * state `entries` is just the single live tail (its resource/damage totals
 * accumulate every frame); when a 15s boundary finalises an entry the next
 * update carries both the now-final entry and the new tail.
 */
export class TeamStatsHistoryItem implements flatbuffers.IUnpackableObject<TeamStatsHistoryItemT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TeamStatsHistoryItem {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTeamStatsHistoryItem(bb:flatbuffers.ByteBuffer, obj?:TeamStatsHistoryItem):TeamStatsHistoryItem {
  return (obj || new TeamStatsHistoryItem()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTeamStatsHistoryItem(bb:flatbuffers.ByteBuffer, obj?:TeamStatsHistoryItem):TeamStatsHistoryItem {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TeamStatsHistoryItem()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

teamId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

baseIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

entries(index: number, obj?:TeamStatsEntry):TeamStatsEntry|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new TeamStatsEntry()).__init(this.bb!.__vector(this.bb_pos + offset) + index * 80, this.bb!) : null;
}

entriesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startTeamStatsHistoryItem(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addTeamId(builder:flatbuffers.Builder, teamId:number) {
  builder.addFieldInt32(0, teamId, 0);
}

static addBaseIndex(builder:flatbuffers.Builder, baseIndex:number) {
  builder.addFieldInt32(1, baseIndex, 0);
}

static addEntries(builder:flatbuffers.Builder, entriesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, entriesOffset, 0);
}

static startEntriesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(80, numElems, 4);
}

static endTeamStatsHistoryItem(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createTeamStatsHistoryItem(builder:flatbuffers.Builder, teamId:number, baseIndex:number, entriesOffset:flatbuffers.Offset):flatbuffers.Offset {
  TeamStatsHistoryItem.startTeamStatsHistoryItem(builder);
  TeamStatsHistoryItem.addTeamId(builder, teamId);
  TeamStatsHistoryItem.addBaseIndex(builder, baseIndex);
  TeamStatsHistoryItem.addEntries(builder, entriesOffset);
  return TeamStatsHistoryItem.endTeamStatsHistoryItem(builder);
}

unpack(): TeamStatsHistoryItemT {
  return new TeamStatsHistoryItemT(
    this.teamId(),
    this.baseIndex(),
    this.bb!.createObjList<TeamStatsEntry, TeamStatsEntryT>(this.entries.bind(this), this.entriesLength())
  );
}


unpackTo(_o: TeamStatsHistoryItemT): void {
  _o.teamId = this.teamId();
  _o.baseIndex = this.baseIndex();
  _o.entries = this.bb!.createObjList<TeamStatsEntry, TeamStatsEntryT>(this.entries.bind(this), this.entriesLength());
}
}

export class TeamStatsHistoryItemT implements flatbuffers.IGeneratedObject {
constructor(
  public teamId: number = 0,
  public baseIndex: number = 0,
  public entries: (TeamStatsEntryT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const entries = builder.createStructOffsetList(this.entries, TeamStatsHistoryItem.startEntriesVector);

  return TeamStatsHistoryItem.createTeamStatsHistoryItem(builder,
    this.teamId,
    this.baseIndex,
    entries
  );
}
}
