// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * One team's start position, in RH-canonical elmos (the same convention
 * as entity-state positions — the engine's `FlipPosZ` is a no-op). `valid`
 * mirrors `CTeam::HasValidStartPos()`. Lets the in-game LuaUI worker answer
 * `Spring.GetTeamStartPosition` (16× BAR widget callers, plus ZK).
 */
export class TeamStartPos implements flatbuffers.IUnpackableObject<TeamStartPosT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TeamStartPos {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

team():number {
  return this.bb!.readInt16(this.bb_pos);
}

allyTeam():number {
  return this.bb!.readInt16(this.bb_pos + 2);
}

x():number {
  return this.bb!.readFloat32(this.bb_pos + 4);
}

y():number {
  return this.bb!.readFloat32(this.bb_pos + 8);
}

z():number {
  return this.bb!.readFloat32(this.bb_pos + 12);
}

valid():boolean {
  return !!this.bb!.readInt8(this.bb_pos + 16);
}

static sizeOf():number {
  return 20;
}

static createTeamStartPos(builder:flatbuffers.Builder, team: number, ally_team: number, x: number, y: number, z: number, valid: boolean):flatbuffers.Offset {
  builder.prep(4, 20);
  builder.pad(3);
  builder.writeInt8(Number(Boolean(valid)));
  builder.writeFloat32(z);
  builder.writeFloat32(y);
  builder.writeFloat32(x);
  builder.writeInt16(ally_team);
  builder.writeInt16(team);
  return builder.offset();
}


unpack(): TeamStartPosT {
  return new TeamStartPosT(
    this.team(),
    this.allyTeam(),
    this.x(),
    this.y(),
    this.z(),
    this.valid()
  );
}


unpackTo(_o: TeamStartPosT): void {
  _o.team = this.team();
  _o.allyTeam = this.allyTeam();
  _o.x = this.x();
  _o.y = this.y();
  _o.z = this.z();
  _o.valid = this.valid();
}
}

export class TeamStartPosT implements flatbuffers.IGeneratedObject {
constructor(
  public team: number = 0,
  public allyTeam: number = 0,
  public x: number = 0.0,
  public y: number = 0.0,
  public z: number = 0.0,
  public valid: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return TeamStartPos.createTeamStartPos(builder,
    this.team,
    this.allyTeam,
    this.x,
    this.y,
    this.z,
    this.valid
  );
}
}
