// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



/**
 * One unit's armored toggle state. Spring tracks two fields per
 * unit: a bool `armoredState` (currently armored?) and a float
 * `armoredMultiple` (damage multiplier while armored, typically 0.5).
 * Emitted only for units whose armoredState is true OR whose
 * armoredMultiple differs from 1.0 — units in the default
 * non-armored state with multiplier 1.0 are omitted entirely.
 */
export class UnitArmoredInfo implements flatbuffers.IUnpackableObject<UnitArmoredInfoT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UnitArmoredInfo {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUnitArmoredInfo(bb:flatbuffers.ByteBuffer, obj?:UnitArmoredInfo):UnitArmoredInfo {
  return (obj || new UnitArmoredInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUnitArmoredInfo(bb:flatbuffers.ByteBuffer, obj?:UnitArmoredInfo):UnitArmoredInfo {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UnitArmoredInfo()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

unitId():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

armored():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

armoredMultiple():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startUnitArmoredInfo(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addUnitId(builder:flatbuffers.Builder, unitId:number) {
  builder.addFieldInt32(0, unitId, 0);
}

static addArmored(builder:flatbuffers.Builder, armored:boolean) {
  builder.addFieldInt8(1, +armored, +false);
}

static addArmoredMultiple(builder:flatbuffers.Builder, armoredMultiple:number) {
  builder.addFieldFloat32(2, armoredMultiple, 0.0);
}

static endUnitArmoredInfo(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUnitArmoredInfo(builder:flatbuffers.Builder, unitId:number, armored:boolean, armoredMultiple:number):flatbuffers.Offset {
  UnitArmoredInfo.startUnitArmoredInfo(builder);
  UnitArmoredInfo.addUnitId(builder, unitId);
  UnitArmoredInfo.addArmored(builder, armored);
  UnitArmoredInfo.addArmoredMultiple(builder, armoredMultiple);
  return UnitArmoredInfo.endUnitArmoredInfo(builder);
}

unpack(): UnitArmoredInfoT {
  return new UnitArmoredInfoT(
    this.unitId(),
    this.armored(),
    this.armoredMultiple()
  );
}


unpackTo(_o: UnitArmoredInfoT): void {
  _o.unitId = this.unitId();
  _o.armored = this.armored();
  _o.armoredMultiple = this.armoredMultiple();
}
}

export class UnitArmoredInfoT implements flatbuffers.IGeneratedObject {
constructor(
  public unitId: number = 0,
  public armored: boolean = false,
  public armoredMultiple: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return UnitArmoredInfo.createUnitArmoredInfo(builder,
    this.unitId,
    this.armored,
    this.armoredMultiple
  );
}
}
