// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { UnitStockpileInfo, UnitStockpileInfoT } from '../spring-web/unit-stockpile-info.js';


/**
 * Per-session broadcast: every visible unit with active stockpile
 * state. Snapshot semantics. Sent every ~1 Hz.
 */
export class UnitStockpileUpdate implements flatbuffers.IUnpackableObject<UnitStockpileUpdateT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UnitStockpileUpdate {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUnitStockpileUpdate(bb:flatbuffers.ByteBuffer, obj?:UnitStockpileUpdate):UnitStockpileUpdate {
  return (obj || new UnitStockpileUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUnitStockpileUpdate(bb:flatbuffers.ByteBuffer, obj?:UnitStockpileUpdate):UnitStockpileUpdate {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UnitStockpileUpdate()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

units(index: number, obj?:UnitStockpileInfo):UnitStockpileInfo|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new UnitStockpileInfo()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

unitsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startUnitStockpileUpdate(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addUnits(builder:flatbuffers.Builder, unitsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, unitsOffset, 0);
}

static createUnitsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startUnitsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endUnitStockpileUpdate(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUnitStockpileUpdate(builder:flatbuffers.Builder, unitsOffset:flatbuffers.Offset):flatbuffers.Offset {
  UnitStockpileUpdate.startUnitStockpileUpdate(builder);
  UnitStockpileUpdate.addUnits(builder, unitsOffset);
  return UnitStockpileUpdate.endUnitStockpileUpdate(builder);
}

unpack(): UnitStockpileUpdateT {
  return new UnitStockpileUpdateT(
    this.bb!.createObjList<UnitStockpileInfo, UnitStockpileInfoT>(this.units.bind(this), this.unitsLength())
  );
}


unpackTo(_o: UnitStockpileUpdateT): void {
  _o.units = this.bb!.createObjList<UnitStockpileInfo, UnitStockpileInfoT>(this.units.bind(this), this.unitsLength());
}
}

export class UnitStockpileUpdateT implements flatbuffers.IGeneratedObject {
constructor(
  public units: (UnitStockpileInfoT)[] = []
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const units = UnitStockpileUpdate.createUnitsVector(builder, builder.createObjectOffsetList(this.units));

  return UnitStockpileUpdate.createUnitStockpileUpdate(builder,
    units
  );
}
}
