// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

/**
 * Classifies a UnitLifecycleEvent. Matches `UnitLifecycleKind` in
 * `Server/UnitLifecycleCollector.h`. These are events that widgets
 * need to learn about but can't be derived from the per-tick entity
 * stream — UnitFromFactory needs the factory id, and Taken/Given
 * need the transfer cause (the entity stream just shows the new team).
 */
export enum UnitLifecycleKind {
  FromFactory = 0,
  Taken = 1,
  Given = 2,

  /**
   * Spring's synced `UnitCreated(unit, builder)`. Fires the moment
   * construction starts (before nano-spray). For own + allied teams
   * only — enemy UnitCreated is synthesised client-side from
   * first-visibility in the entity stream.
   */
  Created = 3
}
