#!/usr/bin/env python3
"""build.py — render tools/audiogen/manifest.json into
data/games/metalstorm/sounds/**.

Order of operations matters: `write_assets_md` runs BEFORE any audio file
is rendered, so a manifest row exists in ASSETS.md before the file it
describes ever lands in the tree (the project-wide asset rule).

Usage:
    python3 tools/audiogen/build.py [--offline] [--only CATEGORY]
        [--dry-run] [--assets-only] [--audioconverter PATH]

--offline: process only source=="synthesis" entries (skip url/local-file
    sourced entries). Every entry today is synthesis, so this is currently
    a no-op — it exists for when a Sonniss/freesound-sourced entry lands.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import recipes  # noqa: E402
from synth import Layer, apply_radio_filter, derive_far, ebur128_report, render_layers  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[2]
GAME_ROOT = REPO_ROOT / "data" / "games" / "metalstorm"
MANIFEST_PATH = Path(__file__).parent / "manifest.json"
ASSETS_MD = GAME_ROOT / "ASSETS.md"

CATEGORY_TO_CONVERTER_ARG = {
    "music": "music",
    "ui": "ui",
}


def load_manifest() -> dict:
    return json.loads(MANIFEST_PATH.read_text())


def find_audioconverter(override: str | None) -> Path:
    if override:
        return Path(override)
    for variant in ("release", "prod", "debug"):
        p = REPO_ROOT / "build" / variant / "tools" / "audioconverter" / "audioconverter"
        if p.exists():
            return p
    raise SystemExit("audioconverter binary not found under build/{release,prod,debug} "
                      "— build it or pass --audioconverter PATH")


def expand_entries(manifest: dict) -> list[dict]:
    """Manifest entries plus their derived `_far` pair (close/far switched
    at ~900 elmos in sounds.lua). Far entries are synthesized here, not
    hand-authored, so recipe authoring only happens once per key."""
    out = []
    for e in manifest["entries"]:
        out.append({**e, "is_far": False})
        if e.get("far"):
            far = dict(e)
            far["key"] = e["key"] + "_far"
            far["output"] = e["output"].rsplit(".", 1)[0] + "_far.webm"
            far["notes"] = f"derived far variant of {e['key']} (low-pass + attenuated, longer tail)"
            far["is_far"] = True
            out.append(far)
    return out


def render_entry(entry: dict, audioconverter: Path, dry_run: bool) -> Path | None:
    if entry["source"] != "synthesis":
        return None
    recipe_fn = getattr(recipes, entry["recipe"])
    layers, duration, post = recipe_fn(**entry.get("recipe_args", {}))
    if entry["is_far"]:
        layers = derive_far(layers)
        duration = duration * 1.15
    out_path = GAME_ROOT / entry["output"]
    if dry_run:
        print(f"[dry-run] would render {out_path} ({len(layers)} layers, {duration:.2f}s)")
        return out_path

    channels = 2 if entry["category"] == "music" else 1
    with tempfile.TemporaryDirectory() as td:
        wav = Path(td) / "raw.wav"
        render_layers(layers, duration, wav,
                       post_hp=post.get("post_hp"), post_lp=post.get("post_lp"),
                       post_gain_db=post.get("post_gain_db", 0.0), channels=channels)
        final_wav = wav
        if entry.get("radio_filter"):
            filtered = Path(td) / "radio.wav"
            apply_radio_filter(wav, filtered)
            final_wav = filtered
        cat_arg = CATEGORY_TO_CONVERTER_ARG.get(entry["category"], "sfx")
        out_path.parent.mkdir(parents=True, exist_ok=True)
        cmd = [str(audioconverter), "--category", cat_arg, "--force",
               str(final_wav), str(out_path)]
        subprocess.run(cmd, check=True)
    return out_path


def assets_md_audio_rows(entries: list[dict], reserved: list[dict]) -> str:
    lines = [
        "## Audio",
        "",
        "Generated by `tools/audiogen/build.py` from `tools/audiogen/manifest.json` "
        "— see `tools/audiogen/README.md`. All synthesis entries are self-authored "
        "(no external source material), so `License` is `Original (...)` per the "
        "allowed classes above. The `Sonniss GDC 2021-2023 — <pack> — royalty-free, "
        "no attribution` rows below are RESERVED: the bundle at "
        "`/Users/shannon/WarriorHut/Projects/assets/audio/sonniss/GDC2021-2023/` was "
        "not present on disk as of 2026-09-17, so no file exists yet for them — fill "
        "in the real Asset path once a pack is trimmed in.",
        "",
        "| Asset (path in tree) | Target def(s) | Origin (URL) | Author | License | Modifications |",
        "|---|---|---|---|---|---|",
    ]
    for e in entries:
        if e["source"] != "synthesis":
            continue
        asset = e["output"]
        origin = "n/a — generated in-session (tools/audiogen synthesis, no external source)"
        author = "tools/audiogen (procedural)"
        license_str = "Original (Metalstorm project, tools/audiogen layered synthesis)"
        mods = e["notes"].replace("|", "\\|")
        lines.append(f"| {asset} | {e['key']} | {origin} | {author} | {license_str} | {mods} |")
    for r in reserved:
        pack = r["pack"].replace("|", "\\|")
        use = r["use"].replace("|", "\\|")
        lines.append(
            f"| _reserved — {pack}_ | (planned: {use}) | "
            "Sonniss GDC 2021-2023 bundle (human download required) | "
            "Sonniss GDC contributors | "
            f"Sonniss GDC 2021-2023 — {pack} — royalty-free, no attribution | "
            "RESERVED — bundle not yet downloaded as of 2026-09-17 |"
        )
    lines.append("")
    return "\n".join(lines)


def write_assets_md(entries: list[dict], reserved: list[dict], dry_run: bool) -> None:
    text = ASSETS_MD.read_text()
    marker = "\n## Audio\n"
    if marker in text:
        head = text.split(marker, 1)[0].rstrip("\n") + "\n\n"
    else:
        head = text.rstrip("\n") + "\n\n"
    new_text = head + assets_md_audio_rows(entries, reserved) + "\n"
    if dry_run:
        print(f"[dry-run] would write {ASSETS_MD} ({len(new_text)} bytes)")
        return
    ASSETS_MD.write_text(new_text)


def write_loudness_report(rendered: list[tuple[dict, Path]], dry_run: bool) -> None:
    out_path = REPO_ROOT / "docs" / "reviews" / "beta" / "audio-loudness.md"
    if dry_run:
        print(f"[dry-run] would write {out_path}")
        return
    by_category: dict[str, list[tuple[dict, dict]]] = {}
    for entry, path in rendered:
        report = ebur128_report(path)
        by_category.setdefault(entry["category"], []).append((entry, report))

    lines = [
        "# Audio loudness report (offline, ffmpeg ebur128)",
        "",
        "Generated by `tools/audiogen/build.py --loudness-report` against the "
        "rendered `.webm` files under `data/games/metalstorm/sounds/**`. Integrated "
        "loudness (I, LUFS) and true peak (dBTP) per `ffmpeg -af ebur128=peak=true`. "
        "No live stack needed — this is a static per-file measurement, not an "
        "in-game listen check (that's L-VERIFY's `client_eval` audio tap).",
        "",
        "**`-70.0 LUFS` entries are an EBU R128 gating artifact, not silence** — "
        "the integrated-loudness gate needs a sustained block above threshold to "
        "report a real number, which very short one-shot clips (UI blips, small "
        "impacts) don't provide. True peak stays meaningful for those rows; "
        "cross-check against `sounds.lua`'s per-key `gain` for actual in-game level.",
        "",
    ]
    for cat in sorted(by_category):
        rows = by_category[cat]
        lines.append(f"## {cat}")
        lines.append("")
        lines.append("| Key | Integrated LUFS | True peak dBTP |")
        lines.append("|---|---|---|")
        for entry, report in sorted(rows, key=lambda r: r[0]["key"]):
            lufs = report.get("integrated_lufs")
            tp = report.get("true_peak_dbtp")
            lines.append(f"| {entry['key']} | {lufs if lufs is not None else 'n/a'} | "
                         f"{tp if tp is not None else 'n/a'} |")
        lines.append("")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n")
    print(f"wrote {out_path}")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--offline", action="store_true")
    ap.add_argument("--only", help="category filter (weapon/impact/explosion/death/ambience/ui/music/reverb)")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--assets-only", action="store_true", help="only (re)write ASSETS.md, render nothing")
    ap.add_argument("--loudness-report", action="store_true", help="render + write docs/reviews/beta/audio-loudness.md")
    ap.add_argument("--audioconverter", default=None)
    args = ap.parse_args()

    manifest = load_manifest()
    all_entries = expand_entries(manifest)
    entries = all_entries
    if args.offline:
        entries = [e for e in entries if e["source"] == "synthesis"]
    if args.only:
        entries = [e for e in entries if e["category"] == args.only]

    # ASSETS.md always covers every entry (close + derived _far), regardless
    # of --only/--offline filtering what actually gets rendered this run —
    # a filtered run must never make the manifest look incomplete.
    write_assets_md(all_entries, manifest["reserved_sonniss"], args.dry_run)
    if args.assets_only:
        return 0

    audioconverter = find_audioconverter(args.audioconverter)
    rendered: list[tuple[dict, Path]] = []
    for entry in entries:
        path = render_entry(entry, audioconverter, args.dry_run)
        if path and not args.dry_run:
            rendered.append((entry, path))
            print(f"rendered {path}")

    if args.loudness_report and not args.dry_run:
        write_loudness_report(rendered, args.dry_run)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
