/**
 * GENERATED by scripts/regen-protocol.sh — do not edit, and do not hand-bump.
 *
 * sha256 of the binary schema (`flatc -b --schema schemas/protocol.fbs`),
 * sent in the Handshake and compared for equality by the game server. See
 * rts/Server/ProtocolSchemaHash.h for the other half.
 */
export const SCHEMA_HASH = '4215f010766e1975a21b1a956990762aa34e943597c28e86bcb13b5b4d3d7eba';
