/**
 * GENERATED by scripts/regen-protocol.sh — do not edit, and do not hand-bump.
 *
 * sha256 of the binary schema (`flatc -b --schema schemas/protocol.fbs`),
 * sent in the Handshake and compared for equality by the game server. See
 * rts/Server/ProtocolSchemaHash.h for the other half.
 */
export const SCHEMA_HASH = '2d9f91ac736f2edc6f0a90430eecee1a135abf0cc3819af3d99cbb4fd37b27da';
