#include <doctest/doctest.h>

#include "Server/ScenarioDb.h"
#include "Server/ScenarioDiscovery.h"

#include <sqlite3.h>

#include <filesystem>
#include <fstream>
#include <sstream>
#include <string>

// Procedurally generated scenarios (tools/mapgen/scenariogen.py) stored in
// SQLite and materialised into `<game>/scenarios/gen_<id>.lua`.
//
// THE CONSTRAINT THESE TESTS EXIST TO PIN. Two consumers can only read the
// filesystem: `ScenarioDiscovery::Discover` (which builds the lobby's Create
// Game picker) and the sim, which loads a scenario by filename via
// `VFS.Include('scenarios/' .. name .. '.lua')`. So a scenario that is only a
// DB row is invisible AND unloadable. The row is the record of truth and the
// file is a cache rebuilt from it — which is only true if rebuilding actually
// reproduces the file, hence the byte-identical round-trip case below.
//
// The load-bearing behavioural case is `terminal`: a generated scenario with
// no `victory = true` objective must report `terminal == false` and must
// therefore never be returned by `DefaultForMap`. That rule is what stops the
// lobby auto-creating a war that can never end.

namespace fs = std::filesystem;
namespace SD = ScenarioDiscovery;

namespace {

/// An in-memory DB with the table created, plus a scratch game directory.
struct Fixture {
    sqlite3* db = nullptr;
    fs::path game;

    explicit Fixture(const std::string& tag) {
        REQUIRE(sqlite3_open(":memory:", &db) == SQLITE_OK);
        ScenarioDb::EnsureTable(db);
        game = fs::temp_directory_path() / ("scndb_" + tag);
        fs::remove_all(game);
        fs::create_directories(game / "scenarios");
    }
    ~Fixture() {
        sqlite3_close(db);
        std::error_code ec;
        fs::remove_all(game, ec);
    }

    std::string Path() const { return game.string(); }

    /// Drop an authored (non-generated) scenario into the same directory, so
    /// every test runs against a directory that mixes shipped and generated
    /// content — which is the real situation.
    void WriteShipped(const std::string& name, const std::string& body) const {
        std::ofstream f(game / "scenarios" / name);
        f << body;
    }

    std::string ReadFile(const std::string& rel) const {
        std::ifstream f(game / "scenarios" / rel, std::ios::binary);
        std::ostringstream ss;
        ss << f.rdbuf();
        return ss.str();
    }
};

bool HasColumn(sqlite3* db, const std::string& table, const std::string& column) {
    sqlite3_stmt* stmt = nullptr;
    const std::string sql = "SELECT " + column + " FROM " + table + " LIMIT 1";
    const int rc = sqlite3_prepare_v2(db, sql.c_str(), -1, &stmt, nullptr);
    sqlite3_finalize(stmt);
    return rc == SQLITE_OK;
}

int64_t CountRows(sqlite3* db) {
    sqlite3_stmt* stmt = nullptr;
    REQUIRE(sqlite3_prepare_v2(db, "SELECT COUNT(*) FROM generated_scenarios",
                               -1, &stmt, nullptr) == SQLITE_OK);
    REQUIRE(sqlite3_step(stmt) == SQLITE_ROW);
    const int64_t n = sqlite3_column_int64(stmt, 0);
    sqlite3_finalize(stmt);
    return n;
}

/// A minimal but structurally real generated scenario: the shape
/// scenariogen.py emits, trimmed to the fields ScenarioDiscovery reads.
std::string GeneratedLua(const std::string& name, const std::string& map,
                         bool victory) {
    std::string s =
        "-- GENERATED by tools/mapgen/scenariogen.py\n"
        "return {\n"
        "    version = 1,\n"
        "    name    = '" + name + "',\n"
        "    world   = { map = '" + map + "' },\n"
        "    sides = {\n"
        "        { faction = 'compact', team = 0 },\n"
        "        { faction = 'union',   team = 1 },\n"
        "        { faction = 'reavers', team = 2 },\n"
        "    },\n"
        "    units = {\n"
        "        { def = 'ms_rifle', team = 0, x = 100, z = 100 },\n"
        "        { def = 'ms_rifle', team = 1, x = 900, z = 900 },\n"
        "    },\n"
        "    ai = { { team = 2, profile = 'npc_raider' } },\n"
        "    objectives = {\n"
        "        { type = 'control', region = 'north' },\n";
    if (victory)
        s += "        { type = 'control', region = 'ridge', victory = true },\n";
    s += "    },\n}\n";
    return s;
}

ScenarioDb::Record MakeRecord(const std::string& id, const std::string& map,
                              bool victory,
                              const std::string& name = "Generated War") {
    ScenarioDb::Record r;
    r.id = id;
    r.gameId = "metalstorm";
    r.displayName = name;
    r.mapId = map;
    r.seed = 7;
    r.generatorVersion = 2;
    r.params = R"({"roster":"standard","sides":2})";
    r.lua = GeneratedLua(name, map, victory);
    r.createdBy = "admin";
    return r;
}

} // namespace

// ==========================================================================
// Schema
// ==========================================================================

TEST_CASE("ScenarioDb.EnsureTable creates generated_scenarios fresh") {
    Fixture f("ensure_fresh");
    CHECK(HasColumn(f.db, "generated_scenarios", "id"));
    CHECK(HasColumn(f.db, "generated_scenarios", "game_id"));
    CHECK(HasColumn(f.db, "generated_scenarios", "display_name"));
    CHECK(HasColumn(f.db, "generated_scenarios", "map_id"));
    CHECK(HasColumn(f.db, "generated_scenarios", "seed"));
    CHECK(HasColumn(f.db, "generated_scenarios", "generator_version"));
    CHECK(HasColumn(f.db, "generated_scenarios", "params"));
    CHECK(HasColumn(f.db, "generated_scenarios", "lua"));
    CHECK(HasColumn(f.db, "generated_scenarios", "created_by"));
    CHECK(HasColumn(f.db, "generated_scenarios", "created_at"));
}

TEST_CASE("ScenarioDb.EnsureTable MIGRATES a stale schema, never drops it") {
    sqlite3* db = nullptr;
    REQUIRE(sqlite3_open(":memory:", &db) == SQLITE_OK);

    // A table from before `created_by` existed, with a scenario already in it.
    // Unlike `maps` or `game_servers`, this row is the ONLY copy of the thing
    // — a DROP+CREATE migration would destroy a war that rooms may already
    // point at, so the `users` ALTER TABLE pattern is required here.
    REQUIRE(sqlite3_exec(db,
        "CREATE TABLE generated_scenarios ("
        "  id TEXT PRIMARY KEY,"
        "  game_id TEXT NOT NULL DEFAULT '',"
        "  display_name TEXT NOT NULL DEFAULT '',"
        "  map_id TEXT NOT NULL DEFAULT '',"
        "  seed INTEGER NOT NULL DEFAULT 0,"
        "  generator_version INTEGER NOT NULL DEFAULT 0,"
        "  params TEXT NOT NULL DEFAULT '',"
        "  lua TEXT NOT NULL DEFAULT '',"
        "  created_at DATETIME DEFAULT CURRENT_TIMESTAMP"
        ")", nullptr, nullptr, nullptr) == SQLITE_OK);
    REQUIRE(sqlite3_exec(db,
        "INSERT INTO generated_scenarios (id, game_id, map_id, lua) "
        "VALUES ('gen_old_map_abcd', 'metalstorm', 'old_map', 'return {}')",
        nullptr, nullptr, nullptr) == SQLITE_OK);
    REQUIRE_FALSE(HasColumn(db, "generated_scenarios", "created_by"));

    ScenarioDb::EnsureTable(db);

    CHECK(HasColumn(db, "generated_scenarios", "created_by"));
    // The pre-existing scenario survived the migration.
    CHECK(CountRows(db) == 1);
    auto kept = ScenarioDb::FindById(db, "gen_old_map_abcd");
    REQUIRE(kept.has_value());
    CHECK(kept->mapId == "old_map");

    sqlite3_close(db);
}

TEST_CASE("ScenarioDb.EnsureTable is idempotent and preserves rows") {
    Fixture f("ensure_idem");
    REQUIRE(ScenarioDb::Upsert(f.db, MakeRecord("gen_basin_aaaa", "basin", true)));
    ScenarioDb::EnsureTable(f.db);
    ScenarioDb::EnsureTable(f.db);
    CHECK(CountRows(f.db) == 1);
}

// ==========================================================================
// Accessor
// ==========================================================================

TEST_CASE("ScenarioDb: store and read back every field") {
    Fixture f("roundtrip");
    const ScenarioDb::Record in = MakeRecord("gen_basin_aaaa", "basin", true,
                                             "Ashen Reach — Standard War");
    REQUIRE(ScenarioDb::Upsert(f.db, in));

    auto out = ScenarioDb::FindById(f.db, "gen_basin_aaaa");
    REQUIRE(out.has_value());
    CHECK(out->id == in.id);
    CHECK(out->gameId == in.gameId);
    CHECK(out->displayName == in.displayName);
    CHECK(out->mapId == in.mapId);
    CHECK(out->seed == in.seed);
    CHECK(out->generatorVersion == in.generatorVersion);
    CHECK(out->params == in.params);
    CHECK(out->lua == in.lua);
    CHECK(out->createdBy == in.createdBy);
    CHECK_FALSE(out->createdAt.empty());
}

TEST_CASE("ScenarioDb: re-generating the same id is an idempotent upsert") {
    // An id encodes (map, seed, generator version) and generation is
    // deterministic, so a repeat id means "you generated the same scenario
    // twice", not a conflict. One row, latest content, original created_at.
    Fixture f("upsert");
    ScenarioDb::Record r = MakeRecord("gen_basin_aaaa", "basin", true);
    REQUIRE(ScenarioDb::Upsert(f.db, r));
    const std::string firstCreatedAt =
        ScenarioDb::FindById(f.db, r.id)->createdAt;

    r.displayName = "Renamed";
    r.lua = GeneratedLua("Renamed", "basin", true);
    REQUIRE(ScenarioDb::Upsert(f.db, r));

    CHECK(CountRows(f.db) == 1);
    auto out = ScenarioDb::FindById(f.db, r.id);
    REQUIRE(out.has_value());
    CHECK(out->displayName == "Renamed");
    // created_at is COALESCEd from the existing row: a re-run must not make a
    // months-old scenario look freshly minted.
    CHECK(out->createdAt == firstCreatedAt);
}

TEST_CASE("ScenarioDb: ListForGame filters by game and sorts by id") {
    Fixture f("list");
    REQUIRE(ScenarioDb::Upsert(f.db, MakeRecord("gen_basin_zzzz", "basin", true)));
    REQUIRE(ScenarioDb::Upsert(f.db, MakeRecord("gen_basin_aaaa", "basin", true)));
    ScenarioDb::Record other = MakeRecord("gen_other_bbbb", "other", true);
    other.gameId = "zk";
    REQUIRE(ScenarioDb::Upsert(f.db, other));

    const auto ms = ScenarioDb::ListForGame(f.db, "metalstorm");
    REQUIRE(ms.size() == 2);
    // Sorted by id, matching ScenarioDiscovery::Discover's ordering so the
    // picker is stable across restarts.
    CHECK(ms[0].id == "gen_basin_aaaa");
    CHECK(ms[1].id == "gen_basin_zzzz");
    CHECK(ScenarioDb::ListAll(f.db).size() == 3);
    CHECK(ScenarioDb::ListForGame(f.db, "nosuchgame").empty());
}

TEST_CASE("ScenarioDb.Delete reports whether a row was actually removed") {
    Fixture f("delete");
    REQUIRE(ScenarioDb::Upsert(f.db, MakeRecord("gen_basin_aaaa", "basin", true)));
    CHECK(ScenarioDb::Delete(f.db, "gen_basin_aaaa"));
    // False, not true: the endpoint answers 404 for "was not there", so a
    // DELETE that matched nothing must be distinguishable from one that did.
    CHECK_FALSE(ScenarioDb::Delete(f.db, "gen_basin_aaaa"));
    CHECK(CountRows(f.db) == 0);
}

TEST_CASE("ScenarioDb.ValidateId rejects anything unsafe as a filename") {
    CHECK(ScenarioDb::ValidateId("gen_basin_9jye"));

    // Not ours — must never overwrite an authored scenario.
    CHECK_FALSE(ScenarioDb::ValidateId("meridian_basin"));
    CHECK_FALSE(ScenarioDb::ValidateId("tutorial_01"));
    CHECK_FALSE(ScenarioDb::ValidateId(""));
    CHECK_FALSE(ScenarioDb::ValidateId("gen_"));

    // Path traversal, in every form that reaches a filename or a VFS include.
    CHECK_FALSE(ScenarioDb::ValidateId("gen_../../etc/passwd"));
    CHECK_FALSE(ScenarioDb::ValidateId("gen_a/b"));
    CHECK_FALSE(ScenarioDb::ValidateId("gen_a\\b"));
    CHECK_FALSE(ScenarioDb::ValidateId("gen_a.b"));

    // Outside the [a-z0-9_] set scenario_id() emits.
    CHECK_FALSE(ScenarioDb::ValidateId("gen_Basin"));
    CHECK_FALSE(ScenarioDb::ValidateId("gen_basin-1"));
    CHECK_FALSE(ScenarioDb::ValidateId("gen_basin 1"));
    CHECK_FALSE(ScenarioDb::ValidateId("gen_" + std::string(200, 'a')));
}

TEST_CASE("ScenarioDb: an unsafe id cannot be stored or materialised") {
    Fixture f("unsafe");
    ScenarioDb::Record bad = MakeRecord("../../evil", "basin", true);
    CHECK_FALSE(ScenarioDb::Upsert(f.db, bad));
    CHECK_FALSE(ScenarioDb::Materialise(bad, f.Path()));
    CHECK(ScenarioDb::PathFor(f.Path(), bad.id).empty());
    CHECK(CountRows(f.db) == 0);
}

TEST_CASE("ScenarioDb.DisambiguateDisplayName only renames real collisions") {
    // The generator picks its title suffix as SCENARIO_SUFFIXES[seed % len],
    // so two seeds on one map can mint the same name; the picker is a flat
    // option list with nothing else to tell them apart.
    Fixture f("names");
    REQUIRE(ScenarioDb::Upsert(
        f.db, MakeRecord("gen_basin_aaaa", "basin", true, "Ashen Reach — War")));

    CHECK(ScenarioDb::DisambiguateDisplayName(
              f.db, "metalstorm", "Ashen Reach — War", "gen_basin_bbbb") ==
          "Ashen Reach — War (2)");

    // A row already holding the name under its OWN id is not a collision:
    // re-generating must be idempotent, not a ratchet that turns the title
    // into "… (7)" over seven re-runs.
    CHECK(ScenarioDb::DisambiguateDisplayName(
              f.db, "metalstorm", "Ashen Reach — War", "gen_basin_aaaa") ==
          "Ashen Reach — War");

    // A different game is a different namespace.
    CHECK(ScenarioDb::DisambiguateDisplayName(
              f.db, "zk", "Ashen Reach — War", "gen_basin_bbbb") ==
          "Ashen Reach — War");
}

// ==========================================================================
// Materialisation — the bridge to the two filesystem-only consumers
// ==========================================================================

TEST_CASE("ScenarioDb: a stored scenario is discovered alongside shipped ones") {
    Fixture f("merge");
    // An authored scenario and a generated one in the same directory. After
    // materialisation the lobby's single funnel must see both, and must not be
    // able to tell them apart beyond the id.
    f.WriteShipped("meridian_basin.lua",
                   GeneratedLua("Meridian Basin — Standard War", "meridian", true));
    REQUIRE(ScenarioDb::Upsert(
        f.db, MakeRecord("gen_basin_aaaa", "basin", true, "Ashen Reach — War")));

    const auto sync = ScenarioDb::SyncToDisk(f.db, "metalstorm", f.Path());
    CHECK(sync.written == 1);
    CHECK(sync.failed == 0);

    const auto found = SD::Discover(f.Path());
    REQUIRE(found.size() == 2);

    const SD::ScenarioInfo* gen = SD::FindById(found, "gen_basin_aaaa");
    REQUIRE(gen != nullptr);
    CHECK(gen->displayName == "Ashen Reach — War");
    CHECK(gen->mapId == "basin");
    CHECK(gen->terminal);
    CHECK_FALSE(gen->tutorial);

    // Sides resolve exactly as they do for a shipped scenario: the NPC side
    // (every team claimed by an `ai` entry) is excluded from the playable set.
    const auto sides = SD::PlayableSides(*gen);
    REQUIRE(sides.size() == 2);
    CHECK(sides[0].faction == "compact");
    CHECK(sides[0].team == 0);
    CHECK(sides[0].staged);
    CHECK(sides[1].faction == "union");
    CHECK(sides[1].team == 1);
    CHECK(sides[1].staged);
    CHECK(SD::EncodeWarSides(*gen) == "compact:0,union:1");

    // The authored one is untouched and still discovered.
    CHECK(SD::FindById(found, "meridian_basin") != nullptr);
}

TEST_CASE("ScenarioDb: a generated scenario with no victory is not terminal "
          "and is never the map default") {
    // The deliberate rule: `victory = true` is the only terminal condition
    // game_gameover.lua watches, so `DefaultForMap` requires it rather than
    // merely preferring it. Auto-applying an endless generated war is exactly
    // the failure the whole scenario-in-the-lobby design exists to prevent.
    Fixture f("terminal");
    REQUIRE(ScenarioDb::Upsert(
        f.db, MakeRecord("gen_basin_aaaa", "basin", /*victory=*/false)));
    REQUIRE(ScenarioDb::SyncToDisk(f.db, "metalstorm", f.Path()).written == 1);

    const auto found = SD::Discover(f.Path());
    const SD::ScenarioInfo* gen = SD::FindById(found, "gen_basin_aaaa");
    REQUIRE(gen != nullptr);
    CHECK_FALSE(gen->terminal);

    // Present in the list — still explicitly selectable ...
    CHECK(found.size() == 1);
    // ... but never handed to a room automatically.
    CHECK(SD::DefaultForMap(found, "basin") == nullptr);

    SUBCASE("a terminal generated scenario on the same map does become the default") {
        REQUIRE(ScenarioDb::Upsert(
            f.db, MakeRecord("gen_basin_bbbb", "basin", /*victory=*/true)));
        REQUIRE(ScenarioDb::SyncToDisk(f.db, "metalstorm", f.Path()).written == 2);

        const auto both = SD::Discover(f.Path());
        REQUIRE(both.size() == 2);
        const SD::ScenarioInfo* def = SD::DefaultForMap(both, "basin");
        REQUIRE(def != nullptr);
        CHECK(def->id == "gen_basin_bbbb");
    }
}

TEST_CASE("ScenarioDb: rebuild-from-DB reproduces every file byte-identically") {
    // The whole premise of the design — the row is the record of truth, the
    // file is a regenerable cache. `data/` is gitignored, so "the files are
    // gone" is a routine state; if this round trip did not hold, a data wipe
    // would silently lose every generated war.
    Fixture f("rebuild");
    REQUIRE(ScenarioDb::Upsert(
        f.db, MakeRecord("gen_basin_aaaa", "basin", true, "War One")));
    REQUIRE(ScenarioDb::Upsert(
        f.db, MakeRecord("gen_ridge_bbbb", "ridge", false, "War Two")));
    f.WriteShipped("meridian_basin.lua", GeneratedLua("Meridian", "meridian", true));

    REQUIRE(ScenarioDb::SyncToDisk(f.db, "metalstorm", f.Path()).written == 2);
    const std::string beforeA = f.ReadFile("gen_basin_aaaa.lua");
    const std::string beforeB = f.ReadFile("gen_ridge_bbbb.lua");
    const std::string beforeShipped = f.ReadFile("meridian_basin.lua");
    REQUIRE_FALSE(beforeA.empty());
    REQUIRE_FALSE(beforeB.empty());

    // Wipe every materialised file.
    std::error_code ec;
    fs::remove(f.game / "scenarios" / "gen_basin_aaaa.lua", ec);
    fs::remove(f.game / "scenarios" / "gen_ridge_bbbb.lua", ec);
    REQUIRE_FALSE(fs::exists(f.game / "scenarios" / "gen_basin_aaaa.lua"));

    const auto again = ScenarioDb::SyncToDisk(f.db, "metalstorm", f.Path());
    CHECK(again.written == 2);
    CHECK(again.failed == 0);

    CHECK(f.ReadFile("gen_basin_aaaa.lua") == beforeA);
    CHECK(f.ReadFile("gen_ridge_bbbb.lua") == beforeB);
    // The authored scenario was never a rebuild candidate and is unchanged.
    CHECK(f.ReadFile("meridian_basin.lua") == beforeShipped);

    // And the rebuilt files are what discovery reads — a byte-identical file
    // that no longer parses would still be a regression.
    const auto found = SD::Discover(f.Path());
    CHECK(found.size() == 3);
    CHECK(SD::FindById(found, "gen_basin_aaaa") != nullptr);
}

TEST_CASE("ScenarioDb: a deleted row does not leave an orphaned .lua behind") {
    // The orphan is the specific failure: discovery would keep offering a war
    // forever with nothing in the DB left to explain it.
    Fixture f("orphan");
    REQUIRE(ScenarioDb::Upsert(f.db, MakeRecord("gen_basin_aaaa", "basin", true)));
    REQUIRE(ScenarioDb::Upsert(f.db, MakeRecord("gen_ridge_bbbb", "ridge", true)));
    f.WriteShipped("meridian_basin.lua", GeneratedLua("Meridian", "meridian", true));
    REQUIRE(ScenarioDb::SyncToDisk(f.db, "metalstorm", f.Path()).written == 2);

    REQUIRE(ScenarioDb::Delete(f.db, "gen_basin_aaaa"));

    const auto sync = ScenarioDb::SyncToDisk(f.db, "metalstorm", f.Path());
    CHECK(sync.written == 1);
    CHECK(sync.orphansRemoved == 1);
    CHECK_FALSE(fs::exists(f.game / "scenarios" / "gen_basin_aaaa.lua"));

    const auto found = SD::Discover(f.Path());
    CHECK(SD::FindById(found, "gen_basin_aaaa") == nullptr);
    CHECK(SD::FindById(found, "gen_ridge_bbbb") != nullptr);
    // The sweep only ever considers `gen_*` — an authored scenario cannot be
    // collected however wrong the table is, and this runs unattended at every
    // lobby start.
    CHECK(SD::FindById(found, "meridian_basin") != nullptr);
}

TEST_CASE("ScenarioDb: the orphan sweep never touches authored scenarios") {
    // Belt and braces on the case above: an EMPTY table must not empty the
    // directory. If the sweep were keyed on anything but the `gen_` prefix,
    // a fresh DB against a populated game folder would delete shipped content.
    Fixture f("sweep_safety");
    f.WriteShipped("meridian_basin.lua", GeneratedLua("Meridian", "meridian", true));
    f.WriteShipped("tutorial_01.lua", GeneratedLua("Tutorial", "meridian", false));
    f.WriteShipped("scenario_smoke_test.lua", GeneratedLua("Smoke", "flat", false));

    const auto sync = ScenarioDb::SyncToDisk(f.db, "metalstorm", f.Path());
    CHECK(sync.written == 0);
    CHECK(sync.orphansRemoved == 0);
    CHECK(SD::Discover(f.Path()).size() == 3);
}

TEST_CASE("ScenarioDb.Unmaterialise removes only the named generated file") {
    Fixture f("unmat");
    REQUIRE(ScenarioDb::Upsert(f.db, MakeRecord("gen_basin_aaaa", "basin", true)));
    REQUIRE(ScenarioDb::SyncToDisk(f.db, "metalstorm", f.Path()).written == 1);

    CHECK(ScenarioDb::Unmaterialise("gen_basin_aaaa", f.Path()));
    CHECK_FALSE(fs::exists(f.game / "scenarios" / "gen_basin_aaaa.lua"));
    // Already gone, and an id we would never have written.
    CHECK_FALSE(ScenarioDb::Unmaterialise("gen_basin_aaaa", f.Path()));
    CHECK_FALSE(ScenarioDb::Unmaterialise("meridian_basin", f.Path()));
}

TEST_CASE("ScenarioDb.SyncToDisk creates a missing scenarios/ directory") {
    // A game folder with no scenarios/ at all is the state of a fresh clone
    // after a `data/` wipe — sync must create it rather than record failures.
    Fixture f("mkdir");
    std::error_code ec;
    fs::remove_all(f.game / "scenarios", ec);
    REQUIRE_FALSE(fs::exists(f.game / "scenarios"));

    REQUIRE(ScenarioDb::Upsert(f.db, MakeRecord("gen_basin_aaaa", "basin", true)));
    const auto sync = ScenarioDb::SyncToDisk(f.db, "metalstorm", f.Path());
    CHECK(sync.written == 1);
    CHECK(sync.failed == 0);
    CHECK(SD::Discover(f.Path()).size() == 1);
}

TEST_CASE("ScenarioDb: materialisation leaves no .tmp file for discovery to trip on") {
    // Materialise writes to a temp path and renames, so a concurrent Discover
    // can never read a half-written scenario. The temp file must not survive —
    // it would not be discovered (wrong extension) but it would accumulate.
    Fixture f("atomic");
    REQUIRE(ScenarioDb::Upsert(f.db, MakeRecord("gen_basin_aaaa", "basin", true)));
    REQUIRE(ScenarioDb::SyncToDisk(f.db, "metalstorm", f.Path()).written == 1);

    int strays = 0;
    for (const auto& e : fs::directory_iterator(f.game / "scenarios")) {
        if (e.path().extension() == ".tmp")
            ++strays;
    }
    CHECK(strays == 0);
}
