// Worldsim phase 3 item 3: the offline notification channels — Discord
// webhook + Web Push — behind the WorldNotificationBus seam W11 left.
//
// Three layers, tested in order of purity:
//   1. **The crypto** (WebPushCrypto) against FIXED vectors: RFC 8291
//      Appendix A verbatim (the canonical aes128gcm encryption vector), a
//      second vector generated independently with Python `cryptography`
//      (cross-implementation agreement, not self-agreement), and a
//      reference-signed ES256 JWT the verifier must accept (an ES256
//      signature is randomised per RFC 7518, so the fixed vector pins the
//      VERIFY direction and the sign direction is pinned by round-trip
//      through it plus byte-exact header/claims encoding).
//   2. **The store and the assembly**: world_push_subscriptions against the
//      same in-memory-db pattern the rest of the layer uses; the
//      Discord/WebPush request builders as pure functions of config + event.
//   3. **The dispatcher** against a fake HTTP sink: delivery order, failure
//      isolation (a throwing/dead sink never kills the worker), and the
//      bounded queue's drop behaviour. No real network anywhere.

#include <doctest/doctest.h>
#include <nlohmann/json.hpp>
#include <sqlite3.h>

#include <atomic>
#include <condition_variable>
#include <mutex>
#include <stdexcept>
#include <vector>

#include "Server/WebPushCrypto.h"
#include "Server/WorldOfflineChannels.h"

namespace {

// ─────────────────────────── fixed vectors ─────────────────────────────────
// Generated by scratchpad gen_vectors.py with Python `cryptography` 46.x as
// the independent reference implementation. The rfc8291 block is RFC 8291
// Appendix A, inputs and output verbatim (the script asserts the published
// public keys derive from the published scalars before emitting the body).

// RFC 8291 Appendix A
constexpr const char* kRfcPlaintext = "When I grow up, I want to be a watermelon";
constexpr const char* kRfcUaPrivate = "q1dXpw3UpT5VOmu_cf_v6ih07Aems3njxI-JWgLcM94";
constexpr const char* kRfcUaPublic =
    "BCVxsr7N_eNgVRqvHtD0zTZsEc6-VV-JvLexhqUzORcxaOzi6-AYWXvTBHm4bjyPjs7Vd8pZGH6SRpkNtoIAiw4";
constexpr const char* kRfcAsPrivate = "yfWPiYE-n46HLnH0KqZOF1fJJU3MYrct3AELtAQ-oRw";
constexpr const char* kRfcAsPublic =
    "BP4z9KsN6nGRTbVYI_c7VJSPQTBtkgcy27mlmlMoZIIgDll6e3vCYLocInmYWAmS6TlzAC8wEqKK6PBru3jl7A8";
constexpr const char* kRfcAuth = "BTBZMqHH6r4Tts7J_aSIgg";
constexpr const char* kRfcSalt = "DGv6ra1nlYgDCS1FRnbzlw";
constexpr const char* kRfcBody =
    "DGv6ra1nlYgDCS1FRnbzlwAAEABBBP4z9KsN6nGRTbVYI_c7VJSPQTBtkgcy27mlmlMoZIIg"
    "Dll6e3vCYLocInmYWAmS6TlzAC8wEqKK6PBru3jl7A_yl95bQpu6cVPTpK4Mqgkf1CXztLVB"
    "St2Ks3oZwbuwXPXLWyouBWLVWGNWQexSgSxsj_Qulcy4a-fN";

// Second, independently generated vector (different keys, plaintext, salt).
constexpr const char* kOwnPlaintext = "Staging opened at Meridian Basin.";
constexpr const char* kOwnUaPrivate = "AQIDBAUGBwgJCgsMDQ4PEBESExQVFhcYGRobHB0eHyA";
constexpr const char* kOwnUaPublic =
    "BFFcPW6545a5BNP-yn9U_c0MwemXvzddylFa0KbDtANfRTa-OlDzGPv5pUdZAqIhUCvvDVfgjFOyzApW8X2fk1Q";
constexpr const char* kOwnAsPrivate = "QEFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaW1xdXl8";
constexpr const char* kOwnAuth = "EBESExQVFhcYGRobHB0eHw";
constexpr const char* kOwnSalt = "ICEiIyQlJicoKSorLC0uLw";
constexpr const char* kOwnBody =
    "ICEiIyQlJicoKSorLC0uLwAAEABBBGjsfPCM1BBuQ7FN6JVCZSK9CkUVDAJ-RceVNDTXR-e6"
    "4685qI677oZ5u2HnhFw6icubWjI3w_2wsFh9uvQVEY2yltJVd2ziSy4JZt3oy11wEfcASx-M"
    "yjFsOqYftgdXiBRPm6rVrpxKxCt3G7_XwlRTMg";

// VAPID reference pair + a JWT signed by the Python reference implementation
// over exactly the header/claims serialisation SignVapidJwt uses.
constexpr const char* kVapidPrivate = "ZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXp7fH1-f4CBgoM";
constexpr const char* kVapidPublic =
    "BFFC9Ip8gMr0dUSkKPxX0nKmxnitXpP_y6NmZqmWOeUd0b22-1mBRFZ6Jlfo_zYZ-6oM0qBAwZqyKvkQxwWnV7o";
constexpr const char* kVapidAudience = "https://push.example.net";
constexpr const char* kVapidSubject = "mailto:ops@warriorhut.com";
constexpr int64_t kVapidExpiry = 1700000600;
constexpr const char* kVapidSigningInput =
    "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9."
    "eyJhdWQiOiJodHRwczovL3B1c2guZXhhbXBsZS5uZXQiLCJleHAiOjE3MDAwMDA2MDAsInN1"
    "YiI6Im1haWx0bzpvcHNAd2Fycmlvcmh1dC5jb20ifQ";
constexpr const char* kReferenceJwt =
    "eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9."
    "eyJhdWQiOiJodHRwczovL3B1c2guZXhhbXBsZS5uZXQiLCJleHAiOjE3MDAwMDA2MDAsInN1"
    "YiI6Im1haWx0bzpvcHNAd2Fycmlvcmh1dC5jb20ifQ."
    "4kyyCC4xFTyL150T1RV6dSWJRU5uOB3BE3WZM3olnDWviwlKLde7HRSn_cGWj7Me6i-TU0K1"
    "ObgIRXpnz6q4YA";

std::vector<uint8_t> BytesOf(const char* s) {
    const std::string str(s);
    return std::vector<uint8_t>(str.begin(), str.end());
}

WorldNotificationEvent SampleEvent() {
    WorldNotificationEvent ev;
    ev.worldId = "earth";
    ev.poiId = "poi-meridian";
    ev.poiName = "Meridian Basin";
    ev.kind = WorldNotificationKind::StagingOpened;
    ev.attackerFactionId = "red";
    ev.defenderFactionId = "blue";
    ev.stagingId = 7;
    ev.worldMs = 123456;
    return ev;
}

struct SubDb {
    sqlite3* db = nullptr;
    SubDb() {
        REQUIRE(sqlite3_open(":memory:", &db) == SQLITE_OK);
        WebPushSubscriptions::EnsureTables(db);
    }
    ~SubDb() { sqlite3_close(db); }
};

WebPushSubscriptionRecord Sub(const std::string& world, int64_t account,
                              const std::string& endpoint) {
    WebPushSubscriptionRecord s;
    s.worldId = world;
    s.accountId = account;
    s.endpoint = endpoint;
    s.p256dh = kOwnUaPublic;
    s.auth = kOwnAuth;
    s.createdAt = 1000;
    return s;
}

}  // namespace

// ─────────────────────────── 1. the crypto ─────────────────────────────────

TEST_CASE("phase 3: base64url round-trips and refuses the standard alphabet's extras") {
    const std::vector<uint8_t> data{0x00, 0x01, 0xFE, 0xFF, 0x3E, 0x3F, 0x7A};
    CHECK(WebPush::Base64UrlDecode(WebPush::Base64UrlEncode(data)) == data);
    // Unpadded, URL-safe alphabet.
    const std::string enc = WebPush::Base64UrlEncode(data);
    CHECK(enc.find('=') == std::string::npos);
    CHECK(enc.find('+') == std::string::npos);
    CHECK(enc.find('/') == std::string::npos);
    // '+' and '/' belong to the OTHER base64; a subscription pasted in the
    // wrong alphabet must fail loudly, not decode to different bytes.
    CHECK(WebPush::Base64UrlDecode("ab+c").empty());
    CHECK(WebPush::Base64UrlDecode("ab/c").empty());
    // Padding is tolerated (some clients send it).
    CHECK(WebPush::Base64UrlDecode("AQID==") == std::vector<uint8_t>{1, 2, 3});
}

TEST_CASE("phase 3: P-256 public keys derive from the reference scalars byte-exactly") {
    // RFC 8291 Appendix A publishes both halves of both pairs — deriving one
    // from the other pins our whole key register to the spec's encodings.
    CHECK(WebPush::DeriveP256PublicKey(kRfcUaPrivate) == kRfcUaPublic);
    CHECK(WebPush::DeriveP256PublicKey(kRfcAsPrivate) == kRfcAsPublic);
    CHECK(WebPush::DeriveP256PublicKey(kOwnUaPrivate) == kOwnUaPublic);
    CHECK(WebPush::DeriveP256PublicKey(kVapidPrivate) == kVapidPublic);
    // Malformed scalars answer empty, never a plausible key.
    CHECK(WebPush::DeriveP256PublicKey("").empty());
    CHECK(WebPush::DeriveP256PublicKey("AQID").empty());  // 3 bytes
    CHECK(WebPush::DeriveP256PublicKey("not!base64").empty());
}

TEST_CASE("phase 3: RFC 8291 Appendix A encrypts verbatim") {
    const auto body = WebPush::EncryptAes128GcmDeterministic(
        BytesOf(kRfcPlaintext), kRfcUaPublic, kRfcAuth,
        WebPush::Base64UrlDecode(kRfcSalt), kRfcAsPrivate);
    REQUIRE(!body.empty());
    CHECK(body.size() == 144);  // the RFC's own count
    CHECK(WebPush::Base64UrlEncode(body) == kRfcBody);
}

TEST_CASE("phase 3: the second (independently generated) encryption vector agrees") {
    const auto body = WebPush::EncryptAes128GcmDeterministic(
        BytesOf(kOwnPlaintext), kOwnUaPublic, kOwnAuth,
        WebPush::Base64UrlDecode(kOwnSalt), kOwnAsPrivate);
    REQUIRE(!body.empty());
    CHECK(WebPush::Base64UrlEncode(body) == kOwnBody);
}

TEST_CASE("phase 3: deterministic encryption refuses malformed inputs rather than sealing garbage") {
    const auto salt = WebPush::Base64UrlDecode(kOwnSalt);
    // Wrong-size auth secret.
    CHECK(WebPush::EncryptAes128GcmDeterministic(BytesOf("x"), kOwnUaPublic,
                                                 "AQID", salt, kOwnAsPrivate)
              .empty());
    // p256dh that is not a 65-byte point.
    CHECK(WebPush::EncryptAes128GcmDeterministic(BytesOf("x"), kOwnAuth,
                                                 kOwnAuth, salt, kOwnAsPrivate)
              .empty());
    // Truncated salt.
    CHECK(WebPush::EncryptAes128GcmDeterministic(
              BytesOf("x"), kOwnUaPublic, kOwnAuth,
              std::vector<uint8_t>{1, 2, 3}, kOwnAsPrivate)
              .empty());
}

TEST_CASE("phase 3: production encryption randomises the salt and ephemeral key per message") {
    const auto a =
        WebPush::EncryptAes128Gcm(BytesOf("hello"), kOwnUaPublic, kOwnAuth);
    const auto b =
        WebPush::EncryptAes128Gcm(BytesOf("hello"), kOwnUaPublic, kOwnAuth);
    REQUIRE(!a.empty());
    REQUIRE(!b.empty());
    // RFC 8188 header: salt(16) ‖ rs(4) ‖ idlen(1)=65 ‖ point(65) ‖ record.
    CHECK(a.size() == 16u + 4u + 1u + 65u + (5u + 1u + 16u));
    CHECK(a[20] == 65);
    CHECK(a[21] == 0x04);
    // Same plaintext, different bytes — or the salt/key reuse the spec
    // forbids has crept in.
    CHECK(a != b);
}

TEST_CASE("phase 3: the ES256 verifier accepts the reference-signed JWT and nothing tampered") {
    CHECK(WebPush::VerifyEs256Jwt(kReferenceJwt, kVapidPublic));
    // Wrong key.
    CHECK_FALSE(WebPush::VerifyEs256Jwt(kReferenceJwt, kRfcAsPublic));
    // One flipped claim byte.
    std::string tampered = kReferenceJwt;
    tampered[45] = tampered[45] == 'A' ? 'B' : 'A';
    CHECK_FALSE(WebPush::VerifyEs256Jwt(tampered, kVapidPublic));
    // Structural garbage.
    CHECK_FALSE(WebPush::VerifyEs256Jwt("nodots", kVapidPublic));
    CHECK_FALSE(WebPush::VerifyEs256Jwt("a.b", kVapidPublic));
}

TEST_CASE("phase 3: SignVapidJwt reproduces the reference signing input and verifies") {
    const std::string jwt = WebPush::SignVapidJwt(kVapidAudience, kVapidSubject,
                                                  kVapidExpiry, kVapidPrivate);
    REQUIRE(!jwt.empty());
    // The header/claims halves are byte-exact against the reference (ES256's
    // signature is randomised, the signing input is not).
    CHECK(jwt.substr(0, jwt.find_last_of('.')) == kVapidSigningInput);
    CHECK(WebPush::VerifyEs256Jwt(jwt, kVapidPublic));
    CHECK_FALSE(WebPush::VerifyEs256Jwt(jwt, kRfcAsPublic));
    // A malformed private key signs nothing.
    CHECK(WebPush::SignVapidJwt(kVapidAudience, kVapidSubject, kVapidExpiry, "AQID")
              .empty());
}

TEST_CASE("phase 3: the VAPID header and endpoint origin have RFC 8292's shape") {
    const std::string h = WebPush::VapidAuthorizationHeader(
        kVapidAudience, kVapidSubject, kVapidExpiry, kVapidPrivate, kVapidPublic);
    REQUIRE(!h.empty());
    CHECK(h.rfind("vapid t=", 0) == 0);
    CHECK(h.find(", k=") != std::string::npos);
    CHECK(h.find(kVapidPublic) != std::string::npos);
    // The t= token itself verifies.
    const size_t tFrom = 8;
    const size_t tTo = h.find(", k=");
    CHECK(WebPush::VerifyEs256Jwt(h.substr(tFrom, tTo - tFrom), kVapidPublic));

    CHECK(WebPush::EndpointOrigin("https://push.example.net/send/abc123") ==
          "https://push.example.net");
    CHECK(WebPush::EndpointOrigin("https://host:8443/x") == "https://host:8443");
    CHECK(WebPush::EndpointOrigin("https://host") == "https://host");
    CHECK(WebPush::EndpointOrigin("no-scheme/path").empty());
    CHECK(WebPush::EndpointOrigin("").empty());
}

TEST_CASE("phase 3: generated VAPID keys are well-formed and self-consistent") {
    const auto pair = WebPush::GenerateVapidKeys();
    REQUIRE(pair.has_value());
    CHECK(WebPush::Base64UrlDecode(pair->privateKeyB64).size() == 32);
    CHECK(WebPush::Base64UrlDecode(pair->publicKeyB64).size() == 65);
    CHECK(WebPush::DeriveP256PublicKey(pair->privateKeyB64) == pair->publicKeyB64);
}

// ─────────────────────────── 2a. per-world config ──────────────────────────

TEST_CASE("phase 3: both channels default OFF, and a partial config does not disable what it omits") {
    // No config at all.
    const auto none = WorldOfflineChannelRules::FromWorldConfig(nlohmann::json());
    CHECK_FALSE(none.discord.enabled);
    CHECK_FALSE(none.webPush.enabled);

    // A discord-only config leaves webPush untouched and vice versa; a
    // webPush block naming only `enabled` keeps every default rate.
    nlohmann::json cfg;
    cfg["notifications"]["discord"]["enabled"] = true;
    cfg["notifications"]["discord"]["webhookUrl"] = "https://discord.test/hook";
    cfg["notifications"]["webPush"]["enabled"] = true;
    const auto r = WorldOfflineChannelRules::FromWorldConfig(cfg);
    CHECK(r.discord.enabled);
    CHECK(r.discord.webhookUrl == "https://discord.test/hook");
    CHECK(r.discord.events.empty());
    CHECK(r.webPush.enabled);
    CHECK(r.webPush.ttlSeconds == 3600);
    CHECK(r.webPush.jwtTtlSeconds == 12 * 3600);

    // Every rate is data.
    cfg["notifications"]["webPush"]["ttlSeconds"] = 60;
    cfg["notifications"]["webPush"]["jwtTtlSeconds"] = 600;
    cfg["notifications"]["discord"]["events"] =
        nlohmann::json::array({"opened", "materialised"});
    const auto r2 = WorldOfflineChannelRules::FromWorldConfig(cfg);
    CHECK(r2.webPush.ttlSeconds == 60);
    CHECK(r2.webPush.jwtTtlSeconds == 600);
    REQUIRE(r2.discord.events.size() == 2);
}

TEST_CASE("phase 3: an empty event list means every kind, a named list narrows") {
    const std::vector<std::string> all;
    CHECK(WorldChannelEventEnabled(all, WorldNotificationKind::StagingOpened));
    CHECK(WorldChannelEventEnabled(all, WorldNotificationKind::StagingFailed));

    const std::vector<std::string> some{"opened", "materialised"};
    CHECK(WorldChannelEventEnabled(some, WorldNotificationKind::StagingOpened));
    CHECK(WorldChannelEventEnabled(some, WorldNotificationKind::StagingMaterialised));
    CHECK_FALSE(WorldChannelEventEnabled(some, WorldNotificationKind::StagingCancelled));
    CHECK_FALSE(WorldChannelEventEnabled(some, WorldNotificationKind::StagingFailed));
}

// ─────────────────────────── 2b. the subscription store ────────────────────

TEST_CASE("phase 3: the subscription table is world-scoped and never room-scoped") {
    SubDb h;
    sqlite3_stmt* s = nullptr;
    REQUIRE(sqlite3_prepare_v2(h.db, "PRAGMA table_info(world_push_subscriptions)",
                               -1, &s, nullptr) == SQLITE_OK);
    std::vector<std::string> cols;
    while (sqlite3_step(s) == SQLITE_ROW)
        cols.push_back(reinterpret_cast<const char*>(sqlite3_column_text(s, 1)));
    sqlite3_finalize(s);
    REQUIRE(!cols.empty());
    CHECK(cols.front() == "world_id");
    for (const auto& c : cols) CHECK(c != "room_id");
}

TEST_CASE("phase 3: a re-subscribe rotates the keys in place, per (world, account, endpoint)") {
    SubDb h;
    REQUIRE(WebPushSubscriptions::Upsert(h.db, Sub("earth", 1, "https://p.test/a")));
    auto rotated = Sub("earth", 1, "https://p.test/a");
    rotated.p256dh = kRfcUaPublic;
    rotated.auth = kRfcAuth;
    REQUIRE(WebPushSubscriptions::Upsert(h.db, rotated));

    const auto rows = WebPushSubscriptions::ListForAccount(h.db, "earth", 1);
    REQUIRE(rows.size() == 1);  // replaced, not duplicated
    CHECK(rows[0].p256dh == kRfcUaPublic);
    CHECK(rows[0].auth == kRfcAuth);

    // A second endpoint for the same account is a second browser, kept.
    REQUIRE(WebPushSubscriptions::Upsert(h.db, Sub("earth", 1, "https://p.test/b")));
    CHECK(WebPushSubscriptions::ListForAccount(h.db, "earth", 1).size() == 2);
    // Another world's identical endpoint is its own row.
    REQUIRE(WebPushSubscriptions::Upsert(h.db, Sub("mars", 1, "https://p.test/a")));
    CHECK(WebPushSubscriptions::ListForAccount(h.db, "earth", 1).size() == 2);
    CHECK(WebPushSubscriptions::ListForAccount(h.db, "mars", 1).size() == 1);
}

TEST_CASE("phase 3: removal is scoped to the acting account") {
    SubDb h;
    REQUIRE(WebPushSubscriptions::Upsert(h.db, Sub("earth", 1, "https://p.test/a")));
    REQUIRE(WebPushSubscriptions::Upsert(h.db, Sub("earth", 2, "https://p.test/a")));
    // Account 2 removing the shared endpoint touches only its own row.
    REQUIRE(WebPushSubscriptions::Remove(h.db, "earth", 2, "https://p.test/a"));
    CHECK(WebPushSubscriptions::ListForAccount(h.db, "earth", 1).size() == 1);
    CHECK(WebPushSubscriptions::ListForAccount(h.db, "earth", 2).empty());
}

TEST_CASE("phase 3: the store refuses a blank subscription rather than storing it") {
    SubDb h;
    auto s = Sub("earth", 1, "https://p.test/a");
    s.p256dh = "";
    CHECK_FALSE(WebPushSubscriptions::Upsert(h.db, s));
    s = Sub("earth", 0, "https://p.test/a");
    CHECK_FALSE(WebPushSubscriptions::Upsert(h.db, s));
    CHECK(WebPushSubscriptions::ListForAccount(h.db, "earth", 1).empty());
}

TEST_CASE("phase 3: the fan-out read gathers every recipient's every browser") {
    SubDb h;
    REQUIRE(WebPushSubscriptions::Upsert(h.db, Sub("earth", 1, "https://p.test/a")));
    REQUIRE(WebPushSubscriptions::Upsert(h.db, Sub("earth", 1, "https://p.test/b")));
    REQUIRE(WebPushSubscriptions::Upsert(h.db, Sub("earth", 2, "https://p.test/c")));
    REQUIRE(WebPushSubscriptions::Upsert(h.db, Sub("earth", 3, "https://p.test/d")));
    const auto rows = WebPushSubscriptions::ListForAccounts(h.db, "earth", {1, 3});
    CHECK(rows.size() == 3);  // two browsers for 1, one for 3, none of 2's
}

// ─────────────────────────── 2c. request assembly ──────────────────────────

TEST_CASE("phase 3: the Discord payload carries the headline and the structured fields") {
    const auto body = DiscordWebhookPayload(SampleEvent());
    CHECK(body["content"].get<std::string>() ==
          WorldNotificationHeadline(WorldNotificationKind::StagingOpened,
                                    "Meridian Basin"));
    REQUIRE(body["embeds"].size() == 1);
    CHECK(body["embeds"][0]["title"].get<std::string>() == "Meridian Basin");
    bool sawAttacker = false;
    for (const auto& f : body["embeds"][0]["fields"])
        if (f["name"] == "Attacker" && f["value"] == "red") sawAttacker = true;
    CHECK(sawAttacker);
}

TEST_CASE("phase 3: the Discord builder is gated on enabled + URL + event kind") {
    WorldDiscordConfig cfg;
    cfg.enabled = true;
    cfg.webhookUrl = "https://discord.test/hook";
    const auto ev = SampleEvent();

    const auto post = BuildDiscordPost(cfg, ev);
    REQUIRE(post.has_value());
    CHECK(post->url == cfg.webhookUrl);
    REQUIRE(post->headers.size() == 1);
    CHECK(post->headers[0] == "Content-Type: application/json");
    // The body is the payload, byte for byte.
    const auto parsed = nlohmann::json::parse(
        std::string(post->body.begin(), post->body.end()));
    CHECK(parsed == DiscordWebhookPayload(ev));

    WorldDiscordConfig off = cfg;
    off.enabled = false;
    CHECK_FALSE(BuildDiscordPost(off, ev).has_value());
    WorldDiscordConfig noUrl = cfg;
    noUrl.webhookUrl.clear();
    CHECK_FALSE(BuildDiscordPost(noUrl, ev).has_value());
    WorldDiscordConfig narrowed = cfg;
    narrowed.events = {"materialised"};
    CHECK_FALSE(BuildDiscordPost(narrowed, ev).has_value());
    auto matEv = ev;
    matEv.kind = WorldNotificationKind::StagingMaterialised;
    CHECK(BuildDiscordPost(narrowed, matEv).has_value());
}

TEST_CASE("phase 3: the Web Push builder assembles an encrypted, VAPID-authorized POST") {
    WorldWebPushConfig cfg;
    cfg.enabled = true;
    cfg.vapidPublicKey = kVapidPublic;
    cfg.vapidPrivateKey = kVapidPrivate;
    cfg.subject = kVapidSubject;
    cfg.ttlSeconds = 900;
    const auto sub = Sub("earth", 42, "https://push.example.net/send/abc123");
    const auto ev = SampleEvent();

    const auto post = BuildWebPushPost(sub, cfg, ev, /*now=*/1700000000);
    REQUIRE(post.has_value());
    CHECK(post->url == sub.endpoint);
    // The body is a well-formed aes128gcm message for the subscription's key.
    REQUIRE(post->body.size() > 86u);
    CHECK(post->body[20] == 65);    // keyid length
    CHECK(post->body[21] == 0x04);  // uncompressed ephemeral point

    std::string authz, ttl, encoding;
    for (const auto& h : post->headers) {
        if (h.rfind("Authorization: ", 0) == 0) authz = h.substr(15);
        if (h.rfind("TTL: ", 0) == 0) ttl = h.substr(5);
        if (h.rfind("Content-Encoding: ", 0) == 0) encoding = h.substr(18);
    }
    CHECK(ttl == "900");
    CHECK(encoding == "aes128gcm");
    REQUIRE(authz.rfind("vapid t=", 0) == 0);
    // The JWT inside verifies against the world's configured public key.
    const size_t tTo = authz.find(", k=");
    REQUIRE(tTo != std::string::npos);
    CHECK(WebPush::VerifyEs256Jwt(authz.substr(8, tTo - 8), kVapidPublic));

    // Gates: disabled, missing keys/subject, narrowed events, bad endpoint,
    // malformed subscription keys.
    auto off = cfg;
    off.enabled = false;
    CHECK_FALSE(BuildWebPushPost(sub, off, ev, 0).has_value());
    auto noSubject = cfg;
    noSubject.subject.clear();
    CHECK_FALSE(BuildWebPushPost(sub, noSubject, ev, 0).has_value());
    auto narrowed = cfg;
    narrowed.events = {"cancelled"};
    CHECK_FALSE(BuildWebPushPost(sub, narrowed, ev, 0).has_value());
    auto badEndpoint = sub;
    badEndpoint.endpoint = "not-a-url";
    CHECK_FALSE(BuildWebPushPost(badEndpoint, cfg, ev, 0).has_value());
    auto badKeys = sub;
    badKeys.p256dh = "AQID";
    CHECK_FALSE(BuildWebPushPost(badKeys, cfg, ev, 0).has_value());
}

// ─────────────────────────── 3. the dispatcher ─────────────────────────────

TEST_CASE("phase 3: the dispatcher delivers queued posts to the fake sink in order") {
    std::mutex m;
    std::vector<std::string> sent;
    WorldOfflineDispatcher d([&](const OutboundHttpPost& p) -> int {
        std::lock_guard<std::mutex> lock(m);
        sent.push_back(p.label);
        return 200;
    });
    for (int i = 0; i < 5; ++i) {
        OutboundHttpPost p;
        p.label = "post-" + std::to_string(i);
        CHECK(d.Enqueue(std::move(p)));
    }
    d.DrainForTest();
    std::lock_guard<std::mutex> lock(m);
    REQUIRE(sent.size() == 5);
    CHECK(sent.front() == "post-0");
    CHECK(sent.back() == "post-4");
    CHECK(d.DroppedCount() == 0);
}

TEST_CASE("phase 3: a dead or throwing sink never blocks the bus or kills the worker") {
    std::atomic<int> calls{0};
    WorldOfflineDispatcher d([&](const OutboundHttpPost& p) -> int {
        ++calls;
        if (p.label == "boom") throw std::runtime_error("sink exploded");
        if (p.label == "gone") return 410;
        if (p.label == "dead") return -1;
        return 200;
    });
    OutboundHttpPost a; a.label = "boom";
    OutboundHttpPost b; b.label = "gone";
    OutboundHttpPost c; c.label = "dead";
    OutboundHttpPost okPost; okPost.label = "ok";
    CHECK(d.Enqueue(std::move(a)));
    CHECK(d.Enqueue(std::move(b)));
    CHECK(d.Enqueue(std::move(c)));
    CHECK(d.Enqueue(std::move(okPost)));
    d.DrainForTest();
    // Every post reached the sink — the explosion on the first did not eat
    // the rest, and Enqueue itself never blocked on any of it.
    CHECK(calls.load() == 4);
}

TEST_CASE("phase 3: the queue is bounded — a stuck far end drops posts instead of growing") {
    std::mutex m;
    std::condition_variable cv;
    bool release = false;
    std::atomic<int> delivered{0};
    WorldOfflineDispatcher d(
        [&](const OutboundHttpPost&) -> int {
            std::unique_lock<std::mutex> lock(m);
            cv.wait(lock, [&] { return release; });
            ++delivered;
            return 200;
        },
        /*maxQueue=*/2);

    // First post occupies the worker (blocked in the sink); the queue then
    // holds at most 2; everything past that is dropped, and Enqueue says so.
    OutboundHttpPost p1; p1.label = "p1";
    CHECK(d.Enqueue(std::move(p1)));
    // Give the worker a moment to pick p1 up so the queue is empty again —
    // DrainForTest can't help here (the sink is deliberately stuck), so poll.
    for (int i = 0; i < 200 && d.DroppedCount() == 0; ++i) {
        OutboundHttpPost probe; probe.label = "probe";
        d.Enqueue(std::move(probe));
        if (d.DroppedCount() > 0) break;
    }
    CHECK(d.DroppedCount() > 0);

    {
        std::lock_guard<std::mutex> lock(m);
        release = true;
    }
    cv.notify_all();
    d.DrainForTest();
    // Whatever was queued at the cap was still delivered once released.
    CHECK(delivered.load() >= 1);
    CHECK(delivered.load() <= 3);  // p1 + at most maxQueue probes
}
