/**
 * Handshake admission policy — PLAN-protocol-guard task 3.
 *
 * The rule that decides whether anybody can play. Before this task it lived
 * inline in ClientMessageHandler.cpp's switch, where it needed a NetworkServer,
 * a Simulation and a live room to reach, so it had no test at all — which is
 * how the epoch integer sat unmoved through 15 schema edits without anything
 * noticing.
 *
 * The last case here is the one that matters most and is not about the rule:
 * the client's copies of the two constants are read off disk and compared with
 * the server's. Lockstep between two files nobody edits together is exactly the
 * discipline that has failed repeatedly, and the C++ side cannot import the TS.
 */
#include <doctest/doctest.h>

#include "Server/HandshakePolicy.h"
#include "Server/ProtocolSchemaHash.h"

#include <fstream>
#include <regex>
#include <sstream>
#include <string>

namespace {

std::string ReadFile(const std::string& path) {
    std::ifstream in(path);
    REQUIRE_MESSAGE(in.good(), "cannot open " << path);
    std::stringstream ss;
    ss << in.rdbuf();
    return ss.str();
}

/// The one hash both sides are supposed to be carrying.
const std::string kServerHash{Protocol::SCHEMA_HASH};

}  // namespace

TEST_CASE("handshake policy accepts a client built from this tree") {
    const auto v = Protocol::CheckHandshake(
        Protocol::CURRENT_PROTOCOL_VERSION, kServerHash);
    CHECK(v.accepted);
    CHECK(v.message.empty());
    CHECK(v.logDetail.empty());
}

TEST_CASE("handshake policy rejects a stale epoch and names both numbers") {
    const auto v = Protocol::CheckHandshake(
        static_cast<uint16_t>(Protocol::CURRENT_PROTOCOL_VERSION - 1),
        kServerHash);
    REQUIRE_FALSE(v.accepted);
    // Both values in the message, because "version mismatch" without the
    // numbers is a support ticket rather than a diagnosis.
    CHECK(v.message.find("client v" + std::to_string(
        Protocol::CURRENT_PROTOCOL_VERSION - 1)) != std::string::npos);
    CHECK(v.message.find("server v" + std::to_string(
        Protocol::CURRENT_PROTOCOL_VERSION)) != std::string::npos);
    CHECK(v.logDetail.find("protocol version") != std::string::npos);
}

TEST_CASE("handshake policy rejects a drifted schema hash and names both") {
    std::string drifted = kServerHash;
    drifted[0] = (drifted[0] == 'a') ? 'b' : 'a';
    const auto v = Protocol::CheckHandshake(
        Protocol::CURRENT_PROTOCOL_VERSION, drifted);
    REQUIRE_FALSE(v.accepted);
    CHECK(v.message.find(drifted.substr(0, 12)) != std::string::npos);
    CHECK(v.message.find(kServerHash.substr(0, 12)) != std::string::npos);
    CHECK(v.logDetail.find("schema hash") != std::string::npos);
}

TEST_CASE("handshake policy rejects a missing hash, and it reads differently") {
    // A pre-guard bundle sends no hash at all. It is stale by definition —
    // every post-guard client sends one — but it must not be reported as a
    // client whose hash happened to start with twelve blanks.
    const auto v = Protocol::CheckHandshake(
        Protocol::CURRENT_PROTOCOL_VERSION, "");
    REQUIRE_FALSE(v.accepted);
    CHECK(v.message.find("<none>") != std::string::npos);
    CHECK(v.message.find(kServerHash.substr(0, 12)) != std::string::npos);

    std::string drifted = kServerHash;
    drifted[0] = (drifted[0] == 'a') ? 'b' : 'a';
    const auto mismatch = Protocol::CheckHandshake(
        Protocol::CURRENT_PROTOCOL_VERSION, drifted);
    CHECK(v.message != mismatch.message);
}

TEST_CASE("handshake policy reports the epoch first when both disagree") {
    // Order matters for the human reading the log: a client one epoch behind
    // is ALSO carrying a different schema (that is what an epoch bump means),
    // and naming the hash first would send every reader hunting a regen they
    // do not need.
    const auto v = Protocol::CheckHandshake(
        static_cast<uint16_t>(Protocol::CURRENT_PROTOCOL_VERSION - 1), "");
    REQUIRE_FALSE(v.accepted);
    CHECK(v.logDetail.find("protocol version") != std::string::npos);
    CHECK(v.logDetail.find("schema hash") == std::string::npos);
}

TEST_CASE("the client's constants are in lockstep with the server's") {
    // Neither file can import the other, and both are edited by hand exactly
    // once per epoch. This is the check that fails the day someone bumps one.
    const std::string versionTs =
        ReadFile(std::string(SPRING_SOURCE_DIR) +
                 "/client/src/core/protocol-version.ts");
    std::smatch m;
    const std::regex verRe(R"(PROTOCOL_VERSION\s*=\s*(\d+))");
    REQUIRE_MESSAGE(std::regex_search(versionTs, m, verRe),
                    "no PROTOCOL_VERSION assignment in protocol-version.ts");
    CHECK(std::stoi(m[1].str()) ==
          static_cast<int>(Protocol::CURRENT_PROTOCOL_VERSION));

    // The hash pair is regenerated by one script run, so this asserts the two
    // outputs of that run were committed together — the half-applied-regen
    // case the build guards also cover, checked here from the other side.
    const std::string hashTs =
        ReadFile(std::string(SPRING_SOURCE_DIR) +
                 "/client/src/protocol/schema-hash.ts");
    const std::regex hashRe(R"(SCHEMA_HASH\s*=\s*'([0-9a-f]{64})')");
    REQUIRE_MESSAGE(std::regex_search(hashTs, m, hashRe),
                    "no SCHEMA_HASH assignment in schema-hash.ts");
    CHECK(m[1].str() == kServerHash);
}
