-- mapinfo.lua — GENERATED by tools/mapgen (terragen). Do not hand-edit.
local mapinfo = {
    name = "Meridian Basin",
    shortname = "meridian_basin",
    description = "Two sides of an eroded river basin: ridge corridors, three fords, civilian valleys.",
    author = "terragen",
    version = "1",
    mapfile = "maps/meridian_basin.smf",
    legacycoordsystem = false,

    maxmetal = 0.5,
    extractorradius = 90,

    smf = {
        minheight = -120.0,
        maxheight = 1500.0,
    },

    water = {
        damage = 0,
        voidwater = false,
        surfacecolor = { 0.35, 0.42, 0.5 },
        surfacealpha = 0.45,
        basecolor = { 0.28, 0.36, 0.43 },
        mincolor = { 0.05, 0.08, 0.11 },
        absorb = { 0.006, 0.004, 0.002 },
    },

    atmosphere = {
        fogcolor = { 0.72, 0.76, 0.80 },
        skycolor = { 0.45, 0.60, 0.79 },
        suncolor = { 1.0, 0.98, 0.92 },
    },

    lighting = {
        groundambientcolor = { 0.42, 0.42, 0.44 },
        grounddiffusecolor = { 0.92, 0.90, 0.85 },
        groundspecularcolor = { 0.08, 0.08, 0.08 },
    },

    resources = {
        splatdistrtex = "splat_distr.png",
        splatdetailtex = "splat_detail.png",
    },

    splats = {
        texscales = { 0.006, 0.02, 0.009, 0.0022 },
        texmults = { 0.25, 0.35, 0.22, 0.22 },
    },

    -- typemap value 1 = road surface
    terraintypes = {
        [0] = {
            name = "default",
            hardness = 1.0,
            tankspeed = 1.0, kbotspeed = 1.0, hoverspeed = 1.0, shipspeed = 1.0,
        },
        [1] = {
            name = "road",
            hardness = 1.2,
            tankspeed = 1.35, kbotspeed = 1.35,
            hoverspeed = 1.35, shipspeed = 1.0,
        },
    },

    teams = {
        [0] = { startPos = { x = 2400, z = 1200 } },
        [1] = { startPos = { x = 6600, z = 1200 } },
        [2] = { startPos = { x = 9400, z = 1200 } },
        [3] = { startPos = { x = 13400, z = 1200 } },
        [4] = { startPos = { x = 2400, z = 15184 } },
        [5] = { startPos = { x = 6600, z = 15184 } },
        [6] = { startPos = { x = 9400, z = 15184 } },
        [7] = { startPos = { x = 13400, z = 15184 } },
    },
}
return mapinfo
