// ConfigReader — tiny Lua-backed reader for .config.lua / .config.json files
// used by the lobby's discovery paths (GameDiscovery, AIDiscovery).
//
// Why a separate reader instead of the rts/Lua/ LuaConfigLoader used
// by the sim? LuaConfigLoader pulls in LuaParser, which transitively
// references 30+ sim-state globals (unitHandler, gs, modInfo, etc.)
// the lobby has no way to supply. Dragging all of that in just to
// evaluate a two-field config table would be a huge link-surface
// for no benefit — the lobby doesn't need event handlers, sandbox
// modes, or VFS integration.
//
// Instead we spin up a bare lua_State (the `lua` library is already
// linked to spring-lobby for MapProcessor), open the standard libs,
// evaluate the script, and read fields off the returned table. The
// public API mirrors LuaConfig::Load: a `.config.lua` wins over a
// `.config.json` when both are present (author hand-edits beat
// tool-generated output), and either end up wrapped in the same
// lookup interface.
//
// For JSON support, we preload the same embedded json.lua that the
// sim's LuaParser uses (`LuaJsonSrc.h`, generated by CMake from
// rts/lib/lua/json-lua/json.lua) and wrap the raw file contents in
// `return json.decode([==[ ... ]==])`. This keeps JSON and Lua
// configs reading through a single code path.
#pragma once

#include <memory>
#include <string>

struct lua_State;

namespace ConfigReader {

/// File suffixes for the .config.lua / .config.json convention.
constexpr const char* kLuaSuffix  = ".config.lua";
constexpr const char* kJsonSuffix = ".config.json";

/// Handle to a loaded config. Owns its lua_State and keeps the
/// returned table at the top of the stack for the lifetime of the
/// object — don't run arbitrary Lua calls against this state from
/// outside.
class Config {
public:
    /// Load `<basePath>.config.lua` if it exists, else
    /// `<basePath>.config.json`, else return nullptr. Errors during
    /// evaluation are logged to stderr and result in nullptr.
    static std::unique_ptr<Config> Load(const std::string& basePath);

    ~Config();
    Config(const Config&) = delete;
    Config& operator=(const Config&) = delete;

    /// Read a string field from the top-level table. Returns
    /// `defaultValue` if the field is missing or not a string.
    std::string GetString(const std::string& key,
                          const std::string& defaultValue = "") const;

    /// Read a numeric field, cast to int. Returns `defaultValue`
    /// if the field is missing or not a number.
    int GetInt(const std::string& key, int defaultValue = 0) const;

    /// Read a numeric field as float. Returns `defaultValue`
    /// if the field is missing or not a number.
    float GetFloat(const std::string& key, float defaultValue = 0.0f) const;

    /// Read a boolean field. Returns `defaultValue` if the field is
    /// missing or not a boolean.
    bool GetBool(const std::string& key, bool defaultValue = false) const;

private:
    Config();

    /// Owned Lua state with the result table at stack index 1.
    lua_State* L = nullptr;
};

} // namespace ConfigReader
