// Friends — the account↔account social graph, and the only store behind
// PLAN-metalstorm-lobby.md §8 ("friends + 'join my friends' war/side' is the
// primary discovery path in a persistent world — people play where their
// friends are").
//
// Task 9a.
//
// ── Directed edges, mutuality DERIVED ──────────────────────────────────────
// One row is one account's claim on another: "I consider you a friend." A
// friendship is the two rows existing; a pending request is one of them. There
// is deliberately **no `state` column**, and that is the design call rather
// than a shortcut:
//
//   * a state column has to be kept consistent across the pair, so `pending`
//     on one row and `accepted` on the other is representable — and whichever
//     reader looks at only one row is then right by accident;
//   * two directed rows cannot disagree with each other, because there is
//     nothing for them to disagree about. `Mutual` is a JOIN, not a value
//     somebody has to remember to write twice.
//
// The consequence worth stating: **accept IS request, in the other
// direction.** There is no separate accept verb, and `POST /api/friends/add`
// on an account that has already added you completes the friendship. That is
// one route instead of two, and — more usefully — the two players' actions are
// literally the same act, so neither can be in a state the other cannot reach.
//
// ── Removal is symmetric ───────────────────────────────────────────────────
// `Remove` deletes BOTH directions. A friendship one side has walked out of is
// not a friendship, and leaving the reverse edge would park the remover in the
// other player's list forever as an unanswered incoming request — an "add me
// back?" prompt generated by the person who just left. See Remove's comment.
//
// ── No denormalised username ───────────────────────────────────────────────
// Edges key on `account_id` only and the username is JOINed from `users` at
// read time. Task 8c's guest upgrade is the path that renames an account, and
// it is exactly what turned `war_player_bindings.username` stale on its first
// live arm; a table added *after* that finding should not re-create it. The
// cost is one join in a query that already touches `users` for the faction.
#pragma once

#include <cstdint>
#include <string>
#include <vector>

struct sqlite3;

/// How the caller and one other account stand, from the CALLER's side. Always
/// evaluated for a specific viewer — `Outgoing` and `Incoming` are the same
/// pair of rows read from opposite ends.
enum class FriendEdge {
    None,      ///< no row in either direction
    Outgoing,  ///< the caller asked; the other account has not asked back
    Incoming,  ///< the other account asked; the caller has not answered
    Mutual,    ///< both rows exist — an actual friendship
};

inline const char* FriendEdgeToString(FriendEdge e) {
    switch (e) {
        case FriendEdge::Outgoing: return "outgoing";
        case FriendEdge::Incoming: return "incoming";
        case FriendEdge::Mutual:   return "mutual";
        case FriendEdge::None:     break;
    }
    return "none";
}

/// One row of a friends list: another account, and how it stands with the
/// viewer. Presence is NOT here — it is decided by FriendPresence.h from
/// facts this table knows nothing about (war bindings, room membership, lobby
/// activity), and mixing the two would make the social graph depend on who
/// happens to be online.
struct FriendListEntry {
    int64_t     accountId = 0;
    std::string username;
    /// `users.faction_id`, empty for a dev/manifest account that has none.
    /// Carried because a friend's faction decides whether "join them" can ever
    /// mean the same side (FriendPresence.h's DecideFriendJoin).
    std::string factionId;
    FriendEdge  edge = FriendEdge::None;
    /// When the *caller's own* edge was created, or 0 when the caller has not
    /// made one (an incoming request the caller has not answered).
    int64_t     since = 0;
};

class Friends {
public:
    /// Create the table if absent. Additive only — the same discipline
    /// WarPlayerBindings::EnsureTable states: this is the only copy of the
    /// graph, so a schema change migrates rather than drops.
    static void EnsureTable(sqlite3* db);

    /// Record "`fromId` considers `toId` a friend". Idempotent — a repeated
    /// add only re-stamps nothing (the original `created_at` is kept, so
    /// "friends since" does not reset when somebody clicks twice).
    ///
    /// Returns false for a self-add or a bad handle; the caller checks that
    /// `toId` exists before calling (the route does, so it can answer 404).
    static bool Add(sqlite3* db, int64_t fromId, int64_t toId, int64_t now);

    /// Delete both directions between two accounts. Returns rows deleted
    /// (0, 1 or 2 — 1 means a request was withdrawn or declined, 2 means a
    /// friendship ended).
    static int Remove(sqlite3* db, int64_t aId, int64_t bId);

    /// How `viewerId` stands with `otherId`.
    static FriendEdge EdgeBetween(sqlite3* db, int64_t viewerId, int64_t otherId);

    /// Every account with an edge in either direction, as `viewerId` sees
    /// them, ordered mutual-first then by username so a list does not reorder
    /// itself as people come and go.
    ///
    /// INNER JOINs `users`: an edge whose other end no longer exists (the
    /// abandoned-guest sweep deletes rows) is invisible here rather than a
    /// blank entry, and PruneOrphans clears it on the maintenance tick.
    static std::vector<FriendListEntry> ListFor(sqlite3* db, int64_t viewerId);

    /// Just the mutual half, as account ids. The war browser's "friends here"
    /// filter reads this: a pending request is not a friend and must not
    /// route anybody anywhere.
    static std::vector<int64_t> MutualIds(sqlite3* db, int64_t viewerId);

    /// Drop every edge touching an account, in both directions. Called when
    /// the account goes away.
    static int DeleteForAccount(sqlite3* db, int64_t accountId);

    /// Drop edges whose either end has no `users` row. The abandoned-guest
    /// sweep (GuestAccounts::PruneAbandoned) deletes accounts without knowing
    /// this table exists, and an edge pointing at a deleted account is
    /// unreachable by ListFor and would otherwise accumulate for the life of
    /// the db — the same reason WarPlayerBindings::DeleteForRoom exists.
    static int PruneOrphans(sqlite3* db);
};
