/**
 * GENERATED by scripts/regen-protocol.sh — do not edit, and do not hand-bump.
 *
 * sha256 of the binary schema (`flatc -b --schema schemas/protocol.fbs`).
 * The client sends its own copy of this string in the Handshake; a mismatch
 * means the two sides were built from different wire schemas, which is the
 * stale-cached-bundle failure CURRENT_PROTOCOL_VERSION was supposed to catch
 * and never did (the integer went unmoved through 15 schema edits).
 *
 * Insensitive to comments and formatting in the .fbs by construction.
 */
#pragma once

namespace Protocol {

constexpr char SCHEMA_HASH[] = "38e45b220812734fab1ead6b2e8f78f16b74bcdcde8aaaaf1f8d23655a25b753";

}  // namespace Protocol
