#!/usr/bin/env bash
#
# Regenerate everything derived from schemas/protocol.fbs.
#
# This is the ONLY supported way to change the wire schema. It replaces the
# two-command recipe that used to live in ARCHITECTURE.md, which was wrong in
# two ways that both shipped: it omitted --gen-object-api on the C++ side (so
# following it produced a header without the *T native-object types the tree
# actually uses), and being two commands a human types, it was simply not run —
# the committed C++ bindings sat 5 days stale behind an fbs edit.
#
# Outputs, all committed:
#   rts/protocol_generated.h              C++ bindings   (flatc --cpp --gen-object-api)
#   client/src/protocol/spring-web/*.ts   TS bindings    (flatc --ts  --gen-object-api)
#   rts/Server/ProtocolSchemaHash.h       sha256 of the binary schema, for C++
#   client/src/protocol/schema-hash.ts    the same hash, for the client
#
# The hash is taken over the *binary* schema (`flatc -b --schema`), not the .fbs
# text, so that it tracks wire-visible structure and nothing else. Verified
# properties of that choice (measured, not assumed):
#   - a comment-only or whitespace-only .fbs edit leaves the hash UNCHANGED
#   - adding a field changes it
#   - it is reproducible across runs and across build dirs
#   - it DOES depend on the schema's file basename (`protocol.fbs`), which is
#     why this script always invokes flatc on that path rather than on a copy
#     under a temporary name.
#
# PLAN-protocol-guard task 1.
set -euo pipefail

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$repo_root"

schema="schemas/protocol.fbs"
[[ -f $schema ]] || { echo "regen-protocol: $schema not found (repo root: $repo_root)" >&2; exit 1; }

# --- locate flatc -----------------------------------------------------------
# flatc is built by the CMake FetchContent step, so it only exists once a build
# dir has been configured. Any configured build dir will do; they all build the
# same pinned FlatBuffers version.
flatc=""
for candidate in build/debug build/release build/prod build/*; do
    if [[ -x $candidate/_deps/flatbuffers-build/flatc ]]; then
        flatc="$candidate/_deps/flatbuffers-build/flatc"
        break
    fi
done
if [[ -z $flatc ]]; then
    cat >&2 <<'EOF'
regen-protocol: no flatc found.

flatc is built by the CMake FetchContent step, so a build dir has to be
configured first. Either of these gives you one:

    cmake -S . -B build/debug   -DCMAKE_BUILD_TYPE=Debug
    cmake -S . -B build/release -DCMAKE_BUILD_TYPE=Release

then re-run scripts/regen-protocol.sh.
EOF
    exit 1
fi
echo "regen-protocol: using $flatc ($("$flatc" --version))"

# --- 1. C++ bindings --------------------------------------------------------
# This is now the ONLY producer of rts/protocol_generated.h — CMake used to
# write a second copy into build/<cfg>/generated/ that no target could see
# (include order elected the committed one), and that dead producer was removed
# with the drift guard in PLAN-protocol-guard task 2. --gen-object-api is
# required: the tree uses the *T native-object types.
"$flatc" --cpp --gen-object-api -o rts/ "$schema"
echo "regen-protocol: wrote rts/protocol_generated.h"

# --- 2. TypeScript bindings -------------------------------------------------
# Writes a file per type under client/src/protocol/spring-web/. It only ever
# overwrites the types this schema declares, so the hand-maintained files
# beside them (protocol.ts, and the ipc-* types generated from a schema this
# repo no longer carries) are left alone. Do not "clean" that directory.
"$flatc" --ts --gen-object-api -o client/src/protocol/ "$schema"
echo "regen-protocol: wrote client/src/protocol/spring-web/"

# --- 3. Schema hash ---------------------------------------------------------
bfbs_dir=$(mktemp -d)
trap 'rm -rf "$bfbs_dir"' EXIT
"$flatc" -b --schema -o "$bfbs_dir" "$schema"

if command -v shasum >/dev/null 2>&1; then
    hash=$(shasum -a 256 "$bfbs_dir/protocol.bfbs" | cut -d' ' -f1)
elif command -v sha256sum >/dev/null 2>&1; then
    hash=$(sha256sum "$bfbs_dir/protocol.bfbs" | cut -d' ' -f1)
else
    echo "regen-protocol: neither shasum nor sha256sum available" >&2
    exit 1
fi
[[ ${#hash} -eq 64 ]] || { echo "regen-protocol: implausible hash '$hash'" >&2; exit 1; }

cat > rts/Server/ProtocolSchemaHash.h <<EOF
/**
 * GENERATED by scripts/regen-protocol.sh — do not edit, and do not hand-bump.
 *
 * sha256 of the binary schema (\`flatc -b --schema schemas/protocol.fbs\`).
 * The client sends its own copy of this string in the Handshake; a mismatch
 * means the two sides were built from different wire schemas, which is the
 * stale-cached-bundle failure CURRENT_PROTOCOL_VERSION was supposed to catch
 * and never did (the integer went unmoved through 15 schema edits).
 *
 * Insensitive to comments and formatting in the .fbs by construction.
 */
#pragma once

namespace Protocol {

constexpr char SCHEMA_HASH[] = "$hash";

}  // namespace Protocol
EOF
echo "regen-protocol: wrote rts/Server/ProtocolSchemaHash.h"

cat > client/src/protocol/schema-hash.ts <<EOF
/**
 * GENERATED by scripts/regen-protocol.sh — do not edit, and do not hand-bump.
 *
 * sha256 of the binary schema (\`flatc -b --schema schemas/protocol.fbs\`),
 * sent in the Handshake and compared for equality by the game server. See
 * rts/Server/ProtocolSchemaHash.h for the other half.
 */
export const SCHEMA_HASH = '$hash';
EOF
echo "regen-protocol: wrote client/src/protocol/schema-hash.ts"

echo "regen-protocol: schema hash $hash"
echo "regen-protocol: done — commit every file above together."
