-- scenarios/gen_synth_flat_wq1v.lua — GENERATED by tools/mapgen/scenariogen.py
-- map=synth_flat seed=11 generator-version=2
--
-- Do not hand-edit: regenerate with
--   tools/mapgen/scenariogen.py data/maps/synth_flat --seed 11
-- Generation is deterministic, so the same map and seed reproduce
-- this file byte for byte.
--
-- This file must stay a PURE Lua table literal. ScenarioDiscovery
-- parses it with a bare lua_State — the lobby binary has no VFS, no
-- Spring.* and no sim globals — so a `require` or a computed global at
-- file scope does not fail loudly, it makes the scenario silently
-- vanish from the lobby's list (ScenarioDiscovery.h:33-37).
--
-- Verified at generation time against synth_flat's own
-- heightmap: both landing zones and the victory region are mutually
-- reachable on the passability mask for HEAVY, INFANTRY, VEH — every movement class this roster
-- stages, not just the default VEH.

return {
    version   = 1,
    name      = 'Cell 2 3 — Redoubt',
    tutorial  = false,
    ephemeral = true,           -- a generated one-off, not a persistent war

    world = {
        map     = 'synth_flat',
        -- Each side opens owning its own landing zone; everything else,
        -- the victory region included, starts uncontrolled.
        regions = {
            { key = 'r0_0', team = 0 },
            { key = 'r3_3', team = 1 },
        },

        -- PLACED HISTORY (PLAN-metalstorm-model-integration §M3/§M4).
        -- Features, not units: the loader calls Spring.CreateFeature for
        -- these and stages them BEFORE units, so a wreck owns its squares
        -- before anything is put down near it.
        --
        -- A `name` here is published at GameStart as
        -- landmark_<name>_x/_z, which is how the command language
        -- addresses it ("hold the crossing").
        features = {

            -- ANCIENT-TECH RELICS. Placed history a faction is squatting
            -- on (the guardian bands are in `units` below). They block
            -- and they do NOT animate: FeatureRenderer thin-instances one
            -- mesh per def, so the spire's authored ring orbit goes
            -- unplayed — recorded in the def's static_clip_unplayed.
            { def = 'ms_monolith_spire', x = 13, z = 604, name = 'Cell 0 2 Spire' },

            -- THE WRECK FIELD, on the ground the war is about. These
            -- BLOCK (features/wrecks.lua), so the generator stamps every
            -- one into the passability mask and re-runs the reachability
            -- gate: a field that walls off the crossing it decorates is
            -- the Meridian defect re-created out of scenery.
            { def = 'ms_tank_wreck', x = 919, z = 914, facing = 'east' },
            { def = 'ms_tank_wreck', x = 516, z = 1318, facing = 'east' },
            { def = 'ms_train_wreck', x = 643, z = 1415, facing = 'south' },
            { def = 'ms_tank_wreck', x = 432, z = 1372, facing = 'north' },
            { def = 'ms_train_wreck', x = 967, z = 1398, facing = 'south' },
        },
    },

    -- One team per playable side, numbered consecutively from 0 so the
    -- engine materialises no unoccupied gap teams between them. Every
    -- side below is staged an army in `units`, which is what makes
    -- ScenarioDiscovery resolve it with staged == true — a side with no
    -- army is a room slot that starts with nothing (endtoend D19).
    sides = {
        { faction = 'compact', team = 0 },
        { faction = 'union', team = 1 },
        -- Team 2 is an NPC faction holding the fortified
        -- clusters (see `ai` below). Every non-Gaia team is its own
        -- ally team, so it is hostile to every player with no extra
        -- configuration.
        { faction = 'marauders', team = 2 },
    },

    -- The NPC faction squatting on the fortified ground. Like `sides`,
    -- this declares what the brain should WANT; the launch decides
    -- whether an AI is actually there. Without an --ai slot the loader
    -- warns and these units idle — declared but never silently
    -- half-alive. `kinds` must come from game_scenario.lua's
    -- AI_SLATE_KINDS: an unknown kind is a hard validation error.
    ai = {
        {
            team    = 2,
            profile = 'npc_raider',
            slate   = {
                kinds   = { 'garrison', 'raid' },
                home    = 'r2_1',
                targets = { 'r1_3', 'r2_2' },
                reach   = 2,
            },
            -- Deliberately meagre: an NPC has no objective income, so
            -- without a stipend it spends its opening grant and is
            -- permanently broke; with a large one it stops being flavour.
            stipend = { amount = 35, periodSec = 60 },
        },
    },

    units = {
        -- Pre-deployed armies. `count`/`spacing` use the loader's own grid
        -- spread (game_scenario.lua gridOffsets), which is also the shape
        -- its count-weighted centroid check understands.
        --
        -- Every mobile entry carries an opening FIGHT toward the victory
        -- region: a staged force with no orders sits on its spawn tile
        -- forever and cannot contest anything (war_units_unordered).
        -- side 0 — landing zone r0_0
        { def = 'ms_tanks_s2', team = 0, x = -262, z = 128, facing = 'south', count = 4, spacing = 150,
          orders = { { cmd = 'FIGHT', params = { 640, 0, 896 } } } },
        { def = 'ms_tanks_s3', team = 0, x = 311, z = 311, facing = 'south', count = 2, spacing = 180,
          orders = { { cmd = 'FIGHT', params = { 640, 0, 896 } } } },
        { def = 'ms_soldiers_s1', team = 0, x = -209, z = -66, facing = 'south', count = 6, spacing = 100,
          orders = { { cmd = 'FIGHT', params = { 640, 0, 896 } } } },
        { def = 'ms_artillery_s2', team = 0, x = 27, z = -248, facing = 'south', count = 2, spacing = 160,
          orders = { { cmd = 'FIGHT', params = { 640, 0, 896 } } } },
        { def = 'ms_engineers_s1', team = 0, x = 322, z = -209, facing = 'south', count = 2, spacing = 120,
          orders = { { cmd = 'FIGHT', params = { 640, 0, 896 } } } },
        { def = 'ms_scout_buggy', team = 0, x = 403, z = -147, facing = 'south', count = 2, spacing = 130,
          orders = { { cmd = 'FIGHT', params = { 640, 0, 896 } } } },
        { def = 'ms_supply_truck', team = 0, x = 127, z = -132, facing = 'south', count = 2, spacing = 140,
          orders = { { cmd = 'FIGHT', params = { 640, 0, 896 } } } },
        { def = 'ms_radar_s1', team = 0, x = 311, z = -55, facing = 'south' },
        -- side 1 — landing zone r3_3
        { def = 'ms_tanks_s2', team = 1, x = 1156, z = 896, facing = 'south', count = 4, spacing = 150,
          orders = { { cmd = 'FIGHT', params = { 640, 0, 896 } } } },
        { def = 'ms_tanks_s3', team = 1, x = 1171, z = 1171, facing = 'south', count = 2, spacing = 180,
          orders = { { cmd = 'FIGHT', params = { 640, 0, 896 } } } },
        { def = 'ms_soldiers_s1', team = 1, x = 896, z = 1156, facing = 'south', count = 6, spacing = 100,
          orders = { { cmd = 'FIGHT', params = { 640, 0, 896 } } } },
        { def = 'ms_artillery_s2', team = 1, x = 1272, z = 795, facing = 'south', count = 2, spacing = 160,
          orders = { { cmd = 'FIGHT', params = { 640, 0, 896 } } } },
        { def = 'ms_engineers_s1', team = 1, x = 896, z = 1286, facing = 'south', count = 2, spacing = 120,
          orders = { { cmd = 'FIGHT', params = { 640, 0, 896 } } } },
        { def = 'ms_scout_buggy', team = 1, x = 1263, z = 528, facing = 'south', count = 2, spacing = 130,
          orders = { { cmd = 'FIGHT', params = { 640, 0, 896 } } } },
        { def = 'ms_supply_truck', team = 1, x = 1346, z = 635, facing = 'south', count = 2, spacing = 140,
          orders = { { cmd = 'FIGHT', params = { 640, 0, 896 } } } },
        { def = 'ms_radar_s1', team = 1, x = 1079, z = 712, facing = 'south' },

        -- Existing settlement and NPC garrisons. `team = 'neutral'`
        -- resolves to the Gaia team at stage time: the Gaia id is
        -- playerTeamCount, which depends on the roster and so is NOT
        -- knowable when this file is written. These are staged through
        -- `units` rather than the `civilians` block on purpose — that
        -- block registers everything role='ambient', and routines.tick
        -- then issues CMD_MOVE at every ambient entry every tick, which
        -- would enroll immobile buildings in a move loop they can never
        -- satisfy.
        -- Forward Base: Cell 1 3 (r1_3) — hostile team 2
        { def = 'ms_command_nexus', team = 2, x = 384, z = 896, facing = 'south' },
        { def = 'ms_tanks_s2', team = 2, x = 592, z = 786, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 384, 0, 896 } } } },
        { def = 'ms_tanks_s2', team = 2, x = 355, z = 1130, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 384, 0, 896 } } } },
        { def = 'ms_tanks_s2', team = 2, x = 151, z = 935, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 384, 0, 896 } } } },
        { def = 'ms_soldiers_s2', team = 2, x = 478, z = 680, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 384, 0, 896 } } } },
        { def = 'ms_supply_truck', team = 2, x = 468, z = 1115, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 384, 0, 896 } } } },
        { def = 'ms_supply_truck', team = 2, x = 210, z = 736, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 384, 0, 896 } } } },
        { def = 'ms_command_s2', team = 2, x = 545, z = 1067, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 384, 0, 896 } } } },
        -- Outpost: Cell 2 2 (r2_2) — hostile team 2
        { def = 'ms_garrison', team = 2, x = 640, z = 640, facing = 'south' },
        { def = 'ms_soldiers_s1', team = 2, x = 825, z = 535, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 640, 0, 640 } } } },
        { def = 'ms_soldiers_s1', team = 2, x = 709, z = 438, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 640, 0, 640 } } } },
        { def = 'ms_technical', team = 2, x = 642, z = 853, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 640, 0, 640 } } } },
        -- Outpost: Cell 2 1 (r2_1) — hostile team 2
        { def = 'ms_garrison', team = 2, x = 606, z = 320, facing = 'south' },
        { def = 'ms_staticdefense_s2', team = 2, x = 603, z = 472, facing = 'south' },
        { def = 'ms_soldiers_s1', team = 2, x = 662, z = 172, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 640, 0, 384 } } } },
        { def = 'ms_soldiers_s1', team = 2, x = 814, z = 261, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 640, 0, 384 } } } },
        { def = 'ms_technical', team = 2, x = 511, z = 554, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 640, 0, 384 } } } },
        { def = 'ms_technical', team = 2, x = 426, z = 383, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 640, 0, 384 } } } },
        { def = 'ms_artillery_s2', team = 2, x = 852, z = 366, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 640, 0, 384 } } } },
        -- Township: Cell 3 2 (r3_2) — neutral (Gaia)
        { def = 'ms_habitat', team = 'neutral', x = 889, z = 711, facing = 'south' },
        { def = 'ms_civilians', team = 'neutral', x = 1127, z = 594, facing = 'south' },
        { def = 'ms_civilians', team = 'neutral', x = 761, z = 833, facing = 'south' },
        { def = 'ms_civilians', team = 'neutral', x = 1074, z = 485, facing = 'south' },
        -- Township: Cell 0 3 (r0_3) — neutral (Gaia)
        { def = 'ms_depot', team = 'neutral', x = 9, z = 875, facing = 'south' },
        { def = 'ms_staticdefense_s1', team = 'neutral', x = 160, z = 860, facing = 'south' },
        { def = 'ms_civilians', team = 'neutral', x = 149, z = 1108, facing = 'south' },
        { def = 'ms_militia', team = 'neutral', x = 77, z = 689, facing = 'south' },
        { def = 'ms_militia', team = 'neutral', x = 193, z = 620, facing = 'south' },
        -- Township: Cell 3 1 (r3_1) — neutral (Gaia)
        { def = 'ms_depot', team = 'neutral', x = 1009, z = 346, facing = 'south' },
        { def = 'ms_civilians', team = 'neutral', x = 1007, z = 565, facing = 'south' },
        { def = 'ms_civilians', team = 'neutral', x = 860, z = 173, facing = 'south' },
        { def = 'ms_civilians', team = 'neutral', x = 1146, z = 251, facing = 'south' },
        { def = 'ms_militia', team = 'neutral', x = 751, z = 226, facing = 'south' },
        -- Extraction Site: Cell 1 2 (r1_2) — neutral (Gaia)
        { def = 'ms_depot', team = 'neutral', x = 348, z = 577, facing = 'south' },
        { def = 'ms_civilians', team = 'neutral', x = 249, z = 390, facing = 'south' },
        { def = 'ms_civilians', team = 'neutral', x = 109, z = 571, facing = 'south' },
        { def = 'ms_militia', team = 'neutral', x = 138, z = 498, facing = 'south' },
        { def = 'ms_supply_truck', team = 'neutral', x = 495, z = 458, facing = 'south' },

        -- NAMED RESOURCE SITES (§M4, worldbuilding decision 1). One
        -- capturable structure each, on Gaia, named after the region it
        -- stands in — which is the name a player has already seen on the
        -- overlay, and the name the loader publishes as
        -- landmark_<name>_x/_z for the command language to resolve.
        --
        -- They pay NOTHING: income in Metalstorm is Authority
        -- (worldbuilding decision 3), so a site is worth holding because
        -- it anchors an objective and because it is somewhere the story
        -- can point at, not because it produces.
        -- Cell 0 1 Grain Silo (r0_1)
        { def = 'ms_grain_silo', team = 'neutral', x = 81, z = 328, facing = 'south', name = 'Cell 0 1 Grain Silo' },
        -- Cell 2 0 Metal Pit (r2_0)
        { def = 'ms_metal_pit', team = 'neutral', x = 592, z = 73, facing = 'south', name = 'Cell 2 0 Metal Pit' },
        -- Cell 1 1 Oil Derrick (r1_1)
        { def = 'ms_oil_derrick', team = 'neutral', x = 330, z = 304, facing = 'south', name = 'Cell 1 1 Oil Derrick' },

        -- ANCIENT-TECH GUARDIANS (§M4, worldbuilding directive 4). The
        -- relic itself is a FEATURE (see world.features above); what can
        -- be fought is the band squatting on it. Anarchic archetype —
        -- gun trucks and militia, not line armour.
        -- guarding Cell 0 2 Spire (r0_2)
        { def = 'ms_technical', team = 2, x = -111, z = 733, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 13, 0, 604 } } } },
        { def = 'ms_technical', team = 2, x = -100, z = 464, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 13, 0, 604 } } } },
        { def = 'ms_militia', team = 2, x = 107, z = 756, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 13, 0, 604 } } } },
    },

    objectives = {
        -- THE VICTORY OBJECTIVE. `victory = true` is the only terminal
        -- condition game_gameover.lua watches, and ScenarioDiscovery's
        -- DefaultForMap refuses a scenario without one. Exactly one.
        --
        -- Open race (forTeam nil) so either side may take it, and so it
        -- cannot be scoped to a team the launch did not supply — an
        -- objective on a missing team throws "Bad teamID" out of the
        -- Objectives gadget's callin, gadgetHandler removes the gadget,
        -- and the victory objective can then never progress at all.
        --
        -- notBefore + holdFrames = 5400 frames, against a
        -- worst-case approach of 949 frames for the
        -- slowest staged side. The x1.5 margin is because that estimate
        -- is straight-line and so understates real travel time; matching
        -- it exactly would pass the loader's check and still let the war
        -- be decided before the two armies ever meet.
        { type = 'control', scope = 'strategic', forTeam = nil,
          region = 'r2_3', reward = 300,
          victory = true,
          notBefore = 0, holdFrames = 5400,
          expiresAtFrame = nil },

        -- Tactical prizes on the occupied ground: settlements, the named
        -- resource sites, and the ancient-tech caches. Open race for the
        -- same reason as above; no expiry.
        --
        -- A resource site pays NO income (worldbuilding decision 3), so
        -- its objective is the entire mechanical reason to take it — the
        -- silo is worth holding because the region it stands in scores.
        { type = 'control', scope = 'tactical', forTeam = nil, region = 'r0_1', reward = 130, expiresAtFrame = nil },  -- Cell 0 1 Grain Silo
        { type = 'control', scope = 'tactical', forTeam = nil, region = 'r0_2', reward = 200, expiresAtFrame = nil },  -- Cell 0 2 Spire
        { type = 'control', scope = 'tactical', forTeam = nil, region = 'r0_3', reward = 110, expiresAtFrame = nil },  -- Township
        { type = 'control', scope = 'tactical', forTeam = nil, region = 'r1_1', reward = 130, expiresAtFrame = nil },  -- Cell 1 1 Oil Derrick
        { type = 'control', scope = 'tactical', forTeam = nil, region = 'r1_2', reward = 110, expiresAtFrame = nil },  -- Extraction Site
        { type = 'control', scope = 'tactical', forTeam = nil, region = 'r1_3', reward = 110, expiresAtFrame = nil },  -- Forward Base
        { type = 'control', scope = 'tactical', forTeam = nil, region = 'r2_0', reward = 130, expiresAtFrame = nil },  -- Cell 2 0 Metal Pit
        { type = 'control', scope = 'tactical', forTeam = nil, region = 'r2_1', reward = 110, expiresAtFrame = nil },  -- Outpost
        { type = 'control', scope = 'tactical', forTeam = nil, region = 'r2_2', reward = 110, expiresAtFrame = nil },  -- Outpost
        { type = 'control', scope = 'tactical', forTeam = nil, region = 'r3_1', reward = 110, expiresAtFrame = nil },  -- Township
        { type = 'control', scope = 'tactical', forTeam = nil, region = 'r3_2', reward = 110, expiresAtFrame = nil },  -- Township
    },
}
