-- scenarios/gen_synth_wide_ug1b.lua — GENERATED by tools/mapgen/scenariogen.py
-- map=synth_wide seed=11 generator-version=6
--
-- Do not hand-edit: regenerate with
--   tools/mapgen/scenariogen.py data/maps/synth_wide --seed 11
-- Generation is deterministic, so the same map and seed reproduce
-- this file byte for byte.
--
-- This file must stay a PURE Lua table literal. ScenarioDiscovery
-- parses it with a bare lua_State — the lobby binary has no VFS, no
-- Spring.* and no sim globals — so a `require` or a computed global at
-- file scope does not fail loudly, it makes the scenario silently
-- vanish from the lobby's list (ScenarioDiscovery.h:33-37).
--
-- Verified at generation time against synth_wide's own
-- heightmap: both landing zones and the victory region are mutually
-- reachable on the passability mask for HEAVY, INFANTRY, VEH — every movement class this roster
-- stages, not just the default VEH.

return {
    version   = 1,
    name      = 'Cell 1 2 — Redoubt',
    tutorial  = false,
    ephemeral = true,           -- a generated one-off, not a persistent war

    world = {
        map     = 'synth_wide',
        -- Each side opens owning its own landing zone; everything else,
        -- the victory region included, starts uncontrolled.
        regions = {
            { key = 'r0_0', team = 0 },
            { key = 'r2_2', team = 1 },

            -- A region with a town in it is NAMED AFTER THE TOWN, and its
            -- published centre moves to the town's centre. `name` is
            -- game_regions.lua's `region_<key>_name` rulesParam — the path
            -- the client's named-entity index reads to build the command
            -- composer's Target picker, so this is what makes a town
            -- addressable by name in a typed or spoken order, and what a
            -- parley proposal's `terms.regionKey` resolves to.
            --
            -- One place, one name, one key. A region is kilometres of
            -- ground and the town is the only part of it a player can
            -- point at: leaving the region's own name in place would give
            -- that ground two names, and leaving its centroid in place
            -- would send "attack <town>" to a spot out in the fields.
            -- `team` is deliberately absent — naming a place says nothing
            -- about who holds it, and the tactical objective on this same
            -- region below is what makes that a question.
            { key = 'r0_2', name = 'Vesper Watch', x = 1189, z = 2905 },
        },

        -- PLACED HISTORY (PLAN-metalstorm-model-integration §M3/§M4).
        -- Features, not units: the loader calls Spring.CreateFeature for
        -- these and stages them BEFORE units, so a wreck owns its squares
        -- before anything is put down near it.
        --
        -- A `name` here is published at GameStart as
        -- landmark_<name>_x/_z, which is how the command language
        -- addresses it ("hold the crossing").
        features = {

            -- ANCIENT-TECH RELICS. Placed history a faction is squatting
            -- on (the guardian bands are in `units` below). They block
            -- and they do NOT animate: FeatureRenderer thin-instances one
            -- mesh per def, so the spire's authored ring orbit goes
            -- unplayed — recorded in the def's static_clip_unplayed.
            { def = 'ms_monolith_spire', x = 505, z = 2175, name = 'Cell 0 1 Spire' },

            -- THE WRECK FIELD, on the ground the war is about. These
            -- BLOCK (features/wrecks.lua), so the generator stamps every
            -- one into the passability mask and re-runs the reachability
            -- gate: a field that walls off the crossing it decorates is
            -- the Meridian defect re-created out of scenery.
            { def = 'ms_tank_wreck', x = 2066, z = 3212, facing = 'south' },
            { def = 'ms_train_wreck', x = 1889, z = 3535, facing = 'east' },
            { def = 'ms_colossus_wreck', x = 1953, z = 3235, facing = 'east', name = 'Cell 1 2 Hulk' },
            { def = 'ms_tank_wreck', x = 2219, z = 3310, facing = 'east' },
            { def = 'ms_train_wreck', x = 2261, z = 3692, facing = 'south' },
        },
    },

    -- ======================================================================
    -- TOWNS (town-planner T4). Street-and-lot settlements planned on this
    -- map's own heightmap rather than scattered on rings: streets, lots
    -- with frontage, a wall where the town built one, and the people who
    -- live there. A town's buildings are in `units` and its population is
    -- in `civilians` — two different wires, on purpose (see both blocks).
    --
    -- This block is what makes a town a PLACE the rest of the game can
    -- reason about: game_scenario.lua hands it to GG.Towns, which
    -- publishes each town's statics, binds its civilians into a district
    -- the estate can count, and resolves `hall` to the live unit that is
    -- this town's PARLEY VENUE. `key` is the region key, so a town needs
    -- no second namespace: it is addressed exactly as its region is.
    towns = {
        -- Vesper Watch: grid_quarter, stockade, 11 lot(s), 6 gateway(s), 16 civilian entr(y/ies)
        {
            key       = 'r0_2',
            name      = 'Vesper Watch',
            region    = 'r0_2',
            x = 1189, z = 2905, radius = 760,
            archetype = 'grid_quarter', defense = 'stockade',
            -- The meeting hall: exactly one per town, and the venue a
            -- parley addressed to the civilian estate about this
            -- district is held at. GG.Towns resolves it to a live
            -- unitID by looking for this def at this position once the
            -- units below are staged; destroy it and the estate has
            -- nowhere left to negotiate about this town.
            hall = { def = 'ms_meeting_hall', x = 1351, z = 2746 },
        },
    },

    -- One team per playable side, numbered consecutively from 0 so the
    -- engine materialises no unoccupied gap teams between them. Every
    -- side below is staged an army in `units`, which is what makes
    -- ScenarioDiscovery resolve it with staged == true — a side with no
    -- army is a room slot that starts with nothing (endtoend D19).
    sides = {
        { faction = 'compact', team = 0 },
        { faction = 'union', team = 1 },
        -- Team 2 is an NPC faction holding the fortified
        -- clusters (see `ai` below). Every non-Gaia team is its own
        -- ally team, so it is hostile to every player with no extra
        -- configuration.
        { faction = 'marauders', team = 2 },
    },

    -- The NPC faction squatting on the fortified ground. Like `sides`,
    -- this declares what the brain should WANT; the launch decides
    -- whether an AI is actually there. Without an --ai slot the loader
    -- warns and these units idle — declared but never silently
    -- half-alive. `kinds` must come from game_scenario.lua's
    -- AI_SLATE_KINDS: an unknown kind is a hard validation error.
    ai = {
        {
            team    = 2,
            profile = 'npc_raider',
            slate   = {
                kinds   = { 'garrison', 'raid' },
                home    = 'r2_0',
                targets = { 'r0_1', 'r1_0' },
                reach   = 2,
            },
            -- Deliberately meagre: an NPC has no objective income, so
            -- without a stipend it spends its opening grant and is
            -- permanently broke; with a large one it stops being flavour.
            stipend = { amount = 35, periodSec = 60 },
        },
    },

    units = {
        -- Pre-deployed armies. `count`/`spacing` use the loader's own grid
        -- spread (game_scenario.lua gridOffsets), which is also the shape
        -- its count-weighted centroid check understands.
        --
        -- Every mobile entry carries an opening FIGHT toward the victory
        -- region: a staged force with no orders sits on its spawn tile
        -- forever and cannot contest anything (war_units_unordered).
        -- side 0 — landing zone r0_0
        { def = 'ms_tanks_s2', team = 0, x = 942, z = 682, facing = 'south', count = 4, spacing = 150,
          orders = { { cmd = 'FIGHT', params = { 2047, 0, 3412 } } } },
        { def = 'ms_tanks_s3', team = 0, x = 957, z = 957, facing = 'south', count = 2, spacing = 180,
          orders = { { cmd = 'FIGHT', params = { 2047, 0, 3412 } } } },
        { def = 'ms_soldiers_s1', team = 0, x = 682, z = 942, facing = 'south', count = 6, spacing = 100,
          orders = { { cmd = 'FIGHT', params = { 2047, 0, 3412 } } } },
        { def = 'ms_artillery_s2', team = 0, x = 406, z = 957, facing = 'south', count = 2, spacing = 160,
          orders = { { cmd = 'FIGHT', params = { 2047, 0, 3412 } } } },
        { def = 'ms_engineers_s1', team = 0, x = 422, z = 682, facing = 'south', count = 2, spacing = 120,
          orders = { { cmd = 'FIGHT', params = { 2047, 0, 3412 } } } },
        { def = 'ms_scout_buggy', team = 0, x = 498, z = 498, facing = 'south', count = 2, spacing = 130,
          orders = { { cmd = 'FIGHT', params = { 2047, 0, 3412 } } } },
        { def = 'ms_supply_truck', team = 0, x = 682, z = 422, facing = 'south', count = 2, spacing = 140,
          orders = { { cmd = 'FIGHT', params = { 2047, 0, 3412 } } } },
        { def = 'ms_radar_s1', team = 0, x = 865, z = 498, facing = 'south' },
        -- side 1 — landing zone r2_2
        { def = 'ms_tanks_s2', team = 1, x = 3672, z = 3412, facing = 'south', count = 4, spacing = 150,
          orders = { { cmd = 'FIGHT', params = { 2047, 0, 3412 } } } },
        { def = 'ms_tanks_s3', team = 1, x = 3687, z = 3687, facing = 'south', count = 2, spacing = 180,
          orders = { { cmd = 'FIGHT', params = { 2047, 0, 3412 } } } },
        { def = 'ms_soldiers_s1', team = 1, x = 3412, z = 3672, facing = 'south', count = 6, spacing = 100,
          orders = { { cmd = 'FIGHT', params = { 2047, 0, 3412 } } } },
        { def = 'ms_artillery_s2', team = 1, x = 3136, z = 3687, facing = 'south', count = 2, spacing = 160,
          orders = { { cmd = 'FIGHT', params = { 2047, 0, 3412 } } } },
        { def = 'ms_engineers_s1', team = 1, x = 3152, z = 3412, facing = 'south', count = 2, spacing = 120,
          orders = { { cmd = 'FIGHT', params = { 2047, 0, 3412 } } } },
        { def = 'ms_scout_buggy', team = 1, x = 3228, z = 3228, facing = 'south', count = 2, spacing = 130,
          orders = { { cmd = 'FIGHT', params = { 2047, 0, 3412 } } } },
        { def = 'ms_supply_truck', team = 1, x = 3412, z = 3152, facing = 'south', count = 2, spacing = 140,
          orders = { { cmd = 'FIGHT', params = { 2047, 0, 3412 } } } },
        { def = 'ms_radar_s1', team = 1, x = 3595, z = 3228, facing = 'south' },

        -- Existing settlement and NPC garrisons. `team = 'neutral'`
        -- resolves to the Gaia team at stage time: the Gaia id is
        -- playerTeamCount, which depends on the roster and so is NOT
        -- knowable when this file is written. These are staged through
        -- `units` rather than the `civilians` block on purpose — that
        -- block registers everything role='ambient', and routines.tick
        -- then issues CMD_MOVE at every ambient entry every tick, which
        -- would enroll immobile buildings in a move loop they can never
        -- satisfy.
        -- Vesper Watch (r0_2) — neutral (Gaia). A PLANNED town: 11 building(s)
        -- on 6 street(s), stockade defense. `facing` is load-bearing here and not
        -- decoration: a town's buildings FRONT THEIR STREET, which is
        -- what makes a row read as a row, and the engine derives the
        -- blocked footprint from it by swapping the sizes.
        { def = 'ms_meeting_hall', team = 'neutral', x = 1351, z = 2746, facing = 'west' },
        { def = 'ms_market_stalls', team = 'neutral', x = 1270, z = 3158, facing = 'west' },
        { def = 'ms_watchtower', team = 'neutral', x = 1757, z = 2672, facing = 'east' },
        { def = 'ms_water_works', team = 'neutral', x = 690, z = 3137, facing = 'west' },
        { def = 'ms_shanty_block', team = 'neutral', x = 1096, z = 2502, facing = 'east' },
        { def = 'ms_shanty_block', team = 'neutral', x = 1385, z = 2537, facing = 'west' },
        { def = 'ms_shanty_block', team = 'neutral', x = 1016, z = 3126, facing = 'east' },
        { def = 'ms_shanty_block', team = 'neutral', x = 990, z = 3335, facing = 'east' },
        { def = 'ms_shanty_block', team = 'neutral', x = 767, z = 2515, facing = 'west' },
        { def = 'ms_shanty_block', team = 'neutral', x = 1435, z = 3431, facing = 'south' },
        { def = 'ms_shanty_block', team = 'neutral', x = 975, z = 2732, facing = 'south' },
        { def = 'ms_barricade_set', team = 'neutral', x = 496, z = 3361, facing = 'south' },
        { def = 'ms_barricade_set', team = 'neutral', x = 539, z = 2559, facing = 'west' },
        { def = 'ms_barricade_set', team = 'neutral', x = 594, z = 2306, facing = 'north' },
        { def = 'ms_barricade_set', team = 'neutral', x = 1929, z = 2521, facing = 'east' },
        { def = 'ms_barricade_set', team = 'neutral', x = 1911, z = 2778, facing = 'east' },
        { def = 'ms_barricade_set', team = 'neutral', x = 1590, z = 3659, facing = 'south' },
        { def = 'ms_barricade_set', team = 'neutral', x = 782, z = 3557, facing = 'south' },
        { def = 'ms_barricade_set', team = 'neutral', x = 1800, z = 2444, facing = 'north' },
        { def = 'ms_barricade_set', team = 'neutral', x = 1664, z = 3454, facing = 'east' },
        -- Township: Cell 2 1 (r2_1) — neutral (Gaia)
        { def = 'ms_habitat', team = 'neutral', x = 3412, z = 2047, facing = 'south' },
        { def = 'ms_depot', team = 'neutral', x = 3311, z = 2278, facing = 'south' },
        { def = 'ms_staticdefense_s1', team = 'neutral', x = 3568, z = 2108, facing = 'south' },
        { def = 'ms_civilians', team = 'neutral', x = 3515, z = 2258, facing = 'south' },
        { def = 'ms_civilians', team = 'neutral', x = 3192, z = 1961, facing = 'south' },
        { def = 'ms_civilians', team = 'neutral', x = 3188, z = 2123, facing = 'south' },
        -- Township: Cell 1 1 (r1_1) — neutral (Gaia)
        { def = 'ms_habitat', team = 'neutral', x = 2047, z = 2047, facing = 'south' },
        { def = 'ms_habitat', team = 'neutral', x = 2129, z = 2284, facing = 'south' },
        { def = 'ms_depot', team = 'neutral', x = 1829, z = 1919, facing = 'south' },
        { def = 'ms_habitat', team = 'neutral', x = 1812, z = 2138, facing = 'south' },
        { def = 'ms_civilians', team = 'neutral', x = 2047, z = 1811, facing = 'south' },
        { def = 'ms_civilians', team = 'neutral', x = 2278, z = 2090, facing = 'south' },
        { def = 'ms_civilians', team = 'neutral', x = 1971, z = 1823, facing = 'south' },
        { def = 'ms_militia', team = 'neutral', x = 2253, z = 1934, facing = 'south' },
        -- Forward Base: Cell 2 0 (r2_0) — hostile team 2
        { def = 'ms_command_nexus', team = 2, x = 3412, z = 682, facing = 'south' },
        { def = 'ms_garrison', team = 2, x = 3204, z = 748, facing = 'south' },
        { def = 'ms_staticdefense_s3', team = 2, x = 3620, z = 745, facing = 'south' },
        { def = 'ms_staticdefense_s3', team = 2, x = 3611, z = 592, facing = 'south' },
        { def = 'ms_foundry', team = 2, x = 3357, z = 358, facing = 'south' },
        { def = 'ms_tanks_s2', team = 2, x = 3673, z = 838, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 3412, 0, 682 } } } },
        { def = 'ms_tanks_s2', team = 2, x = 3466, z = 981, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 3412, 0, 682 } } } },
        { def = 'ms_tanks_s2', team = 2, x = 3335, z = 977, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 3412, 0, 682 } } } },
        { def = 'ms_soldiers_s2', team = 2, x = 3128, z = 569, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 3412, 0, 682 } } } },
        { def = 'ms_soldiers_s2', team = 2, x = 3659, z = 503, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 3412, 0, 682 } } } },
        { def = 'ms_soldiers_s2', team = 2, x = 3592, z = 436, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 3412, 0, 682 } } } },
        { def = 'ms_supply_truck', team = 2, x = 3711, z = 623, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 3412, 0, 682 } } } },
        { def = 'ms_supply_truck', team = 2, x = 3744, z = 508, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 3412, 0, 682 } } } },
        -- Outpost: Cell 1 0 (r1_0) — hostile team 2
        { def = 'ms_garrison', team = 2, x = 2047, z = 682, facing = 'south' },
        { def = 'ms_staticdefense_s2', team = 2, x = 1897, z = 654, facing = 'south' },
        { def = 'ms_garrison', team = 2, x = 2058, z = 454, facing = 'south' },
        { def = 'ms_staticdefense_s2', team = 2, x = 2198, z = 694, facing = 'south' },
        { def = 'ms_soldiers_s1', team = 2, x = 2136, z = 875, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 2047, 0, 682 } } } },
        { def = 'ms_soldiers_s1', team = 2, x = 1842, z = 742, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 2047, 0, 682 } } } },
        { def = 'ms_soldiers_s1', team = 2, x = 1870, z = 801, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 2047, 0, 682 } } } },
        { def = 'ms_technical', team = 2, x = 2213, z = 549, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 2047, 0, 682 } } } },
        { def = 'ms_scout_buggy', team = 2, x = 1900, z = 527, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 2047, 0, 682 } } } },
        -- Outpost: Cell 0 1 (r0_1) — hostile team 2
        { def = 'ms_garrison', team = 2, x = 682, z = 2047, facing = 'south' },
        { def = 'ms_staticdefense_s2', team = 2, x = 533, z = 2015, facing = 'south' },
        { def = 'ms_staticdefense_s2', team = 2, x = 690, z = 1895, facing = 'south' },
        { def = 'ms_depot', team = 2, x = 892, z = 1959, facing = 'south' },
        { def = 'ms_soldiers_s1', team = 2, x = 473, z = 2089, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 682, 0, 2047 } } } },
        { def = 'ms_soldiers_s1', team = 2, x = 768, z = 1852, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 682, 0, 2047 } } } },
        { def = 'ms_soldiers_s1', team = 2, x = 512, z = 1917, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 682, 0, 2047 } } } },
        { def = 'ms_technical', team = 2, x = 743, z = 2251, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 682, 0, 2047 } } } },
        { def = 'ms_artillery_s2', team = 2, x = 833, z = 2197, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 682, 0, 2047 } } } },

        -- NAMED RESOURCE SITES (§M4, worldbuilding decision 1). One
        -- capturable structure each, on Gaia, named after the region it
        -- stands in — which is the name a player has already seen on the
        -- overlay, and the name the loader publishes as
        -- landmark_<name>_x/_z for the command language to resolve.
        --
        -- They pay NOTHING: income in Metalstorm is Authority
        -- (worldbuilding decision 3), so a site is worth holding because
        -- it anchors an objective and because it is somewhere the story
        -- can point at, not because it produces.
        -- Cell 0 2 Grain Silo (r0_2)
        { def = 'ms_grain_silo', team = 'neutral', x = 767, z = 3343, facing = 'south', name = 'Cell 0 2 Grain Silo' },
        -- Cell 1 1 Metal Pit (r1_1)
        { def = 'ms_metal_pit', team = 'neutral', x = 2162, z = 1861, facing = 'south', name = 'Cell 1 1 Metal Pit' },
        -- Cell 2 1 Oil Derrick (r2_1)
        { def = 'ms_oil_derrick', team = 'neutral', x = 3325, z = 1846, facing = 'south', name = 'Cell 2 1 Oil Derrick' },

        -- ANCIENT-TECH GUARDIANS (§M4, worldbuilding directive 4). The
        -- relic itself is a FEATURE (see world.features above); what can
        -- be fought is the band squatting on it. Anarchic archetype —
        -- gun trucks and militia, not line armour.
        -- guarding Cell 0 1 Spire (r0_1)
        { def = 'ms_technical', team = 2, x = 388, z = 2312, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 505, 0, 2175 } } } },
        { def = 'ms_technical', team = 2, x = 339, z = 2104, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 505, 0, 2175 } } } },
        { def = 'ms_militia', team = 2, x = 277, z = 2072, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 505, 0, 2175 } } } },
        { def = 'ms_militia', team = 2, x = 400, z = 2028, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 505, 0, 2175 } } } },
        { def = 'ms_militia', team = 2, x = 356, z = 1973, facing = 'south',
          orders = { { cmd = 'FIGHT', params = { 505, 0, 2175 } } } },
    },

    -- ======================================================================
    -- THE POPULATION. A DIFFERENT WIRE FROM `units` ABOVE, DELIBERATELY.
    -- These entries route through GG.Civilians.Spawn and land in the
    -- civilian REGISTRY, which is the source of truth for who is a
    -- civilian and what they are: civilians/routines.lua wanders the
    -- `ambient` ones, civilians/estate.lua counts them as their district's
    -- population, and game_scenario.lua's own populateCiviliansInArea
    -- resolves protect/escort objectives against them. A unit staged
    -- through `units` is invisible to all three.
    --
    -- The reverse is just as load-bearing and is why a town's BUILDINGS
    -- are not here: the registry would enroll immobile structures in a
    -- per-tick CMD_MOVE they can never satisfy.
    --
    -- `town` is what binds a civilian to a district. estate.lua groups the
    -- population by `info.districtId` and — until this generator emitted
    -- one — always found none, because no spawn path had ever set it; its
    -- own header says the mechanism was real and saw nothing.
    --
    -- `role`: `ambient` is the population, `garrison` is the militia on the
    -- gates. routines.lua only moves `ambient`, so a garrison holds its
    -- post instead of strolling off the gateway it was put on, and the
    -- estate does not count armed volunteers as the civilians a protect
    -- objective is about.
    civilians = {
        units = {
            -- Vesper Watch (r0_2): 4 militia, 2 market, 2 parked, 2 traffic, 6 residents
            { def = 'ms_militia', x = 612, z = 2805, facing = 'west', role = 'garrison', town = 'r0_2' },
            { def = 'ms_militia', x = 1004, z = 2337, facing = 'north', role = 'garrison', town = 'r0_2' },
            { def = 'ms_militia', x = 1256, z = 2365, facing = 'north', role = 'garrison', town = 'r0_2' },
            { def = 'ms_militia', x = 1620, z = 2440, facing = 'north', role = 'garrison', town = 'r0_2' },
            { def = 'ms_civilians', x = 1225, z = 3225, facing = 'west', role = 'ambient', town = 'r0_2' },
            { def = 'ms_civilians', x = 1243, z = 3082, facing = 'west', role = 'ambient', town = 'r0_2' },
            { def = 'ms_civtruck', x = 1433, z = 3179, facing = 'east', role = 'ambient', town = 'r0_2' },
            { def = 'ms_civtruck', x = 840, z = 3156, facing = 'east', role = 'ambient', town = 'r0_2' },
            { def = 'ms_civbus', x = 1808, z = 2894, facing = 'south', role = 'ambient', town = 'r0_2' },
            { def = 'ms_civtruck', x = 1210, z = 2756, facing = 'south', role = 'ambient', town = 'r0_2' },
            { def = 'ms_civilians', x = 1266, z = 2699, facing = 'west', role = 'ambient', town = 'r0_2' },
            { def = 'ms_civilians', x = 1192, z = 2514, facing = 'east', role = 'ambient', town = 'r0_2' },
            { def = 'ms_civilians', x = 1289, z = 2525, facing = 'west', role = 'ambient', town = 'r0_2' },
            { def = 'ms_civilians', x = 1112, z = 3138, facing = 'east', role = 'ambient', town = 'r0_2' },
            { def = 'ms_civilians', x = 1086, z = 3347, facing = 'east', role = 'ambient', town = 'r0_2' },
            { def = 'ms_civilians', x = 958, z = 2826, facing = 'south', role = 'ambient', town = 'r0_2' },
        },
    },

    objectives = {
        -- THE VICTORY OBJECTIVE. `victory = true` is the only terminal
        -- condition game_gameover.lua watches, and ScenarioDiscovery's
        -- DefaultForMap refuses a scenario without one. Exactly one.
        --
        -- Open race (forTeam nil) so either side may take it, and so it
        -- cannot be scoped to a team the launch did not supply — an
        -- objective on a missing team throws "Bad teamID" out of the
        -- Objectives gadget's callin, gadgetHandler removes the gadget,
        -- and the victory objective can then never progress at all.
        --
        -- notBefore + holdFrames = 5400 frames, against a
        -- worst-case approach of 2496 frames for the
        -- slowest staged side. The x1.5 margin is because that estimate
        -- is straight-line and so understates real travel time; matching
        -- it exactly would pass the loader's check and still let the war
        -- be decided before the two armies ever meet.
        { type = 'control', scope = 'strategic', forTeam = nil,
          region = 'r1_2', reward = 300,
          victory = true,
          notBefore = 0, holdFrames = 5400,
          expiresAtFrame = nil },

        -- Tactical prizes on the occupied ground: settlements, the named
        -- resource sites, and the ancient-tech caches. Open race for the
        -- same reason as above; no expiry.
        --
        -- A resource site pays NO income (worldbuilding decision 3), so
        -- its objective is the entire mechanical reason to take it — the
        -- silo is worth holding because the region it stands in scores.
        { type = 'control', scope = 'tactical', forTeam = nil, region = 'r0_1', reward = 200, expiresAtFrame = nil },  -- Cell 0 1 Spire
        { type = 'control', scope = 'tactical', forTeam = nil, region = 'r0_2', reward = 130, expiresAtFrame = nil },  -- Cell 0 2 Grain Silo
        { type = 'control', scope = 'tactical', forTeam = nil, region = 'r1_0', reward = 110, expiresAtFrame = nil },  -- Outpost
        { type = 'control', scope = 'tactical', forTeam = nil, region = 'r1_1', reward = 130, expiresAtFrame = nil },  -- Cell 1 1 Metal Pit
        { type = 'control', scope = 'tactical', forTeam = nil, region = 'r2_0', reward = 110, expiresAtFrame = nil },  -- Forward Base
        { type = 'control', scope = 'tactical', forTeam = nil, region = 'r2_1', reward = 130, expiresAtFrame = nil },  -- Cell 2 1 Oil Derrick

        -- PROTECT. The township's `ambient` residents, resolved at
        -- frame 30 by game_scenario.lua's deferred sweep (the units do
        -- not exist when this file is parsed). `expiresAtFrame` is
        -- MANDATORY for this type — protect.init refuses an open-ended
        -- one, because 'survive until expiry' has no other way to
        -- resolve — and expiry counts as SUCCESS here, uniquely.
        --
        -- quorum 1: the town does not have to come through whole, it
        -- has to come through. A quorum of 'everyone' would fail the
        -- objective to the first stray shell and teach a player that
        -- the objective was never really theirs to win.
        -- Vesper Watch (r0_2): 16 residents
        { type = 'protect', scope = 'tactical', forTeam = 0,
          params = { targetUnitIDs = {}, quorum = 1 },
          _populateTargetsFrom = { x = 1189, z = 2905, r = 760, role = 'ambient' },
          reward = 120, expiresAtFrame = 9000 },

        -- EXTRACT. Two phases: hold `threshold` strength inside the
        -- pickup area for `holdFrames`, then the payload is moved to
        -- the extract area and >= quorum arriving completes it. The
        -- move is done BY THE GADGET, which is what makes this type
        -- authorable from a generated file at all — no player can
        -- order a civilian anywhere.
        -- Vesper Watch (r0_2) -> side 1's landing zone
        { type = 'extract', scope = 'tactical', forTeam = 1,
          params = { payloadUnitIDs = {},
              pickupArea = { x = 1189, z = 2905, r = 760 },
              extractArea = { x = 3412, z = 3412, r = 400 },
              holdFrames = 300, threshold = 5000, quorum = 1 },
          _populatePayloadFrom = { x = 1189, z = 2905, r = 760, role = 'ambient' },
          reward = 150, expiresAtFrame = 27000 },

        -- KILL. `targetUnitID` is a SINGLE runtime id, so it rides the
        -- general `_populateUnitsFrom` marker with the one singular
        -- `into`: the frame-30 sweep resolves the match nearest the
        -- marker centre, and SKIPS the objective if the target failed
        -- to stage — a skipped objective, never a broken one. Open
        -- race (forTeam nil): kill.onUnitDestroyed credits whoever
        -- actually lands the blow.
        -- target: the forward base's ms_command_nexus at r2_0
        { type = 'kill', scope = 'tactical', forTeam = nil,
          _populateUnitsFrom = { x = 3412, z = 682, r = 160,
              defs = { 'ms_command_nexus' }, team = 2, into = 'targetUnitID' },
          reward = 160, expiresAtFrame = nil },

        -- INFRA (open-ended). buildingUnitIDs resolves at frame 30 via
        -- `_populateUnitsFrom`, narrowed to the settlement's own def
        -- names on the NEUTRAL (Gaia) team so a garrison or a passing
        -- army never pollutes the list. quorum 1 for protect's reason:
        -- the settlement does not have to come through whole — infra
        -- FAILS below quorum, and 'lose any one building' would be a
        -- failure condition the holder cannot reasonably meet.
        -- Vesper Watch (r0_2): 6 building def(s)
        { type = 'infra', scope = 'tactical', forTeam = 0,
          params = { buildingUnitIDs = {}, quorum = 1, rewardPerMinute = 5 },
          _populateUnitsFrom = { x = 1189, z = 2905, r = 760,
              defs = { 'ms_barricade_set', 'ms_market_stalls', 'ms_meeting_hall', 'ms_shanty_block', 'ms_watchtower', 'ms_water_works' }, team = 'neutral', into = 'buildingUnitIDs' },
          reward = 0, expiresAtFrame = nil },
    },
}
