# Regenerates the build-stamp header. Invoked via `cmake -P` by the
# generate_build_stamp custom target (CMakeLists.txt) as a pre-build step, so
# it re-reads HEAD on every `cmake --build` rather than once per configure —
# the stamp then names the commit actually linked into the binary.
#
# Expects -DOUTPUT_HEADER=<path> -DSPRING_SOURCE_DIR=<path> on the command line.

execute_process(
    COMMAND git rev-parse --short HEAD
    WORKING_DIRECTORY ${SPRING_SOURCE_DIR}
    OUTPUT_VARIABLE GIT_SHORT_HASH
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
)
if(NOT GIT_SHORT_HASH)
    set(GIT_SHORT_HASH "unknown")
endif()
string(TIMESTAMP BUILD_TIME "%Y%m%d%H%M%S")
set(SPRING_BUILD_STAMP "${GIT_SHORT_HASH}-${BUILD_TIME}")

set(HEADER_CONTENT "// Auto-generated by GenerateBuildStamp.cmake at build time. Do not edit.\n#pragma once\n#define SPRING_BUILD_STAMP \"${SPRING_BUILD_STAMP}\"\n")

if(EXISTS ${OUTPUT_HEADER})
    file(READ ${OUTPUT_HEADER} EXISTING_CONTENT)
else()
    set(EXISTING_CONTENT "")
endif()

# Only touch the file's mtime when the content actually changed, so a rebuild
# within the same second (or a re-run of just this target) doesn't force the
# handful of translation units that include it to recompile for nothing.
if(NOT EXISTING_CONTENT STREQUAL HEADER_CONTENT)
    file(WRITE ${OUTPUT_HEADER} "${HEADER_CONTENT}")
endif()
