/**
 * EntityRenderer — per-piece thin-instanced entity rendering.
 *
 * Each unit type's glb model is loaded and decomposed into pieces
 * (chassis, turret, arms, legs, etc.). Each piece becomes a separate
 * thin-instance source mesh. All units of the same type share the
 * same piece meshes — 1000 tanks = 1 draw call per piece type, not
 * 1000 draw calls.
 *
 * The piece hierarchy from the glb is preserved so individual pieces
 * can be animated (turret rotation, walking legs) by overriding their
 * local transforms. For now all pieces use their rest pose from the
 * model file.
 *
 * Defs without a model fall back to a single procedural shape using
 * thin instances (box/cylinder/cone/sphere).
 */

import {
    Scene,
    MeshBuilder,
    Mesh,
    TransformNode,
    Matrix,
    Vector3,
    Quaternion,
    StandardMaterial,
    ShaderMaterial,
    Effect,
    Color3,
    BoundingInfo,
    SceneLoader,
    Texture,
    RawTexture,
    Engine,
} from '@babylonjs/core';
import '@babylonjs/loaders/glTF/index.js';
// KTX2 loader is registered in main.ts (the app entry). All unit
// textures resolve to `.ktx2` URIs after the texture pipeline migration.
import type { EntityStateSnapshot } from './entity-state.js';
import { EntityInterpolator } from './entity-interpolator.js';
import type { UnitDefInfo } from './connection.js';
import type { PieceStateSnapshot } from './piece-state.js';
import { stampUrl } from '../config.js';

/** Parsed model config from a .config.json or .config.lua sidecar. */
interface ModelConfig {
    tex1?: string;
    tex2?: string;
    invertteamcolor?: boolean;
    /** Piece names in canonical (server) order. Used to align the
     *  client's per-piece indexing with the server's piece-state
     *  envelope, which references pieces by their JSON-config index.
     *  Sourced from the JSON sidecar — Lua-only configs typically
     *  don't carry a piece array, in which case this is undefined and
     *  the client falls back to GLB-traversal order (which won't line
     *  up for animation but is still valid for rest-pose rendering). */
    pieceNames?: string[];
    /** parent[i] = parent index of piece i in canonical order (-1 for
     *  the model root). Walks the same JSON tree as `pieceNames`. */
    pieceParents?: number[];
    /** Model-local axis-aligned bounding box minimum (Y is up). Used to
     *  decide how much to shift the model so its visible base sits on
     *  the ground. Sourced from the JSON sidecar; absent for Lua-only
     *  configs. */
    minY?: number;
    /** Model-local axis-aligned bounding box maximum Y. */
    maxY?: number;
    /** Model-local "midpos" Y (Spring's authored visual centre). When
     *  this sits well above origin the model was authored with origin
     *  at its physical base (common for tall structures whose
     *  foundations extend below origin and are meant to be hidden by
     *  terrain). When it sits at/below origin the model uses centre-
     *  origin and we should lift its base up to ground level. */
    midY?: number;
}

/** Loaded texture set for a unit def. */
interface UnitTextures {
    diffuse: Texture;
    teamMask: Texture | null;
    invertTeamColor: boolean;
}

/**
 * Fetch and parse a model's metadata sidecar. There are two forms,
 * with strict precedence rules that mirror the modelimporter tool:
 *
 *   `<stem>.config.lua` — hand-authored, author-owned. Wins.
 *   `<stem>.config.json` — auto-generated by modelimporter alongside
 *                          the glb. Used only when no Lua sibling exists.
 *
 * The Lua-wins rule matches the modelimporter's behaviour: "if a
 * sibling .config.lua exists, the importer writes nothing at all" —
 * the Lua file signals that the author has taken full control of
 * this model's metadata. Mixing precedence here (preferring JSON)
 * would silently drop hand-authored tex1 / tex2 overrides, which is
 * exactly the bug we hit on ZK's strikecom.
 */
async function fetchModelConfig(modelUrl: string): Promise<ModelConfig | null> {
    // Always try the JSON form too, even when a Lua sibling exists —
    // hand-authored Lua configs typically only carry override fields
    // (tex1/tex2/invertteamcolor) and lean on the JSON for the piece
    // tree we need for animation indexing. ModelConfigLoader on the
    // server takes the same belt-and-braces approach.
    const luaUrl  = modelUrl.replace(/\.glb$/, '.config.lua');
    const jsonUrl = modelUrl.replace(/\.glb$/, '.config.json');

    let luaText: string | null = null;
    let jsonData: any = null;

    try {
        const r = await fetch(luaUrl);
        if (r.ok) luaText = await r.text();
    } catch { /* missing is fine */ }

    try {
        const r = await fetch(jsonUrl);
        if (r.ok) jsonData = await r.json();
    } catch { /* missing is fine */ }

    if (luaText === null && jsonData === null) return null;

    let tex1: string | undefined;
    let tex2: string | undefined;
    let invertteamcolor: boolean | undefined;

    // Lua wins on the texture/team-color fields per the modelimporter rule.
    if (luaText !== null) {
        tex1 = luaText.match(/tex1\s*=\s*"([^"]+)"/)?.[1];
        tex2 = luaText.match(/tex2\s*=\s*"([^"]+)"/)?.[1];
        const invertMatch = luaText.match(/invertteamcolor\s*=\s*(true|false)/);
        invertteamcolor = invertMatch ? invertMatch[1] === 'true' : undefined;
    }
    if (jsonData !== null) {
        if (tex1 === undefined && typeof jsonData.tex1 === 'string') tex1 = jsonData.tex1;
        if (tex2 === undefined && typeof jsonData.tex2 === 'string') tex2 = jsonData.tex2;
        if (invertteamcolor === undefined && typeof jsonData.invertteamcolor === 'boolean')
            invertteamcolor = jsonData.invertteamcolor;
    }
    // Hand-authored .config.lua files reference legacy `.dds` (or .tga,
    // .png) filenames; the runtime only ships `.ktx2`, so rewrite the
    // extension. modelimporter does the same for tex1/tex2 it auto-
    // detects, but Lua-supplied overrides bypass that pass.
    const toKtx2 = (name: string | undefined): string | undefined => {
        if (!name) return name;
        const dot = name.lastIndexOf('.');
        const slash = name.lastIndexOf('/');
        if (dot === -1 || dot < slash) return name + '.ktx2';
        return name.substring(0, dot) + '.ktx2';
    };
    tex1 = toKtx2(tex1);
    tex2 = toKtx2(tex2);

    // Pieces — always from JSON (the canonical machine-generated form).
    let pieceNames: string[] | undefined;
    let pieceParents: number[] | undefined;
    if (jsonData !== null && Array.isArray(jsonData.pieces)) {
        pieceNames = jsonData.pieces.map((p: { name?: string }) =>
            typeof p?.name === 'string' ? p.name : '');
        pieceParents = jsonData.pieces.map((p: { parent?: number }) =>
            typeof p?.parent === 'number' ? p.parent : -1);
    }

    // Bounding-box / midpos extents (only the Y component is used).
    let minY: number | undefined;
    let maxY: number | undefined;
    let midY: number | undefined;
    if (jsonData !== null) {
        if (Array.isArray(jsonData.mins) && typeof jsonData.mins[1] === 'number') minY = jsonData.mins[1];
        if (Array.isArray(jsonData.maxs) && typeof jsonData.maxs[1] === 'number') maxY = jsonData.maxs[1];
        if (Array.isArray(jsonData.midpos) && typeof jsonData.midpos[1] === 'number') midY = jsonData.midpos[1];
    }

    return { tex1, tex2, invertteamcolor, pieceNames, pieceParents, minY, maxY, midY };
}

/**
 * Resolve a texture filename from a config (e.g. "strikecom.ktx2") to
 * a full URL. Textures live in `models/` alongside the .glb files —
 * gameconverter writes them there so the glb's image URIs (which the
 * glTF loader resolves relative to the .glb) point at sibling files.
 * Babylon's glTF loader rejects URIs containing `..` per the glTF
 * spec, which forced this layout.
 */
function resolveTextureUrl(modelUrl: string, textureName: string): string {
    const lastSlash = modelUrl.lastIndexOf('/');
    return `${modelUrl.substring(0, lastSlash + 1)}${textureName}`;
}

// ─── Team color shader ───
// Spring's legacy team color: finalColor = tex1 * (1 - mask) + teamColor * mask
// where mask = tex2.a (or 1 - tex2.a when invertteamcolor is set).

// ─── Team color shader ───
// Spring's legacy team color: finalColor = tex1 * (1 - mask) + teamColor * tex1 * mask
// where mask = tex2.a (or 1 - tex2.a when invertteamcolor is set).
// Uses Babylon's instancesDeclaration/instancesVertex includes for thin-instance support.

// Nanoframe is encoded inline in the team-color shader so we don't
// duplicate the per-piece pipeline. Two per-instance values ride along
// in the 4x4 thin-instance matrix's normally-zero W row:
//   m33 (column 3, row 3) = buildProgress (0..1, 1=finished)
//   m31 (column 1, row 3) = groundY        (entity foot world Y)
// Affine transforms always have m30=m31=m32=0 / m33=1, so packing
// values there only corrupts wp.w — which we discard before projection.
const TEAMCOLOR_VERTEX = `
    precision highp float;
    attribute vec3 position;
    attribute vec3 normal;
    attribute vec2 uv;

    #include<instancesDeclaration>

    uniform mat4 viewProjection;

    varying vec2 vUV;
    varying vec3 vNormal;
    varying float vBuildProgress;
    varying float vAboveGround;

    void main() {
        #include<instancesVertex>

        vBuildProgress = finalWorld[3][3];
        float groundY  = finalWorld[1][3];

        vec4 wp = finalWorld * vec4(position, 1.0);
        vAboveGround = wp.y - groundY;
        vNormal = normalize(mat3(finalWorld) * normal);
        vUV = uv;
        // wp.w is corrupted by our packed values — rebuild as homogeneous 1.
        gl_Position = viewProjection * vec4(wp.xyz, 1.0);
    }
`;

const TEAMCOLOR_FRAGMENT = `
    precision highp float;
    uniform sampler2D diffuseTex;
    uniform sampler2D teamMaskTex;
    uniform vec3 teamColor;
    uniform float hasTeamMask;
    uniform float invertMask;
    uniform vec3 lightDir;
    uniform float modelHeight;

    varying vec2 vUV;
    varying vec3 vNormal;
    varying float vBuildProgress;
    varying float vAboveGround;

    void main() {
        // KTX2/Basis-encoded mip chains are clean — the LOD-bias and
        // MAX_LEVEL hacks the previous DDS pipeline needed to dodge
        // corrupt 1x1/2x2 mip levels in ZK's source DXT5 textures
        // are gone. The transcoder rebuilds a fresh, well-formed
        // chain at upload time.
        vec4 base = texture2D(diffuseTex, vUV);
        vec3 color = base.rgb;

        if (hasTeamMask > 0.5) {
            vec4 t2 = texture2D(teamMaskTex, vUV);
            // Spring S3O tex2 convention:
            //   R = team color mask (where to tint)
            //   G = reflectivity / specular
            //   B = self-illumination
            //   A = typically 1.0 (not used as mask)
            float mask = t2.r;
            if (invertMask > 0.5) mask = 1.0 - mask;
            color = mix(base.rgb, teamColor * base.rgb, mask);
        }

        // Half-Lambert + hemispheric ambient. Plain N·L Lambert (with a
        // flat ambient floor) leaves the side faces of tall, thin units
        // — radar masts, the Lotus turret spire — sitting at the
        // minimum 40% term whenever the camera is far enough away that
        // their bright top face has shrunk to a few pixels. Half-Lambert
        // shifts the diffuse range from [0..1] to [0.5..1] so dark
        // sides keep some shape, and a small upward sky-tint lifts the
        // floor for upward-facing surfaces without crushing downward
        // ones. The combined output ranges roughly 0.55–1.05 so well-
        // lit faces stay visibly brighter than poorly-lit ones.
        float halfLambert = dot(vNormal, lightDir) * 0.5 + 0.5;
        float skyTint     = vNormal.y * 0.5 + 0.5;
        vec3  lit         = color * (0.45 + 0.55 * halfLambert + 0.05 * skyTint);

        // Nanoframe pass — only active during construction. Below the
        // rising plane the model is fully lit; above it we cut a
        // checkerboard stipple so the unfinished portion reads as
        // "ghosted" without using alpha blending (which would force
        // the whole material into Babylon's transparent pass and break
        // depth ordering between pieces). A bright scan band sits at
        // the plane to sell the "construction in progress" look.
        if (vBuildProgress < 1.0) {
            float planeY = vBuildProgress * max(modelHeight, 1.0);
            if (vAboveGround > planeY) {
                // Checkerboard discard — 50% coverage keeps the unit's
                // silhouette readable from a distance while still
                // looking visibly under-construction up close.
                vec2 px = floor(gl_FragCoord.xy);
                if (mod(px.x + px.y, 2.0) < 1.0) discard;
                // Tint the surviving pixels toward the team color so
                // the ghosted region looks like an active build site.
                lit = mix(lit, teamColor * 0.7, 0.6);
            }
            // 3-elmo-wide gaussian glow centred at the plane.
            float bandIntensity = exp(-pow((vAboveGround - planeY) / 2.0, 2.0)) * 1.5;
            lit += teamColor * bandIntensity;
        }
        gl_FragColor = vec4(lit, 1.0);
    }
`;

// Register the shader once
Effect.ShadersStore['teamColorVertexShader'] = TEAMCOLOR_VERTEX;
Effect.ShadersStore['teamColorFragmentShader'] = TEAMCOLOR_FRAGMENT;

/// 1×1 white textures used as a fallback diffuse + teamMask when a model
/// has no texture sidecar. They're cached per-scene so every textureless
/// piece shares the same GPU resource. Rendered as pure team-coloured
/// surfaces (white × teamMask = teamColor in the shader).
const WHITE_TEX_CACHE = new WeakMap<Scene, { diffuse: RawTexture; mask: RawTexture }>();

function getWhiteFallbackTextures(scene: Scene): { diffuse: RawTexture; mask: RawTexture } {
    let pair = WHITE_TEX_CACHE.get(scene);
    if (pair) return pair;
    const px = new Uint8Array([255, 255, 255, 255]);
    const diffuse = new RawTexture(px, 1, 1, Engine.TEXTUREFORMAT_RGBA, scene,
        false, false, Texture.NEAREST_SAMPLINGMODE);
    diffuse.name = 'unit-fallback-diffuse';
    const mask = new RawTexture(px.slice(), 1, 1, Engine.TEXTUREFORMAT_RGBA, scene,
        false, false, Texture.NEAREST_SAMPLINGMODE);
    mask.name = 'unit-fallback-teammask';
    pair = { diffuse, mask };
    WHITE_TEX_CACHE.set(scene, pair);
    return pair;
}

/**
 * Create a team-color material for a unit piece. Uses the teamColor
 * shader with diffuse + team mask textures. Supports thin instances
 * via Babylon's instancesDeclaration/instancesVertex includes.
 */
function createTeamColorMaterial(
    name: string,
    textures: UnitTextures,
    teamColor: Color3,
    modelHeight: number,
    scene: Scene,
): ShaderMaterial {
    const mat = new ShaderMaterial(name, scene, 'teamColor', {
        attributes: ['position', 'normal', 'uv'],
        uniforms: ['world', 'viewProjection', 'teamColor', 'hasTeamMask',
                   'invertMask', 'lightDir', 'modelHeight'],
        samplers: ['diffuseTex', 'teamMaskTex'],
        defines: ['#define INSTANCES', '#define THIN_INSTANCES'],
    });

    mat.setTexture('diffuseTex', textures.diffuse);
    mat.setColor3('teamColor', teamColor);
    mat.setVector3('lightDir', new Vector3(-0.5, 1.0, 0.3).normalize());
    mat.setFloat('modelHeight', modelHeight);

    if (textures.teamMask) {
        mat.setTexture('teamMaskTex', textures.teamMask);
        mat.setFloat('hasTeamMask', 1.0);
        mat.setFloat('invertMask', textures.invertTeamColor ? 1.0 : 0.0);
    } else {
        mat.setFloat('hasTeamMask', 0.0);
        mat.setFloat('invertMask', 0.0);
    }

    // Keep the material fully opaque. The build-progress effect uses
    // discard-based stipple in the fragment shader instead of alpha
    // blending — alpha < 1 would push the material into Babylon's
    // transparent pass, sort pieces back-to-front per camera, and
    // skip depth writes, which produces the per-orbit "texture shift"
    // artefacts we hit when this was set to 0.999.
    mat.alpha = 1.0;
    mat.needAlphaBlending = () => false;
    mat.needAlphaTesting  = () => true;

    // Disable backface culling: modelimporter (Assimp + S3O) emits
    // glTF with CCW winding but Babylon's default is CW, so culling
    // strips the visible surfaces and we end up rendering the inside
    // of each piece. Two-sided is cheap on these low-poly meshes and
    // matches the original Spring renderer's behaviour.
    mat.backFaceCulling = false;
    return mat;
}

/**
 * Load textures referenced by a model config. Returns the loaded
 * texture set, or null if no tex1 is configured. tex1/tex2 in the
 * config are `.ktx2` filenames; Babylon's KTX2 loader transcodes
 * Basis Universal payloads to a GPU-native format at upload time.
 */
function loadUnitTextures(
    config: ModelConfig,
    modelUrl: string,
    scene: Scene,
): UnitTextures | null {
    if (!config.tex1) return null;

    const tex1Url = resolveTextureUrl(modelUrl, config.tex1);
    const diffuse = new Texture(tex1Url, scene);
    diffuse.hasAlpha = false;
    diffuse.anisotropicFilteringLevel = 8;

    let teamMask: Texture | null = null;
    if (config.tex2) {
        const tex2Url = resolveTextureUrl(modelUrl, config.tex2);
        teamMask = new Texture(tex2Url, scene);
        teamMask.hasAlpha = true;
        teamMask.anisotropicFilteringLevel = 8;
    }

    return {
        diffuse,
        teamMask,
        invertTeamColor: config.invertteamcolor ?? false,
    };
}

// Spring engine's 10 default team colors (from TeamBase::teamDefaultColor).
const TEAM_COLORS = [
    new Color3(90/255, 90/255, 255/255),   // blue
    new Color3(200/255, 0/255, 0/255),     // red
    new Color3(255/255, 255/255, 255/255), // white
    new Color3(38/255, 155/255, 32/255),   // green
    new Color3(7/255, 31/255, 125/255),    // dark blue
    new Color3(150/255, 10/255, 180/255),  // purple
    new Color3(255/255, 255/255, 0/255),   // yellow
    new Color3(50/255, 50/255, 50/255),    // black
    new Color3(152/255, 200/255, 220/255), // light blue
    new Color3(171/255, 171/255, 131/255), // tan
];

// Fallback shape types for defs without models
enum UnitShape { Box = 0, Cylinder, Cone, Sphere }
const SHAPE_COUNT = 4;

function defIdToShape(defId: number): UnitShape {
    return (defId % SHAPE_COUNT) as UnitShape;
}

export interface EntityMeta {
    defId: number;
    team: number;
    healthScale: number;
    /** 0..1 build completion. Drives the nanoframe shader: below 1 the
     *  unit renders as a wireframe with a rising scan band; at 1 it is
     *  shaded normally. The server emits 255 once construction finishes
     *  so the byte → float mapping pins finished units to exactly 1.0. */
    buildProgress: number;
}

/** Per-piece pose override for one unit, indexed by piece index.
 *  Pieces not present in this map keep their rest-pose transform. */
type PieceOverrides = Map<number, { px: number; py: number; pz: number;
                                     rx: number; ry: number; rz: number; }>;

/** A single piece (body part) within a model template. */
interface PieceInfo {
    /** The mesh with vertices in piece-local space. */
    mesh: Mesh;
    /** Piece name from the glb node (e.g. "Turret", "LegLeft"). */
    name: string;
    /** Index of the parent piece (-1 for root-level pieces). */
    parentIndex: number;
    /** Local transform relative to parent (from glb hierarchy).
     *  Multiply parent chain to get the rest-pose world matrix. */
    localMatrix: Matrix;
    /** Pre-computed rest-pose world matrix (product of all ancestors'
     *  localMatrix values). Used directly when no animation override. */
    restWorldMatrix: Matrix;
}

/** Loaded model template for a unit def. */
interface ModelTemplate {
    pieces: PieceInfo[];
    /** Vertical offset so the model's base sits at Y=0. */
    yOffset: number;
    /** Y-extent of the model from foot to top, in elmos. Used by the
     *  nanoframe shader as the rising-plane scale: planeY ramps from
     *  0 (no progress) to modelHeight (fully built). */
    modelHeight: number;
    /** Loaded textures (diffuse + team mask). Null if no textures. */
    textures: UnitTextures | null;
}

/** Per-piece thin-instance render mesh, keyed by (defId, team, pieceIdx). */
interface PieceRenderEntry {
    mesh: Mesh;
    pieceIdx: number;
}

export class EntityRenderer {
    private scene: Scene;
    private interpolator = new EntityInterpolator();
    private entityMeta = new Map<number, EntityMeta>();
    private teamMaterials: StandardMaterial[] = [];

    // --- Model loading ---
    private modelTemplates = new Map<number, ModelTemplate | null>();
    private modelsReady: Promise<void> = Promise.resolve();
    private defModelUrls = new Map<number, string>();

    // --- Render meshes ---
    // Per-piece thin-instance meshes, keyed by "model:{defId}:{team}:{pieceIdx}"
    // or "shape:{shape}:{team}" for fallbacks.
    private renderMeshes = new Map<string, Mesh>();

    // --- Per-entity piece pose overrides ---
    // Populated by applyPieceState() from server-streamed piece transforms.
    // Pieces missing from a unit's override map render at rest pose.
    private pieceOverrides = new Map<number, PieceOverrides>();

    // --- Fallback shape meshes ---
    private shapeMeshes = new Map<number, Mesh>();

    // Selection ring (still uses thin instances directly)
    private selectionMesh: Mesh | null = null;
    private selectedIds: number[] = [];

    constructor(scene: Scene) {
        this.scene = scene;

        for (let i = 0; i < TEAM_COLORS.length; i++) {
            const mat = new StandardMaterial(`team${i}Mat`, scene);
            mat.diffuseColor = TEAM_COLORS[i];
            mat.specularColor = new Color3(0.3, 0.3, 0.3);
            this.teamMaterials.push(mat);
        }
    }

    /**
     * Register unit defs and start loading their models.
     */
    setUnitDefs(defs: UnitDefInfo[]): void {
        const loadPromises: Promise<void>[] = [];
        let loaded = 0;
        let skipped = 0;
        let alreadyKnown = 0;

        for (const def of defs) {
            if (this.defModelUrls.has(def.defId)) {
                alreadyKnown++;
                continue;
            }

            this.defModelUrls.set(def.defId, def.modelUrl);

            if (!def.modelUrl) {
                this.modelTemplates.set(def.defId, null);
                skipped++;
                continue;
            }

            loadPromises.push(this.loadModel(def).then(tmpl => {
                this.modelTemplates.set(def.defId, tmpl);
                if (tmpl) loaded++;
                else skipped++;
            }));
        }

        if (loadPromises.length > 0 || skipped > 0) {
            const batchReady = Promise.all(loadPromises).then(() => {
                console.log(
                    `[entity-renderer] defs batch: ${loaded} loaded, ${skipped} fallback` +
                    (alreadyKnown > 0 ? `, ${alreadyKnown} already known` : '')
                );
            });
            this.modelsReady = this.modelsReady.then(() => batchReady);
        }
    }

    private async loadModel(def: UnitDefInfo): Promise<ModelTemplate | null> {
        try {
            const lastSlash = def.modelUrl.lastIndexOf('/');
            const baseUrl = def.modelUrl.substring(0, lastSlash + 1);
            const fileName = def.modelUrl.substring(lastSlash + 1);

            const result = await SceneLoader.ImportMeshAsync(
                '', baseUrl, stampUrl(fileName), this.scene,
            );

            // Build piece list from the imported hierarchy. We need to
            // map glb nodes to pieces, preserving parent relationships.
            // The glb node tree may contain TransformNodes (no geometry)
            // as structural parents — we keep those as pieces too so the
            // hierarchy chain is unbroken.
            const allNodes = result.meshes as (Mesh | TransformNode)[];
            // Also include transform nodes that aren't meshes
            for (const tn of result.transformNodes || []) {
                if (!allNodes.includes(tn)) allNodes.push(tn);
            }

            // Map each node to an index for parent lookups
            const nodeToIndex = new Map<TransformNode, number>();
            for (let i = 0; i < allNodes.length; i++) {
                nodeToIndex.set(allNodes[i], i);
            }

            // Compute world matrices while hierarchy is intact
            for (const n of allNodes) n.computeWorldMatrix(true);

            // Build piece infos
            const pieces: PieceInfo[] = [];
            const nodeTopiece = new Map<TransformNode, number>();

            // Babylon's GLB loader splits multi-primitive meshes into a
            // parent TransformNode and child Mesh nodes named
            // `<parent>_primitive<n>`. The parent has the JSON-config
            // name; the children carry the geometry. Pre-pass: claim each
            // such primitive for its parent so the main loop emits one
            // piece (the parent name + densest primitive's geometry).
            const primitiveByParent = new Map<TransformNode, Mesh>();
            const absorbedPrimitives = new Set<Mesh>();
            for (const child of allNodes) {
                if (!(child instanceof Mesh)) continue;
                const parent = child.parent;
                if (!parent) continue;
                const re = new RegExp(`^${parent.name}_primitive\\d+$`);
                if (!re.test(child.name)) continue;
                const verts = child.getTotalVertices();
                const existing = primitiveByParent.get(parent as TransformNode);
                if (!existing || existing.getTotalVertices() < verts) {
                    primitiveByParent.set(parent as TransformNode, child);
                }
            }
            // Mark all primitives belonging to a parent as absorbed (we
            // only render the densest one; the rest are dropped).
            for (const child of allNodes) {
                if (!(child instanceof Mesh)) continue;
                const parent = child.parent;
                if (!parent) continue;
                const re = new RegExp(`^${parent.name}_primitive\\d+$`);
                if (re.test(child.name)) absorbedPrimitives.add(child);
            }

            for (let i = 0; i < allNodes.length; i++) {
                const node = allNodes[i];
                let isMesh = node instanceof Mesh && node.getTotalVertices() > 0;

                // Skip the __root__ container Babylon creates
                if (node.name === '__root__') continue;
                // Skip a primitive child whose geometry was rolled up
                // into its parent piece.
                if (node instanceof Mesh && absorbedPrimitives.has(node)) continue;

                // If this is a TransformNode with absorbed primitive
                // children, surface the chosen primitive as our geometry.
                let primitiveMesh: Mesh | null = null;
                if (!isMesh) {
                    primitiveMesh = primitiveByParent.get(node) ?? null;
                    if (primitiveMesh) isMesh = true;
                }

                // Find parent piece index
                let parentIndex = -1;
                let p = node.parent;
                while (p) {
                    if (nodeTopiece.has(p as TransformNode)) {
                        parentIndex = nodeTopiece.get(p as TransformNode)!;
                        break;
                    }
                    p = p.parent;
                }

                // Get local matrix relative to parent
                const localMatrix = node.getWorldMatrix().clone();
                if (parentIndex >= 0) {
                    // localMatrix = parentWorldInverse × worldMatrix
                    const parentWorld = pieces[parentIndex].restWorldMatrix;
                    const parentInv = Matrix.Invert(parentWorld);
                    localMatrix.copyFrom(parentInv.multiply(node.getWorldMatrix()));
                }

                const restWorldMatrix = node.getWorldMatrix().clone();

                const pieceIdx = pieces.length;
                nodeTopiece.set(node, pieceIdx);

                if (isMesh) {
                    const mesh = (primitiveMesh ?? node) as Mesh;
                    // Detach from hierarchy, keep vertices in piece-local space
                    mesh.parent = null;
                    mesh.position.set(0, 0, 0);
                    mesh.rotationQuaternion = Quaternion.Identity();
                    mesh.scaling.set(1, 1, 1);
                    mesh.isPickable = false;
                    mesh.isVisible = false;
                    mesh.thinInstanceEnablePicking = false;
                    mesh.alwaysSelectAsActiveMesh = true;
                    mesh.setBoundingInfo(new BoundingInfo(
                        new Vector3(-1e6, -1e6, -1e6),
                        new Vector3(1e6, 1e6, 1e6),
                    ));
                    mesh.renderingGroupId = 2;

                    pieces.push({
                        mesh,
                        name: node.name,
                        parentIndex,
                        localMatrix,
                        restWorldMatrix,
                    });
                } else {
                    // Structural node (no geometry) — still needed for
                    // hierarchy chain. Use a dummy mesh reference.
                    pieces.push({
                        mesh: null!,
                        name: node.name,
                        parentIndex,
                        localMatrix,
                        restWorldMatrix,
                    });
                    // Hide the node
                    node.setEnabled(false);
                }
            }

            // Fetch model config — provides tex1/tex2 plus the canonical
            // (server-side) piece array. We need to align our piece
            // indices with the server's, since the piece-state envelope
            // identifies pieces by their JSON-config index.
            const config = await fetchModelConfig(def.modelUrl);

            // Reorder our GLB-traversal pieces array to match the
            // canonical config order. Pieces present in the JSON tree
            // but missing from the GLB (rare; structural-only nodes
            // sometimes get optimised out) get null-mesh placeholders
            // so descendants can still chain their parents correctly.
            let orderedPieces = pieces;
            if (config?.pieceNames && config.pieceParents) {
                const byName = new Map<string, PieceInfo>();
                for (const p of pieces) byName.set(p.name, p);

                const ordered: PieceInfo[] = [];
                for (let i = 0; i < config.pieceNames.length; i++) {
                    const name = config.pieceNames[i];
                    const parentIdx = config.pieceParents[i];
                    const found = byName.get(name);
                    if (found) {
                        ordered.push({
                            mesh: found.mesh,
                            name,
                            parentIndex: parentIdx,
                            localMatrix: found.localMatrix,
                            restWorldMatrix: found.restWorldMatrix,
                        });
                    } else {
                        ordered.push({
                            mesh: null!,
                            name,
                            parentIndex: parentIdx,
                            localMatrix: Matrix.Identity(),
                            restWorldMatrix: Matrix.Identity(),
                        });
                    }
                }

                // The GLB hierarchy may not match the JSON config (Assimp
                // can flatten or re-parent during import), so the imported
                // localMatrix isn't reliably local-to-(named-parent).
                // restWorldMatrix *is* reliable though — it's the GLB's
                // node.getWorldMatrix() captured at import. Use that as
                // ground truth and rebuild localMatrix relative to the
                // JSON-config parent: local = world × parent_world⁻¹.
                for (let i = 0; i < ordered.length; i++) {
                    const p = ordered[i];
                    if (p.parentIndex >= 0 && p.parentIndex < ordered.length) {
                        const parentRest = ordered[p.parentIndex].restWorldMatrix;
                        const parentInv = Matrix.Invert(parentRest);
                        ordered[i].localMatrix = p.restWorldMatrix.multiply(parentInv);
                    } else {
                        ordered[i].localMatrix = p.restWorldMatrix.clone();
                    }
                }

                orderedPieces = ordered;
            }

            // Filter to only pieces with geometry for rendering
            const geometryPieces = orderedPieces.filter(p => p.mesh != null);

            if (geometryPieces.length === 0) {
                console.warn(`[entity-renderer] ${def.name}: glb has no geometry`);
                return null;
            }

            // Compute the model's vertical extent from the rest-pose
            // bounding boxes. Used both to pick yOffset and to size the
            // build-progress scan plane in the shader.
            let bbMinY = Infinity;
            let bbMaxY = -Infinity;
            for (const p of geometryPieces) {
                p.mesh.refreshBoundingInfo();
                const bb = p.mesh.getBoundingInfo().boundingBox;
                const corners = [
                    Vector3.TransformCoordinates(bb.minimum, p.restWorldMatrix),
                    Vector3.TransformCoordinates(bb.maximum, p.restWorldMatrix),
                ];
                for (const c of corners) {
                    if (c.y < bbMinY) bbMinY = c.y;
                    if (c.y > bbMaxY) bbMaxY = c.y;
                }
            }
            const modelHeight = Math.max(1, bbMaxY - bbMinY);

            // Pick yOffset based on Spring's authored model conventions.
            //
            // Authors use one of two origin styles:
            //   A. Origin at physical base (typical for tall structures —
            //      windmills, radars, factories). Often these have parts
            //      that extend BELOW origin (foundations) which the
            //      original engine relies on terrain to occlude. midpos.y
            //      sits well above origin (in the body of the structure).
            //      → render with no shift; trust terrain to clip the
            //         foundation.
            //   B. Origin near the visual centre / waist (typical for
            //      humanoid mechs and walking units). midpos.y sits
            //      near zero or below. The model's "feet" live well
            //      below origin and would sink into the ground if drawn
            //      unshifted.
            //      → shift up by -minY so the feet land at ground level.
            //
            // The midpos.y signal cleanly separates the two: structures
            // have midpos high up in their body, mechs have it near the
            // unit's centre-of-mass which is close to origin.
            const minY = config?.minY ?? bbMinY;
            const midY = config?.midY;
            // 0.1 * modelHeight cleanly classifies the ZK examples
            // (commander midpos≈-3 vs windmill midpos≈+17 vs radar
            // midpos≈+21) and stays robust across model sizes.
            const baseAtOrigin = midY !== undefined && midY > modelHeight * 0.1;
            const yOffset = baseAtOrigin ? 0 : Math.max(0, -minY);

            // Load textures (sharing across all teams; team color is
            // applied per-team via the shader uniform).
            const textures = config ? loadUnitTextures(config, def.modelUrl, this.scene) : null;

            console.log(
                `[entity-renderer] ${def.name}: model loaded, ` +
                `${geometryPieces.length} piece(s) with geometry, ` +
                `${orderedPieces.length} total nodes, yOffset=${yOffset.toFixed(1)}` +
                (config?.tex1 ? `, tex1=${config.tex1}` : '') +
                (config?.tex2 ? `, tex2=${config.tex2}` : '') +
                (config?.pieceNames ? `, aligned to config (${config.pieceNames.length} pieces)` : ''),
            );

            return { pieces: orderedPieces, yOffset, modelHeight, textures };
        } catch (err) {
            // Babylon raises "Scene has been disposed" when ImportMeshAsync
            // is in-flight while the scene tears down (game exit / lobby
            // restart). Not a content failure — drop silently.
            if (this.scene.isDisposed) return null;
            console.warn(
                `[entity-renderer] ${def.name}: failed to load ${def.modelUrl}`,
                err,
            );
            return null;
        }
    }

    /** Replace the selected-unit id list. Called by InputManager. */
    setSelection(ids: readonly number[]): void {
        this.selectedIds = ids.slice();
    }

    /**
     * Build a fallback Mesh for one (shape, team) pair.
     */
    private buildFallbackMesh(shape: UnitShape, team: number): Mesh {
        const name = `render_fallback_${shape}_${team}`;
        let mesh: Mesh;
        let height: number;
        switch (shape) {
            case UnitShape.Box:
                height = 12;
                mesh = MeshBuilder.CreateBox(name, { width: 16, height, depth: 20 }, this.scene);
                break;
            case UnitShape.Cylinder:
                height = 14;
                mesh = MeshBuilder.CreateCylinder(name, { height, diameter: 18, tessellation: 8 }, this.scene);
                break;
            case UnitShape.Cone:
                height = 16;
                mesh = MeshBuilder.CreateCylinder(name, { height, diameterTop: 0, diameterBottom: 16, tessellation: 8 }, this.scene);
                break;
            case UnitShape.Sphere:
            default:
                height = 14;
                mesh = MeshBuilder.CreateSphere(name, { diameter: 14, segments: 6 }, this.scene);
                break;
        }
        mesh.position.y = height / 2;
        mesh.bakeCurrentTransformIntoVertices();
        mesh.material = this.teamMaterials[team];
        mesh.thinInstanceEnablePicking = false;
        mesh.alwaysSelectAsActiveMesh = true;
        mesh.setBoundingInfo(new BoundingInfo(
            new Vector3(-1e6, -1e6, -1e6),
            new Vector3(1e6, 1e6, 1e6),
        ));
        mesh.renderingGroupId = 2;
        return mesh;
    }

    /**
     * Get or create the thin-instance render mesh for a specific piece
     * of a specific (defId, team). Clones the template piece mesh.
     */
    private getOrCreatePieceMesh(defId: number, team: number, pieceIdx: number, piece: PieceInfo): Mesh {
        const key = `model:${defId}:${team}:${pieceIdx}`;
        let mesh = this.renderMeshes.get(key);
        if (!mesh) {
            mesh = piece.mesh.clone(`unit_${defId}_t${team}_p${pieceIdx}_${piece.name}`);
            mesh.makeGeometryUnique();

            const tmpl = this.modelTemplates.get(defId);
            const teamColor = TEAM_COLORS[team % TEAM_COLORS.length];
            const matName = `unit_${defId}_t${team}_p${pieceIdx}_mat`;

            // Always use the team-color shader. The thin-instance world
            // matrix packs groundY into m31 and buildProgress into m33
            // (see TEAMCOLOR_VERTEX comment). Babylon's default GPU
            // pipeline divides by the corrupted wp.w during projection
            // and renders the geometry as long streaks; only the
            // teamColor shader knows to reconstruct gl_Position from
            // wp.xyz alone. Skipping the replacement (the previous
            // `else if (!mesh.material)` branch) left units without a
            // texture sidecar — e.g. ZK's `factoryveh` — keeping the
            // PBR material from the glTF import and rendering broken.
            if (tmpl?.textures) {
                mesh.material = createTeamColorMaterial(
                    matName, tmpl.textures, teamColor, tmpl.modelHeight, this.scene);
            } else {
                // No texture sidecar — synthesise white diffuse + full
                // mask so the unit renders as a flat team-coloured shape
                // through the same shader as textured units.
                const fallback = getWhiteFallbackTextures(this.scene);
                mesh.material = createTeamColorMaterial(
                    matName,
                    { diffuse: fallback.diffuse, teamMask: fallback.mask, invertTeamColor: false },
                    teamColor,
                    tmpl?.modelHeight ?? 1,
                    this.scene,
                );
            }

            mesh.isPickable = false;
            mesh.isVisible = false;
            mesh.thinInstanceEnablePicking = false;
            mesh.alwaysSelectAsActiveMesh = true;
            mesh.setBoundingInfo(new BoundingInfo(
                new Vector3(-1e6, -1e6, -1e6),
                new Vector3(1e6, 1e6, 1e6),
            ));
            mesh.renderingGroupId = 2;
            this.renderMeshes.set(key, mesh);
        }
        return mesh;
    }

    private getFallbackMesh(defId: number, team: number): Mesh {
        const shape = defIdToShape(defId);
        const teamIdx = team % this.teamMaterials.length;
        const key = `shape:${shape}:${teamIdx}`;
        let mesh = this.renderMeshes.get(key);
        if (!mesh) {
            mesh = this.buildFallbackMesh(shape, teamIdx);
            this.renderMeshes.set(key, mesh);
        }
        return mesh;
    }

    /**
     * Build the selection-ring template on first use.
     */
    private ensureSelectionMesh(): Mesh {
        if (this.selectionMesh) return this.selectionMesh;
        const mesh = MeshBuilder.CreateTorus('selection_ring', {
            diameter: 26,
            thickness: 3,
            tessellation: 24,
        }, this.scene);
        mesh.scaling.y = 0.15;
        mesh.bakeCurrentTransformIntoVertices();

        const mat = new StandardMaterial('selectionMat', this.scene);
        mat.diffuseColor = new Color3(0, 0, 0);
        mat.emissiveColor = new Color3(1.0, 0.9, 0.2);
        mat.specularColor = new Color3(0, 0, 0);
        mat.disableLighting = true;
        mesh.material = mat;

        mesh.thinInstanceEnablePicking = false;
        mesh.alwaysSelectAsActiveMesh = true;
        mesh.setBoundingInfo(new BoundingInfo(
            new Vector3(-1e6, -1e6, -1e6),
            new Vector3(1e6, 1e6, 1e6),
        ));
        // Ring sits in the same rendering group as units so depth
        // testing hides the half that's behind the unit's geometry.
        // Previously this was group 3 (drawn after units regardless of
        // depth), which made the ring appear floating above the model.
        mesh.renderingGroupId = 2;
        mesh.isVisible = false;
        this.selectionMesh = mesh;
        return mesh;
    }

    private updateSelectionRings(now: number): void {
        if (this.selectedIds.length === 0) {
            if (this.selectionMesh) {
                this.selectionMesh.isVisible = false;
                this.selectionMesh.thinInstanceCount = 0;
            }
            return;
        }

        const mesh = this.ensureSelectionMesh();
        const matrices: number[] = [];
        let count = 0;
        const tmp = new Float32Array(16);
        for (const id of this.selectedIds) {
            const p = this.interpolator.getInterpolated(id, now);
            if (!p) continue;
            const m = Matrix.Compose(
                new Vector3(1, 1, 1),
                Quaternion.Identity(),
                new Vector3(p.x, p.y + 1.0, p.z),
            );
            m.copyToArray(tmp, 0);
            for (let j = 0; j < 16; j++) matrices.push(tmp[j]);
            count++;
        }

        if (count === 0) {
            mesh.isVisible = false;
            mesh.thinInstanceCount = 0;
            return;
        }

        mesh.isVisible = true;
        const buf = new Float32Array(matrices);
        mesh.thinInstanceSetBuffer('matrix', buf, 16, false);
        mesh.thinInstanceCount = count;
    }

    /**
     * Build the model-space world matrix for every piece in a template,
     * applying server overrides where present. Pieces without an
     * override fall back to their precomputed rest local matrix. The
     * pieces array is in topological order (parent before child) — see
     * loadModel — so a single forward pass suffices.
     *
     * The GLB encodes the Spring→Babylon basis change as a rotation
     * baked into the *root* piece's world matrix — every parent-relative
     * `localMatrix` along the chain stays in Spring-aligned axes, with
     * pure Spring offsets in m[12..14] and rotations about Spring's
     * own X/Y/Z. The chain `local.multiply(parent)` then carries the
     * basis rotation outward and lands the leaf in Babylon coordinates.
     *
     * So overrides convert *directly*: translation = Spring (px,py,pz)
     * unchanged, and rotation = Spring's `T(pos) * RY * RX * RZ`
     * (RZ first, RY last) about the literal axes (1,0,0)/(0,1,0)/(0,0,1).
     */
    private computePieceWorldMatrices(
        tmpl: ModelTemplate,
        overrides: PieceOverrides,
    ): Matrix[] {
        const out = new Array<Matrix>(tmpl.pieces.length);
        for (let i = 0; i < tmpl.pieces.length; i++) {
            const piece = tmpl.pieces[i];
            const ov = overrides.get(i);
            const local = ov
                ? this.springToBabylonLocal(ov)
                : piece.localMatrix;
            out[i] = piece.parentIndex >= 0
                ? local.multiply(out[piece.parentIndex])
                : local.clone();
        }
        return out;
    }

    /** Build a parent-relative local matrix from a server piece pose.
     *  Stays in Spring-aligned axes — the basis change is applied by the
     *  ancestor chain (see comment on computePieceWorldMatrices). */
    private springToBabylonLocal(ov: {
        px: number; py: number; pz: number;
        rx: number; ry: number; rz: number;
    }): Matrix {
        // Spring's per-piece transform: T(pos) * RY * RX * RZ.
        // Babylon q1.multiply(q2) = q1*q2 applies q2 first then q1, so
        // qY * qX * qZ applies in order qZ → qX → qY (Spring's order).
        const qZ = Quaternion.RotationAxis(new Vector3(0, 0, 1), ov.rz);
        const qX = Quaternion.RotationAxis(new Vector3(1, 0, 0), ov.rx);
        const qY = Quaternion.RotationAxis(new Vector3(0, 1, 0), ov.ry);
        const rot = qY.multiply(qX).multiply(qZ);

        return Matrix.Compose(
            new Vector3(1, 1, 1),
            rot,
            new Vector3(ov.px, ov.py, ov.pz),
        );
    }

    /**
     * Apply a server-streamed piece-state snapshot. Overwrites the per-
     * unit override map so pieces that fell back to rest pose (and so
     * weren't included by the server) automatically clear.
     */
    applyPieceState(snapshot: PieceStateSnapshot): void {
        // Track the units mentioned this snapshot; any unit previously
        // animated but absent here goes back to rest pose.
        const seen = new Set<number>();
        for (const u of snapshot.units) {
            seen.add(u.unitId);
            let map = this.pieceOverrides.get(u.unitId);
            if (!map) {
                map = new Map();
                this.pieceOverrides.set(u.unitId, map);
            } else {
                map.clear();
            }
            for (const p of u.pieces) {
                map.set(p.pieceIdx, {
                    px: p.px, py: p.py, pz: p.pz,
                    rx: p.rx, ry: p.ry, rz: p.rz,
                });
            }
        }
        // Clear overrides for units that have animations on file but
        // were left out of this snapshot — those pieces are at rest now.
        for (const id of this.pieceOverrides.keys()) {
            if (!seen.has(id)) this.pieceOverrides.delete(id);
        }
    }

    update(snapshot: EntityStateSnapshot, isDelta: boolean = false): void {
        const { count, entityIds, positionsX, positionsY, positionsZ, headings, health, defIds, teams, buildProgress } = snapshot;
        if (!entityIds) return;

        const now = performance.now();

        for (let i = 0; i < count; i++) {
            const id = entityIds[i];

            this.interpolator.pushState(
                id,
                positionsX ? positionsX[i] : 0,
                positionsY ? positionsY[i] : 0,
                positionsZ ? positionsZ[i] : 0,
                headings ? headings[i] : 0,
                now,
            );

            let meta = this.entityMeta.get(id);
            if (!meta) {
                meta = { defId: 0, team: 0, healthScale: 1.0, buildProgress: 1.0 };
                this.entityMeta.set(id, meta);
            }
            if (defIds) meta.defId = defIds[i];
            if (teams) meta.team = teams[i];
            if (health) meta.healthScale = 0.3 + (health[i] / 65535) * 0.7;
            if (buildProgress) meta.buildProgress = buildProgress[i] / 255;
        }

        if (!isDelta) {
            const seen = new Set<number>();
            for (let i = 0; i < count; i++) seen.add(entityIds[i]);
            for (const id of this.entityMeta.keys()) {
                if (!seen.has(id)) {
                    this.entityMeta.delete(id);
                    this.interpolator.remove(id);
                    this.pieceOverrides.delete(id);
                }
            }
        }
    }

    tick(): void {
        const now = performance.now();

        // Collect per-piece instance matrices.
        // Key: render mesh key → { mesh, matrices[], count }
        const groups = new Map<string, { mesh: Mesh; matrices: number[]; count: number }>();

        for (const [id, meta] of this.entityMeta) {
            const lerped = this.interpolator.getInterpolated(id, now);
            if (!lerped) continue;

            const tmpl = this.modelTemplates.get(meta.defId);

            if (tmpl) {
                // Entity world transform
                const rotation = (lerped.heading / 65535) * Math.PI * 2;
                const entityMatrix = Matrix.Compose(
                    new Vector3(1, 1, 1),
                    Quaternion.RotationYawPitchRoll(rotation, 0, 0),
                    new Vector3(lerped.x, lerped.y + tmpl.yOffset, lerped.z),
                );

                // Compute per-piece world-in-model matrices. Animated
                // pieces (those with a server override) replace their
                // rest local matrix with T(pos) * R(rot); all others
                // reuse the precomputed rest world matrix to avoid the
                // chain walk in the static case.
                const overrides = this.pieceOverrides.get(id);
                const pieceWorld = overrides
                    ? this.computePieceWorldMatrices(tmpl, overrides)
                    : null;

                // Push one instance matrix per piece with geometry
                for (let pi = 0; pi < tmpl.pieces.length; pi++) {
                    const piece = tmpl.pieces[pi];
                    if (!piece.mesh) continue; // structural node, no geometry

                    const key = `model:${meta.defId}:${meta.team}:${pi}`;
                    let group = groups.get(key);
                    if (!group) {
                        const mesh = this.getOrCreatePieceMesh(meta.defId, meta.team, pi, piece);
                        group = { mesh, matrices: [], count: 0 };
                        groups.set(key, group);
                    }

                    // Instance matrix = entityWorld × pieceModelWorld
                    // This places piece-local vertices into final world position.
                    const modelWorld = pieceWorld ? pieceWorld[pi] : piece.restWorldMatrix;
                    const instanceMatrix = modelWorld.multiply(entityMatrix);
                    const arr = new Float32Array(16);
                    instanceMatrix.copyToArray(arr, 0);
                    // Pack nanoframe inputs into the matrix's normally-zero
                    // row 3 entries — see TEAMCOLOR_VERTEX comment. These
                    // corrupt wp.w but the shader rebuilds the projection
                    // input from wp.xyz so xyz transforms stay correct.
                    arr[7] = lerped.y;            // m31 → groundY (entity foot Y)
                    arr[15] = meta.buildProgress; // m33 → buildProgress
                    for (let j = 0; j < 16; j++) group.matrices.push(arr[j]);
                    group.count++;
                }
            } else {
                // Fallback shape
                const shape = defIdToShape(meta.defId);
                const teamIdx = meta.team % this.teamMaterials.length;
                const key = `shape:${shape}:${teamIdx}`;
                let group = groups.get(key);
                if (!group) {
                    const mesh = this.getFallbackMesh(meta.defId, meta.team);
                    group = { mesh, matrices: [], count: 0 };
                    groups.set(key, group);
                }

                const rotation = (lerped.heading / 65535) * Math.PI * 2;
                const matrix = Matrix.Compose(
                    new Vector3(1, meta.healthScale, 1),
                    Quaternion.RotationYawPitchRoll(rotation, 0, 0),
                    new Vector3(lerped.x, lerped.y, lerped.z),
                );
                const arr = new Float32Array(16);
                matrix.copyToArray(arr, 0);
                for (let j = 0; j < 16; j++) group.matrices.push(arr[j]);
                group.count++;
            }
        }

        // Update render meshes
        const activeKeys = new Set<string>();
        for (const [key, group] of groups) {
            activeKeys.add(key);
            group.mesh.isVisible = true;
            const buf = new Float32Array(group.matrices);
            group.mesh.thinInstanceSetBuffer('matrix', buf, 16, false);
            group.mesh.thinInstanceCount = group.count;
        }

        // Hide meshes not active this frame
        for (const [rKey, mesh] of this.renderMeshes) {
            if (!activeKeys.has(rKey)) {
                mesh.isVisible = false;
                mesh.thinInstanceCount = 0;
            }
        }

        this.updateSelectionRings(now);
    }

    get entityCount(): number {
        return this.entityMeta.size;
    }

    getEntities(): IterableIterator<[number, EntityMeta]> {
        return this.entityMeta.entries();
    }

    getEntityMeta(id: number): EntityMeta | undefined {
        return this.entityMeta.get(id);
    }

    getEntityPosition(id: number): { x: number; y: number; z: number } | null {
        return this.interpolator.getInterpolated(id);
    }

    /**
     * Resolve the live world-space position of one piece on a unit.
     * Honours both the entity's interpolated position/heading and any
     * server-streamed piece-pose override; pieces missing from the
     * override map use their rest-pose transform. Returns null if the
     * unit has no model template, no interpolated position, or the
     * piece index is out of range.
     *
     * BuildBeamRenderer uses this to anchor nano-spray beams at the
     * builder's actual emitter pieces (NanoPieceCache) instead of the
     * unit's centre — so a hovercraft's two side nozzles emit two
     * beams from the right place rather than one beam from the middle.
     */
    getPieceWorldPosition(
        id: number,
        pieceIdx: number,
    ): { x: number; y: number; z: number } | null {
        const meta = this.entityMeta.get(id);
        if (!meta) return null;
        const tmpl = this.modelTemplates.get(meta.defId);
        if (!tmpl || pieceIdx < 0 || pieceIdx >= tmpl.pieces.length) return null;
        const lerped = this.interpolator.getInterpolated(id);
        if (!lerped) return null;

        const overrides = this.pieceOverrides.get(id);
        const modelWorld = overrides
            ? this.computePieceWorldMatrices(tmpl, overrides)[pieceIdx]
            : tmpl.pieces[pieceIdx].restWorldMatrix;

        const rotation = (lerped.heading / 65535) * Math.PI * 2;
        const entityMatrix = Matrix.Compose(
            new Vector3(1, 1, 1),
            Quaternion.RotationYawPitchRoll(rotation, 0, 0),
            new Vector3(lerped.x, lerped.y + tmpl.yOffset, lerped.z),
        );
        const piece = modelWorld.multiply(entityMatrix);
        // Translation lives in row 3 of a row-major Babylon Matrix.
        return { x: piece.m[12], y: piece.m[13], z: piece.m[14] };
    }

    removeEntity(id: number): void {
        this.entityMeta.delete(id);
        this.interpolator.remove(id);
        this.pieceOverrides.delete(id);
    }

    dispose(): void {
        for (const mesh of this.renderMeshes.values()) mesh.dispose();
        this.renderMeshes.clear();
        for (const tmpl of this.modelTemplates.values()) {
            if (tmpl) {
                for (const p of tmpl.pieces) {
                    if (p.mesh) p.mesh.dispose();
                }
                if (tmpl.textures) {
                    tmpl.textures.diffuse.dispose();
                    tmpl.textures.teamMask?.dispose();
                }
            }
        }
        this.modelTemplates.clear();
        if (this.selectionMesh) {
            this.selectionMesh.dispose();
            this.selectionMesh = null;
        }
        this.selectedIds = [];
        this.entityMeta.clear();
        this.interpolator.clear();
        for (const mat of this.teamMaterials) mat.dispose();
    }
}
