/**
 * ImpostorRenderer — billboard/impostor LOD tier for distant units.
 *
 * Per PLAN-metalstorm-beta-units.md §2.1: every unit has up to three
 * representations — full model, impostor (camera-facing quad), and icon.
 * This module handles the impostor tier: textured quads with atlas frames
 * selected by quantized heading (8 views) × animation flipbook frame.
 *
 * Architecture:
 * - One mesh per (defId, team), thin-instanced across all units of that type
 * - Per-instance attributes: world position, heading (for frame select), team ID
 * - Atlas texture: 8 headings × N animation frames (walk, idle), team mask
 * - Heading quantization: unit's rotation → nearest 45° heading → atlas column
 * - Animation frame: driven by velocity/state (coordinated with fx-offload X4)
 *
 * Coordination with PLAN-fx-offload.md X2 (piece-transform texture / animation):
 * The per-instance attribute pattern here (heading, animFrame, teamId) is
 * COMPATIBLE with X2's planned data-texture substrate — when X2 lands, both
 * the impostor path and the full-model skinning path will share the same
 * instance-data structures. This implementation deliberately uses a subset of
 * X2's eventual schema so no breaking changes are required later.
 *
 * Atlas textures are the authored/baked sprite sheets (beta-units task 4b:
 * `<stem>_impostor.ktx2` + optional `<stem>_impostor_team.ktx2` under the
 * game's models/ dir — generated by tools/fable-model-forge/
 * gen_impostor_sprites.py for the impostor-only infantry/civilians).
 * Material: stock PBRMaterial (alpha-tested cutout) + the same
 * TeamColorPlugin the unit model path uses, so sprites sit in the scene
 * sun/ambient/CSM lighting exactly like 3D members would.
 */

import {
    Scene,
    Mesh,
    MeshBuilder,
    Vector3,
    Matrix,
    Quaternion,
    PBRMaterial,
    Texture,
    Engine,
    type CascadedShadowGenerator,
} from '@babylonjs/core';
import { TeamColorPlugin } from './team-color-plugin.js';
import { ImpostorUvPlugin } from './impostor-uv-plugin.js';
import { DitherFadePlugin } from './dither-fade-plugin.js';
import {
    type AtlasLayout, SINGLE_CELL_LAYOUT, cardTiltsWithPitch,
    isDirectionalAtlas, selectAtlasCell,
} from './impostor-atlas.js';
import { getTeamColor } from './team-colors.js';
import type { PresentationClock } from './presentation-clock.js';
import type { EntityStateSnapshot } from './entity-state.js';

/** Impostor atlas metadata — per unit def. Sourced from the def's client
 *  content or auto-derived from the model. */
export interface ImpostorAtlas {
    /** Atlas texture URI (diffuse + alpha). v2 directional layout: `yawBins`
     *  columns × (`pitchBins`·`frames`) rows — see impostor-atlas.ts /
     *  impostor_convention.py. */
    diffuseUri: string;
    /** Team-color mask atlas URI (R = blend amount, same layout). */
    teamMaskUri?: string;
    /** Number of walk-cycle frames (atlas rows [0, walkFrames)). */
    walkFrames: number;
    /** Number of idle frames (atlas rows [walkFrames, walkFrames+idleFrames)). */
    idleFrames: number;
    /** Quad size in world units (elmos). Derived from model bounds. */
    width: number;
    height: number;
    /** Directional grid this sheet was baked on. Absent = a legacy single-view
     *  sheet (`SINGLE_CELL_LAYOUT`): one horizon-level front view, so its cards
     *  stay upright — see `cardTiltsWithPitch()`. */
    layout?: AtlasLayout;
    /** Ground-anchor lift in elmos — see {@link cardLift}. */
    centreY?: number;
}

/** An atlas's grid, defaulting a legacy sheet to the single-cell layout. */
export function layoutOf(atlas: ImpostorAtlas | undefined): AtlasLayout {
    return atlas?.layout ?? SINGLE_CELL_LAYOUT;
}

/**
 * How far above its ground point the card's CENTRE must sit, so the figure's
 * feet land on the terrain rather than hovering (or sinking).
 *
 * `height/2` is only correct when the baker put the model's ground point on
 * the cell's BOTTOM edge. A baker that keeps a margin, or that fits all 24
 * views to one shared scale (so the tallest view sets the scale and the rest
 * leave slack), ends up with clear pixels below the feet — and then `height/2`
 * hovers the sprite by exactly that slack. The `infantry_v2` sheets do this:
 * their ground point sits ~18% of a cell above its bottom edge, so the
 * declared lift is ~0.32·height rather than 0.5·height. Atlases that declare
 * nothing keep the bottom-edge assumption.
 */
export function cardLift(atlas: ImpostorAtlas | undefined): number {
    const declared = atlas?.centreY;
    if (typeof declared === 'number' && Number.isFinite(declared) && declared > 0) {
        return declared;
    }
    return (atlas?.height ?? 0) * 0.5;
}

/**
 * The card rotation shared by every impostor card of one atlas this frame
 * (PLAN-metalstorm-impostors.md §Card orientation).
 *
 * Two things make this a per-FRAME value rather than a per-instance one:
 * directionality comes from atlas cell SELECTION, not from twisting the quad,
 * and a shared rotation is precisely what stops a tight squad's sprites from
 * fanning out radially when the camera is close.
 *
 * Tilt is decided by the atlas (`cardTiltsWithPitch`):
 *  - elevation rows present → the camera's full world rotation, so the card
 *    turns to face a steep top-down camera and actually presents the top-down
 *    row it selected. Without this the card is near edge-on and smears.
 *  - single row → yaw about world up only, keeping the card upright; a lone
 *    horizon-level view laid flat would read as a fallen unit.
 *
 * Yaw is taken from the camera's own basis (its world matrix row 2 is the
 * toward-viewer axis in Babylon RH), not from each sprite's position→camera
 * vector, so it is genuinely uniform across the batch.
 */
export function computeCardRotation(
    camera: { getWorldMatrix(): Matrix; absoluteRotation: Quaternion } | null | undefined,
    layout: AtlasLayout,
): Quaternion {
    if (!camera) return Quaternion.Identity();
    if (cardTiltsWithPitch(layout)) return camera.absoluteRotation.clone();
    const m = camera.getWorldMatrix().m;
    return Quaternion.RotationYawPitchRoll(Math.atan2(m[8], m[10]), 0, 0);
}

/** LOD tier — drives EntityRenderer's per-entity visibility decision. */
export enum LodTier {
    /** Full 3D model, all pieces, thin-instanced per piece. */
    Full = 'full',
    /** Camera-facing billboard quad, atlas frame by heading × anim. */
    Impostor = 'impostor',
    /** Strategic map symbol (not rendered by EntityRenderer). */
    Icon = 'icon',
}

/** Per-def LOD thresholds (world-space distance from camera). */
export interface LodThresholds {
    /** Distance beyond which to switch from Full → Impostor (elmos). */
    impostorDistance: number;
    /** Distance beyond which to switch from Impostor → Icon (elmos). */
    iconDistance: number;
}

/** Per-instance impostor data (populated by EntityRenderer each frame). */
interface ImpostorInstance {
    /** Entity world position (XYZ). */
    x: number;
    y: number;
    z: number;
    /** Unit's heading in radians (0 = +Z, π/2 = +X, Babylon RH). */
    heading: number;
    /** Current animation frame index (0-based row in the atlas). */
    animFrame: number;
    /** Team ID (for team-colour shader). */
    team: number;
}

/** Quantize a heading (radians) to the nearest atlas column (0–7). */
export function quantizeHeading(radians: number): number {
    // 8 headings: 0° (col 0), 45° (col 1), ..., 315° (col 7)
    // Normalize to [0, 2π), then divide into 8 bins
    let normalized = radians % (2 * Math.PI);
    if (normalized < 0) normalized += 2 * Math.PI;
    return Math.floor((normalized + Math.PI / 8) / (Math.PI / 4)) % 8;
}

/**
 * Build the impostor sprite material for one (atlas, team): PBR albedo =
 * the sprite atlas (alpha-tested cutout — binary silhouette, not blended,
 * so no depth-sort artifacts between overlapping billboards), matte
 * dielectric so the sprite takes scene sun/ambient/shadow like the unit
 * models, plus TeamColorPlugin against the optional `_impostor_team.ktx2`
 * R-mask sidecar. Shared with the squad member fan-out path
 * (squad-render-backend.ts), which draws per-member sprites beyond the def's
 * impostorDistance.
 *
 * `withFade` attaches DitherFadePlugin so the caller can crossfade the sprite
 * in/out across the member LOD boundary via a per-instance `ditherFade`
 * attribute (squad member fan-out, M5). A caller that opts in MUST upload a
 * `ditherFade` thin-instance buffer (default 1.0), or every fragment reads
 * fade=0 and discards. The entity-level impostor path leaves it off (hard
 * Full↔Impostor swap, no per-instance fade attribute).
 */
export function createImpostorMaterial(
    name: string,
    atlas: ImpostorAtlas,
    team: number,
    scene: Scene,
    withFade = false,
): PBRMaterial {
    const mat = new PBRMaterial(name, scene);
    mat.metallic = 0.0;
    mat.roughness = 1.0;
    if (atlas.diffuseUri) {
        const tex = new Texture(atlas.diffuseUri, scene);
        tex.hasAlpha = true;
        mat.albedoTexture = tex;
        mat.useAlphaFromAlbedoTexture = true;
        mat.transparencyMode = PBRMaterial.PBRMATERIAL_ALPHATEST;
        // Slightly below the usual 0.5: the sprites are LANCZOS-downscaled
        // + mipmapped, so a soft edge survives into the distance mips —
        // 0.4 keeps thin parts (limbs, rifle) from eroding away.
        mat.alphaCutOff = 0.4;
    }
    // Quad is DOUBLESIDE geometry but instances always face the camera;
    // disable culling anyway so grazing angles never drop the sprite.
    mat.backFaceCulling = false;
    mat.twoSidedLighting = true;

    const plugin = new TeamColorPlugin(mat);
    plugin.teamColor = getTeamColor(team);
    if (atlas.teamMaskUri) {
        const mask = new Texture(atlas.teamMaskUri, scene);
        mask.hasAlpha = false;
        plugin.teamMask = mask;
    }

    // v2 directional atlas: the per-instance `impostorCell` attribute selects
    // one (yaw, pitch) cell and the UV-remap plugin scales/offsets the quad's
    // UVs into it, so the albedo, alpha, and team mask all read that cell.
    // Legacy 1x1 atlases skip it and keep the whole-quad mapping (M3).
    //
    // `billboard` stays OFF here: this path bakes the shared card rotation into
    // each thin-instance matrix (see render()), so the shader must not rotate
    // again. The feature-LOD path is the one that drives the plugin's billboard.
    const layout = layoutOf(atlas);
    if (isDirectionalAtlas(layout)) {
        const uv = new ImpostorUvPlugin(mat);
        uv.layout = layout;
        uv.cellSelect = true;
        uv.isEnabled = true;
    }
    if (withFade) {
        const fade = new DitherFadePlugin(mat);
        // Per-instance `ditherFade` attribute, and the complementary half of
        // the Bayer pattern versus the member-model material, so the two tiers
        // interleave exactly instead of overlapping (see squad-render-backend).
        fade.useAttribute = true;
        fade.invertPattern = true;
        fade.isEnabled = true;
    }
    return mat;
}

/** Impostor quad renderer — one mesh per (defId, team), thin-instanced. */
export class ImpostorRenderer {
    private scene: Scene;
    private engine: Engine;

    /** Impostor meshes keyed by "impostor:{defId}:{team}". */
    private impostorMeshes = new Map<string, Mesh>();

    /** Atlas metadata per def. Populated lazily when a def streams. */
    private atlases = new Map<number, ImpostorAtlas>();

    /** LOD thresholds per def. */
    private lodThresholds = new Map<number, LodThresholds>();

    /** Presentation clock (drives animation frame timing). */
    private clock: PresentationClock | null = null;

    /** Shadow generator (if impostors should cast shadows). */
    private shadowGenerator: CascadedShadowGenerator | null = null;

    /** Pending instance data per (defId, team), drained each render. */
    private pendingInstances = new Map<string, ImpostorInstance[]>();

    constructor(scene: Scene, engine: Engine) {
        this.scene = scene;
        this.engine = engine;
    }

    setPresentationClock(clock: PresentationClock): void {
        this.clock = clock;
    }

    setShadowGenerator(gen: CascadedShadowGenerator | null): void {
        this.shadowGenerator = gen;
    }

    /** Register an impostor atlas for a def (called when def streams). */
    registerAtlas(defId: number, atlas: ImpostorAtlas): void {
        this.atlases.set(defId, atlas);
    }

    /** Atlas registered for a def, if any. The squad member fan-out adapter
     *  (squad-render-backend.ts) uses this to render members of impostor
     *  defs as sprites instead of proxy capsules. */
    getAtlas(defId: number): ImpostorAtlas | undefined {
        return this.atlases.get(defId);
    }

    /** Register LOD thresholds for a def. */
    registerLodThresholds(defId: number, thresholds: LodThresholds): void {
        this.lodThresholds.set(defId, thresholds);
    }

    /** Add one impostor instance to the pending batch (called per visible entity). */
    addInstance(defId: number, team: number, x: number, y: number, z: number, heading: number): void {
        const key = `impostor:${defId}:${team}`;
        let batch = this.pendingInstances.get(key);
        if (!batch) {
            batch = [];
            this.pendingInstances.set(key, batch);
        }

        // Flipbook frame within the atlas (row-group `frame·pitchBins + pitch`).
        // frames=1 today, so always 0 — walk/idle flipbook rows are fx-offload
        // X2 territory (the atlas layout already reserves them downward, so X2
        // is additive). NOT a standin: single-pose is the plan's M3 state.
        const animFrame = 0;

        batch.push({
            x,
            y,
            z,
            heading,
            animFrame,
            team,
        });
    }

    /** Flush pending instances → thin-instance buffers. Called per render. */
    render(cameraPos: Vector3): void {
        // Card orientation is IDENTICAL for every instance in a frame (see
        // computeCardRotation), so resolve it once here rather than per sprite.
        // Per-atlas, because whether a card tilts depends on its layout.
        const camera = this.scene.activeCamera;

        // Group instances per mesh
        const groups = new Map<string, {
            mesh: Mesh;
            matrices: number[];
            cells: number[];
            count: number;
        }>();

        for (const [key, instances] of this.pendingInstances) {
            if (instances.length === 0) continue;

            const [, defIdStr, teamStr] = key.split(':');
            const defId = Number(defIdStr);
            const team = Number(teamStr);

            const mesh = this.getOrCreateImpostorMesh(defId, team);
            if (!mesh) continue;

            const atlas = this.atlases.get(defId);
            const layout = layoutOf(atlas);

            // One card rotation for the whole batch — shared, so nearby
            // sprites stay parallel instead of fanning out radially.
            const cardRot = computeCardRotation(camera, layout);

            // Instance positions are ground anchors (entity Y is at ground
            // level) — lift the quad so the sprite's feet touch the ground
            // instead of the figure being half-buried, by the atlas's own
            // declared lift (`cardLift`, NOT unconditionally half the height).
            // The lift rides the card's own local up, so a tilted card keeps
            // its base on the terrain rather than hovering above it.
            const lift = new Vector3(0, cardLift(atlas), 0);
            lift.rotateByQuaternionToRef(cardRot, lift);

            const group = {
                mesh,
                matrices: [] as number[],
                cells: [] as number[],
                count: 0,
            };

            for (const inst of instances) {
                // The card rotation is baked into the instance matrix because
                // Mesh.billboardMode does NOT apply per-thin-instance — Babylon
                // computes it once from the MESH's own transform (our mesh sits
                // at the origin), which left the quad edge-on from most camera
                // angles. Unlike a per-instance twist toward the camera
                // POSITION, `cardRot` is shared by the batch (see
                // computeCardRotation), which is what keeps a tight squad's
                // sprites parallel instead of fanning out.
                const mat = Matrix.Compose(Vector3.One(), cardRot,
                    new Vector3(inst.x + lift.x, inst.y + lift.y, inst.z + lift.z));
                const arr = new Float32Array(16);
                mat.copyToArray(arr, 0);
                for (let i = 0; i < 16; i++) group.matrices.push(arr[i]);

                // Per-instance directional cell: column from the relative yaw
                // between the camera and the unit's facing (offset by the
                // atlas's own azimuth phase), row from camera pitch against the
                // atlas's own arc — impostor-atlas.selectAtlasCell. animFrame is
                // reserved for fx-offload X2 flipbook rows (frames=1 today).
                const vx = cameraPos.x - inst.x;
                const vy = cameraPos.y - inst.y;
                const vz = cameraPos.z - inst.z;
                group.cells.push(selectAtlasCell(vx, vy, vz, inst.heading, layout, inst.animFrame));
                group.count++;
            }

            groups.set(key, group);
        }

        // Update mesh buffers
        for (const [, group] of groups) {
            group.mesh.isVisible = true;
            const matBuf = new Float32Array(group.matrices);
            group.mesh.thinInstanceSetBuffer('matrix', matBuf, 16, false);
            // Per-instance directional cell selector (ImpostorUvPlugin reads it
            // in the vertex shader). Harmless on legacy 1×1 atlases (the plugin
            // isn't attached, so the attribute is simply unused).
            group.mesh.thinInstanceSetBuffer('impostorCell',
                new Float32Array(group.cells), 1, false);

            group.mesh.thinInstanceCount = group.count;
            group.mesh.thinInstanceRefreshBoundingInfo(false);
        }

        // Hide meshes not active this frame
        for (const [key, mesh] of this.impostorMeshes) {
            if (!groups.has(key)) {
                mesh.isVisible = false;
                mesh.thinInstanceCount = 0;
            }
        }

        // Clear pending
        this.pendingInstances.clear();
    }

    /** Get or create the impostor mesh for (defId, team). */
    private getOrCreateImpostorMesh(defId: number, team: number): Mesh | null {
        const key = `impostor:${defId}:${team}`;
        let mesh = this.impostorMeshes.get(key);
        if (mesh) return mesh;

        const atlas = this.atlases.get(defId);
        if (!atlas) {
            // No atlas registered yet — skip. EntityRenderer will retry
            // next frame once defs stream.
            console.warn(`[ImpostorRenderer] no atlas for def ${defId} (not yet registered)`);
            return null;
        }

        // Create the billboard quad. NOT mesh.billboardMode — that only
        // billboards the mesh's own transform (this mesh sits at the
        // origin; the actual per-unit positions are thin-instance matrices),
        // so each instance bakes its own camera-facing rotation in render()
        // instead (see the yaw computation there).
        mesh = MeshBuilder.CreatePlane(
            `impostor_${defId}_${team}`,
            { width: atlas.width, height: atlas.height, sideOrientation: Mesh.DOUBLESIDE },
            this.scene,
        );
        mesh.isPickable = false;
        mesh.alwaysSelectAsActiveMesh = true;

        mesh.material = createImpostorMaterial(
            `impostor_mat_${defId}_${team}`, atlas, team, this.scene);

        // Shadow casting (if enabled). The material is ALPHATEST, so the
        // shadow depth pass samples the albedo alpha and casts the sprite
        // silhouette. A DIRECTIONAL atlas is excluded: the UV-remap lives in
        // the material's own vertex shader and doesn't reach Babylon's shadow
        // depth shader, so a directional caster would shadow the whole-atlas
        // silhouette (all cells overlaid). See impostor-uv-plugin.ts — the LOD
        // swap happens at ≲20 px where a cast shadow is sub-pixel anyway.
        if (this.shadowGenerator && !isDirectionalAtlas(layoutOf(atlas))) {
            this.shadowGenerator.addShadowCaster(mesh);
        }

        mesh.isVisible = false; // Hidden until instances populate
        this.impostorMeshes.set(key, mesh);
        return mesh;
    }

    /** Determine the LOD tier for a given entity. */
    determineLodTier(
        defId: number,
        worldPos: Vector3,
        cameraPos: Vector3,
        forceTier?: LodTier,
    ): LodTier {
        // Force-LOD override (model-viewer harness, debug)
        if (forceTier) return forceTier;

        const thresholds = this.lodThresholds.get(defId);
        if (!thresholds) {
            // No thresholds registered → default to full model
            return LodTier.Full;
        }

        const dist = Vector3.Distance(worldPos, cameraPos);
        if (dist >= thresholds.iconDistance) return LodTier.Icon;
        if (dist >= thresholds.impostorDistance) return LodTier.Impostor;
        return LodTier.Full;
    }

    /** Test/debug accessor: current thinInstanceCount per (defId, team) mesh
     *  key ("impostor:{defId}:{team}"). Used by impostor-renderer.test.ts to
     *  assert batching without reaching into private state. */
    getDebugMeshCounts(): Map<string, number> {
        const out = new Map<string, number>();
        for (const [key, mesh] of this.impostorMeshes) {
            out.set(key, mesh.thinInstanceCount);
        }
        return out;
    }

    /** Clean up all impostor meshes. */
    dispose(): void {
        for (const mesh of this.impostorMeshes.values()) {
            mesh.dispose();
        }
        this.impostorMeshes.clear();
        this.atlases.clear();
        this.lodThresholds.clear();
        this.pendingInstances.clear();
    }
}
