/**
 * ImpostorRenderer — billboard/impostor LOD tier for distant units.
 *
 * Per PLAN-metalstorm-beta-units.md §2.1: every unit has up to three
 * representations — full model, impostor (camera-facing quad), and icon.
 * This module handles the impostor tier: textured quads with atlas frames
 * selected by quantized heading (8 views) × animation flipbook frame.
 *
 * Architecture:
 * - One mesh per (defId, team), thin-instanced across all units of that type
 * - Per-instance attributes: world position, heading (for frame select), team ID
 * - Atlas texture: 8 headings × N animation frames (walk, idle), team mask
 * - Heading quantization: unit's rotation → nearest 45° heading → atlas column
 * - Animation frame: driven by velocity/state (coordinated with fx-offload X4)
 *
 * Coordination with PLAN-fx-offload.md X2 (piece-transform texture / animation):
 * The per-instance attribute pattern here (heading, animFrame, teamId) is
 * COMPATIBLE with X2's planned data-texture substrate — when X2 lands, both
 * the impostor path and the full-model skinning path will share the same
 * instance-data structures. This implementation deliberately uses a subset of
 * X2's eventual schema so no breaking changes are required later.
 *
 * Atlas textures are the authored/baked sprite sheets (beta-units task 4b:
 * `<stem>_impostor.ktx2` + optional `<stem>_impostor_team.ktx2` under the
 * game's models/ dir — generated by tools/fable-model-forge/
 * gen_impostor_sprites.py for the impostor-only infantry/civilians).
 * Material: stock PBRMaterial (alpha-tested cutout) + the same
 * TeamColorPlugin the unit model path uses, so sprites sit in the scene
 * sun/ambient/CSM lighting exactly like 3D members would.
 */

import {
    Scene,
    Mesh,
    MeshBuilder,
    Vector3,
    Matrix,
    Quaternion,
    PBRMaterial,
    Texture,
    Engine,
    type CascadedShadowGenerator,
} from '@babylonjs/core';
import { TeamColorPlugin } from './team-color-plugin.js';
import { ImpostorUvPlugin } from './impostor-uv-plugin.js';
import {
    type AtlasGrid, DEFAULT_GRID, isDirectional, atlasRows, selectCellIndex,
} from './impostor-atlas.js';
import { getTeamColor } from './team-colors.js';
import type { PresentationClock } from './presentation-clock.js';
import type { EntityStateSnapshot } from './entity-state.js';

/** Impostor atlas metadata — per unit def. Sourced from the def's client
 *  content or auto-derived from the model. */
export interface ImpostorAtlas {
    /** Atlas texture URI (diffuse + alpha). v2 directional layout: `yawBins`
     *  columns × (`pitchBins`·`frames`) rows — see impostor-atlas.ts /
     *  impostor_convention.py. */
    diffuseUri: string;
    /** Team-color mask atlas URI (R = blend amount, same layout). */
    teamMaskUri?: string;
    /** Number of walk-cycle frames (atlas rows [0, walkFrames)). */
    walkFrames: number;
    /** Number of idle frames (atlas rows [walkFrames, walkFrames+idleFrames)). */
    idleFrames: number;
    /** Quad size in world units (elmos). Derived from model bounds. */
    width: number;
    height: number;
    /** v2 directional grid (PLAN-metalstorm-impostors.md M3). Absent = a
     *  legacy single-frame atlas (1×1×1): the whole quad maps to the whole
     *  texture and no directional select happens. */
    yawBins?: number;
    pitchBins?: number;
    frames?: number;
}

/** The directional grid for an atlas, defaulting a legacy atlas to 1×1×1. */
export function gridOf(atlas: ImpostorAtlas): AtlasGrid {
    if (atlas.yawBins && atlas.pitchBins && atlas.frames) {
        return { yawBins: atlas.yawBins, pitchBins: atlas.pitchBins, frames: atlas.frames };
    }
    return DEFAULT_GRID;
}

/** LOD tier — drives EntityRenderer's per-entity visibility decision. */
export enum LodTier {
    /** Full 3D model, all pieces, thin-instanced per piece. */
    Full = 'full',
    /** Camera-facing billboard quad, atlas frame by heading × anim. */
    Impostor = 'impostor',
    /** Strategic map symbol (not rendered by EntityRenderer). */
    Icon = 'icon',
}

/** Per-def LOD thresholds (world-space distance from camera). */
export interface LodThresholds {
    /** Distance beyond which to switch from Full → Impostor (elmos). */
    impostorDistance: number;
    /** Distance beyond which to switch from Impostor → Icon (elmos). */
    iconDistance: number;
}

/** Per-instance impostor data (populated by EntityRenderer each frame). */
interface ImpostorInstance {
    /** Entity world position (XYZ). */
    x: number;
    y: number;
    z: number;
    /** Unit's heading in radians (0 = +Z, π/2 = +X, Babylon RH). */
    heading: number;
    /** Current animation frame index (0-based row in the atlas). */
    animFrame: number;
    /** Team ID (for team-colour shader). */
    team: number;
}

/** Quantize a heading (radians) to the nearest atlas column (0–7). */
export function quantizeHeading(radians: number): number {
    // 8 headings: 0° (col 0), 45° (col 1), ..., 315° (col 7)
    // Normalize to [0, 2π), then divide into 8 bins
    let normalized = radians % (2 * Math.PI);
    if (normalized < 0) normalized += 2 * Math.PI;
    return Math.floor((normalized + Math.PI / 8) / (Math.PI / 4)) % 8;
}

/**
 * Build the impostor sprite material for one (atlas, team): PBR albedo =
 * the sprite atlas (alpha-tested cutout — binary silhouette, not blended,
 * so no depth-sort artifacts between overlapping billboards), matte
 * dielectric so the sprite takes scene sun/ambient/shadow like the unit
 * models, plus TeamColorPlugin against the optional `_impostor_team.ktx2`
 * R-mask sidecar. Shared with the squad member fan-out path
 * (squad-render-backend.ts), which draws per-member sprites for
 * impostor-only infantry defs.
 */
export function createImpostorMaterial(
    name: string,
    atlas: ImpostorAtlas,
    team: number,
    scene: Scene,
): PBRMaterial {
    const mat = new PBRMaterial(name, scene);
    mat.metallic = 0.0;
    mat.roughness = 1.0;
    if (atlas.diffuseUri) {
        const tex = new Texture(atlas.diffuseUri, scene);
        tex.hasAlpha = true;
        mat.albedoTexture = tex;
        mat.useAlphaFromAlbedoTexture = true;
        mat.transparencyMode = PBRMaterial.PBRMATERIAL_ALPHATEST;
        // Slightly below the usual 0.5: the sprites are LANCZOS-downscaled
        // + mipmapped, so a soft edge survives into the distance mips —
        // 0.4 keeps thin parts (limbs, rifle) from eroding away.
        mat.alphaCutOff = 0.4;
    }
    // Quad is DOUBLESIDE geometry but instances always face the camera;
    // disable culling anyway so grazing angles never drop the sprite.
    mat.backFaceCulling = false;
    mat.twoSidedLighting = true;

    const plugin = new TeamColorPlugin(mat);
    plugin.teamColor = getTeamColor(team);
    if (atlas.teamMaskUri) {
        const mask = new Texture(atlas.teamMaskUri, scene);
        mask.hasAlpha = false;
        plugin.teamMask = mask;
    }

    // v2 directional atlas: the per-instance `cellIndex` attribute selects one
    // (yaw, pitch) cell; the UV-remap plugin rewrites vMainUV1 so the albedo,
    // alpha, and team mask all read that cell. Legacy 1×1 atlases skip it and
    // keep the whole-quad mapping (M3, PLAN-metalstorm-impostors.md).
    const grid = gridOf(atlas);
    if (isDirectional(grid)) {
        const uv = new ImpostorUvPlugin(mat);
        uv.yawBins = grid.yawBins;
        uv.atlasRows = atlasRows(grid);
    }
    return mat;
}

/** Impostor quad renderer — one mesh per (defId, team), thin-instanced. */
export class ImpostorRenderer {
    private scene: Scene;
    private engine: Engine;

    /** Impostor meshes keyed by "impostor:{defId}:{team}". */
    private impostorMeshes = new Map<string, Mesh>();

    /** Atlas metadata per def. Populated lazily when a def streams. */
    private atlases = new Map<number, ImpostorAtlas>();

    /** LOD thresholds per def. */
    private lodThresholds = new Map<number, LodThresholds>();

    /** Presentation clock (drives animation frame timing). */
    private clock: PresentationClock | null = null;

    /** Shadow generator (if impostors should cast shadows). */
    private shadowGenerator: CascadedShadowGenerator | null = null;

    /** Pending instance data per (defId, team), drained each render. */
    private pendingInstances = new Map<string, ImpostorInstance[]>();

    constructor(scene: Scene, engine: Engine) {
        this.scene = scene;
        this.engine = engine;
    }

    setPresentationClock(clock: PresentationClock): void {
        this.clock = clock;
    }

    setShadowGenerator(gen: CascadedShadowGenerator | null): void {
        this.shadowGenerator = gen;
    }

    /** Register an impostor atlas for a def (called when def streams). */
    registerAtlas(defId: number, atlas: ImpostorAtlas): void {
        this.atlases.set(defId, atlas);
    }

    /** Atlas registered for a def, if any. The squad member fan-out adapter
     *  (squad-render-backend.ts) uses this to render members of impostor
     *  defs as sprites instead of proxy capsules. */
    getAtlas(defId: number): ImpostorAtlas | undefined {
        return this.atlases.get(defId);
    }

    /** Register LOD thresholds for a def. */
    registerLodThresholds(defId: number, thresholds: LodThresholds): void {
        this.lodThresholds.set(defId, thresholds);
    }

    /** Add one impostor instance to the pending batch (called per visible entity). */
    addInstance(defId: number, team: number, x: number, y: number, z: number, heading: number): void {
        const key = `impostor:${defId}:${team}`;
        let batch = this.pendingInstances.get(key);
        if (!batch) {
            batch = [];
            this.pendingInstances.set(key, batch);
        }

        // Flipbook frame within the atlas (row-group `frame·pitchBins + pitch`).
        // frames=1 today, so always 0 — walk/idle flipbook rows are fx-offload
        // X2 territory (the atlas layout already reserves them downward, so X2
        // is additive). NOT a standin: single-pose is the plan's M3 state.
        const animFrame = 0;

        batch.push({
            x,
            y,
            z,
            heading,
            animFrame,
            team,
        });
    }

    /** Flush pending instances → thin-instance buffers. Called per render. */
    render(cameraPos: Vector3): void {
        // Screen-aligned (spherical) card orientation, shared by every card
        // this frame: the camera's own world rotation (view yaw + pitch, no
        // roll). Directionality comes from per-instance atlas frame SELECTION,
        // not from twisting each card toward the camera position — that shared
        // rotation is what kills the point-blank fan-out (PLAN M3). Fallback
        // to identity when there's no active camera (unit tests).
        const cardRot = this.scene.activeCamera?.absoluteRotation ?? Quaternion.Identity();

        // Group instances per mesh
        const groups = new Map<string, {
            mesh: Mesh;
            matrices: number[];
            cells: number[];
            count: number;
        }>();

        for (const [key, instances] of this.pendingInstances) {
            if (instances.length === 0) continue;

            const [, defIdStr, teamStr] = key.split(':');
            const defId = Number(defIdStr);
            const team = Number(teamStr);

            const mesh = this.getOrCreateImpostorMesh(defId, team);
            if (!mesh) continue;

            const atlas = this.atlases.get(defId);
            const grid = atlas ? gridOf(atlas) : DEFAULT_GRID;
            // Instance positions are ground anchors (entity Y is at ground
            // level) — lift the quad by half its height so the sprite's feet
            // touch the ground. The card pitches with the camera, so lift along
            // the card's local up (cardRot·Y) rather than world up, keeping the
            // feet on the terrain from a steep angle.
            const halfH = (atlas?.height ?? 0) * 0.5;
            const up = new Vector3(0, halfH, 0);
            up.rotateByQuaternionToRef(cardRot, up);

            const group = {
                mesh,
                matrices: [] as number[],
                cells: [] as number[],
                count: 0,
            };

            for (const inst of instances) {
                const mat = Matrix.Compose(Vector3.One(), cardRot,
                    new Vector3(inst.x + up.x, inst.y + up.y, inst.z + up.z));
                const arr = new Float32Array(16);
                mat.copyToArray(arr, 0);
                for (let i = 0; i < 16; i++) group.matrices.push(arr[i]);

                // Per-instance directional cell: column from the relative yaw
                // between the camera and the unit's facing, row from camera
                // pitch (impostor-atlas.selectCellIndex). animFrame reserved for
                // fx-offload X2 flipbook rows (frames=1 today).
                const vx = cameraPos.x - inst.x;
                const vy = cameraPos.y - inst.y;
                const vz = cameraPos.z - inst.z;
                group.cells.push(selectCellIndex(vx, vy, vz, inst.heading, grid, inst.animFrame));
                group.count++;
            }

            groups.set(key, group);
        }

        // Update mesh buffers
        for (const [, group] of groups) {
            group.mesh.isVisible = true;
            const matBuf = new Float32Array(group.matrices);
            group.mesh.thinInstanceSetBuffer('matrix', matBuf, 16, false);
            // Per-instance directional cell selector (ImpostorUvPlugin reads it
            // in the vertex shader). Harmless on legacy 1×1 atlases (the plugin
            // isn't attached, so the attribute is simply unused).
            group.mesh.thinInstanceSetBuffer('cellIndex',
                new Float32Array(group.cells), 1, false);

            group.mesh.thinInstanceCount = group.count;
            group.mesh.thinInstanceRefreshBoundingInfo(false);
        }

        // Hide meshes not active this frame
        for (const [key, mesh] of this.impostorMeshes) {
            if (!groups.has(key)) {
                mesh.isVisible = false;
                mesh.thinInstanceCount = 0;
            }
        }

        // Clear pending
        this.pendingInstances.clear();
    }

    /** Get or create the impostor mesh for (defId, team). */
    private getOrCreateImpostorMesh(defId: number, team: number): Mesh | null {
        const key = `impostor:${defId}:${team}`;
        let mesh = this.impostorMeshes.get(key);
        if (mesh) return mesh;

        const atlas = this.atlases.get(defId);
        if (!atlas) {
            // No atlas registered yet — skip. EntityRenderer will retry
            // next frame once defs stream.
            console.warn(`[ImpostorRenderer] no atlas for def ${defId} (not yet registered)`);
            return null;
        }

        // Create the billboard quad. NOT mesh.billboardMode — that only
        // billboards the mesh's own transform (this mesh sits at the
        // origin; the actual per-unit positions are thin-instance matrices),
        // so each instance bakes its own camera-facing rotation in render()
        // instead (see the yaw computation there).
        mesh = MeshBuilder.CreatePlane(
            `impostor_${defId}_${team}`,
            { width: atlas.width, height: atlas.height, sideOrientation: Mesh.DOUBLESIDE },
            this.scene,
        );
        mesh.isPickable = false;
        mesh.alwaysSelectAsActiveMesh = true;

        mesh.material = createImpostorMaterial(
            `impostor_mat_${defId}_${team}`, atlas, team, this.scene);

        // Shadow casting (if enabled). The material is ALPHATEST, so the
        // shadow depth pass samples the albedo alpha and casts the sprite
        // silhouette. A DIRECTIONAL atlas is excluded: the UV-remap lives in
        // the material's own vertex shader and doesn't reach Babylon's shadow
        // depth shader, so a directional caster would shadow the whole-atlas
        // silhouette (all cells overlaid). See impostor-uv-plugin.ts — the LOD
        // swap happens at ≲20 px where a cast shadow is sub-pixel anyway.
        if (this.shadowGenerator && !isDirectional(gridOf(atlas))) {
            this.shadowGenerator.addShadowCaster(mesh);
        }

        mesh.isVisible = false; // Hidden until instances populate
        this.impostorMeshes.set(key, mesh);
        return mesh;
    }

    /** Determine the LOD tier for a given entity. */
    determineLodTier(
        defId: number,
        worldPos: Vector3,
        cameraPos: Vector3,
        forceTier?: LodTier,
    ): LodTier {
        // Force-LOD override (model-viewer harness, debug)
        if (forceTier) return forceTier;

        const thresholds = this.lodThresholds.get(defId);
        if (!thresholds) {
            // No thresholds registered → default to full model
            return LodTier.Full;
        }

        const dist = Vector3.Distance(worldPos, cameraPos);
        if (dist >= thresholds.iconDistance) return LodTier.Icon;
        if (dist >= thresholds.impostorDistance) return LodTier.Impostor;
        return LodTier.Full;
    }

    /** Test/debug accessor: current thinInstanceCount per (defId, team) mesh
     *  key ("impostor:{defId}:{team}"). Used by impostor-renderer.test.ts to
     *  assert batching without reaching into private state. */
    getDebugMeshCounts(): Map<string, number> {
        const out = new Map<string, number>();
        for (const [key, mesh] of this.impostorMeshes) {
            out.set(key, mesh.thinInstanceCount);
        }
        return out;
    }

    /** Clean up all impostor meshes. */
    dispose(): void {
        for (const mesh of this.impostorMeshes.values()) {
            mesh.dispose();
        }
        this.impostorMeshes.clear();
        this.atlases.clear();
        this.lodThresholds.clear();
        this.pendingInstances.clear();
    }
}
